-- Run once in the Supabase SQL Editor before starting the app.
-- Private schema: intentionally outside the default public Data API schema.
CREATE SCHEMA IF NOT EXISTS qc_portal;
REVOKE ALL ON SCHEMA qc_portal FROM PUBLIC;

CREATE TABLE IF NOT EXISTS qc_portal.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    test_date DATE,
    project_assignment TEXT NOT NULL DEFAULT '',
    scheduled_discipline TEXT NOT NULL DEFAULT '',
    assigned_disciplines TEXT[] NOT NULL DEFAULT ARRAY['All Disciplines']::TEXT[],
    invitation_sent_at TIMESTAMPTZ,
    active_login_token TEXT,
    active_login_at TIMESTAMPTZ,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Candidate', 'Reviewer', 'Admin'))
);
CREATE TABLE IF NOT EXISTS qc_portal.app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
INSERT INTO qc_portal.app_settings(key, value) VALUES ('maintenance_mode', 'false')
ON CONFLICT (key) DO NOTHING;
CREATE TABLE IF NOT EXISTS qc_portal.assessment_drafts (
    user_id BIGINT PRIMARY KEY REFERENCES qc_portal.users(id) ON DELETE CASCADE,
    payload JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS qc_portal.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discipline TEXT NOT NULL,
    q_type TEXT NOT NULL CHECK (q_type IN ('mcq', 'essay', 'oral_practical')),
    question_text TEXT NOT NULL,
    options TEXT,
    correct_answer TEXT,
    rubric TEXT,
    max_points INTEGER NOT NULL CHECK (max_points > 0),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    subject TEXT NOT NULL DEFAULT 'General',
    sub_subject TEXT NOT NULL DEFAULT 'General',
    is_scored BOOLEAN NOT NULL DEFAULT TRUE,
    difficulty TEXT NOT NULL DEFAULT 'moderate' CHECK (difficulty IN ('easy', 'moderate', 'difficult')),
    topic_group TEXT NOT NULL DEFAULT 'General',
    delivery_stage TEXT NOT NULL DEFAULT 'standard' CHECK (delivery_stage IN ('standard', 'oral_opening')),
    CHECK (delivery_stage = 'standard' OR (q_type = 'oral_practical' AND is_scored = FALSE))
);
CREATE TABLE IF NOT EXISTS qc_portal.assessment_settings (
    question_type TEXT PRIMARY KEY,
    question_count INTEGER NOT NULL CHECK (question_count > 0),
    max_points DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (max_points > 0),
    non_scored_count INTEGER NOT NULL DEFAULT 0 CHECK (non_scored_count >= 0),
    easy_count INTEGER NOT NULL DEFAULT 0 CHECK (easy_count >= 0),
    moderate_count INTEGER NOT NULL DEFAULT 0 CHECK (moderate_count >= 0),
    difficult_count INTEGER NOT NULL DEFAULT 0 CHECK (difficult_count >= 0),
    oral_opening_count INTEGER NOT NULL DEFAULT 2 CHECK (oral_opening_count >= 0)
);
INSERT INTO qc_portal.assessment_settings(question_type, question_count) VALUES
    ('mcq', 20), ('essay', 5), ('oral_practical', 10)
ON CONFLICT (question_type) DO NOTHING;
CREATE TABLE IF NOT EXISTS qc_portal.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name TEXT NOT NULL,
    designation TEXT NOT NULL DEFAULT '',
    iqama_no TEXT NOT NULL DEFAULT '',
    employee_no TEXT NOT NULL DEFAULT '',
    exam_date DATE NOT NULL DEFAULT CURRENT_DATE,
    project_assignment TEXT NOT NULL DEFAULT '',
    discipline TEXT NOT NULL,
    mcq_max DOUBLE PRECISION NOT NULL DEFAULT 0,
    essay_max DOUBLE PRECISION NOT NULL DEFAULT 0,
    oral_practical_max DOUBLE PRECISION NOT NULL DEFAULT 0,
    max_possible_points DOUBLE PRECISION NOT NULL CHECK (max_possible_points > 0),
    status TEXT NOT NULL CHECK (status IN ('Pending Review', 'Graded')),
    reviewer_comments TEXT DEFAULT '',
    user_id BIGINT REFERENCES qc_portal.users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    graded_at TIMESTAMPTZ,
    reviewer_id BIGINT REFERENCES qc_portal.users(id),
    token TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS qc_portal.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES qc_portal.submissions(id),
    question_id BIGINT NOT NULL REFERENCES qc_portal.questions(id),
    submitted_answer TEXT NOT NULL,
    awarded_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    snapshot TEXT NOT NULL,
    UNIQUE (submission_id, question_id)
);
CREATE INDEX IF NOT EXISTS submissions_user_idx ON qc_portal.submissions(user_id);
CREATE INDEX IF NOT EXISTS submissions_status_idx ON qc_portal.submissions(status);
CREATE INDEX IF NOT EXISTS answers_submission_idx ON qc_portal.answers(submission_id);
CREATE INDEX IF NOT EXISTS answers_question_idx ON qc_portal.answers(question_id);
CREATE INDEX IF NOT EXISTS questions_discipline_idx ON qc_portal.questions(discipline);
CREATE INDEX IF NOT EXISTS users_candidate_date_idx ON qc_portal.users(role, test_date);

-- No client API policies: only the trusted server's database owner connection
-- accesses these tables. App-level roles are checked in database.py.
ALTER TABLE qc_portal.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE qc_portal.answers ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA qc_portal FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA qc_portal FROM PUBLIC;
