"""
Civil QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: ACI 318, ASTM C39, ASTM C143, SAES-Q-001, SAES-Q-005, SAES-A-114
"""

D = "Civil QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. According to ACI 318 and Saudi Aramco standards, what is the maximum allowable time between batching (introduction of water to the cement) and complete discharge of transit-mixed concrete at the site?",
"30 minutes\n60 minutes\n90 minutes\n120 minutes",
"90 minutes",
"ASTM C94 and general ACI standards dictate a maximum of 90 minutes (or 300 drum revolutions, whichever comes first) from the time water is introduced to the cement until discharge is complete, to prevent premature setting. In hot weather, this time is often reduced.",
1),

(D,"mcq",
"2. When performing a slump test (ASTM C143), how many layers of concrete should be used to fill the slump cone?",
"Two equal layers by volume.\nThree equal layers by volume.\nThree equal layers by height.\nFour equal layers by height.",
"Three equal layers by volume.",
"The slump cone must be filled in three layers, each approximately one-third of the VOLUME of the mold. (This roughly equates to depths of 2-5/8 inches, 6-1/8 inches, and the top).",
1),

(D,"mcq",
"3. How many times must each layer be rodded during a concrete slump test?",
"10 times\n15 times\n25 times\n30 times",
"25 times",
"ASTM C143 requires each of the three layers to be rodded exactly 25 times uniformly over the cross-section with a standard 5/8-inch diameter hemispherical-tipped tamping rod.",
1),

(D,"mcq",
"4. What is the standard temperature range for curing concrete test cylinders in the laboratory for the first 48 hours (initial curing) according to ASTM C31?",
"10°C to 15°C (50°F to 59°F)\n16°C to 27°C (60°F to 80°F)\n28°C to 35°C (82°F to 95°F)\n0°C to 5°C (32°F to 41°F)",
"16°C to 27°C (60°F to 80°F)",
"Standard initial curing requires cylinders to be stored at a temperature between 16°C and 27°C (60°F and 80°F) in an environment preventing moisture loss. For high-strength concrete (>6000 psi), the range is narrowed to 20°C to 26°C.",
1),

(D,"mcq",
"5. In earthwork, what does the term 'Optimum Moisture Content' (OMC) refer to?",
"The maximum amount of water a soil can hold before turning to mud.\nThe moisture content at which maximum dry density is achieved during compaction.\nThe natural moisture content of the soil before excavation.\nThe moisture content required for plant growth.",
"The moisture content at which maximum dry density is achieved during compaction.",
"Determined by a Proctor compaction test, OMC is the specific water content at which a given soil type can be compacted to its absolute maximum dry density, providing the strongest foundation.",
1),

(D,"mcq",
"6. What field test is most commonly used to determine the in-place density of compacted soil (backfill)?",
"Standard Penetration Test (SPT)\nNuclear Moisture-Density Gauge or Sand Cone Method\nCalifornia Bearing Ratio (CBR)\nAtterberg Limits",
"Nuclear Moisture-Density Gauge or Sand Cone Method",
"The Sand Cone method (ASTM D1556) and the Nuclear Gauge (ASTM D6938) are the standard field tests used to verify that contractors have achieved the specified degree of compaction (e.g., 95% of Modified Proctor density).",
1),

(D,"mcq",
"7. When casting concrete in hot weather (e.g., summer in Saudi Arabia), what is the maximum allowable concrete temperature at the time of placement according to SAES-Q-001?",
"25°C (77°F)\n32°C (90°F)\n38°C (100°F)\n45°C (113°F)",
"32°C (90°F)",
"Saudi Aramco standard SAES-Q-001 limits the maximum concrete temperature at the point of delivery/placement to 32°C (90°F) to prevent flash setting, thermal cracking, and strength reduction. Ice is often substituted for mix water to achieve this.",
1),

(D,"mcq",
"8. What is the primary purpose of 'curing' concrete?",
"To dry the concrete as quickly as possible.\nTo maintain satisfactory moisture content and temperature to allow cement hydration and strength development.\nTo wash away surface laitance.\nTo improve the color of the finished surface.",
"To maintain satisfactory moisture content and temperature to allow cement hydration and strength development.",
"Curing is not drying. Curing ensures water remains trapped inside the concrete so the chemical reaction (hydration) between cement and water can continue, allowing the concrete to reach its designed compressive strength and durability.",
1),

(D,"mcq",
"9. Which additive is commonly used in concrete to resist freeze-thaw cycles (though less critical in the Middle East, it's a core ACI concept)?",
"Retarder\nSuperplasticizer\nAir-entraining agent\nAccelerator",
"Air-entraining agent",
"Air-entraining admixtures create microscopic air bubbles that provide space for water to expand into when it freezes, preventing the concrete from cracking. It also improves workability.",
1),

(D,"mcq",
"10. For a standard compressive strength test (ASTM C39), concrete cylinders are usually broken at what age to determine the specified design strength (f'c)?",
"3 days\n7 days\n14 days\n28 days",
"28 days",
"The 28-day compressive strength is the universal standard metric used to verify that the concrete has achieved its structural design strength (f'c).",
1),

(D,"mcq",
"11. In reinforced concrete, what is 'concrete cover'?",
"The plastic sheet laid over the concrete for curing.\nThe distance from the outer surface of the concrete to the outer surface of the reinforcing steel.\nThe roof of a concrete structure.\nThe epoxy coating applied to the rebar.",
"The distance from the outer surface of the concrete to the outer surface of the reinforcing steel.",
"Concrete cover protects the reinforcing steel from environmental corrosion and fire. Saudi Aramco requires very specific, often thick, cover dimensions (e.g., 75mm for earth-contact concrete) to protect against severe chloride environments.",
1),

(D,"mcq",
"12. A soil with a high 'Plasticity Index' (PI) is generally considered:",
"Excellent for structural backfill.\nA highly expansive clay that is unsuitable for structural foundations without treatment.\nPure sand.\nSolid rock.",
"A highly expansive clay that is unsuitable for structural foundations without treatment.",
"A high PI indicates a clay soil that absorbs massive amounts of water, swelling significantly when wet and shrinking/cracking when dry. It is disastrous for foundations and is usually removed or treated.",
1),

(D,"mcq",
"13. What is the purpose of 'Vibrating' concrete during placement?",
"To mix the cement and water further.\nTo consolidate the concrete, removing entrapped air voids (honeycombing) and ensuring it flows around rebar.\nTo push the heavy aggregates to the bottom.\nTo heat the concrete in cold weather.",
"To consolidate the concrete, removing entrapped air voids (honeycombing) and ensuring it flows around rebar.",
"Vibration liquefies the mortar, allowing entrapped air bubbles to rise and escape, preventing voids (honeycombs) and ensuring a dense, structurally sound matrix that bonds tightly to the reinforcement.",
1),

(D,"mcq",
"14. When overlapping (splicing) reinforcing steel bars (rebar), the length of the lap is primarily determined by:",
"The length of the available wire ties.\nThe bar diameter, concrete strength, and steel yield strength.\nThe distance between formwork ties.\nThe size of the aggregate in the concrete.",
"The bar diameter, concrete strength, and steel yield strength.",
"Lap splice lengths are calculated based on the bar diameter (e.g., 40d or 50d) to ensure sufficient bond length for stress to transfer from one bar into the concrete and then into the adjacent bar without failing.",
1),

(D,"mcq",
"15. What defect is caused by adding excess water to a concrete mix at the job site to make it easier to pour?",
"Increased final compressive strength.\nReduced strength, increased shrinkage cracking, and higher permeability.\nBetter bonding to the rebar.\nSlower setting time with no negative effects.",
"Reduced strength, increased shrinkage cracking, and higher permeability.",
"The Water/Cement (W/C) ratio is the most critical factor in concrete design. Adding unauthorized water increases the W/C ratio, drastically reducing structural strength and making the concrete porous and prone to rapid corrosion of internal rebar.",
1),

(D,"mcq",
"16. Which type of cement is specified for concrete structures exposed to severe sulfate conditions (like highly saline groundwater in the Middle East)?",
"Type I (Normal)\nType III (High Early Strength)\nType V (Sulfate Resisting)\nWhite Portland Cement",
"Type V (Sulfate Resisting)",
"Type V Portland cement is formulated with low Tricalcium Aluminate (C3A) to resist chemical attack from sulfates in soil and groundwater, which would otherwise cause the concrete to expand, crack, and disintegrate.",
1),

(D,"mcq",
"17. According to SAES-Q-001, what is the required protection for reinforcing steel used in structures near the Arabian Gulf coast?",
"Galvanizing\nFusion Bonded Epoxy (FBE) coating\nStainless steel only\nNo special protection needed if cover is thick enough",
"Fusion Bonded Epoxy (FBE) coating",
"Due to the extremely aggressive chloride environment near the coast, Saudi Aramco heavily utilizes Fusion Bonded Epoxy (FBE) coated rebar (distinctive green color) to prevent rapid rebar corrosion and subsequent concrete spalling.",
1),

(D,"mcq",
"18. What is 'Honeycombing' in concrete?",
"A decorative pattern applied to the surface.\nA defect characterized by coarse aggregate not being fully coated with mortar, leaving large voids and exposed stone, usually due to poor vibration or grout leakage.\nA type of lightweight aggregate.\nA highly desirable matrix structure for strength.",
"A defect characterized by coarse aggregate not being fully coated with mortar, leaving large voids and exposed stone, usually due to poor vibration or grout leakage.",
"Honeycombing represents a severe structural and durability defect. It occurs when mortar leaks out of poorly sealed forms, or when vibration is insufficient to make the concrete flow and consolidate properly.",
1),

(D,"mcq",
"19. What does 'FDT' stand for in civil earthwork inspection?",
"Final Design Thickness\nField Density Test\nFoundation Depth Tolerance\nFine Dirt Texture",
"Field Density Test",
"Field Density Testing (usually by nuclear gauge or sand cone) verifies that the compacted soil meets the required percentage of maximum dry density determined by the laboratory Proctor test.",
1),

(D,"mcq",
"20. When casting a concrete slab, what is the purpose of 'control joints' (contraction joints)?",
"To connect two different concrete pours together.\nTo create intentional, straight planes of weakness to control where the concrete will inevitably crack as it shrinks during curing.\nTo allow water to drain through the slab.\nTo provide a decorative groove.",
"To create intentional, straight planes of weakness to control where the concrete will inevitably crack as it shrinks during curing.",
"Concrete shrinks as it cures. If it is constrained, it will crack randomly. Control joints (cut about 1/4 the depth of the slab) force the cracking to occur in a neat, straight line hidden within the joint.",
1),

(D,"mcq",
"21. A structural drawing calls for a 'chamfer' on all exposed concrete columns. What does this mean?",
"A heavy coat of paint.\nA 45-degree beveled edge cast into the corners of the column to prevent the sharp edges from chipping and breaking off.\nA specific type of rebar tie.\nA waterstop placed in the construction joint.",
"A 45-degree beveled edge cast into the corners of the column to prevent the sharp edges from chipping and breaking off.",
"Sharp 90-degree corners on concrete easily chip and spall when struck. Chamfer strips are placed in the formwork to create flat, beveled corners that are highly resistant to impact damage.",
1),

(D,"mcq",
"22. What is the purpose of a 'Waterstop' in a concrete structure?",
"To stop the mixer truck from adding water.\nTo prevent concrete from flowing out of the forms.\nA flexible physical barrier (PVC or rubber) embedded across construction or expansion joints in water-retaining structures to prevent water from leaking through the joint.\nTo cure the concrete by holding water on the surface.",
"A flexible physical barrier (PVC or rubber) embedded across construction or expansion joints in water-retaining structures to prevent water from leaking through the joint.",
"Cold joints (construction joints) are natural leak paths. A continuous waterstop is embedded half in the first pour and half in the second pour, creating a physical dam that stops water migration.",
1),

(D,"mcq",
"23. Which test is used to measure the consistency, workability, and flowability of freshly mixed concrete?",
"Compressive Strength Test\nSlump Test\nProctor Test\nSchmidt Hammer Test",
"Slump Test",
"The Slump Test (ASTM C143) is the universally accepted field test to measure the workability and consistency of a batch of concrete, serving as a quick indicator of water content and batch-to-batch uniformity.",
1),

(D,"mcq",
"24. When backfilling around a newly constructed concrete retaining wall, what precaution must be taken?",
"The backfill must be poured as a slurry.\nThe concrete must have reached its full 28-day design strength, or an approved percentage thereof, before heavy compaction equipment pushes earth against it.\nOnly large boulders should be used against the wall.\nBackfilling must be completed before the concrete cures.",
"The concrete must have reached its full 28-day design strength, or an approved percentage thereof, before heavy compaction equipment pushes earth against it.",
"Compacting heavy soil against a 'green' (uncured) concrete wall can easily crack or overturn the wall. Engineering approval regarding concrete strength gain is required before backfilling begins.",
1),

(D,"mcq",
"25. What is the allowable tolerance for the placement of reinforcing steel (cover) according to typical ACI standards?",
"± 25 mm (1 inch)\n± 10 mm (3/8 inch)\n± 50 mm (2 inches)\nNo tolerance, it must be exact.",
"± 10 mm (3/8 inch)",
"While specific tolerances vary by member type and depth, ACI 117 typically allows a tolerance of -10mm to -13mm on concrete cover, meaning cover cannot be reduced by more than that amount to prevent corrosion risks.",
1),

(D,"mcq",
"26. What is a 'Bleeding' in freshly placed concrete?",
"The rusting of rebar causing red stains.\nThe appearance of water on the surface of the concrete after placement and compaction, caused by the settlement of heavier solid particles.\nThe loss of cement paste through holes in the formwork.\nThe addition of red pigment.",
"The appearance of water on the surface of the concrete after placement and compaction, caused by the settlement of heavier solid particles.",
"Bleed water is normal, but excessive bleeding indicates a poor mix design. Finishing operations (troweling) must NOT be performed while bleed water is present, or the water will be forced back into the surface, creating a weak, dusting layer (laitance).",
1),

(D,"mcq",
"27. What non-destructive test can be used to estimate the in-place compressive strength of hardened concrete?",
"Slump Test\nSchmidt (Rebound) Hammer Test\nProctor Compaction Test\nSand Cone Test",
"Schmidt (Rebound) Hammer Test",
"The Schmidt hammer bounces a spring-loaded mass off the concrete surface. The rebound value correlates roughly to surface hardness and compressive strength. It is an estimation tool, not a substitute for cylinder testing or core drilling.",
1),

(D,"mcq",
"28. During asphalt paving operations, what is the purpose of applying a 'Tack Coat'?",
"To seal the final surface against water.\nTo provide a bond between an existing paved surface and the new asphalt overlay.\nTo color the asphalt black.\nTo cool the asphalt down quickly.",
"To provide a bond between an existing paved surface and the new asphalt overlay.",
"A tack coat is a light application of liquid asphalt emulsion sprayed on an existing pavement to ensure the new layer of hot mix asphalt adheres chemically and mechanically, preventing sliding or delamination.",
1),

(D,"mcq",
"29. What is 'Laitance' on a concrete surface?",
"A specialized coating applied for chemical resistance.\nA weak, fragile layer of cement and fine aggregates brought to the surface by bleeding water and over-finishing.\nA type of high-strength reinforcement.\nA structural crack.",
"A weak, fragile layer of cement and fine aggregates brought to the surface by bleeding water and over-finishing.",
"Laitance has zero structural strength and poor bond characteristics. It must be mechanically removed (by blasting or grinding) before applying epoxy coatings, sealers, or pouring a second layer of concrete, otherwise the bond will fail.",
1),

(D,"mcq",
"30. When pouring a deep concrete column, why is a 'tremie' pipe or elephant trunk used?",
"To measure the temperature of the concrete.\nTo prevent 'segregation' of the concrete mix by guiding it smoothly to the bottom instead of letting it free-fall and hit the rebar cage.\nTo pump water out of the column.\nTo apply vibration to the bottom of the pour.",
"To prevent 'segregation' of the concrete mix by guiding it smoothly to the bottom instead of letting it free-fall and hit the rebar cage.",
"If concrete free-falls from a height (usually > 1.5 meters) and hits rebar, the heavy aggregate separates from the cement paste (segregation), resulting in rock pockets and severe honeycombing at the bottom of the column.",
1),

(D,"mcq",
"31. In surveying and site layout, what does a 'Benchmark' (BM) represent?",
"A mark showing where a bench will be installed.\nA point of known elevation and coordinates used as a permanent reference for all other site measurements.\nA temporary wooden stake.\nThe boundary of the property.",
"A point of known elevation and coordinates used as a permanent reference for all other site measurements.",
"A benchmark is a highly accurate, fixed reference point established by professional surveyors. All site elevations (cut and fill, top of concrete) are measured relative to this benchmark.",
1),

(D,"mcq",
"32. Why are 'Spacers' (or chairs) used when tying rebar inside formwork?",
"To make the rebar look neat.\nTo hold the rebar off the formwork at a precise distance, guaranteeing the specified concrete cover is achieved.\nTo connect different sizes of rebar together.\nTo provide lifting points for the crane.",
"To hold the rebar off the formwork at a precise distance, guaranteeing the specified concrete cover is achieved.",
"Concrete cover is critical for corrosion protection. Spacers (made of plastic or concrete) are clipped to the rebar to physically prevent it from touching the wooden forms or the ground, ensuring the exact required thickness of concrete covers the steel.",
1),

(D,"mcq",
"33. What is the required ambient condition for storing epoxy-coated rebar on site?",
"Directly on the ground, uncovered.\nOn wooden supports (dunnage) off the ground, and covered with opaque tarpaulins to protect the epoxy from UV sunlight degradation.\nStored in a pool of water.\nWelded to the structural steel.",
"On wooden supports (dunnage) off the ground, and covered with opaque tarpaulins to protect the epoxy from UV sunlight degradation.",
"The FBE (Fusion Bonded Epoxy) coating degrades rapidly when exposed to the UV rays in sunlight, turning chalky and losing its protective properties. It must be protected from the sun and kept out of mud/water.",
1),

(D,"mcq",
"34. In road construction, what is the layer immediately beneath the asphalt surface course called?",
"Subgrade\nBase Course\nTopsoil\nBedrock",
"Base Course",
"The typical flexible pavement structure is: Subgrade (compacted native soil), Subbase (often lower quality aggregate), Base Course (high quality, highly compacted crushed stone), and the Asphalt Surface course.",
1),

(D,"mcq",
"35. Which admixture is used to drastically increase the slump (flowability) of concrete without adding extra water, which would compromise strength?",
"Retarder\nSuperplasticizer (High Range Water Reducer)\nAccelerator\nAir Entrainer",
"Superplasticizer (High Range Water Reducer)",
"Superplasticizers disperse cement particles chemically, allowing concrete to flow like a liquid (high slump) for highly congested rebar pours, while keeping the water/cement ratio very low to maintain high strength.",
1),

(D,"mcq",
"36. What is the standard test to measure the temperature of freshly mixed concrete?",
"ASTM C1064\nASTM C39\nASTM C143\nASTM C31",
"ASTM C1064",
"ASTM C1064 is the standard test method for measuring the temperature of freshly mixed Portland cement concrete. A calibrated thermometer is inserted into the fresh concrete with at least 3 inches of cover.",
1),

(D,"mcq",
"37. If a concrete cylinder fails its 28-day compressive strength test, what is the standard ACI procedure for further investigation?",
"Demolish the structure immediately.\nExtract and test core samples from the actual poured structure in the area representing the failed batch (ASTM C42).\nAccept it if it's within 10%.\nAdd extra rebar to the next pour.",
"Extract and test core samples from the actual poured structure in the area representing the failed batch (ASTM C42).",
"Cylinder failures can result from poor sampling, bad curing, or rough handling. If they fail, structural cores are drilled from the actual placed concrete to determine its true in-situ strength before any demolition decisions are made.",
1),

(D,"mcq",
"38. What does 'Curing Compound' do when sprayed on fresh concrete?",
"It colors the concrete.\nIt forms a continuous membrane over the surface that traps the mixing water inside the concrete, allowing hydration to occur without the need for continuous water spraying.\nIt removes laitance.\nIt melts ice in cold weather.",
"It forms a continuous membrane over the surface that traps the mixing water inside the concrete, allowing hydration to occur without the need for continuous water spraying.",
"Liquid membrane-forming curing compounds dry to form a film that seals the pores of the concrete, preventing moisture evaporation. This is a highly effective curing method in hot, arid climates where continuous wet curing is difficult.",
1),

(D,"mcq",
"39. When welding reinforcing steel, what is the most critical material property to verify on the Mill Test Certificate (MTC)?",
"The color of the steel.\nThe Carbon Equivalent (CE) value, which determines weldability.\nThe length of the bars.\nThe rust scale present.",
"The Carbon Equivalent (CE) value, which determines weldability.",
"Not all rebar is weldable. High carbon content makes steel brittle when welded. The Carbon Equivalent (CE) must be calculated from the MTC to ensure it falls within weldable limits (typically < 0.45), otherwise special low-hydrogen procedures or pre-heating are required.",
1),

(D,"mcq",
"40. In soil compaction, what is the purpose of a 'Sheep's Foot' roller?",
"For rolling hot asphalt smooth.\nFor compacting cohesive soils (clays). The 'feet' penetrate the soil, kneading and compacting it from the bottom up.\nFor compacting clean sand.\nFor finishing concrete slabs.",
"For compacting cohesive soils (clays). The 'feet' penetrate the soil, kneading and compacting it from the bottom up.",
"A sheep's foot (or padfoot) roller uses high-pressure nubs to punch through layers of cohesive (clay/silt) soil, kneading the layers together and eliminating voids. Smooth drum vibratory rollers are used for granular (sand/gravel) soils.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Describe the comprehensive Quality Control inspection process for a major concrete pour (e.g., a large foundation) from pre-pour to post-pour.",
"","",
"Grade on: Pre-pour: Verify formwork dimensions/plumbness, rebar size/spacing/tying against IFC drawings. Verify concrete cover using spacers. Check embedded items (anchor bolts, conduits). Ensure forms are clean and oiled. Pre-pour sign-off. During Pour: Verify concrete delivery tickets (mix design, time batching). Measure Slump, Temperature, Air Content. Cast test cylinders. Ensure proper vibration (no segregation). Post-Pour: Verify curing method (wet burlap, compound) starts immediately. Protect from extreme weather. Demolding inspection for honeycombing/cracks.",
20),

(D,"essay",
"2. Explain the significance of the Water-Cement (W/C) ratio in concrete mix design. What are the consequences of a contractor adding unauthorized water at the job site?",
"","",
"Grade on: The W/C ratio is the mathematical ratio of the weight of water to the weight of cement. It is the single most critical factor dictating concrete strength and durability. A lower W/C ratio yields higher strength and lower permeability. Unauthorized water (retempering) makes it easier to pour but ruins the designed ratio, leading to drastically reduced compressive strength, increased shrinkage cracking, high porosity, and rapid corrosion of internal rebar.",
20),

(D,"essay",
"3. Detail the procedure for evaluating a failed 28-day concrete cylinder test. What steps must the QA/QC Inspector and structural engineer take before deciding to demolish the structure?",
"","",
"Grade on: A failed cylinder does not automatically mean the structure is unsafe; the cylinder may have been improperly cast, cured, or broken. Step 1: Review lab procedures and companion cylinder breaks. Step 2: Non-destructive testing (Schmidt Hammer, UPV) to map the suspect area. Step 3: Core extraction (ASTM C42) from the actual structure in the area of the failed batch. Step 4: If core tests meet ACI 318 criteria (average of 3 cores >= 85% f'c, no single core < 75% f'c), the concrete is structurally accepted. If it fails, engineering analysis or demolition follows.",
20),

(D,"essay",
"4. Discuss the specific challenges and required mitigation strategies for casting concrete in extremely hot weather (e.g., Middle East summer).",
"","",
"Grade on: Challenges: Rapid slump loss, flash setting, high plastic shrinkage cracking, decreased 28-day strength. Mitigation: Control concrete temperature (<32°C/90°F) by chilling mixing water or using flaked ice. Shade aggregate stockpiles. Night-time pouring. Use retarding admixtures. Windbreaks to stop surface drying. Immediate application of curing compounds or wet burlap to prevent plastic shrinkage cracks before final set.",
20),

(D,"essay",
"5. What is Soil Compaction, and why is it necessary? Explain the relationship between Maximum Dry Density (MDD) and Optimum Moisture Content (OMC).",
"","",
"Grade on: Compaction mechanically expels air from soil voids, increasing density, load-bearing capacity, and reducing settlement/permeability. The Proctor test plots moisture vs. dry density. Water acts as a lubricant; as moisture increases, density increases up to a peak (MDD). The exact moisture content at this peak is the OMC. Adding water beyond the OMC replaces heavy soil particles with lighter water, decreasing density. Field compaction must target the OMC.",
20),

(D,"essay",
"6. Outline the inspection requirements for Epoxy-Coated Reinforcing Steel (FBE coated rebar) from receiving on site to concrete pouring.",
"","",
"Grade on: Receiving: Check MTCs. Inspect for coating damage during transport. Storage: Store off the ground on wooden dunnage, covered with opaque tarps to prevent UV chalking. Handling: Use nylon slings, not wire rope. Installation: Tie wire must be PVC-coated to prevent scratching the epoxy. Touch-up: Any cut ends, welds, or scratches >1% of surface area must be repaired with manufacturer-approved two-part liquid epoxy before pouring.",
20),

(D,"essay",
"7. Describe the procedure for performing a Field Density Test using a Nuclear Moisture-Density Gauge. What safety precautions are involved?",
"","",
"Grade on: Procedure: Prepare a perfectly flat, smooth surface. Drive the pin to the desired depth to create a hole for the source rod (Direct Transmission method is most accurate). Lower the rod. Take the reading (usually 1 minute). The gauge calculates wet density, moisture content, and dry density. Compare dry density to the lab Proctor MDD to get % compaction. Safety: Gauge contains radioactive isotopes (Cesium-137, Americium-241/Be). Requires licensed operator, TLD radiation badge, secure locked transport, and maintaining safe distances when not operating.",
20),

(D,"essay",
"8. Explain the different types of joints used in concrete slabs on grade (Construction, Contraction/Control, and Isolation/Expansion). Provide a use-case for each.",
"","",
"Grade on: Construction Joint: Used to stop a pour for the day; physically connects two pours, often with dowels for load transfer. Contraction (Control) Joint: A saw cut (1/4 slab depth) made to create a weak plane, forcing inevitable shrinkage cracks to occur in a neat, hidden straight line. Isolation (Expansion) Joint: A full-depth gap filled with compressible material (e.g., cork, foam) used where a slab meets a fixed structure (wall, column) to allow independent movement without cracking.",
20),

(D,"essay",
"9. You inspect a newly stripped concrete wall and find severe 'Honeycombing' exposing the rebar. Describe the non-conformance procedure and the approved method for structural repair.",
"","",
"Grade on: NCR is issued. The structural engineer must evaluate the extent. Repair Method: Chipping hammer must remove all loose, unconsolidated concrete until sound concrete is reached. Cut behind the rebar to allow repair material to encase it. Square the edges of the patch (no feathered edges). Clean and apply bonding agent. Pack with non-shrink, high-strength structural repair grout (e.g., epoxy or cementitious). Cure properly.",
20),

(D,"essay",
"10. Discuss the importance of Anchor Bolt surveying and setting prior to casting concrete foundations. What tolerances are typically acceptable?",
"","",
"Grade on: Anchor bolts connect the structural steel framework to the foundation. If they are out of alignment, the steel building will not fit together. Verification requires precise total station surveying matching the structural steel shop drawings. Bolts must be rigidly secured to templates to prevent shifting during concrete vibration. Typical tolerance (e.g., AISC) is extremely tight: ±1/16 to 1/8 inch (approx 2-3 mm) from center, and elevation must be exact to allow base plate grouting.",
20),

(D,"essay",
"11. What is non-shrink grout, where is it used, and what specific QC checks are required during its application under a structural steel base plate?",
"","",
"Grade on: Non-shrink grout expands slightly during curing to guarantee 100% bearing contact between a steel base plate and the concrete foundation, transferring massive loads. QC checks: Surface prep (concrete must be roughened to exposed aggregate for bond), SSD (Saturated Surface Dry) condition to prevent concrete absorbing grout water, proper formwork with a 'head box' to pour from one side only (preventing trapped air), checking flowability, and ensuring continuous wet curing.",
20),

(D,"essay",
"12. Explain the difference between 'Flexible' (Asphalt) and 'Rigid' (Concrete) pavements in terms of how they transfer traffic loads to the subgrade.",
"","",
"Grade on: Flexible Pavement (Asphalt): Acts like a flexible mat. It transfers loads downward in a conical shape. The stress is highest at the surface and dissipates through multiple layers (Surface, Base, Subbase) before reaching the subgrade. Requires highly compacted granular bases. Rigid Pavement (Concrete): Acts like a rigid bridge. The high stiffness of the concrete slab distributes the load over a very wide area of the subgrade. Subgrade strength is less critical, but uniform support is vital to prevent slab cracking.",
20),

(D,"essay",
"13. Detail the inspection requirements for Hot Mix Asphalt (HMA) paving operations. Include temperature controls, laydown, and compaction.",
"","",
"Grade on: Subgrade/Base approval (Prime/Tack coat applied). Delivery: Check asphalt temperature in the truck (typically 135-160°C); reject if too cold (won't compact) or too hot (binder burns). Laydown: Check uncompacted thickness, screed operation. Compaction: Must begin immediately while mix is hot. Sequence involves Breakdown rolling (heavy vibratory), Intermediate rolling (pneumatic tired for sealing), and Finish rolling (static steel drum to remove marks). Final check: Core drilling for density and thickness.",
20),

(D,"essay",
"14. Discuss the mechanisms of Sulfate Attack and Chloride-induced Corrosion in reinforced concrete. How does a civil inspector verify the concrete mix is designed to resist these?",
"","",
"Grade on: Sulfate Attack: Sulfates in soil/groundwater react with C3A in cement, forming expansive compounds (ettringite) that crack and disintegrate the concrete. Mitigated by using Type V (Sulfate Resisting) cement. Chloride Corrosion: Chlorides (salt) penetrate the concrete, destroying the passive oxide layer on rebar, causing it to rust. Rust expands 6x its volume, spalling the concrete. Mitigated by low W/C ratio (dense concrete), thick concrete cover, and FBE-coated rebar. Inspector verifies mix design for cement type, max W/C ratio, and minimum cover.",
20),

(D,"essay",
"15. Describe the Standard Penetration Test (SPT) used in geotechnical investigations. What does the 'N-value' indicate?",
"","",
"Grade on: SPT is an in-situ dynamic penetration test. A thick-walled sample tube is driven into the ground at the bottom of a borehole by blows from a 140 lb (63.5 kg) hammer falling 30 inches. The 'N-value' is the number of blows required to drive the tube the last 12 inches (300 mm) of an 18-inch drive. It provides an empirical indication of soil relative density (for sands) and consistency (for clays), used heavily in foundation design.",
20),

(D,"essay",
"16. What is 'Plastic Shrinkage Cracking' in concrete? When does it occur, what causes it, and how is it prevented?",
"","",
"Grade on: These are shallow, parallel cracks that appear on the surface of freshly poured concrete while it is still plastic (before it sets). Cause: Occurs when the rate of water evaporation from the surface exceeds the rate at which bleed water rises to the surface. The surface dries, shrinks, and tears. Aggravated by hot, dry, windy conditions. Prevention: Windbreaks, sunshades, fog misting the air above the slab, or applying evaporation retarder chemicals immediately after screeding.",
20),

(D,"essay",
"17. You are inspecting structural steel erection. Explain the QC requirements for verifying high-strength bolted connections using the 'Turn-of-Nut' method.",
"","",
"Grade on: Turn-of-nut is a highly reliable tensioning method. QC process: 1. Ensure all plies of steel are drawn firmly together in a 'snug-tight' condition (done by a few hits of an impact wrench or full effort with a spud wrench). 2. The inspector ensures the bolt, nut, and steel are match-marked with a straight line across all three. 3. The nut is then turned a specific required rotation (e.g., 1/3, 1/2, or 2/3 of a turn depending on bolt length/diameter). 4. Inspector verifies the match marks have moved the exact required rotation.",
20),

(D,"essay",
"18. Discuss the importance of maintaining an accurate 'As-Built' survey for underground utilities (piping, electrical duct banks). What happens if this QC step is missed?",
"","",
"Grade on: Underground utilities are hidden once backfilled. The surveyor must record exact coordinates and elevations of pipes, warning tapes, and duct banks before covering. If missed, future excavations (for new structures or repairs) risk striking live electrical lines (fatalities), pressurized gas lines (explosions), or water mains. It also prevents clashing with future foundation piles. Red-line drawings must be updated dynamically.",
20),

(D,"essay",
"19. Explain the procedure and purpose of a 'Pile Load Test' (Static Load Test) for deep foundations.",
"","",
"Grade on: Purpose: To verify the actual geotechnical load-bearing capacity of a driven or bored pile against the design loads, and to measure settlement under load. Procedure (ASTM D1143): A test pile is installed. A massive reaction frame is built over it, anchored by reaction piles or kentledge (heavy dead weights). A hydraulic jack pushes down on the test pile. Load is applied in increments (up to 200% of design load). Settlement is measured with highly accurate dial gauges. The load-settlement curve proves the pile is safe.",
20),

(D,"essay",
"20. What is 'Laitance', why is it detrimental to construction joints, and how must a QC inspector verify it has been removed?",
"","",
"Grade on: Laitance is a weak, friable layer of cement paste and fine sand brought to the top of a concrete pour by bleeding water. It has zero tensile strength. If a second layer of concrete (or an epoxy coating) is poured over laitance, the bond will fail completely at that weak layer. Inspector verification: Before the next pour, the surface must be mechanically roughened (by sandblasting, water blasting, or bush hammering) until the laitance is entirely gone and the coarse aggregate is cleanly exposed. Verify surface is clean and SSD.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. A concrete transit mixer arrives on site. The ticket shows it was batched 2 hours ago. The specification limits time to 90 minutes. The concrete still looks wet. Do you accept it?",
"","",
"Grade on: No, reject the truck. The 90-minute limit (or 300 revolutions) is a strict ASTM/ACI requirement. Even if the concrete looks workable, the chemical hydration process is well underway. Disturbing it now will permanently reduce its final structural strength.",
10),

(D,"oral",
"2. During a slump test, after removing the cone, the concrete simply collapses into a messy puddle. What does this indicate and what do you do?",
"","",
"Grade on: This is a 'shear' or 'collapse' slump, indicating an extremely high water-cement ratio, a lack of cohesion in the mix, or excessive superplasticizer. It is not a valid slump measurement. Reject the batch as it is likely severely over-watered and will not meet strength requirements.",
10),

(D,"oral",
"3. You see a laborer using a high-pressure hose to wash down the formwork, leaving large puddles of water inside just before the concrete is poured. What is your concern?",
"","",
"Grade on: Puddles of standing water inside the formwork will mix with the fresh concrete as it is poured. This drastically increases the water-cement ratio in localized areas (especially at the base of columns or walls), resulting in extremely weak, porous concrete and honeycombing. The water must be blown out with compressed air before pouring.",
10),

(D,"oral",
"4. What is the difference between 'Curing' and 'Drying' concrete?",
"","",
"Grade on: Drying is simply the evaporation of water. Curing is the deliberate trapping of moisture inside the concrete to allow the chemical reaction (hydration) between cement and water to continue for days/weeks. If concrete 'dries' too fast, hydration stops, and it will never reach its designed strength.",
10),

(D,"oral",
"5. Why do we cover epoxy-coated rebar with tarps while it sits in the laydown yard?",
"","",
"Grade on: The green Fusion Bonded Epoxy (FBE) coating is highly susceptible to ultraviolet (UV) degradation from the sun. If left exposed, the epoxy turns into a chalky powder, losing its thickness, flexibility, and ability to protect the steel from chloride corrosion.",
10),

(D,"oral",
"6. You are testing compacted soil with a nuclear gauge. The reading shows 89% compaction. The spec requires 95%. What instructions do you give the contractor?",
"","",
"Grade on: The soil fails. Instruct the contractor to either apply more compaction effort (more roller passes), or check the moisture content. If the soil is too dry, they must add water (bring it closer to Optimum Moisture Content). If it is too wet, they must scarify (disc) it, let it dry, and re-roll. Re-test after rework.",
10),

(D,"oral",
"7. A concrete pump operator is dropping concrete 4 meters down into a column form without using an elephant trunk (tremie pipe). What defect will this cause?",
"","",
"Grade on: 'Segregation' and 'Honeycombing'. Free-falling heavy concrete hitting the rebar cage causes the heavy rocks (coarse aggregate) to separate from the sticky cement paste. The rocks fall to the bottom with no paste to bind them, creating massive voids (honeycombs) at the base of the column.",
10),

(D,"oral",
"8. What is 'Concrete Cover' and why is it so strictly inspected?",
"","",
"Grade on: Cover is the minimum distance between the outside of the concrete and the closest piece of rebar. It is strictly inspected because it is the only thing protecting the steel from moisture, oxygen, and chlorides (which cause rust and spalling) and from heat during a fire. If cover is too thin, the structure will fail prematurely.",
10),

(D,"oral",
"9. You find the contractor welding rebar together because they ran out of tie wire. Is this acceptable?",
"","",
"Grade on: No, stop work immediately. Most standard rebar is high-carbon steel and is NOT weldable. Welding it makes the steel extremely brittle at the weld point, destroying its tensile strength. Weldable rebar (low Carbon Equivalent) must be specifically ordered and welded via approved WPS.",
10),

(D,"oral",
"10. Explain the purpose of a 'Waterstop' in a concrete retaining wall.",
"","",
"Grade on: A waterstop is a continuous strip of rubber or PVC embedded across a cold joint (construction joint) between two separate concrete pours. Because cold joints do not bond perfectly, water will naturally leak through them. The waterstop acts as a physical dam to block this water migration.",
10),

(D,"oral",
"11. The contractor is pouring concrete and it's raining heavily. What do you do?",
"","",
"Grade on: Stop the pour if the rain is heavy enough to wash the cement paste off the surface of the fresh concrete or significantly alter the surface water/cement ratio. If they must finish a section, they must erect immediate waterproof tenting/tarps over the pour area.",
10),

(D,"oral",
"12. What does a 'Schmidt Hammer' (Rebound Hammer) tell you about concrete?",
"","",
"Grade on: It provides an estimate of the surface hardness of hardened concrete. By measuring how far a spring-loaded mass rebounds off the surface, you can correlate it (roughly) to compressive strength. It is a quick non-destructive screening tool to find weak spots, not a replacement for core testing.",
10),

(D,"oral",
"13. Why must we vibrate concrete?",
"","",
"Grade on: When poured, concrete contains large amounts of entrapped air pockets. Vibrating liquefies the mix, allowing these air bubbles to rise to the surface and escape. This 'consolidates' the concrete, ensuring it is dense, strong, completely surrounds the rebar, and is free of honeycombs.",
10),

(D,"oral",
"14. What happens if a worker leaves the vibrator in one spot in the concrete for a long time (over-vibration)?",
"","",
"Grade on: Over-vibration causes segregation. The heavy aggregates will sink to the bottom of the form, and the light water and cement paste will rise to the top. This results in a weak, powdery top surface (laitance) and a rock-heavy bottom.",
10),

(D,"oral",
"15. What is the difference between a Construction Joint and a Control Joint?",
"","",
"Grade on: A Construction Joint is a physical stopping point where pouring ended for the day; two separate pours meet here. A Control (Contraction) Joint is a shallow saw-cut made in a continuous slab to create a weak line, forcing the concrete to crack exactly there as it shrinks, rather than cracking randomly.",
10),

(D,"oral",
"16. You see a dark, damp patch on the outside of a concrete water tank that was poured a week ago. What do you suspect?",
"","",
"Grade on: Suspect a leak through a defect in the concrete, most likely a honeycomb, a poorly consolidated tie-hole, or a failure in the waterstop at a cold joint. It requires further investigation and likely structural repair (injection).",
10),

(D,"oral",
"17. Explain 'Tack Coat' and 'Prime Coat' in asphalt paving.",
"","",
"Grade on: A Prime Coat is sprayed on the raw soil/aggregate base course to bind the loose dust and waterproof it before paving. A Tack Coat is a sticky asphalt emulsion sprayed between layers of asphalt (e.g., between the binder course and wearing course) to glue them together and prevent slipping.",
10),

(D,"oral",
"18. What is the role of the Surveyor's 'Benchmark'?",
"","",
"Grade on: It is an immovable, highly accurate reference point with a known elevation and coordinate. The entire construction site (every foundation depth, pipe slope, and building height) is measured relative to this exact point.",
10),

(D,"oral",
"19. The concrete cylinder failed at 28 days. The project manager says, 'Just pour the next floor, it will be fine.' What is your response?",
"","",
"Grade on: Refuse. A failed 28-day break means the structure below may not support the design loads. Pouring the next floor adds massive dead load to a potentially weak structure, risking catastrophic collapse. Core drilling and structural engineering approval are mandatory before proceeding.",
20),

(D,"oral",
"20. Why do we chamfer the corners of concrete columns?",
"","",
"Grade on: Sharp 90-degree concrete corners are fragile and will easily chip, spall, and break off if bumped by equipment or during formwork removal. A chamfer (a 45-degree flat edge) eliminates the sharp point, making the corner highly resistant to impact damage.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Identify the equipment required to perform a Concrete Slump Test (ASTM C143) and describe the sequence of filling the cone.",
"","",
"Grade on: Equipment: Standard slump cone (12 inches high, 8 inch base, 4 inch top), 5/8-inch hemispherical tipped tamping rod, tape measure, flat non-absorbent base plate. Sequence: Dampen cone, stand on foot pieces. Fill in 3 layers (by volume: approx 2-5/8', 6-1/8', and top). Rod each layer 25 times, penetrating slightly into the layer below. Strike off top. Lift straight up steadily in 3-7 seconds.",
15),

(D,"practical",
"2. Demonstrate how to read a batch ticket from a ready-mix concrete truck to ensure it meets the pour specification.",
"","",
"Grade on: Check: 1. Date and Time batched (water added). 2. Mix design code (matches approved submittal for strength/cement type). 3. Admixtures added. 4. Target slump. 5. Maximum aggregate size. Calculate time elapsed to ensure it is within the 90-minute limit.",
15),

(D,"practical",
"3. Inspect a physical rebar cage (or photograph). Identify at least 3 critical QC checks before approving it for concrete pouring.",
"","",
"Grade on: 1. Rebar size and spacing match drawings. 2. Lap splice lengths are correct. 3. Concrete cover is maintained using approved plastic/concrete spacers on bottom and sides. 4. Tie wires are tight and bent inward (away from cover). 5. Rebar is clean (no oil, mud, excessive flaky rust).",
15),

(D,"practical",
"4. Given a set of 3 concrete test cylinders cast yesterday, demonstrate how they should be handled, marked, and stored for initial curing.",
"","",
"Grade on: Do not drop or jar them. Mark them clearly on the side (not the lid) with permanent marker: date, pour location, and batch ticket number. Store them immediately in a temperature-controlled environment (16-27°C) shielded from direct sunlight and prevented from moisture loss (under wet burlap/plastic or in a curing box).",
15),

(D,"practical",
"5. Review a compaction test report (Proctor curve and Field Density Test). Determine if the field test passes a 95% compaction requirement.",
"","",
"Grade on: Read the Lab Maximum Dry Density (MDD) from the peak of the Proctor curve (e.g., 2.00 g/cc). Read the Field Dry Density from the nuclear gauge printout (e.g., 1.92 g/cc). Calculate: (1.92 / 2.00) * 100 = 96%. 96% >= 95%, so the test passes. Also verify field moisture is near Optimum Moisture Content (OMC).",
15),

(D,"practical",
"6. Demonstrate the use of a digital thermometer to measure the temperature of freshly mixed concrete in a wheelbarrow.",
"","",
"Grade on: Ensure thermometer is calibrated. Insert the probe into the fresh concrete so that the sensing portion is submerged under at least 3 inches (75 mm) of concrete in all directions. Press the concrete gently around the stem to prevent ambient air pockets. Wait until the reading stabilizes (at least 2 minutes, but not more than 5). Record temperature.",
15),

(D,"practical",
"7. Inspect a photo of a newly stripped concrete column showing severe 'honeycombing' at the bottom. Detail the steps required to issue an NCR and repair it.",
"","",
"Grade on: Issue NCR for poor consolidation. Do not allow the contractor to just 'patch it over'. Repair: Chipping hammer must remove all loose rock until solid concrete is reached. Cut 1 inch behind exposed rebar. Clean out dust. Apply bonding agent. Form and pour/pack with approved high-strength non-shrink structural repair grout. Wet cure.",
15),

(D,"practical",
"8. Given a structural drawing, locate the requirement for concrete cover on a foundation footing cast against earth, and explain why it is thicker than a suspended slab.",
"","",
"Grade on: Locate general notes. Footings cast against earth typically require 3 inches (75mm) of cover (ACI 318). A suspended interior slab may only need 3/4 inch (20mm). Reason: Concrete cast directly against dirt mixes with soil, reducing effective cover. Also, ground moisture contains highly corrosive chlorides and sulfates that will attack the rebar if cover is thin.",
15),

(D,"practical",
"9. Explain how to verify the installation of a PVC Waterstop in a construction joint before the first pour.",
"","",
"Grade on: The waterstop must be positioned exactly in the center of the wall thickness. Exactly half of its width must be embedded in the first pour, and half left exposed for the second pour. It must be securely tied to the rebar using 'hog rings' or punched holes in the outer flanges so it does not fold over or shift during concrete vibration.",
15),

(D,"practical",
"10. Review a batch ticket where the contractor added 20 gallons of water at the site. The mix design allows a maximum W/C ratio of 0.45. How do you determine if this is acceptable?",
"","",
"Grade on: Look at the batch ticket for the 'Trim Water' or 'Water Withheld' allowance. The batch plant often holds back a small amount of water from the max W/C ratio to allow for on-site slump adjustment. If the 20 gallons is less than the 'withheld' amount, it is allowed (re-tempering). If it pushes the total water above the 0.45 ratio, it must be strictly rejected.",
15),

(D,"practical",
"11. Demonstrate the visual inspection of structural steel high-strength bolts tightened using the Turn-of-Nut method.",
"","",
"Grade on: Inspect the connection. Verify that all bolts, nuts, and the steel plate have a distinct, straight line drawn across them (match mark) made during the snug-tight phase. Verify that the mark on the nut has rotated away from the mark on the bolt/plate by the specific required angle (e.g., 1/3 or 1/2 turn, 120 or 180 degrees).",
15),

(D,"practical",
"12. Inspect a photo of an asphalt paving operation. The roller is working far behind the paver, and the asphalt looks tearing and cracked. Identify the QC issue.",
"","",
"Grade on: Temperature failure. Asphalt must be compacted while it is highly viscous and hot (e.g., above 120°C depending on mix). If the roller lags too far behind, the asphalt cools and becomes stiff. Rolling cold asphalt breaks the aggregate interlock, causing tearing, cracking, and failure to achieve density. Must monitor temperature behind the screed constantly.",
15),

(D,"practical",
"13. Given a set of construction drawings, identify the difference between a Plan view, an Elevation view, and a Section view.",
"","",
"Grade on: Plan view: Looking down from above (bird's eye), showing layout and horizontal dimensions. Elevation view: Looking straight at the side of a structure, showing heights and exterior features. Section view: An imaginary vertical slice through the structure, showing internal details (rebar placement, wall thickness).",
15),

(D,"practical",
"14. Demonstrate how to check the plumbness (vertical alignment) of a concrete column formwork before pouring.",
"","",
"Grade on: Use a heavy plumb bob dropped from the top of the formwork, measuring the distance from the string to the form at the top and bottom (they should be identical). Alternatively, use a long, high-quality builder's spirit level (minimum 4 feet) or a total station/theodolite surveying instrument for tall columns.",
15),

(D,"practical",
"15. Evaluate a scenario: You are pouring a large slab. The ready-mix plant breaks down, and the next truck will be delayed by 2 hours. What action must be taken?",
"","",
"Grade on: A 2-hour delay will cause a 'Cold Joint'. The concrete already placed will set before the new concrete arrives, meaning they will not bond, creating a structural weak plane and leak path. You must instruct the contractor to immediately install a construction joint (bulkhead/header board) straight across the slab, perpendicular to the rebar, to terminate the pour neatly.",
15),

(D,"practical",
"16. Inspect a photo of epoxy-coated rebar showing a large chip in the green coating, exposing rusting steel. Describe the repair procedure.",
"","",
"Grade on: The rust and loose coating must be removed using a wire brush or emery cloth down to clean metal. Wipe clean of dust/oil. Use a manufacturer-approved, two-part liquid epoxy touch-up kit. Apply with a brush, overlapping the surrounding good coating. Must be done before concrete is poured.",
15),

(D,"practical",
"17. Describe how you would verify the thickness of an asphalt road course during laying and after completion.",
"","",
"Grade on: During laying: Use a depth probe (T-bar) pushed through the hot, uncompacted mat behind the paver screed. (Must know the compaction shrink factor, typically 20-25%). After completion: The only definitive QC method is extracting cylindrical core samples using a core drill, measuring their actual physical thickness, and testing them for density.",
15),

(D,"practical",
"18. You notice plastic shrinkage cracks appearing on a concrete slab 30 minutes after screeding. What immediate action do you demand from the contractor?",
"","",
"Grade on: The surface is drying faster than bleed water can rise. Immediate action: Apply an evaporation retarder (monomolecular film) spray, or start fog-misting the air above the slab (do not spray water directly ON the concrete). Erect windbreaks or sunshades. DO NOT allow them to simply trowel water into the cracks.",
15),

(D,"practical",
"19. Check a foundation excavation (trench) before concrete blinding is poured. What are the key QC criteria?",
"","",
"Grade on: 1. Depth and dimensions match drawings. 2. Soil is compacted to specified density (requires FDT report). 3. Bottom is clean, level, and free of loose debris, mud, or standing water. 4. If termite treatment is required, ensure it was applied. 5. Surveyor has placed level pegs for the blinding thickness.",
15),

(D,"practical",
"20. Demonstrate how to verify that a freshly applied curing compound is adequate.",
"","",
"Grade on: Curing compound must form a continuous, unbroken membrane. Visual check: It usually contains a white fugitive dye to ensure even coverage. Look for 'holidays' (missed spots) or areas where it is applied too thin. It must be applied at the manufacturer's specified coverage rate (e.g., sq meters per liter) immediately after the final finishing and the water sheen disappears.",
15),

]  # end QUESTIONS
