"""
Coating QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: SSPC, NACE, ISO 8501, ISO 8502, SAES-H-001, SAES-H-101, SAEP-316
"""

D = "Coating QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. According to ISO 8501-1, what does the surface preparation grade 'Sa 2.5' represent?",
"Light blast cleaning\nThorough blast cleaning\nVery thorough blast cleaning (Near White Metal)\nBlast cleaning to visually clean steel (White Metal)",
"Very thorough blast cleaning (Near White Metal)",
"Sa 2.5 is defined as 'Very thorough blast cleaning' (equivalent to NACE No. 2 / SSPC-SP 10 Near-White Metal). When viewed without magnification, the surface shall be free from visible oil, grease, dirt, and from most of the mill scale, rust, paint coatings and foreign matter. Any remaining traces of contamination shall show only as slight stains in the form of spots or stripes.",
1),

(D,"mcq",
"2. Before any abrasive blast cleaning is performed on a steel surface, what is the mandatory first step according to SSPC-SP 1?",
"Solvent cleaning to remove all visible oil, grease, and cutting compounds.\nPower tool cleaning to remove loose rust.\nMeasuring the ambient dew point.\nApplying a rust converter.",
"Solvent cleaning to remove all visible oil, grease, and cutting compounds.",
"SSPC-SP 1 Solvent Cleaning is a prerequisite for all other surface preparation methods. Abrasive blasting a surface with oil or grease will merely drive the contaminants deeper into the steel profile, leading to premature coating failure.",
1),

(D,"mcq",
"3. When measuring environmental conditions before coating application, the steel surface temperature must typically be at least how many degrees above the dew point?",
"1°C (2°F)\n3°C (5°F)\n5°C (9°F)\n10°C (18°F)",
"3°C (5°F)",
"Standard industry practice and Saudi Aramco standards require the steel surface temperature to be a minimum of 3°C (approx. 5°F) above the dew point. This provides a safety margin to ensure invisible micro-condensation does not form on the steel, which would cause flash rusting or loss of coating adhesion.",
1),

(D,"mcq",
"4. What instrument is used to measure the surface profile (anchor pattern) created by abrasive blasting?",
"A sling psychrometer\nA dry film thickness (DFT) gauge\nTestex Press-O-Film replica tape and a spring micrometer\nA holiday detector",
"Testex Press-O-Film replica tape and a spring micrometer",
"Replica tape (e.g., Testex) is pressed into the blasted surface, creating a reverse replica of the peaks and valleys. The thickness of this replica is then measured with a specially calibrated spring micrometer to determine the surface profile depth, which ensures mechanical adhesion of the coating.",
1),

(D,"mcq",
"5. A multi-component epoxy coating is mixed. The manufacturer's data sheet specifies an 'induction time' (sweat-in time) of 15 minutes. What does this mean?",
"The time you have to apply the coating before it hardens.\nThe time required for the solvent to evaporate after application.\nThe mandatory waiting period after mixing the base and curing agent before application can begin.\nThe time it takes for the coating to become touch-dry.",
"The mandatory waiting period after mixing the base and curing agent before application can begin.",
"Induction time (or sweat-in time) is the required resting period after mixing the resin and hardener to allow the chemical cross-linking reaction to begin. Applying the coating before this time has elapsed can result in blushing, improper curing, or poor adhesion.",
1),

(D,"mcq",
"6. What is the primary purpose of a 'Stripe Coat' during a coating application?",
"To mark the boundaries of different inspection zones.\nTo apply an extra layer of coating by brush or roller to edges, corners, welds, and complex geometries where spray application may be thin.\nTo provide a decorative finish to the pipeline.\nTo act as a primer for the main coating.",
"To apply an extra layer of coating by brush or roller to edges, corners, welds, and complex geometries where spray application may be thin.",
"Coating tends to pull away from sharp edges and complex shapes due to surface tension during curing. Stripe coating ensures these critical, high-risk areas build adequate dry film thickness (DFT).",
1),

(D,"mcq",
"7. When measuring Dry Film Thickness (DFT) on a blasted surface using a magnetic gauge, what calibration adjustment must be made according to SSPC-PA 2?",
"No adjustment is needed.\nA base metal reading (BMR) or zero correction must be established on the bare blasted profile to account for the magnetic effect of the steel peaks.\nThe gauge must be calibrated on a smooth glass plate.\nThe readings must be multiplied by a factor of 1.5.",
"A base metal reading (BMR) or zero correction must be established on the bare blasted profile to account for the magnetic effect of the steel peaks.",
"The rough peaks of a blasted surface cause the DFT gauge probe to sit slightly above the true magnetic base. This creates a false positive thickness reading. Calibrating over a shim on the bare blasted profile, or establishing a Base Metal Reading (BMR) and subtracting it, corrects this error.",
1),

(D,"mcq",
"8. What defect is characterized by tiny, deep holes in the coating film that expose the substrate, often caused by trapped air, moisture, or solvent escaping during curing?",
"Chalking\nAlligatoring\nPinholing\nSaponification",
"Pinholing",
"Pinholes are minute, deep holes that often penetrate entirely to the substrate. They act as direct paths for corrosion and must be detected using a holiday detector and repaired.",
1),

(D,"mcq",
"9. Which of the following abrasive blasting media is STRICTLY prohibited for use on stainless steel surfaces?",
"Garnet\nAluminum Oxide\nGlass Beads\nCarbon Steel Grit or Chilled Iron Shot",
"Carbon Steel Grit or Chilled Iron Shot",
"Using carbon steel abrasives on stainless steel embeds free iron particles into the stainless surface. Upon exposure to moisture, these embedded iron particles will rapidly rust, causing localized galvanic corrosion and destroying the stainless steel's passivity.",
1),

(D,"mcq",
"10. High-voltage holiday detection (spark testing) is used to find flaws in coatings. If the test voltage is set too high for a given coating thickness, what can happen?",
"The detector will fail to find holidays.\nThe high voltage can burn a hole through (puncture) a perfectly good, sound coating.\nThe coating will cure too rapidly.\nThe battery of the detector will drain quickly.",
"The high voltage can burn a hole through (puncture) a perfectly good, sound coating.",
"Dielectric strength is the voltage a coating can withstand before breaking down. If the holiday detector voltage exceeds the dielectric strength of the applied film thickness, it will strike an arc right through the good coating, creating a new defect (burn-through). NACE SP0188 provides voltage formulas.",
1),

(D,"mcq",
"11. What is the phenomenon where a coating deteriorates on the surface due to UV light exposure, leaving a loose, powdery residue?",
"Blistering\nChecking\nChalking\nUndercutting",
"Chalking",
"Chalking is the degradation of the resin binder by ultraviolet (UV) radiation (sunlight), leaving the exposed pigment particles on the surface as a chalky powder. Epoxies are highly prone to chalking; hence they are usually topcoated with UV-resistant polyurethanes.",
1),

(D,"mcq",
"12. During surface preparation, a 'Bresle Patch' test is conducted. What is this test measuring?",
"Surface profile depth\nThe presence and concentration of soluble salts (like chlorides) on the steel surface\nAmbient humidity\nCoating adhesion",
"The presence and concentration of soluble salts (like chlorides) on the steel surface",
"The Bresle method (ISO 8502-6 and -9) extracts soluble salts from a blasted steel surface using deionized water in an adhesive patch. The conductivity of the water is then measured to determine the salt concentration (e.g., mg/m² of chlorides), which cause osmotic blistering if painted over.",
1),

(D,"mcq",
"13. In a 3-Layer Polyethylene (3LPE) pipeline coating system, what is the primary function of the first layer (Fusion Bonded Epoxy - FBE)?",
"To provide mechanical impact resistance.\nTo provide UV protection.\nTo provide superior adhesion to the steel and primary corrosion protection.\nTo act as a waterproof barrier.",
"To provide superior adhesion to the steel and primary corrosion protection.",
"In 3LPE, the FBE layer directly contacts the steel, providing excellent adhesion and cathodic disbondment resistance (corrosion protection). The middle layer (copolymer adhesive) bonds the FBE to the thick outer PE layer, which provides mechanical and moisture protection.",
1),

(D,"mcq",
"14. What does the term 'Pot Life' refer to when working with two-component paints?",
"The total shelf life of the paint in the warehouse.\nThe maximum time the mixed paint remains usable before it cures in the mixing bucket.\nThe time it takes for the paint to cure on the pipe.\nThe time required for the paint to become dry to touch.",
"The maximum time the mixed paint remains usable before it cures in the mixing bucket.",
"Pot life is the working time available after mixing the base and hardener. Once the pot life is exceeded, the exothermic reaction causes the paint to become too viscous to spray or apply, and it will harden in the 'pot'.",
1),

(D,"mcq",
"15. A Pull-Off Adhesion Test (e.g., using an Elcometer 106 or Defelsko Positest AT) is performed per ASTM D4541. The dolly pulls off at 15 MPa. Examination of the dolly shows it is 100% covered in the primer, and the steel substrate is completely exposed. What type of failure is this?",
"Cohesive failure within the primer.\nAdhesive failure between the primer and the topcoat.\nAdhesive failure between the primer and the steel substrate.\nGlue failure.",
"Adhesive failure between the primer and the steel substrate.",
"Because the break occurred exactly at the interface between the steel and the first coat of paint (leaving bare steel and a dolly full of primer), it is an adhesive failure between the substrate and the coating system.",
1),

(D,"mcq",
"16. What is 'Amine Blush'? ",
"A cosmetic issue caused by adding too much thinner.\nA sticky, waxy, or cloudy exudate on the surface of an epoxy coating caused by the reaction of the amine curing agent with moisture and carbon dioxide in the air.\nA type of paint used specifically for high-temperature service.\nA failure caused by abrasive blasting with contaminated grit.",
"A sticky, waxy, or cloudy exudate on the surface of an epoxy coating caused by the reaction of the amine curing agent with moisture and carbon dioxide in the air.",
"Amine blush occurs when epoxies are applied in high humidity or low temperatures. The blush acts as a bond-breaker. If a subsequent coat of paint is applied over un-removed amine blush, severe intercoat adhesion failure (delamination) will occur.",
1),

(D,"mcq",
"17. According to SSPC-PA 2, when taking a 'spot measurement' of Dry Film Thickness, how many individual gauge readings must be taken to calculate the average for that one spot?",
"One\nTwo\nThree\nFive",
"Three",
"SSPC-PA 2 defines a 'spot measurement' as the average of at least three gauge readings taken within a 1.5 inch (4 cm) diameter circle. This accounts for the micro-roughness of the surface profile.",
1),

(D,"mcq",
"18. Which coating defect is characterized by the paint film shrinking and pulling away from edges or itself, leaving bare spots resembling fish eyes?",
"Sagging\nOrange Peel\nCissing (Fisheyes)\nWrinkling",
"Cissing (Fisheyes)",
"Cissing or 'Fisheyes' is caused by surface contamination (typically oil, grease, or silicone) on the substrate or previous coat. The new paint cannot wet the contaminated surface and retracts, leaving a crater with a bare center.",
1),

(D,"mcq",
"19. In the context of Saudi Aramco standards (SAES-H-001), what is APCS?",
"Aramco Pipeline Coating Standard\nApproved Protective Coating Systems\nAutomated Paint Control System\nApplied Polymer Coating Standard",
"Approved Protective Coating Systems",
"APCS refers to the Approved Protective Coating Systems. Saudi Aramco assigns specific APCS numbers (e.g., APCS-1A, APCS-2B) to designate exact combinations of surface preparation, primers, and topcoats for specific environments (e.g., atmospheric, immersion, high temp).",
1),

(D,"mcq",
"20. When applying an inorganic zinc (IOZ) silicate primer, what environmental condition is uniquely REQUIRED for the coating to cure properly?",
"Extremely low humidity (below 30%)\nHigh ambient temperatures (above 40°C)\nMoisture (humidity in the air) to trigger the hydrolysis and polycondensation curing reaction.\nA vacuum environment.",
"Moisture (humidity in the air) to trigger the hydrolysis and polycondensation curing reaction.",
"Unlike epoxies that cure by chemical cross-linking of two mixed parts, inorganic zinc silicates cure by reacting with moisture in the atmosphere. If the air is too dry, IOZ will not cure and will remain powdery.",
1),

(D,"mcq",
"21. What is the primary purpose of Cathodic Disbondment Testing (CDT) for pipeline coatings?",
"To measure how well the coating resists UV degradation.\nTo evaluate the coating's resistance to separation from the steel substrate when subjected to a defect (holiday) and a cathodic protection (CP) current in a wet environment.\nTo determine the flexibility of the coating.\nTo measure the dielectric strength.",
"To evaluate the coating's resistance to separation from the steel substrate when subjected to a defect (holiday) and a cathodic protection (CP) current in a wet environment.",
"When a pipeline has a coating defect, the Cathodic Protection (CP) system drives current to the bare steel. This creates a highly alkaline environment at the defect (generating hydrogen gas). CDT tests how well the coating resists peeling away from the steel under these harsh chemical and physical conditions.",
1),

(D,"mcq",
"22. A contractor is applying a two-coat epoxy system. The manufacturer specifies a 'Maximum Overcoating Window' of 7 days. It has been 10 days since the first coat was applied. What is the required QC action before applying the second coat?",
"Proceed with coating; 3 days late is within typical tolerances.\nWash the surface with water and apply the second coat.\nThe first coat has cured too hard for chemical bonding. The surface must be sweep-blasted (abraded) to create a mechanical profile (tooth) and solvent-wiped before applying the second coat.\nApply an etchant acid to soften the first coat.",
"The first coat has cured too hard for chemical bonding. The surface must be sweep-blasted (abraded) to create a mechanical profile (tooth) and solvent-wiped before applying the second coat.",
"If the maximum overcoat window is exceeded, the first coat becomes fully cross-linked and glossy. A second coat applied over this will not chemically bond, leading to massive delamination. The gloss must be removed by sweep blasting to ensure mechanical adhesion.",
1),

(D,"mcq",
"23. Which abrasive is considered 'expendable' (used once and discarded) due to its friability?",
"Steel Grit\nSteel Shot\nCopper Slag (e.g., Black Beauty)\nAluminum Oxide",
"Copper Slag (e.g., Black Beauty)",
"Expendable abrasives like copper slag, coal slag, or garnet shatter upon impact with the steel. They are generally used for open blasting and discarded. Steel grit and shot are highly durable and are recycled hundreds of times in automated blast rooms.",
1),

(D,"mcq",
"24. What happens if paint is applied at a wet film thickness (WFT) significantly heavier than the manufacturer's recommendation?",
"The paint will cure faster and be stronger.\nDefects such as sagging, running, solvent entrapment, mud-cracking, and excessively long cure times are likely to occur.\nIt will increase the pot life of the remaining paint.\nNo negative effects, thicker is always better.",
"Defects such as sagging, running, solvent entrapment, mud-cracking, and excessively long cure times are likely to occur.",
"Applying paint too thickly is a major cause of failure. Solvents get trapped under the cured surface skin, leaving the paint soft underneath. On vertical surfaces, gravity pulls the heavy wet film down, causing sags and runs. Thickly applied inorganic zinc will 'mud-crack'.",
1),

(D,"mcq",
"25. In the context of surface preparation, what does the term 'Flash Rust' refer to?",
"Rust that forms on steel during the manufacturing process at the mill.\nLight, sudden rusting of a newly blast-cleaned steel surface, typically caused by high humidity, moisture, or rain before the primer is applied.\nRust caused by electrical flashover.\nRust under an existing coating.",
"Light, sudden rusting of a newly blast-cleaned steel surface, typically caused by high humidity, moisture, or rain before the primer is applied.",
"Freshly blasted steel is highly reactive. If exposed to moisture (high humidity, dropping below the dew point, or rain), it will rapidly oxidize (flash rust). Primer must be applied before this occurs, or the steel must be re-blasted.",
1),

(D,"mcq",
"26. What is a 'Wet Sponge' holiday detector used for?",
"Testing thick coatings over 500 microns (20 mils).\nMeasuring the moisture content of concrete.\nDetecting pinholes in thin-film coatings (typically less than 500 microns / 20 mils) on conductive substrates.\nCleaning the surface before painting.",
"Detecting pinholes in thin-film coatings (typically less than 500 microns / 20 mils) on conductive substrates.",
"A low-voltage wet sponge detector (typically 9V, 67.5V, or 90V) uses water to conduct electricity through a pinhole to the steel substrate, completing a circuit and sounding an alarm. It is safe for thin coatings where a high-voltage spark would burn through the paint.",
1),

(D,"mcq",
"27. What is the relationship between Wet Film Thickness (WFT), Dry Film Thickness (DFT), and Volume Solids (%VS)?",
"DFT = WFT + %VS\nDFT = WFT × (%VS / 100)\nWFT = DFT × (%VS / 100)\nThey are not related mathematically.",
"DFT = WFT × (%VS / 100)",
"Volume Solids (%VS) is the percentage of the paint that remains on the surface after all solvents have evaporated. If a paint is 60% Volume Solids, and you apply 100 microns of WFT, the resulting DFT will be 60 microns (100 × 0.60).",
1),

(D,"mcq",
"28. During inspection of a newly painted structural beam, you notice the coating has a rough, pebbly finish resembling the skin of an orange. What is the likely cause of this 'Orange Peel' defect?",
"Excessive thinning of the paint.\nApplying the paint in extremely cold weather.\nPoor flow and leveling of the paint, often due to applying the coating too close, too hot, or with improper atomization pressure/tip size.\nAbrasive grit left on the surface.",
"Poor flow and leveling of the paint, often due to applying the coating too close, too hot, or with improper atomization pressure/tip size.",
"Orange peel occurs when the paint droplets hit the surface but fail to flow out and level smoothly before the solvent evaporates. It is usually an application technique or equipment setup issue.",
1),

(D,"mcq",
"29. What is the primary function of an 'Airless' spray system compared to a 'Conventional' air spray system?",
"Airless uses compressed air to atomize the paint at the nozzle.\nAirless forces paint through a tiny tip at extremely high fluid pressure (e.g., 3000 psi) to atomize it, allowing for the application of high-viscosity, high-build coatings with less overspray.\nAirless is only used for very thin, watery liquids.\nAirless relies on gravity to feed the paint.",
"Airless forces paint through a tiny tip at extremely high fluid pressure (e.g., 3000 psi) to atomize it, allowing for the application of high-viscosity, high-build coatings with less overspray.",
"Conventional spray uses compressed air to blast the paint into a mist. Airless spray uses a hydraulic pump to put the paint itself under massive pressure. When it exits the tiny tungsten carbide tip, the sudden pressure drop shatters the paint into a fine mist. It applies paint much faster and thicker.",
1),

(D,"mcq",
"30. A coating specification calls for NACE No. 3 / SSPC-SP 6. What is the common name for this surface preparation grade?",
"White Metal Blast Cleaning\nNear-White Metal Blast Cleaning\nCommercial Blast Cleaning\nBrush-Off Blast Cleaning",
"Commercial Blast Cleaning",
"Commercial Blast Cleaning (SSPC-SP 6 / NACE 3 / ISO Sa 2) requires the removal of all visible oil, grease, dirt, rust, and mill scale. However, random staining from rust, mill scale, or old paint is permitted to remain on no more than 33% of each square inch of surface area.",
1),

(D,"mcq",
"31. When testing for soluble salts using a Bresle patch, why is it critical to ensure no air bubbles are trapped inside the patch during the extraction process?",
"Air bubbles will cause the water to boil.\nAir bubbles will dissolve into the water and increase the chloride reading.\nAir bubbles prevent the deionized water from contacting the steel surface in that area, leading to an incomplete extraction and a falsely low salt reading.\nAir bubbles will burst the patch.",
"Air bubbles prevent the deionized water from contacting the steel surface in that area, leading to an incomplete extraction and a falsely low salt reading.",
"The extraction relies on the deionized water washing the entire surface area within the patch. If an air bubble is present, the salt under that bubble is not dissolved, resulting in an inaccurate, low reading.",
1),

(D,"mcq",
"32. Thermal Spray Aluminum (TSA) is specified for a high-temperature piping system. How does TSA primarily protect the steel substrate?",
"By acting solely as a thick barrier coating.\nBy releasing corrosion inhibitors into the environment.\nBy providing a sacrificial (galvanic) cathodic protection layer; aluminum is more active than steel and will preferentially corrode if the coating is damaged.\nBy insulating the steel from high temperatures.",
"By providing a sacrificial (galvanic) cathodic protection layer; aluminum is more active than steel and will preferentially corrode if the coating is damaged.",
"TSA acts as an anodic, sacrificial coating. Even if the TSA is scratched and bare steel is exposed, the aluminum will act as a galvanic anode, protecting the exposed steel cathode from rusting.",
1),

(D,"mcq",
"33. What defect is typically caused by applying a hard, rigid topcoat over a softer, flexible primer, resulting in the topcoat cracking like dried mud?",
"Blistering\nAlligatoring (Crocodiling)\nUndercutting\nChalking",
"Alligatoring (Crocodiling)",
"Alligatoring (patterned cracking resembling reptile skin) occurs when a hard topcoat is applied over a soft undercoat, or when a topcoat is applied before the primer has sufficiently cured and solvent is still trapped.",
1),

(D,"mcq",
"34. According to SSPC-PA 2, if a 'spot measurement' (the average of 3 gauge readings) falls below the specified minimum DFT, but is still within a certain percentage, it may be acceptable depending on the restriction level. Under Restriction Level 3 (the default), what is the absolute lowest acceptable spot measurement?",
"100% of the specified minimum.\n80% of the specified minimum.\n50% of the specified minimum.\nThere is no minimum as long as the overall average is fine.",
"80% of the specified minimum.",
"Under SSPC-PA 2 Restriction Level 3, no single 'spot measurement' shall be less than 80% of the specified minimum DFT. (Note: individual gauge readings making up the spot can be lower, but their average must be >= 80%). Also, no spot measurement shall exceed 120% of the specified maximum.",
1),

(D,"mcq",
"35. Which standard provides visual reference photographs for evaluating the degree of rusting on painted steel surfaces?",
"SSPC-PA 2\nASTM D610\nISO 8502-3\nNACE SP0188",
"ASTM D610",
"ASTM D610 (Standard Practice for Evaluating Degree of Rusting on Painted Steel Surfaces) provides a 0 to 10 scale with visual references to quantify the percentage of the surface area that has failed due to rust.",
1),

(D,"mcq",
"36. What is 'Osmotic Blistering' in a coating system?",
"Blisters caused by excessive heat applied to the coating.\nBlisters formed when water vapor passes through a semi-permeable coating membrane to dissolve water-soluble salts left on the steel substrate, creating fluid pressure that pushes the coating off the steel.\nBlisters caused by solvent trapped between coats.\nBlisters caused by cathodic protection current.",
"Blisters formed when water vapor passes through a semi-permeable coating membrane to dissolve water-soluble salts left on the steel substrate, creating fluid pressure that pushes the coating off the steel.",
"All organic coatings are slightly permeable to moisture vapor. If soluble salts (like chlorides) are left on the steel, water vapor travels through the coating, dissolves the salt, creates a concentrated solution, and osmotic pressure draws more water in, creating a liquid-filled blister.",
1),

(D,"mcq",
"37. When mixing a zinc-rich epoxy primer, why must the mixture be continuously agitated during application?",
"To prevent the epoxy from curing too fast.\nTo keep the heavy zinc dust particles suspended in the liquid; otherwise, they will quickly settle to the bottom of the pot, resulting in a coating with no zinc on the pipe.\nTo incorporate air into the paint for better atomization.\nTo evaporate the solvent.",
"To keep the heavy zinc dust particles suspended in the liquid; otherwise, they will quickly settle to the bottom of the pot, resulting in a coating with no zinc on the pipe.",
"Zinc is a heavy metal. If a zinc-rich paint is not continuously stirred (using a pneumatic agitator on the spray pot), the zinc dust will fall to the bottom. The painter will end up spraying clear epoxy resin on the top half of the job, and thick zinc sludge on the bottom half.",
1),

(D,"mcq",
"38. What is the ISO standard test method for assessing dust quantity and size on steel surfaces prepared for painting (using clear adhesive tape)?",
"ISO 8501-1\nISO 8502-3\nISO 8502-6\nISO 8503",
"ISO 8502-3",
"ISO 8502-3 details the tape test. Clear adhesive tape is pressed onto the blasted steel and then transferred to a contrasting display board. The quantity and size of the dust particles adhering to the tape are compared against standard pictorial ratings.",
1),

(D,"mcq",
"39. A pipeline is buried underground. Which of the following coating properties is most critical for long-term survival in conjunction with Cathodic Protection?",
"High gloss finish\nResistance to chalking\nResistance to cathodic disbondment\nFlexibility at extreme low temperatures",
"Resistance to cathodic disbondment",
"Buried pipelines rely on a dual system: Coatings + Cathodic Protection (CP). If the coating is damaged, the CP system protects the bare steel but generates a high pH (alkaline) environment. The coating must resist peeling back (disbonding) under these alkaline conditions.",
1),

(D,"mcq",
"40. During application of an internal tank lining (e.g., Novolac Epoxy), the specification mandates a '100% Holiday-Free' finish. What equipment must the QC inspector use for final acceptance?",
"A wet sponge detector at 90 Volts.\nA high-voltage spark tester (DC holiday detector) set to the voltage calculated based on the final DFT (e.g., per NACE SP0188).\nA cross-hatch adhesion tester.\nA magnetic pull-off gauge.",
"A high-voltage spark tester (DC holiday detector) set to the voltage calculated based on the final DFT (e.g., per NACE SP0188).",
"For thick internal tank linings in critical service, high-voltage spark testing is mandatory to find microscopic pinholes. Wet sponge testing is only suitable for thin films (< 500 microns) and won't reliably detect deep flaws in thick tank linings.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Describe the complete Quality Control inspection process for the surface preparation of a carbon steel storage tank prior to the application of the primer. Detail the specific checks, tests, and standards used.",
"","",
"Grade on: 1. Pre-cleaning inspection (SSPC-SP1) for oil/grease. 2. Measure environmental conditions (Ambient Temp, RH, Dew Point, Steel Temp >3C above DP). 3. Inspect blasting equipment (oil/water traps, blotter test, abrasive cleanliness/chloride test). 4. Post-blast visual inspection to standard (e.g., Sa 2.5 / SSPC-SP 10). 5. Measure surface profile using Replica Tape (Testex). 6. Test for soluble salts (Bresle Patch, ISO 8502-6/9) against spec limits. 7. Dust test using tape method (ISO 8502-3).",
20),

(D,"essay",
"2. Explain the phenomenon of 'Osmotic Blistering' in protective coatings. What causes it, how is it prevented, and how can an inspector differentiate it from other types of blistering?",
"","",
"Grade on: Cause: Soluble salts (chlorides/sulfates) left on the substrate. Water vapor permeates the coating, dissolves the salt, creating a concentrated solution. Osmosis draws more water through the semi-permeable membrane (paint) to dilute the solution, creating massive hydraulic pressure that lifts the paint. Prevention: Strict salt testing (Bresle) and removal (washing/chlor-rid) before painting. Differentiation: If a blister is popped and the liquid inside is acidic/salty, or the substrate beneath is rusted/pitted, it is osmotic. (Solvent blisters are usually dry inside).",
20),

(D,"essay",
"3. Compare and contrast Airless Spray and Conventional Air Spray application methods. Discuss the advantages, disadvantages, and typical use cases for each.",
"","",
"Grade on: Airless: Uses hydraulic pressure (up to 5000psi) to force paint through a small tip, shattering it. Adv: Extremely fast, applies high-build/high-viscosity coatings, less bounce-back/overspray. Disadv: Harder to control fine finish, dangerous (injection hazard). Conventional: Uses compressed air to atomize paint at the nozzle. Adv: High operator control, excellent smooth finish. Disadv: Slow, cannot handle heavy mastics, creates massive overspray fog (wastes paint).",
20),

(D,"essay",
"4. You are auditing a coating contractor. Outline the specific documentation and traceability records you expect to find in the 'Coating Daily Inspection Report' for a major pipeline project.",
"","",
"Grade on: Date/Time/Location/Spool numbers. Weather conditions (AM/PM: RH, Air Temp, Steel Temp, Dew point). Abrasive used (type/batch). Surface prep results (Visual grade, Profile depth, Salt test results, Dust test). Coating application details: Paint Manufacturer, Product Name, Batch numbers of Base & Hardener, mixing ratio, pot life limits, thinner used/amount. WFT readings during application. DFT readings (As per SSPC-PA 2). Holiday testing results. Inspector signatures.",
20),

(D,"essay",
"5. Detail the procedure and acceptance criteria for performing High-Voltage Holiday Detection (Spark Testing) on a newly applied FBE pipeline coating according to NACE SP0188.",
"","",
"Grade on: Equipment verification: Ensure ground wire is securely attached to bare steel substrate. Calculate test voltage (e.g., V = 3290 * sqrt(DFT in mm) or consult spec). Verify voltage output with a jeep meter. Procedure: Move wand/spring over the surface at a moderate speed (approx 1 ft/sec). Do not linger in one spot (can burn through). Acceptance: Zero sparks/alarms. Any holidays found must be marked, repaired with approved patch material, and re-tested.",
20),

(D,"essay",
"6. What is a 'Stripe Coat', why is it critical in offshore and marine environments, and how should a QC inspector verify it has been applied correctly?",
"","",
"Grade on: Definition: An extra coat of paint applied by brush/roller to sharp edges, welds, bolts, and corners. Why: Surface tension pulls liquid paint away from sharp edges during curing, leaving them dangerously thin. These are always the first places to rust. Verification: Must be a contrasting color to the primer/subsequent coat. Inspector visually verifies that all welds and edges show the stripe coat color before the full spray coat covers it. Measure DFT specifically on edges if possible.",
20),

(D,"essay",
"7. Explain the application and curing mechanism of Inorganic Zinc (IOZ) silicate primers. Why are they notorious for application failures like 'Mud-cracking' and topcoat blistering?",
"","",
"Grade on: Curing: IOZ cures by reacting with moisture in the air (hydrolysis/polycondensation). Requires minimum humidity to cure (often >50%). Protection: Provides galvanic (sacrificial) protection. Mud-cracking: If applied too thick (> 4-5 mils), the rigid silicate matrix shrinks and cracks heavily like dried mud. Topcoat Blistering: IOZ is extremely porous. When topcoated, air trapped in the pores escapes through the wet topcoat, popping and leaving pinholes/blisters. Mitigation requires a thinned 'mist coat' before the full topcoat to seal the pores.",
20),

(D,"essay",
"8. A contractor is about to apply an epoxy coating over a surface that was primed 14 days ago. The manufacturer's data sheet specifies a 'Maximum Overcoat Interval' of 7 days. Describe the chemical problem occurring and the required remedial action.",
"","",
"Grade on: Problem: Epoxy cures by chemical cross-linking. Within the 7-day window, the surface is still reactive, allowing the next coat to chemically bond (cross-link) with the primer. After 14 days, the primer is fully cured, hard, and glossy. The new coat cannot chemically bond and will eventually peel off in sheets (intercoat adhesion failure). Remedial Action: The glossy surface must be mechanically abraded (Sweep Blasted) to create a rough physical 'tooth' for the new paint to adhere to mechanically. Solvent wiping is not enough.",
20),

(D,"essay",
"9. Describe the procedure for measuring Dry Film Thickness (DFT) on a complex structure according to SSPC-PA 2. Define Gauge Readings, Spot Measurements, and Area Measurements.",
"","",
"Grade on: Procedure: Calibrate gauge (verify accuracy on shims, establish Base Metal Reading/Zero over blast profile). Gauge Reading: A single instrument reading. Spot Measurement: The average of at least 3 gauge readings within a 1.5 inch (4cm) circle. Area Measurement: The average of 5 Spot Measurements taken randomly over a 100 square foot (10 m2) area. Criteria: Average of the Area must be >= specified DFT. No single Spot can be < 80% of specified DFT.",
20),

(D,"essay",
"10. Discuss the different methods of Adhesion Testing (e.g., Cross-Cut, X-Cut, Pull-Off). When would you use each, and what is the difference between a cohesive failure and an adhesive failure?",
"","",
"Grade on: Cross-Cut (ASTM D3359 Method B): Good for thin films (< 5 mils). Slicing a grid and applying tape. X-Cut (Method A): Good for thicker films in the field. Slicing an X and applying tape. Pull-Off (ASTM D4541): Gluing a dolly and pulling with hydraulic force; gives a quantitative value (MPa/psi). Failure types: Adhesive failure is a break at the boundary between layers (e.g., primer to steel, or topcoat to primer) indicating poor bond. Cohesive failure is a break WITHIN a single layer of paint, indicating the bond is stronger than the paint itself.",
20),

(D,"essay",
"11. What is the role of Cathodic Protection (CP) in conjunction with pipeline coatings? Explain what 'Cathodic Disbondment' is and why pipeline coatings are tested for it.",
"","",
"Grade on: Role: Coatings are the primary defense, but no coating is perfect. CP acts as a backup, sending electrical current to any bare steel exposed at holidays to prevent rusting. Cathodic Disbondment: The CP current arriving at the bare steel creates a highly alkaline (high pH) environment and generates hydrogen gas. This harsh chemical environment attacks the coating-to-steel bond, causing the coating to peel away from the holiday. Coatings must be formulated to resist this alkaline attack (tested via CDT - Cathodic Disbondment Testing).",
20),

(D,"essay",
"12. Outline the specific hazards and safety precautions associated with Abrasive Blast Cleaning in a confined space (e.g., inside a storage tank).",
"","",
"Grade on: Hazards: Massive dust generation (silicosis if sand is used, zero visibility), asphyxiation, toxic heavy metals from old paint (lead/zinc), static electricity buildup (explosion hazard), extreme noise, high-pressure injection. Precautions: Strictly confined space entry permit. Continuous forced ventilation/dust extraction. Supplied-air abrasive blasting respirators (Type CE). Grounding/bonding of all blast hoses and nozzles to prevent static sparks. 'Deadman' switch on the blast nozzle is mandatory. Gas monitoring.",
20),

(D,"essay",
"13. Explain the 3-Layer Polyethylene (3LPE) coating system used on pipelines. Detail the function and application method of each of the three layers.",
"","",
"Grade on: Layer 1: Fusion Bonded Epoxy (FBE). Applied as a dry powder onto pre-heated steel (approx 200°C), it melts and cures. Provides primary corrosion protection and excellent adhesion. Layer 2: Copolymer Adhesive. Extruded hot over the FBE. Acts as a chemical tie-coat binding the epoxy to the PE. Layer 3: Polyethylene (PE). Extruded thick outer jacket. Provides exceptional mechanical protection (handling, backfill impact) and a moisture barrier.",
20),

(D,"essay",
"14. You notice a painter thinning a two-part epoxy with an unknown solvent because 'it's too thick to spray.' As a QC inspector, explain why this is a critical non-conformance and what the consequences could be.",
"","",
"Grade on: Non-conformance: Thinners must be strictly approved by the paint manufacturer. Using the wrong solvent (e.g., a fast-evaporating lacquer thinner in an epoxy) can ruin the chemical curing reaction. Consequences: The coating may never fully cure (remains gummy). It changes the Volume Solids percentage, so the WFT calculation will be wrong, leading to low DFT. It may exceed local VOC emission limits. It can cause solvent entrapment and severe blistering later. Action: Stop work, reject the mixed paint, require approved thinner.",
20),

(D,"essay",
"15. Describe the phenomenon of 'Amine Blush'. What coatings does it affect, under what environmental conditions does it form, how is it detected, and how must it be removed?",
"","",
"Grade on: Affects: Amine-cured epoxies. Conditions: Forms when applied in high humidity, low temperatures, or environments with high carbon dioxide (e.g., direct-fired heaters). Reaction of amine curing agent with moisture/CO2. Detection: Leaves a sticky, cloudy, waxy film on the surface. Can cause yellowing. Removal: It is water-soluble. Must be washed off with warm soapy water and scrubbed. Solvent wiping will NOT remove it (just spreads it). If topcoated over, it causes massive intercoat delamination.",
20),

(D,"essay",
"16. Discuss the importance of monitoring 'Dew Point' and 'Steel Surface Temperature' during coating operations. What instrument is used to determine dew point, and what is the rule of thumb for safe application?",
"","",
"Grade on: Importance: Dew point is the temperature at which moisture in the air condenses into liquid water. If the steel is colder than the dew point, a microscopic, invisible layer of condensation forms on the steel. Painting over this water guarantees flash rusting and total adhesion failure. Instrument: Sling psychrometer (wet/dry bulb) or digital psychrometer to find dew point. Surface contact thermometer for steel. Rule of Thumb: Steel surface temperature MUST be a minimum of 3°C (5°F) ABOVE the dew point.",
20),

(D,"essay",
"17. A tank internal lining exhibits massive 'Sagging' and 'Running' on the vertical walls immediately after application. Discuss the possible application errors and environmental factors that caused this.",
"","",
"Grade on: Application errors: 1. Applying the paint too thick (exceeding max WFT per coat). 2. Gun held too close to the surface or moving too slowly. 3. Over-thinning the paint (lowering viscosity too much). 4. Using the wrong spray tip size (too large). Environmental: Cold temperatures slow down solvent evaporation, keeping the paint wet and heavy on the wall for longer, allowing gravity to pull it down. Heat can lower viscosity, also causing runs.",
20),

(D,"essay",
"18. Explain the difference between 'Volume Solids' and 'Weight Solids' in a coating data sheet. How do you use Volume Solids to calculate required Wet Film Thickness (WFT)?",
"","",
"Grade on: Difference: Volume solids represents the physical volume of paint left on the wall after the solvents evaporate. Weight solids is the mass percentage (less useful for thickness calculations). WFT Calculation: DFT = WFT × (Volume Solids % / 100). Therefore, WFT = DFT / (Volume Solids % / 100). If you need 100 microns DFT and the paint is 50% VS, you must apply 200 microns WFT (100 / 0.50). Adding thinner alters this calculation.",
20),

(D,"essay",
"19. What is Thermal Spray Aluminum (TSA)? Describe the application process and its primary advantage over traditional organic coatings in offshore environments.",
"","",
"Grade on: TSA is a metallic coating. Application: Aluminum wire or powder is fed into an arc or flame spray gun, melted, and atomized by compressed air onto heavily blasted steel (Sa 3.0 / sharp profile is critical). Primary Advantage: It is impervious to UV, operates at extremely high temperatures (up to 500°C+, preventing CUI - Corrosion Under Insulation), and acts as a sacrificial galvanic anode (it protects the steel even if scratched down to bare metal). Organic paints just act as a barrier.",
20),

(D,"essay",
"20. Detail the specific quality control checks required when applying a glass-flake reinforced polyester lining to the inside of a seawater storage tank.",
"","",
"Grade on: Surface Prep: Must be heavily blasted (Sa 2.5 or Sa 3.0) with a deep, sharp angular profile (e.g., 75-100 microns) because polyester shrinks heavily during cure and needs massive mechanical grip. Environment: Strict control of styrene vapor extraction. Application: WFT checks are difficult due to glass flakes; focus on consumption rates and inter-coat timing. Overcoating: Polyester has a very short overcoat window before it becomes too hard. Final Inspection: 100% High-Voltage Holiday Testing is mandatory. Barcol hardness test to ensure full cure.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. You measure the ambient conditions: Air Temp is 25°C, Dew Point is 22°C, and Steel Temp is 23°C. Do you allow the painters to start painting? Why or why not?",
"","",
"Grade on: No, stop work. The steel temperature (23°C) is only 1°C above the dew point (22°C). The industry standard and spec requirement is that the steel temperature must be a minimum of 3°C above the dew point to ensure no invisible micro-condensation forms on the surface.",
10),

(D,"oral",
"2. A blaster tells you he doesn't need to solvent wipe the steel before blasting because 'the blasting will take the grease right off'. How do you respond?",
"","",
"Grade on: Refuse permission to blast. Explain that blasting over oil or grease does NOT remove it; the high-velocity abrasive will simply drive the oil deep into the anchor profile of the steel, contaminating the entire surface and ensuring the paint will peel off. SSPC-SP 1 (Solvent Cleaning) is mandatory BEFORE blasting.",
10),

(D,"oral",
"3. What is a 'Blotter Test' and when is it performed?",
"","",
"Grade on: It is a test performed on the compressed air supply used for abrasive blasting or painting (per ASTM D4285). A clean white blotter paper or cloth is held in the air stream (downstream of separators) for 1-2 minutes. It is checked for any signs of water or oil contamination. If contaminated, the air supply must be fixed before work continues.",
10),

(D,"oral",
"4. Explain how you use Testex Replica Tape to measure surface profile.",
"","",
"Grade on: Clean the blasted surface. Place the tape (coarse or X-coarse) on the steel. Rub the circular cutout with a blunt burnishing tool until it turns uniformly gray (pebbly), indicating the foam has crushed into the valleys of the steel. Remove the tape and measure its thickness with a calibrated spring micrometer. Subtract the thickness of the incompressible Mylar backing (2 mils / 50 microns) to get the profile depth.",
10),

(D,"oral",
"5. What does the term 'Pot Life' mean, and what happens if you apply paint that has exceeded its pot life?",
"","",
"Grade on: Pot life is the amount of time a two-component paint remains usable after mixing the base and hardener. If you apply it after the pot life has expired, the chemical cross-linking is too advanced. The paint will not flow or wet out the surface properly, leading to terrible adhesion, dry spray, and a severely compromised coating.",
10),

(D,"oral",
"6. Why is 'Stripe Coating' required on welds, nuts, bolts, and sharp edges?",
"","",
"Grade on: Liquid paint has surface tension. As it dries/cures, it naturally pulls away from sharp edges and peaks, leaving them with a very thin, inadequate film thickness. Stripe coating involves manually brushing an extra layer of paint onto these complex areas to guarantee adequate thickness where corrosion usually starts first.",
10),

(D,"oral",
"7. You are using a magnetic DFT gauge on freshly blasted steel. Why must you calibrate it over a plastic shim on the BARE blasted steel instead of a smooth steel plate?",
"","",
"Grade on: Blasted steel has microscopic peaks and valleys. The magnetic gauge probe will sit on top of the highest peaks. The gauge measures the magnetic flux to the 'magnetic base' (somewhere below the peaks). If you don't account for this by zeroing on the bare blast profile (Base Metal Reading), your final paint thickness reading will be falsely high, reading paint that isn't actually covering the peaks.",
10),

(D,"oral",
"8. What is 'Flash Rust' and what causes it?",
"","",
"Grade on: Flash rust is a rapid, light oxidation that occurs on freshly blasted steel. It is typically caused by exposing the highly reactive blasted steel to high humidity, dropping temperatures (hitting the dew point), or rain before the primer can be applied. The steel turns brown/orange very quickly.",
10),

(D,"oral",
"9. Explain the difference between 'Adhesion' and 'Cohesion' in a paint system.",
"","",
"Grade on: Adhesion is the bond between TWO DIFFERENT materials (e.g., how well the primer sticks to the steel, or the topcoat sticks to the primer). Cohesion is the internal strength WITHIN a single layer of paint (how well the paint molecules stick to themselves).",
10),

(D,"oral",
"10. A contractor applies 200 microns Wet Film Thickness (WFT) of a paint that is 60% Volume Solids. What Dry Film Thickness (DFT) will remain after curing?",
"","",
"Grade on: DFT = WFT × Volume Solids. DFT = 200 × 0.60 = 120 microns. You can expect 120 microns of dry paint.",
10),

(D,"oral",
"11. Why is it dangerous to set the voltage too high on a Holiday Detector (Spark Tester)?",
"","",
"Grade on: Every coating has a dielectric strength (its ability to resist electrical breakdown). If you set the voltage too high for the applied film thickness, the spark will literally burn a hole right through a perfectly good, solid coating to reach the steel, destroying the coating system.",
10),

(D,"oral",
"12. What is 'Chalking' and what type of paint is most famous for doing it?",
"","",
"Grade on: Chalking is the UV (sunlight) degradation of the resin binder on the surface of the paint, leaving a loose, powdery residue of pigment. Epoxy coatings are notoriously susceptible to UV chalking, which is why they are usually topcoated with Polyurethanes outdoors.",
10),

(D,"oral",
"13. You find 'Mud-cracking' in a newly applied Inorganic Zinc (IOZ) primer. What caused it?",
"","",
"Grade on: Mud-cracking in IOZ is almost always caused by applying the coating too thickly. Because IOZ is heavily loaded with zinc dust and has a rigid silicate binder, it shrinks significantly as it cures. If it is too thick (usually > 4-5 mils), the internal stress causes it to shatter and crack like dried mud.",
10),

(D,"oral",
"14. What is the difference between 'Curing' and 'Drying' of a paint?",
"","",
"Grade on: Drying is a physical process where the solvents simply evaporate, leaving the solid resins behind (e.g., standard alkyd or acrylic paints). Curing is a chemical reaction (cross-linking) between two components (like an epoxy base and hardener) to form a completely new, solid plastic polymer.",
10),

(D,"oral",
"15. A painter wants to add extra thinner to the epoxy because it's a hot day. What are two quality problems this will cause?",
"","",
"Grade on: 1. It reduces the Volume Solids percentage. The painter will apply the same WFT but get a much lower DFT, failing inspection. 2. Excess solvent can get trapped in the film as the surface skins over in the heat, causing severe solvent popping (blistering/pinholes) later. 3. It may push the paint over local VOC emission limits.",
10),

(D,"oral",
"16. What does 'Sa 2.5' mean in ISO 8501-1?",
"","",
"Grade on: Sa 2.5 translates to 'Very Thorough Blast Cleaning' (or Near-White Metal). It means the surface must be free from visible oil, grease, dirt, mill scale, rust, and old paint. Any remaining traces of contamination can only appear as slight stains in the form of spots or stripes.",
10),

(D,"oral",
"17. Explain the 'Bresle Patch' test.",
"","",
"Grade on: It is a test to find invisible soluble salts (like chlorides) on blasted steel. An adhesive patch with a latex membrane is stuck to the steel. A known volume of deionized water is injected, massaged against the steel to dissolve any salts, and extracted. The conductivity of the water is then measured; higher conductivity means higher salt contamination.",
10),

(D,"oral",
"18. You see a painter spraying the second coat of epoxy 3 weeks after the first coat was applied. What is your concern?",
"","",
"Grade on: The 'Maximum Overcoat Interval' has likely been vastly exceeded. The first coat is fully cured and glossy, meaning the second coat cannot chemically bond to it. If applied as-is, the second coat will peel off in sheets (intercoat delamination). The surface must be abraded (sweep blasted) to provide a mechanical key before painting.",
10),

(D,"oral",
"19. What is 'Amine Blush' and how do you get rid of it?",
"","",
"Grade on: It is a sticky or waxy film that forms on the surface of curing epoxies in high humidity or cold weather (the amine hardener reacts with moisture and CO2). It MUST be washed off with warm soapy water. Wiping it with solvent will not remove it, it will just spread it around. If you paint over it, the paint will peel.",
10),

(D,"oral",
"20. Why must abrasive blasting NOT be performed on stainless steel using carbon steel grit?",
"","",
"Grade on: Carbon steel grit will embed microscopic iron particles into the relatively soft stainless steel surface. As soon as moisture hits the pipe, these iron particles will rust aggressively, causing galvanic corrosion pits that destroy the passivity and integrity of the stainless steel.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Identify the items required to perform a Blotter Test on a blasting air compressor, and demonstrate the procedure.",
"","",
"Grade on: Needs a piece of clean, white, absorbent cloth or blotter paper. Position the cloth in the discharge air stream (after the oil/water separators) for 1 to 2 minutes. Examine the cloth for any signs of water droplets or oil stains. If clear, the air supply is accepted.",
15),

(D,"practical",
"2. Given a Sling Psychrometer, demonstrate how to determine the ambient relative humidity and dew point.",
"","",
"Grade on: Wet the 'wet bulb' wick with distilled water. Spin the psychrometer rapidly for approx 1-2 minutes until temperatures stabilize. Read both the dry bulb and wet bulb temperatures. Use the provided psychrometric chart (or slide rule) to intersect the two temperatures to find the Relative Humidity and Dew Point.",
15),

(D,"practical",
"3. Demonstrate the proper method for measuring surface profile using Testex Replica Tape and a spring micrometer.",
"","",
"Grade on: 1. Clean the micrometer anvils and zero the gauge. 2. Select appropriate tape grade (e.g., X-Coarse). 3. Stick tape to blasted steel. 4. Use burnishing tool to rub the circular Mylar area until it uniformly turns a dark gray (pebbled appearance). 5. Remove tape, place between micrometer anvils. 6. Read measurement and SUBTRACT 50 microns (2 mils) for the Mylar backing.",
15),

(D,"practical",
"4. You are handed a WFT (Wet Film Thickness) comb. Demonstrate how to correctly use it on a freshly painted curved pipe.",
"","",
"Grade on: Press the comb perpendicularly and firmly into the wet paint down to the substrate. On a curved pipe, ensure the comb is placed longitudinally (parallel to the pipe axis) so all teeth can touch the surface without rocking. Remove and observe the teeth. The WFT is between the highest value tooth that has paint on it and the next highest tooth that is clean.",
15),

(D,"practical",
"5. Evaluate a blasted steel panel against the ISO 8501-1 visual standard book. Justify whether it meets Sa 2, Sa 2.5, or Sa 3.",
"","",
"Grade on: Compare panel to the photos. Sa 2 (Commercial): mostly clean, but distinct residual staining/shadows allowable. Sa 2.5 (Near-White): completely clean of scale/rust, only slight, faint stains/stripes allowable. Sa 3 (White Metal): perfectly uniform gray/white metal, absolutely no staining or shadows allowed.",
15),

(D,"practical",
"6. Demonstrate how to perform a tape test for dust assessment according to ISO 8502-3.",
"","",
"Grade on: Use specific clear adhesive tape. Press a strip of tape firmly onto the blasted steel surface (using thumb or roller). Peel off the tape and stick it onto a contrasting display board (usually black and white striped). Compare the quantity and size of the dust particles captured against the pictorial standards in the ISO manual.",
15),

(D,"practical",
"7. Given a Type 2 electronic magnetic DFT gauge and plastic calibration shims, demonstrate the proper calibration process (Verification of Accuracy and Base Metal Reading) before taking measurements.",
"","",
"Grade on: 1. Verify accuracy by measuring a certified shim on a smooth steel block. 2. Move to the unpainted, blasted steel structure. 3. Place a plastic shim (close to target DFT) on the blasted steel. 4. Measure the shim. 5. Adjust the gauge down to read the known shim thickness, effectively zeroing out the profile effect. (Alternatively, take 10 readings on bare steel, average them for the BMR, and subtract this from future paint readings).",
15),

(D,"practical",
"8. Perform a Cross-Cut Adhesion Test (ASTM D3359) on a provided thin-film coated panel. Evaluate the result.",
"","",
"Grade on: Use a multi-blade cutter (or single blade with guide). Cut a lattice grid into the paint down to the substrate. Brush lightly. Apply standard test tape over the grid, rub firmly with an eraser, and pull off rapidly at an angle close to 180 degrees. Inspect the grid using magnification. Rate from 5B (no peeling) to 0B (massive flaking > 65%) based on the ASTM chart.",
15),

(D,"practical",
"9. Given a Wet Sponge Holiday Detector, demonstrate the setup, verification, and testing of a 200-micron coated panel.",
"","",
"Grade on: Connect ground wire to bare steel edge of the panel. Wet the sponge with plain water (maybe a drop of surfactant/soap). Verify operation by touching the wet sponge to the bare steel ground (should beep/alarm). Glide the sponge across the painted surface at approx 1 ft/sec. Mark any locations that cause an alarm.",
15),

(D,"practical",
"10. Calculate the required WFT: The spec requires 150 microns DFT. The paint datasheet states Volume Solids are 75%. No thinner is added.",
"","",
"Grade on: Formula: WFT = DFT / (Volume Solids %). WFT = 150 / 0.75. WFT = 200 microns. The painter must apply 200 microns of wet paint to achieve 150 microns dry.",
15),

(D,"practical",
"11. Calculate the required WFT with Thinner: Spec requires 100 microns DFT. Volume solids = 60%. The painter adds 10% thinner by volume. What is the new required WFT?",
"","",
"Grade on: Thinner reduces the solid content. Adjusted Volume Solids = VS / (1 + %Thinner) = 60 / 1.10 = 54.5%. New WFT = DFT / Adjusted VS = 100 / 0.545 = 183 microns. (Candidate must demonstrate understanding that adding thinner requires applying a THICKER wet film to get the same dry film).",
15),

(D,"practical",
"12. Given a High-Voltage DC Spark Tester, demonstrate how to safely set the voltage and verify the output using a Jeep Meter.",
"","",
"Grade on: State safety rules (keep hands off wand tip, ensure no explosive gases). Calculate required voltage based on spec (e.g., 100V per mil). Set dial on detector. Connect ground cable. Touch the wand to the high-voltage probe of a standalone 'Jeep Meter' to verify the actual output voltage matches the dial setting. Adjust if necessary.",
15),

(D,"practical",
"13. Perform a Bresle Patch extraction (simulation) on a steel panel and explain how to read the conductivity meter.",
"","",
"Grade on: Apply patch firmly, squeezing out air. Use a syringe to draw 3ml of deionized water. Inject water into patch. Massage the water against the steel for 2-3 minutes. Extract the water back into the syringe. Inject into the conductivity meter well. Multiply the microSiemens reading by the patch factor (e.g., x1 for a standard 3ml patch) to get mg/m2 of salt.",
15),

(D,"practical",
"14. Inspect a painted panel with several defects. Visually identify 'Sagging', 'Pinholing', and 'Orange Peel'. Explain the likely cause of each.",
"","",
"Grade on: Sagging (teardrops/curtains running down): Applied too thick, over-thinned, or spray gun too close. Pinholing (tiny deep holes): Solvent popping, air trapped, spraying over porous substrate (like zinc). Orange Peel (pebbly surface like citrus skin): Poor atomization, pressure too low, paint too thick, or gun held too far away.",
15),

(D,"practical",
"15. Evaluate a coating thickness report according to SSPC-PA 2 rules. Given a set of 5 spot measurements: 85, 90, 110, 120, 115 microns. Target DFT is 100 microns. Is the area accepted or rejected?",
"","",
"Grade on: Rule 1: Area average must be >= 100. Average = (85+90+110+120+115)/5 = 104. Pass. Rule 2: No single spot can be < 80% of target (80 microns). Lowest is 85. Pass. Rule 3: No single spot can be > 120% of target (120 microns). Highest is 120. Pass. The area is ACCEPTED.",
15),

(D,"practical",
"16. Demonstrate how to determine the mixing ratio of a two-part epoxy if you are mixing a partial batch in the field without pre-measured cans.",
"","",
"Grade on: Must refer to the Technical Data Sheet (TDS). Check if the ratio is by VOLUME or by WEIGHT (they are often different due to density). Use calibrated mixing cups (for volume) or a digital scale (for weight). Mix the base thoroughly first, then slowly add the hardener while stirring with a pneumatic/explosion-proof mixer.",
15),

(D,"practical",
"17. Review a Paint Technical Data Sheet (TDS). Locate and state the 'Pot Life' at 30°C, the 'Induction Time', and the 'Maximum Overcoat Interval'.",
"","",
"Grade on: Ability to navigate and extract critical QC data from a complex manufacturer document. Explain that higher temperatures drastically shorten the pot life and overcoat intervals.",
15),

(D,"practical",
"18. You are inspecting a hot-dip galvanized handrail that needs to be painted. Explain the required surface preparation (Sweep Blasting).",
"","",
"Grade on: Galvanizing is too smooth for paint adhesion, but heavy blasting will destroy the protective zinc layer. Sweep blasting requires low pressure (40-50 psi), a fine non-metallic abrasive, and holding the nozzle further back at an angle. The goal is to just 'frost' or dull the surface to provide a profile without removing the zinc.",
15),

(D,"practical",
"19. Demonstrate the proper way to mix a zinc-rich primer. What is the critical step regarding the zinc dust?",
"","",
"Grade on: The liquid resin must be stirred while the zinc dust is slowly sifted in to prevent clumping. CRITICAL STEP: Because zinc is extremely heavy, the paint pot MUST have continuous, constant mechanical agitation during the entire spraying process to keep the zinc suspended. Otherwise, it will settle to the bottom in minutes.",
15),

(D,"practical",
"20. Analyze a failure scenario: A painted pipeline stored outside for 6 months is now peeling badly. The topcoat is peeling away from the primer. The primer is intact. The primer is an epoxy. What is the most likely cause?",
"","",
"Grade on: UV Degradation / Chalking leading to Overcoat window violation. Epoxies left exposed to UV light chalk heavily and their surface becomes impenetrable to new paint. The topcoat was likely applied after the maximum overcoat window without sweeping the epoxy, or the chalky residue was not washed off before topcoating, causing intercoat adhesion failure.",
15),

]  # end QUESTIONS
