"""
Communications QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: BICSI, TIA/EIA-568, SAES-T-Series, IEEE 802.11, IEEE 802.3
"""

D = "Communications QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. According to TIA/EIA-568 standards, what is the maximum allowable permanent link length for Category 6 (Cat 6) UTP copper cabling for 1000BASE-T (Gigabit Ethernet) applications?",
"50 meters\n90 meters\n100 meters\n150 meters",
"90 meters",
"The permanent link (the fixed cable in the wall from the patch panel to the work area outlet) is limited to 90 meters. The remaining 10 meters of the 100-meter total channel limit is reserved for patch cords (equipment cords).",
1),

(D,"mcq",
"2. When terminating a Cat 6 UTP cable onto an RJ45 jack, how much untwisting of the wire pairs is permitted to maintain Category 6 certification?",
"Up to 2 inches (50 mm)\nUp to 1 inch (25 mm)\nMaximum 0.5 inches (13 mm)\nUntwisting doesn't matter as long as the colors match.",
"Maximum 0.5 inches (13 mm)",
"To prevent Near-End Crosstalk (NEXT) and maintain the high-frequency performance of Cat 6 cabling, the wire pairs must remain twisted as close to the point of termination as possible, with a strict maximum untwist of 0.5 inches (13 mm).",
1),

(D,"mcq",
"3. In single-mode fiber optic cabling (SMF), what is the typical core diameter?",
"9 microns (µm)\n50 microns (µm)\n62.5 microns (µm)\n125 microns (µm)",
"9 microns (µm)",
"Single-mode fiber (SMF) has a very small core (typically 9 µm) allowing only one mode of light to propagate, which eliminates modal dispersion and allows for massive bandwidth over very long distances (kilometers). The cladding diameter is 125 µm.",
1),

(D,"mcq",
"4. What is the primary cause of 'Attenuation' in an optical fiber?",
"Crosstalk from adjacent fibers.\nScattering and absorption of light by impurities in the glass core.\nThe speed of light changing in the vacuum.\nElectromagnetic interference from power lines.",
"Scattering and absorption of light by impurities in the glass core.",
"Attenuation is the loss of optical power (signal strength) as light travels through the fiber, primarily caused by Rayleigh scattering and absorption by impurities (like water/OH ions) in the glass.",
1),

(D,"mcq",
"5. When performing an OTDR (Optical Time-Domain Reflectometer) test on a fiber optic link, a sudden 'spike' or upward peak on the trace graph usually indicates:",
"A perfect fusion splice.\nA macro-bend in the cable.\nA highly reflective event, such as a mechanical connector, a mechanical splice, or a broken fiber end face.\nA loss of power at the transmitter.",
"A highly reflective event, such as a mechanical connector, a mechanical splice, or a broken fiber end face.",
"OTDRs measure reflected light. Connectors and polished breaks cause Fresnel reflection, bouncing a strong pulse of light back to the OTDR, which appears as a sharp spike on the trace.",
1),

(D,"mcq",
"6. According to Saudi Aramco standard SAES-T-911, what is the required physical separation distance between unshielded telecommunications cables (UTP) and a 415V, 20A electrical power cable to prevent EMI?",
"No separation is required if they are in conduit.\n50 mm (2 inches)\n150 mm (6 inches) to 300 mm (12 inches) depending on conduit type\n1000 mm (39 inches)",
"150 mm (6 inches) to 300 mm (12 inches) depending on conduit type",
"To prevent Electromagnetic Interference (EMI) from disrupting data signals, telecommunications cables must be separated from power cables. Standard practice (TIA-569 and SAES-T) dictates 6 to 12 inches separation depending on whether the pathways are metallic and grounded.",
1),

(D,"mcq",
"7. What is 'NEXT' in copper data cabling testing?",
"Near-End Crosstalk; interference between two pairs in a cable measured at the same end of the cable as the interfering transmitter.\nNext Expected Transmit; a protocol timing delay.\nNoise Elimination X-Transmission; a shielding standard.\nNear-End X-ray Testing; a cable inspection method.",
"Near-End Crosstalk; interference between two pairs in a cable measured at the same end of the cable as the interfering transmitter.",
"NEXT occurs when a strong transmit signal on one pair couples (induces noise) into an adjacent receiver pair at the same end of the cable, swamping the weak incoming signal. It is a critical failure parameter for UTP cables.",
1),

(D,"mcq",
"8. Which fiber optic connector type uses a 'push-pull' latching mechanism and has a 2.5 mm ferrule?",
"LC (Lucent Connector)\nSC (Subscriber Connector / Standard Connector)\nST (Straight Tip)\nMPO (Multi-fiber Push On)",
"SC (Subscriber Connector / Standard Connector)",
"The SC connector has a square body, uses a push-pull mechanism for quick insertion, and features a standard 2.5 mm ferrule. (LC is smaller with a 1.25 mm ferrule and a retaining tab).",
1),

(D,"mcq",
"9. In outside plant (OSP) fiber optic cable installation, what is the primary purpose of 'loose tube' cable construction?",
"To make the cable easier to strip.\nTo isolate the fragile glass fibers from physical stresses (pulling tension, temperature expansion/contraction) exerted on the outer cable jacket.\nTo allow water to flow through the cable.\nTo reduce the weight of the cable.",
"To isolate the fragile glass fibers from physical stresses (pulling tension, temperature expansion/contraction) exerted on the outer cable jacket.",
"Loose tube cables feature fibers floating loosely inside gel-filled buffer tubes. If the outer cable stretches due to pulling tension or shrinks in the cold, the fibers inside have room to move without being subjected to tensile stress or micro-bending.",
1),

(D,"mcq",
"10. When terminating structured cabling, the T568B wiring scheme dictates that Pin 1 and Pin 2 of the RJ45 jack are which pair?",
"White/Orange and Orange\nWhite/Green and Green\nWhite/Blue and Blue\nWhite/Brown and Brown",
"White/Orange and Orange",
"In the TIA/EIA T568B standard, Pair 2 (Orange) is terminated on pins 1 & 2. (In T568A, Pair 3 - Green - is on pins 1 & 2).",
1),

(D,"mcq",
"11. What is the maximum acceptable insertion loss (attenuation) for a single fusion splice in a fiber optic network, according to typical BICSI/TIA standards?",
"0.01 dB\n0.30 dB\n0.75 dB\n1.50 dB",
"0.30 dB",
"TIA-568 specifies a maximum allowable loss of 0.3 dB per fusion splice. High-quality fusion splicers routinely achieve much lower losses (e.g., 0.02 to 0.05 dB). A splice over 0.3 dB is typically rejected and remade.",
1),

(D,"mcq",
"12. Which of the following wavelengths is standard for long-haul Single-Mode Fiber (SMF) transmission?",
"850 nm\n1300 nm\n1550 nm\n650 nm",
"1550 nm",
"Single-mode systems typically operate at 1310 nm or 1550 nm. 1550 nm is preferred for long-haul because it experiences the lowest optical attenuation (loss) in silica glass, allowing transmission over vast distances.",
1),

(D,"mcq",
"13. In a telecommunications grounding system (TMGB/TGB), what is the maximum acceptable bonding resistance between the equipment chassis and the main grounding busbar?",
"0.1 Ohms\n1.0 Ohms\n5.0 Ohms\n25.0 Ohms",
"0.1 Ohms",
"To ensure safety and proper reference for sensitive electronic equipment, bonding connections in telecom rooms must have extremely low resistance, typically less than 0.1 ohms.",
1),

(D,"mcq",
"14. What does the term 'PoE' stand for in networking?",
"Point of Entry\nPower over Ethernet; delivering low-voltage DC power alongside data over standard UTP cables to devices like IP cameras and WAPs.\nProtocol over Ethernet\nPulse Optical Emitter",
"Power over Ethernet; delivering low-voltage DC power alongside data over standard UTP cables to devices like IP cameras and WAPs.",
"PoE (IEEE 802.3af/at/bt) allows network switches to supply both data and electrical power (up to 90W for latest standards) over standard Cat5e/Cat6 cables, eliminating the need for separate electrical outlets for end devices.",
1),

(D,"mcq",
"15. A contractor is pulling a 48-core fiber optic cable through a conduit. What is a critical QC parameter that must be monitored during the pull to prevent permanent damage?",
"The color of the pull string.\nThe maximum pulling tension and the minimum bend radius.\nThe ambient humidity.\nThe MAC address of the cable.",
"The maximum pulling tension and the minimum bend radius.",
"Optical fibers are glass. Exceeding the manufacturer's maximum pulling tension (typically 600 lbs for OSP cable) will stretch and break the fibers. Exceeding the minimum bend radius (typically 20x cable OD during pulling) will cause micro-bends and fiber fracture.",
1),

(D,"mcq",
"16. In microwave radio communications, what does 'Line of Sight' (LOS) refer to?",
"The ability to see the other tower with binoculars.\nThe first Fresnel zone between the transmitting and receiving antennas must be completely clear of physical obstacles (trees, buildings, terrain) for optimal signal propagation.\nThe laser beam used to align the antennas.\nThe flight path of aircraft.",
"The first Fresnel zone between the transmitting and receiving antennas must be completely clear of physical obstacles (trees, buildings, terrain) for optimal signal propagation.",
"Microwave links require an unobstructed path. It's not just a straight visual line; the radio waves spread out in an elliptical shape called the Fresnel zone. If obstacles encroach into this zone, the signal is diffracted and attenuated, causing link degradation or failure.",
1),

(D,"mcq",
"17. What is 'Return Loss' in a copper data cabling test?",
"The time it takes for a ping to return.\nThe measure of signal reflections occurring along the cable due to impedance mismatches (e.g., poor terminations, kinks in the cable).\nThe loss of power at the receiver.\nThe cost of replacing the cable.",
"The measure of signal reflections occurring along the cable due to impedance mismatches (e.g., poor terminations, kinks in the cable).",
"Return loss measures how much of the transmitted signal reflects back to the source. High return loss (meaning good performance, little reflection) is required for Gigabit Ethernet, which transmits bi-directionally on all four pairs and can be confused by its own echoes.",
1),

(D,"mcq",
"18. Which tool is mandatory for definitively certifying that a newly installed Cat 6A cabling link meets TIA/ISO performance standards for 10-Gigabit Ethernet?",
"A wiremap tester (continuity tester).\nA multimeter.\nA Tier 1 / Level III or IV Cable Certification Tester (e.g., Fluke DSX).\nA laptop pinging a server.",
"A Tier 1 / Level III or IV Cable Certification Tester (e.g., Fluke DSX).",
"Simple continuity testers only check wiring. To certify a link for high-speed data, a specialized certification tester must sweep frequencies up to 500 MHz (for Cat 6A) to measure complex RF parameters like NEXT, Return Loss, Insertion Loss, and Alien Crosstalk.",
1),

(D,"mcq",
"19. What is an 'APC' (Angled Physical Contact) fiber optic connector, and why is it used?",
"A connector made of plastic.\nA connector where the ferrule end-face is polished at an 8-degree angle, forcing reflected light into the cladding to dramatically reduce Optical Return Loss (ORL); commonly used in video and PON networks.\nA connector used only for multi-mode fiber.\nA connector that requires no polishing.",
"A connector where the ferrule end-face is polished at an 8-degree angle, forcing reflected light into the cladding to dramatically reduce Optical Return Loss (ORL); commonly used in video and PON networks.",
"Standard UPC (Ultra Physical Contact) connectors reflect some light straight back down the core. APC connectors (always Green color) have an angled face so reflections bounce off at an angle and are absorbed by the cladding, protecting sensitive lasers and video signals from echo noise.",
1),

(D,"mcq",
"20. In an industrial plant, a communication network is being designed for critical Safety Instrumented Systems (SIS). What network topology provides the highest level of redundancy against cable cuts?",
"Bus Topology\nStar Topology\nSelf-healing Ring Topology (e.g., using MRP or RSTP protocols)\nDaisy Chain Topology",
"Self-healing Ring Topology (e.g., using MRP or RSTP protocols)",
"A ring topology connects switches in a closed loop. If a fiber is cut anywhere in the ring, network protocols (like Rapid Spanning Tree Protocol or Media Redundancy Protocol) instantly detect the break and route traffic the other way around the ring, ensuring zero downtime.",
1),

(D,"mcq",
"21. What is the standard impedance of coaxial cable used for broadband video (CCTV/CATV) transmission?",
"50 Ohms\n75 Ohms\n100 Ohms\n120 Ohms",
"75 Ohms",
"75-ohm coaxial cable (like RG-6 or RG-11) is the standard for video and CATV. 50-ohm cable (like RG-58) is typically used for radio frequency (RF) communications and older Ethernet (Thinnet).",
1),

(D,"mcq",
"22. According to Saudi Aramco standard SAES-T-928, what is the required clearance depth for buried direct-laid telecommunications cables in normal soil?",
"300 mm (12 inches)\n600 mm (24 inches)\n900 mm (36 inches) minimum, with warning tape placed above.\n100 mm (4 inches)",
"900 mm (36 inches) minimum, with warning tape placed above.",
"To protect critical telecom infrastructure from accidental excavation damage, SAES requires deep burial (typically 900 mm) with a non-degradable warning tape buried roughly halfway between the cable and the surface.",
1),

(D,"mcq",
"23. When installing a Wireless Access Point (WAP) in an explosion-proof (Zone 1) hazardous area, what must be true about the antenna?",
"It must be removed.\nIt must be certified Intrinsically Safe (IS) or housed within an Ex d explosion-proof dome with an RF-transparent window.\nIt can be a standard plastic antenna if it is painted black.\nIt must be grounded to the plant water pipe.",
"It must be certified Intrinsically Safe (IS) or housed within an Ex d explosion-proof dome with an RF-transparent window.",
"Standard antennas can generate RF sparks or heat. In Zone 1, the entire WAP must be in an Ex d enclosure. The antenna itself must either be behind an explosion-proof dome (which causes signal loss) or the antenna circuit must be certified Intrinsically Safe via an IS barrier.",
1),

(D,"mcq",
"24. What is 'Alien Crosstalk' (AXT) in data cabling?",
"Interference from outer space.\nInterference coupling from one cable into an adjacent cable within the same bundle, particularly problematic in high-frequency 10GBASE-T (Cat 6A) installations.\nCrosstalk between different pairs in the same cable.\nInterference from a wireless router.",
"Interference coupling from one cable into an adjacent cable within the same bundle, particularly problematic in high-frequency 10GBASE-T (Cat 6A) installations.",
"Unlike NEXT, which is internal to one cable, AXT is noise jumping from one cable to another bundled tightly next to it. Because the DSP in the switch cannot cancel noise from a separate cable, AXT is a critical limiting factor for 10-Gigabit Ethernet over copper.",
1),

(D,"mcq",
"25. In a Public Address / General Alarm (PA/GA) system, why is a 100V (or 70V) line system used for speakers instead of connecting 8-ohm speakers directly?",
"To make the speakers louder.\nTo minimize voltage drop and power loss over long cable runs, allowing dozens of speakers to be daisy-chained on a small gauge wire.\nTo prevent electrical shock.\nTo improve bass response.",
"To minimize voltage drop and power loss over long cable runs, allowing dozens of speakers to be daisy-chained on a small gauge wire.",
"Similar to electrical transmission grids, PA systems step up the audio voltage to 100V at the amplifier. This lowers the current, drastically reducing I²R line losses over long plant distances. A step-down transformer at each speaker converts it back.",
1),

(D,"mcq",
"26. What does the term 'MAC Address' refer to in a communications network?",
"A software IP address.\nA Media Access Control address; a unique, physical, 48-bit hardware identifier assigned to a network interface card (NIC) by the manufacturer.\nThe location of a Macintosh computer.\nA routing protocol.",
"A Media Access Control address; a unique, physical, 48-bit hardware identifier assigned to a network interface card (NIC) by the manufacturer.",
"The MAC address operates at Layer 2 (Data Link Layer) of the OSI model. It is the permanent physical address of the device on the local network segment, unlike an IP address which is assigned dynamically and routes across networks.",
1),

(D,"mcq",
"27. A fiber optic 'V-Groove' is commonly associated with which process?",
"Cable manufacturing.\nMechanical splicing and alignment of fibers in a fusion splicer.\nCleaning the fiber end-face.\nTesting the fiber.",
"Mechanical splicing and alignment of fibers in a fusion splicer.",
"A V-Groove is a precision-machined trench used to physically align two microscopic glass fibers perfectly end-to-end before they are clamped and fused together by an electric arc in a fusion splicer.",
1),

(D,"mcq",
"28. What is the standard test method for determining if a fiber optic end-face is clean before mating it?",
"Wiping it on your shirt.\nBlowing on it with compressed air.\nUsing a Fiber Inspection Microscope (probe) with a video display to visually verify it is free of dirt, oil, and scratches per IEC 61300-3-35.\nRunning a ping test.",
"Using a Fiber Inspection Microscope (probe) with a video display to visually verify it is free of dirt, oil, and scratches per IEC 61300-3-35.",
"A microscopic speck of dirt on a 9-micron core will completely block the light or scratch the mating connector. A video inspection scope is mandatory to verify cleanliness before EVERY mating. 'Inspect Before You Connect'.",
1),

(D,"mcq",
"29. In a CCTV camera installation, what does the 'Varifocal' lens feature allow the technician to do?",
"Change the color balance of the camera.\nAdjust the focal length (zoom in or out) and focus manually during installation to capture the exact desired field of view.\nPan and tilt the camera remotely.\nSee in the dark using infrared.",
"Adjust the focal length (zoom in or out) and focus manually during installation to capture the exact desired field of view.",
"A varifocal lens provides flexibility. Unlike a fixed lens (e.g., exactly 3.6mm), a varifocal lens (e.g., 2.8mm to 12mm) allows the installer to adjust the zoom mechanically at the camera to perfectly frame the scene without moving the camera housing.",
1),

(D,"mcq",
"30. Which testing parameter indicates the difference in arrival time of signals on the four different pairs of a Cat 6 cable?",
"Insertion Loss\nDelay Skew\nReturn Loss\nNEXT",
"Delay Skew",
"Because Gigabit Ethernet splits the data packet across all four pairs simultaneously, the packets must arrive at the receiver at almost the exact same time. Delay Skew measures the difference in travel time. If the twist rates of the pairs differ too much, the delay skew will be too high, causing packet errors.",
1),

(D,"mcq",
"31. According to BICSI best practices, what is the minimum bend radius for a 4-pair UTP cable once installed (not during pulling)?",
"1 inch (25 mm)\n4 times the cable diameter (approx. 1 inch / 25 mm for Cat 6)\n10 times the cable diameter\nThere is no minimum bend radius for copper.",
"4 times the cable diameter (approx. 1 inch / 25 mm for Cat 6)",
"Bending copper data cables too sharply distorts the precisely engineered twist rate of the pairs, causing an impedance mismatch that severely degrades NEXT and Return Loss. The strict rule is a minimum bend radius of 4x the cable Outside Diameter (OD).",
1),

(D,"mcq",
"32. What is an 'ODF' in a telecommunications room?",
"Optical Data Format\nOptical Distribution Frame; a rack/cabinet used to terminate, splice, and patch fiber optic cables.\nOmni-Directional Frequency\nOutside Data Facility",
"Optical Distribution Frame; a rack/cabinet used to terminate, splice, and patch fiber optic cables.",
"An ODF is the primary physical interface for fiber optics in a telecom room. It houses splice cassettes, slack storage, and patch panels, organizing thousands of fragile fiber connections safely.",
1),

(D,"mcq",
"33. In industrial networking, RS-485 is a standard for:",
"High-speed fiber optics.\nSerial, multi-drop, differential data transmission over a twisted pair, allowing long distances (up to 1200m) and multiple devices (like PLCs) on one bus.\nWireless Wi-Fi.\nAnalog video transmission.",
"Serial, multi-drop, differential data transmission over a twisted pair, allowing long distances (up to 1200m) and multiple devices (like PLCs) on one bus.",
"RS-485 is a robust serial communication standard. Because it uses differential signaling on a twisted pair, it is highly immune to electrical noise, making it the backbone of industrial protocols like Modbus RTU.",
1),

(D,"mcq",
"34. When installing conduit for telecom cables in a concrete slab, why are 'sweep' bends (long radius bends) required instead of standard 90-degree plumbing elbows (LB fittings)?",
"To save money on fittings.\nSweep bends maintain the minimum bend radius for telecom cables during pulling, whereas a sharp LB fitting will kink, crush, or break fiber and data cables.\nTo allow water to drain.\nTo make the conduit look better.",
"Sweep bends maintain the minimum bend radius for telecom cables during pulling, whereas a sharp LB fitting will kink, crush, or break fiber and data cables.",
"Standard electrical 'LB' or 'Condulet' sharp 90-degree fittings cannot be used for telecom. Fiber and Cat 6 cannot be pulled through a hard 90 without destroying their geometry. Factory sweeps with a radius of at least 6-10x the conduit diameter are mandatory.",
1),

(D,"mcq",
"35. What is the purpose of a 'Consolidation Point' (CP) in a structured cabling design?",
"To mix power and data cables.\nAn intermediate interconnection point within a ceiling or raised floor that allows flexible zone cabling to modular furniture or work areas without pulling new cables all the way back to the telecom room.\nTo cool the servers.\nTo amplify the signal.",
"An intermediate interconnection point within a ceiling or raised floor that allows flexible zone cabling to modular furniture or work areas without pulling new cables all the way back to the telecom room.",
"A CP creates a 'zone'. A heavy bundle of cables runs from the Telecom Room to the CP. From the CP, short patch cables run to the desks. If the desks move, only the short cables change, saving immense labor and cost.",
1),

(D,"mcq",
"36. What is the function of an 'Optical Attenuator' in a fiber optic link?",
"To clean the fiber.\nTo boost the signal strength.\nTo intentionally reduce the optical power (dim the light) at the receiver to prevent overloading (blinding/burning out) the sensitive photodiode when the cable run is very short.\nTo split the signal to two receivers.",
"To intentionally reduce the optical power (dim the light) at the receiver to prevent overloading (blinding/burning out) the sensitive photodiode when the cable run is very short.",
"Transceivers are rated for a specific distance (e.g., a 40km optic). If you connect a 40km optic over a 2km cable, the light arriving is far too bright and will saturate or destroy the receiver. An attenuator acts like sunglasses to reduce the power to safe levels.",
1),

(D,"mcq",
"37. In an IP-based CCTV system, what does 'PTZ' stand for?",
"Primary Time Zone\nPan, Tilt, and Zoom; a camera that can be remotely directed and zoomed by an operator.\nPower To Zone\nPhysical Transport Zero",
"Pan, Tilt, and Zoom; a camera that can be remotely directed and zoomed by an operator.",
"PTZ cameras have built-in motors allowing a security operator to remotely rotate the camera left/right (Pan), up/down (Tilt), and magnify the image (Zoom) via the network to track a subject.",
1),

(D,"mcq",
"38. According to Saudi Aramco standard SAES-T-888, what is the backup power requirement for critical telecommunications equipment rooms?",
"None, they run on plant power.\nDual-redundant UPS systems backed up by an emergency diesel generator, providing continuous power without interruption.\nSolar panels only.\nBatteries lasting 30 minutes.",
"Dual-redundant UPS systems backed up by an emergency diesel generator, providing continuous power without interruption.",
"Critical telecom (safety networks, PA/GA, core switching) cannot fail during a plant outage. They require a highly reliable UPS system to hold the load seamlessly while the standby generator starts.",
1),

(D,"mcq",
"39. When measuring the shielding effectiveness of a coaxial cable, a 'TDR' is often used. What does TDR stand for?",
"Total Data Rate\nTime-Domain Reflectometer; a device that sends an electrical pulse down a copper cable and measures the reflections to locate faults (similar to how an OTDR works for fiber).\nTerminal Device Router\nTemporary Data Retention",
"Time-Domain Reflectometer; a device that sends an electrical pulse down a copper cable and measures the reflections to locate faults (similar to how an OTDR works for fiber).",
"A TDR acts like an electrical radar. It sends a pulse down a coax or twisted pair. If it hits a short, an open, a crush, or water ingress, the impedance change reflects energy back. The TDR times the echo to tell you exactly how many meters down the cable the fault is.",
1),

(D,"mcq",
"40. What is 'OM3' fiber?",
"A type of Single-Mode Fiber.\nA specific grade of Multi-Mode Fiber (MMF) optimized for 10-Gigabit Ethernet transmission using 850 nm VCSEL lasers, characterized by an aqua-colored jacket.\nAn outdoor copper cable.\nA type of microwave antenna.",
"A specific grade of Multi-Mode Fiber (MMF) optimized for 10-Gigabit Ethernet transmission using 850 nm VCSEL lasers, characterized by an aqua-colored jacket.",
"OM3 (and OM4) are laser-optimized 50/125 µm multimode fibers. Unlike older OM1/OM2 fibers that used LEDs, OM3 uses cheap VCSEL lasers to achieve 10Gbps data rates over short data-center distances (up to 300m).",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Describe the comprehensive quality control testing procedure for certifying a newly installed 48-port Cat 6A UTP cabling panel. What instrument is used, what parameters are tested, and what constitutes a pass?",
"","",
"Grade on: Instrument: Level IV Cable Certification Tester (e.g., Fluke DSX-8000). Procedure: Test Permanent Link (patch panel to faceplate). Attach smart remotes to both ends. Tester sweeps frequencies up to 500 MHz. Parameters: Wiremap (continuity, split pairs), Length (<90m), Insertion Loss, NEXT, PSNEXT, ACR-F, PSACR-F, Return Loss, Delay Skew. Pass: All parameters must show a green 'Pass' with positive headroom (margin) against the TIA-568 Category 6A limits. Test reports saved to PDF.",
20),

(D,"essay",
"2. Explain the difference between Single-Mode Fiber (SMF) and Multi-Mode Fiber (MMF). Discuss core size, light sources, modal dispersion, distance limitations, and typical applications in an industrial plant.",
"","",
"Grade on: MMF: Large core (50/62.5 µm). Uses LED or VCSEL lasers. Light travels in multiple paths (modes) which causes Modal Dispersion (pulses blur together over distance). Distance limited to ~300-500m at high speeds. Used for LANs/intra-building. SMF: Tiny core (9 µm). Uses expensive laser diodes. Only one path (mode) of light, eliminating modal dispersion. Virtually unlimited bandwidth over huge distances (up to 100km+ without repeating). Used for WANs, OSP, inter-building plant backbones.",
20),

(D,"essay",
"3. You are a QC inspector witnessing fiber optic fusion splicing. Detail the steps the technician must take to ensure a high-quality splice, from stripping the fiber to shrinking the protection sleeve.",
"","",
"Grade on: 1. Slide protection sleeve on. 2. Strip outer jacket, Kevlar, and buffer tube. 3. Strip 250µm primary coating using precision strippers. 4. Clean bare glass thoroughly with 99% isopropyl alcohol and lint-free wipe (must 'squeak'). 5. Cleave fiber using a precision cleaver (must be a perfect 90-degree cut). 6. Place in splicer V-groove. 7. Splicer aligns cores and arcs to melt glass. 8. Verify estimated splice loss (< 0.05 dB). 9. Perform proof test (tension). 10. Slide sleeve over splice and bake in the heater oven.",
20),

(D,"essay",
"4. What is an OTDR (Optical Time-Domain Reflectometer)? Explain how it works, what a trace looks like, and what specific faults or features it can identify in a fiber optic cable.",
"","",
"Grade on: How it works: Sends a high-power pulse of laser light down the fiber and measures the timing and power of light scattered (Rayleigh scattering) and reflected (Fresnel reflection) back. Trace: X-axis is distance, Y-axis is optical power (dB). Sloping line = normal fiber attenuation. Downward steps = splice loss (fusion/mechanical). Upward spikes = reflective events (connectors, breaks). Sudden drop to noise floor = cable break. Used to pinpoint exactly how many meters down a 10km cable a break occurred.",
20),

(D,"essay",
"5. Discuss the installation requirements for outside plant (OSP) buried telecommunications conduits. Include trench depth, conduit types, separation from power, warning tapes, and pull boxes.",
"","",
"Grade on: Depth: Typically 900mm (36 inches) per SAES-T. Conduit: Thick-walled PVC or HDPE duct. Separation: Strict minimum separation from high-voltage cables (e.g., 300mm to 1000mm depending on voltage) to prevent EMI and excavation risk. Warning: Bright orange/green warning tape buried halfway between conduit and surface. Pull Boxes/Manholes: Installed every ~150-200m or at major directional changes to allow cable pulling without exceeding tension limits. Long sweep bends mandatory.",
20),

(D,"essay",
"6. Explain the concept of 'Power over Ethernet' (PoE). What are the advantages, what are the IEEE standards (PoE, PoE+, PoE++), and what QC concerns arise when running high-power PoE over large cable bundles?",
"","",
"Grade on: Concept: Injecting 48VDC power onto the same twisted pairs used for data. Advantages: Powers WAPs, cameras, phones without needing a 110V electrician. Standards: 802.3af (15W), 802.3at (PoE+, 30W), 802.3bt (PoE++, up to 90W). QC Concerns: Heat generation. When pushing 90W through 100 cables bundled tightly in a tray, the heat cannot escape. The cable temperature rises, increasing insertion loss, which can cause the data link to fail or the cable to exceed its temperature rating. Bundles must be kept small.",
20),

(D,"essay",
"7. What is 'Structured Cabling'? Describe the hierarchical topology including the Main Distribution Frame (MDF), Intermediate Distribution Frame (IDF), Backbone Cabling, and Horizontal Cabling.",
"","",
"Grade on: Structured Cabling is a standardized architecture for campus networks. MDF (Main Telecom Room): Houses core switches and servers. IDF (Telecom Closets): Located on each floor/area, housing edge switches. Backbone Cabling: Heavy fiber optic cables linking the MDF to all IDFs (vertical/campus runs). Horizontal Cabling: The copper Cat 6/6A cables running from the IDF patch panels through the ceiling to the individual user desks (faceplates). This star topology allows easy management and upgrades.",
20),

(D,"essay",
"8. A CCTV camera provides a blurry image at night, but a clear image during the day. Explain 'IR Shift' and how a 'True Day/Night' (ICR) camera solves this problem.",
"","",
"Grade on: IR Shift: Light waves of different colors focus at slightly different points through a lens. Infrared (IR) light (used at night) focuses at a different depth than visible light (day). If focused by eye during the day, it will be blurry under IR light at night. True Day/Night: Uses a mechanical IR Cut Filter (ICR). During the day, the filter moves over the sensor to block IR, giving true colors. At night, a motor moves the filter away, letting IR in, and the camera shifts focus/switches to B&W to stay sharp.",
20),

(D,"essay",
"9. You are inspecting a telecommunications grounding system (TMGB/TGB). Detail the specific requirements for busbars, bonding conductors, and the connection method to ensure a highly reliable ground.",
"","",
"Grade on: Busbars: Must be solid copper, pre-drilled, mounted on insulators. Conductors: Must be sized correctly (e.g., 6 AWG or larger), green/yellow jacket, routed with minimum bends and no sharp angles (lightning hates sharp turns). Connections: Must use 2-hole copper compression lugs (crimped with proper die, not set-screw). Paint/anodizing MUST be scraped to bare metal on the rack/chassis before bolting the lug. Anti-oxidant paste applied. Test resistance < 0.1 ohms.",
20),

(D,"essay",
"10. Explain what a 'Split Pair' is in a UTP cable termination. Why does a simple wiremap tester often miss this fault, and why is it disastrous for data transmission?",
"","",
"Grade on: Split Pair: The installer connects the wires to the correct pins (e.g., Pin 1/2 and Pin 3/6), but pairs the WRONG colors together (e.g., using one orange wire and one green wire for Pin 1/2). Wiremap Tester: A cheap tester only checks continuity (Pin 1 goes to Pin 1). It sees continuity and says 'Pass'. Disastrous: Ethernet relies on twisted pairs to cancel out electromagnetic noise (common-mode rejection). If the transmit signal is split across two different twists, it creates massive crosstalk (NEXT) and zero noise cancellation. The link will fail instantly.",
20),

(D,"essay",
"11. Describe the function and inspection criteria for a Public Address / General Alarm (PA/GA) system in a hazardous industrial facility.",
"","",
"Grade on: Function: Mass notification for emergency evacuation and general paging. Highly critical life-safety system. Inspection criteria: A+B redundancy (two separate amplifier racks, dual interleaved speaker loops so if one wire is cut, half the speakers still work). Speakers must be Ex-certified for the area (e.g., Ex d horn speakers). Verify 100V line impedance testing. Intelligibility testing (STI - Speech Transmission Index) to ensure messages can be understood over loud plant background noise. Battery backup (UPS) verification.",
20),

(D,"essay",
"12. What are the key QC considerations when installing Wireless Access Points (WAPs) in an industrial warehouse environment (high ceilings, metal racks)?",
"","",
"Grade on: 1. Antennas: Omni-directional antennas placed 15m high will only talk to the roof. Must use directional patch antennas pointed down aisles. 2. Interference: Metal racks reflect RF signals, causing severe multipath interference and dead spots. Must perform an active RF Site Survey to dictate placement. 3. Cabling: Cat 6 cables running to high ceilings must not exceed 90m length. 4. Enclosures: Must be NEMA 4X (dust/water) or Ex-rated if hazardous, which requires external antenna pigtails.",
20),

(D,"essay",
"13. Discuss the safety hazards associated with working on fiber optic cables and lasers. What specific safety protocols must a QC inspector enforce?",
"","",
"Grade on: 1. Invisible Lasers: Telecom lasers (1310/1550nm) are invisible to the human eye but will instantly burn the retina causing permanent blindness. NEVER look into a live fiber or connector. Always use an optical power meter to check for light. 2. Glass Shards: Cleaved fiber ends are microscopic glass needles. They can penetrate skin and travel through the bloodstream. Must use a fiber trash can (sharps container) for all off-cuts. No eating/drinking in splicing areas. Wear safety glasses.",
20),

(D,"essay",
"14. Explain the difference between 'Tier 1' and 'Tier 2' testing for fiber optic cabling according to TIA/BICSI standards.",
"","",
"Grade on: Tier 1 (Basic): Measures the overall insertion loss (attenuation) of the entire link using an Optical Loss Test Set (OLTS - a light source and a power meter). Also measures length and verifies polarity. It gives a pass/fail against the loss budget. Tier 2 (Extended): Includes all Tier 1 tests PLUS an OTDR trace. The OTDR provides a graphical picture of the link, measuring the specific loss of EVERY individual splice and connector along the path. Required by Aramco for full acceptance.",
20),

(D,"essay",
"15. You are reviewing the 'Optical Loss Budget' calculation for a proposed 5km single-mode fiber link. What factors go into this calculation, and how is it used during commissioning?",
"","",
"Grade on: Factors: Cable attenuation (e.g., 5km * 0.35 dB/km = 1.75 dB). Number of connectors (e.g., 2 connectors * 0.75 dB = 1.5 dB). Number of splices (e.g., 4 splices * 0.3 dB = 1.2 dB). Total budget = 1.75 + 1.5 + 1.2 = 4.45 dB. Commissioning: The technician uses an OLTS to measure the ACTUAL loss of the installed cable. If the actual loss (e.g., 3.2 dB) is LESS than the calculated budget (4.45 dB), the link PASSES. If it is higher, there is a bad splice/bend that must be fixed.",
20),

(D,"essay",
"16. What is 'Return Loss' in fiber optics (ORL - Optical Return Loss)? Why is it critical for high-speed single-mode systems, and how is it minimized?",
"","",
"Grade on: ORL is the amount of light that hits a connector or splice and reflects straight backward toward the transmitter. Critical: High-speed lasers are highly sensitive to back-reflections. If light bounces back into the laser cavity, it destabilizes the laser, causing signal jitter and bit errors. Minimized by: Perfectly cleaning connectors before mating. Using APC (Angled Physical Contact) connectors which bounce reflections into the cladding. Ensuring perfect, bubble-free fusion splices.",
20),

(D,"essay",
"17. Describe the design and QC inspection of a telecommunications equipment room (MDF/Telecom Closet). What environmental and structural features must be verified?",
"","",
"Grade on: Location: Above flood level, not sharing walls with heavy electrical transformers (EMI). HVAC: Dedicated 24/7 cooling with positive pressure to prevent dust; IT equipment generates massive heat. Fire: FM-200 or Novec clean agent fire suppression (no water sprinklers). Access: Access control (badge reader). Physical: 19-inch racks securely bolted to floor. Overhead cable trays properly grounded. Adequate clearance (usually 3 feet front and back of racks) for maintenance.",
20),

(D,"essay",
"18. In an Access Control System (ACS), describe the typical components at a secure door and how the 'Fail Safe' vs 'Fail Secure' philosophy affects the selection of electronic locks.",
"","",
"Grade on: Components: Card Reader (Wiegand/OSDP), Electronic Lock (Maglock or Electric Strike), Door Contact (monitors open/closed state), Request to Exit (REX) motion sensor/button, Controller panel. Fail Safe: Maglocks require power to stay locked. If power fails (or fire alarm triggers), the lock drops power and OPENS. Required for emergency egress doors. Fail Secure: Electric strikes require power to UNLOCK. If power fails, they stay LOCKED. Used for high-security IT/Server rooms where security trumps egress (people can still use the mechanical door handle from the inside).",
20),

(D,"essay",
"19. What is 'Bend Radius' and why is it critical for both Copper (Cat 6A) and Fiber Optic cables? What are the typical rules of thumb?",
"","",
"Grade on: Bending stretches the outside and compresses the inside of a cable. Fiber: Exceeding bend radius causes 'macro-bending' (light leaks out of the core, causing massive attenuation) or the glass fractures. Copper: Bending too sharply alters the twist geometry of the pairs, ruining the impedance and causing NEXT/Return Loss failures. Rules: Fiber during pulling = 20x Cable OD. Fiber installed = 10x OD. Copper installed = 4x OD.",
20),

(D,"essay",
"20. Explain the purpose and testing of an IP-based Telephone system (VoIP). What network parameter is absolutely critical for VoIP to function clearly without robotic voices or dropped words?",
"","",
"Grade on: VoIP converts voice audio into digital IP packets and sends them over the LAN. Critical Parameter: QoS (Quality of Service) prioritizing voice packets, and specifically controlling 'Jitter' and 'Latency'. Because voice is real-time, if packets are delayed by heavy network traffic (latency > 150ms) or arrive out of order (jitter), the DSP cannot reassemble the audio smoothly, resulting in choppy, robotic sound. The network switches must be configured/tested to give voice VLANs absolute priority.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. A contractor is pulling Cat 6 cable with a truck. What do you do and why?",
"","",
"Grade on: Stop work immediately. Cat 6 cable has a maximum pulling tension of 25 lbs (11 kg) — basically the strength of one hand pulling. A truck will stretch the copper, permanently ruining the twist rate and the cable's ability to transmit data. The cable must be replaced.",
10),

(D,"oral",
"2. You are inspecting a patch panel and notice the installer has untwisted 2 inches of the Cat 6 pairs to make them reach the punch-down block easily. Is this acceptable?",
"","",
"Grade on: No. TIA standards mandate that the pairs must remain twisted up to exactly 0.5 inches (13mm) from the termination point. Untwisting 2 inches removes the noise cancellation properties, guaranteeing the link will fail the Near-End Crosstalk (NEXT) certification test.",
10),

(D,"oral",
"3. What is the difference between a 'Permanent Link' and a 'Channel' in structured cabling testing?",
"","",
"Grade on: The Permanent Link is the fixed cable hidden in the wall/ceiling, running from the patch panel to the wall outlet (Max 90m). The Channel includes the Permanent Link PLUS the user patch cords at both ends connecting the PC and the Switch (Max 100m). We test the Permanent Link for warranty because patch cords change.",
10),

(D,"oral",
"4. What does a flashing red laser (VFL - Visual Fault Locator) do in fiber optics?",
"","",
"Grade on: It injects a highly visible red laser into a fiber. It is used to trace a specific fiber through a messy rack, or to visually find a break. If a fiber is broken inside a splice tray or jumper, the red light will leak out and glow brightly through the plastic jacket at the break point.",
10),

(D,"oral",
"5. Why must you never look directly into a disconnected fiber optic cable?",
"","",
"Grade on: Telecom lasers (especially in single-mode systems) operate in the infrared spectrum (1310nm/1550nm). The light is completely invisible to the human eye, so you won't blink, but the laser energy will focus on your retina and cause permanent blindness instantly. Always assume a fiber is live.",
10),

(D,"oral",
"6. What is the difference between an SC connector and an LC connector?",
"","",
"Grade on: SC (Standard/Subscriber Connector) is a large, square, push-pull connector with a 2.5mm ferrule. LC (Lucent Connector) is a modern, small-form-factor connector that looks like a plastic RJ45 clip, with a 1.25mm ferrule. LC allows for double the density on a patch panel.",
10),

(D,"oral",
"7. Why do we use an OTDR instead of just a flashlight to test a long fiber cable?",
"","",
"Grade on: A flashlight (or VFL) only tells you if light makes it to the other end. An OTDR (Optical Time-Domain Reflectometer) tells you exactly HOW MUCH light is lost, and more importantly, exactly WHERE every splice, connector, and break is located along a 100km cable by measuring the time it takes for reflections to return.",
10),

(D,"oral",
"8. A CCTV camera on a metal pole is showing moving horizontal lines (hum bars) on the video feed. What is the likely cause?",
"","",
"Grade on: A Ground Loop. The camera chassis is grounded to the pole, and the coax cable shield is grounded at the DVR in the control room. If there is a voltage difference between the pole earth and the DVR earth, AC current flows down the coax shield, creating 60Hz magnetic interference (hum bars). Fix: Install a ground loop isolator.",
10),

(D,"oral",
"9. What is 'Power over Ethernet' (PoE)?",
"","",
"Grade on: PoE is a technology that allows standard Ethernet cables (Cat 5e/6) to carry both data and safe, low-voltage DC electrical power (48V) simultaneously. It allows devices like IP cameras, phones, and Wi-Fi access points to be installed anywhere without needing a separate electrician to install a power outlet.",
10),

(D,"oral",
"10. Why is a 'Service Loop' (Slack loop) left at the end of a telecom cable run?",
"","",
"Grade on: It provides extra length (typically 3 meters in the ceiling above the rack, 1 meter at the desk) to allow the patch panel to be moved, or to allow the technician to cut off the jack and re-terminate the cable a few times if they make a mistake or if the jack breaks in the future.",
10),

(D,"oral",
"11. What is the purpose of an MDF (Main Distribution Frame)?",
"","",
"Grade on: The MDF is the central 'brain' or main telecom room of a building or campus. It houses the core network switches, servers, PBX, and the main demarcation point where the outside telephone/internet lines enter the building. All other IDFs (closets) connect back to the MDF.",
10),

(D,"oral",
"12. You are asked to test a fiber with an OLTS (Optical Loss Test Set). What two pieces of equipment are you holding?",
"","",
"Grade on: An OLTS consists of a calibrated Light Source (plugged into one end of the fiber to inject a known power level) and a Power Meter (plugged into the other end to measure how much power actually arrives). The difference is the Insertion Loss of the cable.",
10),

(D,"oral",
"13. Why do we use Single-Mode Fiber for long distances instead of Multi-Mode?",
"","",
"Grade on: Multi-mode has a large core that allows light to bounce around in multiple paths (modes). Over long distances, these paths take different amounts of time, causing the data pulses to smear together (Modal Dispersion). Single-mode has a microscopic core that only allows light to travel straight down the middle, eliminating dispersion and allowing huge distances.",
10),

(D,"oral",
"14. What color is the jacket of a standard Single-Mode fiber patch cord, and what color is Multi-Mode (OM3)?",
"","",
"Grade on: By industry standard (TIA-598), Single-Mode (OS1/OS2) patch cords are Yellow. Multi-Mode OM1/OM2 are typically Orange. Laser-optimized Multi-Mode OM3/OM4 are Aqua.",
10),

(D,"oral",
"15. What is a 'Split Pair' error in copper cabling?",
"","",
"Grade on: It's a wiring error where the installer punches down the wires to the correct pins, but uses wires from two different twisted pairs to make a circuit. A basic tester shows continuity (Pin 1 to Pin 1), but because the signals aren't twisted together, there is massive crosstalk and the data link fails.",
10),

(D,"oral",
"16. Why must you meticulously clean a fiber optic connector before plugging it in?",
"","",
"Grade on: The core of a single-mode fiber is 9 microns (smaller than a dust particle). A single speck of dust, oil from a fingerprint, or condensation will completely block the laser light. Worse, when you push the connectors together, the dirt will grind into the glass and permanently scratch the polished end-face.",
10),

(D,"oral",
"17. What is 'NEXT' (Near-End Crosstalk)?",
"","",
"Grade on: Crosstalk is electromagnetic noise. NEXT happens when the strong signal transmitting out of Pin 1&2 acts like a radio transmitter and induces its noise into the adjacent receiver pins (3&6) at the SAME END of the cable. It overwhelms the weak incoming signal from the far end. Usually caused by untwisting wires too much at the jack.",
10),

(D,"oral",
"18. You are inspecting a telecom rack and see a green/yellow wire connecting the rack to a copper bar on the wall. What is this?",
"","",
"Grade on: This is the Telecommunications Bonding Backbone (TBB). The rack is bonded to the Telecommunications Grounding Busbar (TGB) to ensure all metal chassis are at the exact same earth potential. This protects equipment from lightning/surges and prevents ground loops that corrupt data.",
10),

(D,"oral",
"19. What is an APC (Angled Physical Contact) fiber connector, and what color is it?",
"","",
"Grade on: An APC connector is always Green. The glass tip is polished at an 8-degree angle. Instead of reflecting light straight back down the pipe (which messes up lasers), the angle bounces any reflections harmlessly into the side cladding. Used heavily in video, PON, and long-haul networks.",
10),

(D,"oral",
"20. In Access Control, what is the difference between a 'Fail Safe' and 'Fail Secure' lock?",
"","",
"Grade on: 'Fail Safe' (like a magnetic lock) needs power to stay locked; if the power goes out, the door unlocks so people can escape a fire. 'Fail Secure' (like an electric strike) needs power to unlock; if the power goes out, it stays locked to keep the room secure (used for server rooms).",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Demonstrate the proper technique for stripping and terminating a Cat 6 UTP cable onto an RJ45 modular jack using the T568B standard.",
"","",
"Grade on: 1. Strip 2 inches of jacket without nicking wires. 2. Cut the center spline. 3. Untwist pairs ONLY to the edge of the IDC block (max 0.5 inches untwisted). 4. Arrange colors per T568B (Org/Wht, Org, Grn/Wht, Blu, Blu/Wht, Grn, Brn/Wht, Brn). 5. Use a punch-down tool with a cutting blade facing OUTWARD to seat and trim wires flush. 6. Snap on the dust cap.",
15),

(D,"practical",
"2. Given a Fluke DSX CableAnalyzer (or similar), demonstrate how to set up the tester to certify a Cat 6A Permanent Link.",
"","",
"Grade on: Turn on Main and Remote units. Attach Permanent Link Adapters to both. Navigate to Project/Setup. Select Test Limit: TIA Cat 6A Perm. Link. Select Cable Type (e.g., UTP/FTP, solid). Save setup. Connect adapters to the patch panel and wall plate. Press TEST. Read and interpret the PASS/FAIL summary screen.",
15),

(D,"practical",
"3. Inspect a physical OTDR trace printout. Identify the launch event, a fusion splice, a mechanical connector, and the end of the fiber.",
"","",
"Grade on: Launch event: Massive initial spike and dead zone at distance 0. Fusion splice: A small, sudden downward step in the sloping line (no spike). Mechanical connector: An upward spike (reflection) followed by a downward step (loss). End of fiber: A massive upward spike followed by a sudden drop to the noise floor (static).",
15),

(D,"practical",
"4. Demonstrate the proper procedure for cleaning and inspecting a fiber optic SC connector before mating.",
"","",
"Grade on: 1. Remove dust cap. 2. Insert connector into a Fiber Inspection Microscope. 3. View end-face on screen to check for dirt/scratches. 4. If dirty, use a dry 'clicker' cleaner (One-Click) or a lint-free wipe lightly moistened with 99% fiber optic cleaning fluid (not standard rubbing alcohol). 5. Swipe in a figure-8 motion. 6. RE-INSPECT with the microscope to verify it is perfectly clean before plugging it in.",
15),

(D,"practical",
"5. Review a telecom rack installation. Identify 3 installation errors based on BICSI best practices.",
"","",
"Grade on: Look for: 1. Cables zip-tied tightly (crushing the jacket/pairs). Should use Velcro straps. 2. Sharp bends in cable routing (violating 4x OD bend radius). 3. No service loop left for future moves/changes. 4. Rack is not bonded with a ground wire to the telecom busbar. 5. Power cables and data cables running parallel in the same bundle without separation.",
15),

(D,"practical",
"6. Given a fiber optic cleaver and a piece of scrap fiber, demonstrate how to prepare and cleave a fiber for fusion splicing.",
"","",
"Grade on: Use Miller strippers to remove the 250µm coating. Wipe the bare glass with an alcohol wipe (it must 'squeak'). Place the fiber in the cleaver exactly at the specified length mark (e.g., 16mm). Close the lid and slide the blade. Open and carefully remove the cleaved fiber. DO NOT wipe it again after cleaving. Dispose of the glass shard in a sharps bin.",
15),

(D,"practical",
"7. Calculate the Optical Loss Budget for a single-mode link: Length = 10 km (0.35 dB/km). 4 Fusion Splices (0.1 dB each). 2 Connector pairs (0.75 dB each).",
"","",
"Grade on: Cable loss = 10 km * 0.35 = 3.5 dB. Splice loss = 4 * 0.1 = 0.4 dB. Connector loss = 2 * 0.75 = 1.5 dB. Total Loss Budget = 3.5 + 0.4 + 1.5 = 5.4 dB. The measured loss with an OLTS must be less than 5.4 dB to pass.",
15),

(D,"practical",
"8. Demonstrate how to use an Optical Power Meter (OPM) and Light Source to measure the insertion loss of a patch cord (Reference/Zeroing process).",
"","",
"Grade on: 1. Turn on Light Source (LS) and OPM. 2. Connect a reference patch cord between them. 3. Press 'Zero' or 'Set Ref' on the OPM (it now reads 0.00 dB). 4. Disconnect the cord from the OPM ONLY. 5. Connect the 'Test Cord' to the OPM using a mating sleeve. 6. The dB reading on the OPM is now the exact Insertion Loss of the Test Cord.",
15),

(D,"practical",
"9. Evaluate a Fluke test report that shows a 'FAIL' for NEXT on Pair 3,6 / 4,5. What is the most likely physical cause, and how do you fix it?",
"","",
"Grade on: NEXT (Near-End Crosstalk) failure is almost always caused by poor termination practice at the jack or patch panel. The technician untwisted the wire pairs too far (more than 0.5 inches) before punching them down, destroying the noise cancellation. Fix: Cut off the jack, strip the cable back, and re-terminate perfectly, keeping the twists right up to the pins.",
15),

(D,"practical",
"10. Inspect an access control door installation. Verify the function of the Request to Exit (REX) sensor and the Maglock.",
"","",
"Grade on: From the secure side, approach the door. The REX (motion sensor above the door) should detect movement, click, and drop power to the maglock, allowing egress. Verify that pushing the emergency break-glass (if fitted) also drops power to the maglock. Verify the door closes completely and the maglock secures tightly without rattling.",
15),

(D,"practical",
"11. Given a digital multimeter, demonstrate how to verify the grounding resistance of a telecommunications rack.",
"","",
"Grade on: Set multimeter to lowest Ohms setting. Place one probe on a bare metal spot on the equipment rack chassis (scratch away paint if necessary). Place the other probe directly on the Telecommunications Grounding Busbar (TGB) copper bar on the wall. The reading must be very low, typically < 0.1 Ohms.",
15),

(D,"practical",
"12. You are handed a spool of 'Indoor/Outdoor' fiber optic cable. How do you verify it is 'Tight Buffered' or 'Loose Tube' by physical inspection?",
"","",
"Grade on: Strip back a few inches of the outer jacket. Loose Tube: You will find plastic tubes filled with a messy gel, and multiple bare (250µm) colored glass fibers floating freely inside the gel. Tight Buffered: Each individual fiber has its own thick (900µm) color-coded plastic jacket extruded tightly over the glass, with no messy gel.",
15),

(D,"practical",
"13. Demonstrate how to focus and aim a varifocal IP CCTV camera using a field test monitor or laptop.",
"","",
"Grade on: Connect laptop to camera PoE port (or test port). Access camera web interface. Physically adjust the camera housing to point at the target (Pan/Tilt). Use the varifocal knobs (or motorized web controls) to adjust 'Zoom' to perfectly frame the scene. Finally, adjust the 'Focus' ring until the image is razor-sharp. Lock the set screws.",
15),

(D,"practical",
"14. Identify the color code for a 12-strand fiber optic cable buffer tube.",
"","",
"Grade on: Must recite standard TIA-598 color code in order: 1. Blue, 2. Orange, 3. Green, 4. Brown, 5. Slate (Gray), 6. White, 7. Red, 8. Black, 9. Yellow, 10. Violet (Purple), 11. Rose (Pink), 12. Aqua.",
15),

(D,"practical",
"15. Evaluate a scenario: You are pulling fiber optic cable into a data center. The contractor wants to use cable ties (zip ties) to secure the fiber to the tray every 12 inches. Do you approve?",
"","",
"Grade on: Disapprove immediately. Standard nylon zip ties focus all pressure onto a tiny point. As they are pulled tight, they crush the fiber optic cable jacket, causing micro-bends in the glass inside, leading to massive attenuation and data loss. MUST use soft Velcro (hook-and-loop) straps for all fiber and data cables.",
15),

(D,"practical",
"16. Demonstrate how to check the connectivity and PoE power of a network wall jack using a basic network tester (e.g., Fluke MicroScanner).",
"","",
"Grade on: Plug the tester into the RJ45 wall jack. The tester will negotiate with the switch. It should display the Link Speed (e.g., 1000 Mbps), confirm whether a switch port is active, and display 'PoE' if the switch is providing 48VDC power. If no link, it acts as a TDR to show distance to the broken wire.",
15),

(D,"practical",
"17. Inspect a PA/GA (Public Address) system speaker installation. What specific features ensure it will work during a plant fire?",
"","",
"Grade on: 1. Cable must be Fire Resistant (e.g., mineral insulated or specialized fire-rated LSZH cable that functions at 750°C for hours). 2. Ceramic terminal blocks inside the speaker (plastic melts and shorts the line). 3. Thermal fuse installed in the speaker (if the speaker melts, the fuse blows, disconnecting the speaker so it doesn't short out the entire 100V loop for the rest of the plant).",
15),

(D,"practical",
"18. Given a piece of RG-6 coaxial cable and a compression BNC connector, describe the critical steps for a perfect termination.",
"","",
"Grade on: 1. Use a 2-step rotary coax stripper to expose exactly 1/4 inch of center conductor and 1/4 inch of bare braid. 2. Fold the wire braid back smoothly over the outer jacket. 3. Ensure the white dielectric is flush with the inner post of the connector. 4. Push connector on firmly until center copper pin is flush with the rim. 5. Compress with proper heavy-duty compression tool.",
15),

(D,"practical",
"19. Review a wireless heat map (predictive survey) for an industrial warehouse. Identify areas of concern.",
"","",
"Grade on: Look at the color gradient (signal strength in dBm). Green (-65 dBm) is good, Red/Grey (-85 dBm) is a dead zone. Identify concerns: APs placed directly above tall metal shelving (shelves block signal). 'Co-channel interference' (APs placed too close together broadcasting on the same channel, e.g., Channel 6). Suggest moving APs to aisles and alternating channels (1, 6, 11).",
15),

(D,"practical",
"20. You are commissioning a newly installed fiber optic ring network. How do you physically prove the 'self-healing' redundancy works?",
"","",
"Grade on: 1. Set up a continuous ping from a PC on one side of the ring to a server on the other side. 2. Physically disconnect (unplug) one of the main fiber optic backbone jumpers connecting two core switches (breaking the ring). 3. Observe the ping. It may drop 1 or 2 packets, but the STP/Ring protocol should instantly re-route traffic the other way. The pings should resume immediately. 4. Plug it back in, break the other side, repeat.",
15),

]  # end QUESTIONS
