"""
Cathodic Protection QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: NACE SP0169, NACE SP0286, SAES-X-400, SAES-X-600
"""

D = "Cathodic Protection QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. According to NACE SP0169, what is the primary criterion for adequate cathodic protection of a steel pipeline?",
"A negative (cathodic) voltage of at least -850 mV measured relative to a saturated copper/copper sulfate (CSE) reference electrode, with the CP current applied.\nA negative (cathodic) polarization potential of at least -850 mV measured relative to a CSE, determined immediately after the CP current is interrupted (instant-off potential).\nA potential of 0 mV.\nA positive potential of +850 mV.",
"A negative (cathodic) polarization potential of at least -850 mV measured relative to a CSE, determined immediately after the CP current is interrupted (instant-off potential).",
"The most accepted criterion is the -850 mV 'instant-off' polarized potential. This measurement removes the IR drop (voltage drop caused by current flowing through the soil resistance), providing the true polarized potential at the pipe-to-soil interface.",
1),

(D,"mcq",
"2. In a galvanic (sacrificial) anode cathodic protection system, what drives the protective current?",
"An external AC power source.\nA Transformer Rectifier (TR).\nThe natural potential difference (galvanic series) between the more active anode metal and the less active steel structure.\nA solar panel.",
"The natural potential difference (galvanic series) between the more active anode metal and the less active steel structure.",
"Galvanic systems do not use external power. They rely on the natural electrochemical potential difference between dissimilar metals. A highly active metal (zinc or magnesium) is connected to the steel. The active metal corrodes (sacrifices itself), sending current to the steel, making the steel the cathode.",
1),

(D,"mcq",
"3. Which reference electrode is most commonly used for measuring pipe-to-soil potentials in normal soil environments?",
"Silver/Silver Chloride (Ag/AgCl)\nCopper/Copper Sulfate (CSE)\nStandard Hydrogen Electrode (SHE)\nZinc/Zinc Sulfate",
"Copper/Copper Sulfate (CSE)",
"The Copper/Copper Sulfate Electrode (CSE) is the industry standard for field measurements in soil due to its ruggedness, stability, and ease of maintenance in the field.",
1),

(D,"mcq",
"4. What reference electrode is typically used for measuring potentials in seawater or highly saline environments?",
"Copper/Copper Sulfate (CSE)\nSilver/Silver Chloride (Ag/AgCl)\nStandard Hydrogen Electrode (SHE)\nCalomel Electrode",
"Silver/Silver Chloride (Ag/AgCl)",
"The Ag/AgCl reference electrode is preferred in seawater because chloride ions in seawater would rapidly contaminate a CSE electrode, causing significant reading errors. The Ag/AgCl electrode is stable in chloride-rich environments.",
1),

(D,"mcq",
"5. What is 'IR Drop' in the context of Cathodic Protection measurements?",
"Infrared radiation from the sun heating the pipe.\nThe voltage drop across the electrolyte (soil/water) caused by the flow of CP current and the resistance of the electrolyte.\nThe internal resistance of the voltmeter.\nThe voltage of the rectifier.",
"The voltage drop across the electrolyte (soil/water) caused by the flow of CP current and the resistance of the electrolyte.",
"By Ohm's law (V = I * R), when CP current flows through the soil to the pipe, a voltage drop occurs. If you measure 'on' potential, this IR drop is included, falsely making the pipe seem more negative than its true polarization. 'Instant-off' measurements eliminate the IR drop.",
1),

(D,"mcq",
"6. In an Impressed Current Cathodic Protection (ICCP) system, what is the function of the Transformer Rectifier (TR)?",
"To convert AC power from the grid into low-voltage DC power to drive the protective current.\nTo convert DC to AC.\nTo measure the pipe-to-soil potential.\nTo provide a galvanic reaction.",
"To convert AC power from the grid into low-voltage DC power to drive the protective current.",
"ICCP systems require an external power source because they use inert anodes (like mixed metal oxide) that do not generate their own galvanic current. The TR steps down the AC voltage and rectifies it to DC, pushing current out through the anodes to the structure.",
1),

(D,"mcq",
"7. Which of the following is a common material used for Impressed Current Anodes?",
"Zinc\nMagnesium\nMixed Metal Oxide (MMO) coated titanium\nAluminum",
"Mixed Metal Oxide (MMO) coated titanium",
"Zinc, Magnesium, and Aluminum are used for sacrificial (galvanic) anodes. MMO, High Silicon Cast Iron (HSCI), and graphite are used for impressed current systems because they have extremely low consumption rates when driven by external power.",
1),

(D,"mcq",
"8. What is the alternative NACE criterion for adequate cathodic protection if the -850 mV polarized potential cannot be achieved?",
"A minimum of 100 mV of cathodic polarization between the surface and a stable reference electrode contacting the electrolyte.\nA reading of 0 mV.\nA potential of -1200 mV.\nA current density of 10 Amps per square meter.",
"A minimum of 100 mV of cathodic polarization between the surface and a stable reference electrode contacting the electrolyte.",
"The 100 mV polarization criterion states that the structure must shift at least 100 mV in the negative direction from its native (depolarized or static) potential. This is often used on bare or poorly coated old pipelines where reaching -850 mV would require massive, damaging current.",
1),

(D,"mcq",
"9. What is 'Stray Current' corrosion?",
"Corrosion caused by microbes in the soil.\nCorrosion resulting from direct electrical current flowing through paths other than the intended circuit, entering a structure, and causing severe localized corrosion where the current leaves the structure to return to its source.\nCorrosion caused by atmospheric oxygen.\nCorrosion caused by dissimilar metals in contact.",
"Corrosion resulting from direct electrical current flowing through paths other than the intended circuit, entering a structure, and causing severe localized corrosion where the current leaves the structure to return to its source.",
"Stray currents (often from DC transit systems like trains, or foreign CP systems) enter a pipeline at one point (providing incidental CP) but travel along the pipe and exit at another point to return to their source. Where the current exits the pipe into the soil, extreme, rapid pitting corrosion occurs.",
1),

(D,"mcq",
"10. When installing a galvanic anode (e.g., magnesium) in soil, what surrounds the anode in its cloth bag?",
"Pure sand.\nConcrete.\nA specialized backfill mixture, typically containing gypsum, bentonite clay, and sodium sulfate.\nGravel.",
"A specialized backfill mixture, typically containing gypsum, bentonite clay, and sodium sulfate.",
"The prepared backfill serves three purposes: it absorbs ground moisture to keep the anode active, lowers the resistance of the anode to earth, and provides a uniform environment to ensure the anode corrodes evenly rather than pitting and breaking apart.",
1),

(D,"mcq",
"11. In CP testing, what does the term 'Native Potential' or 'Static Potential' mean?",
"The potential measured when the CP system is operating at full output.\nThe potential of the structure measured relative to a reference electrode before any cathodic protection current is applied.\nThe potential of the reference electrode itself.\nThe potential difference between two structures.",
"The potential of the structure measured relative to a reference electrode before any cathodic protection current is applied.",
"Native potential is the natural resting voltage of the steel in its specific soil environment before any external CP is applied. It is the baseline used to determine if the 100 mV polarization shift criterion is met.",
1),

(D,"mcq",
"12. What device is installed in a pipeline at specific locations (e.g., entering a plant) to electrically separate the cathodically protected pipeline from unprotected structures or different CP zones?",
"A bonding cable.\nAn isolation joint (Monolithic Isolation Joint or Flange Insulation Kit).\nA rectifier.\nA test station.",
"An isolation joint (Monolithic Isolation Joint or Flange Insulation Kit).",
"Electrical isolation is critical. Without it, the CP current intended for the pipeline would 'short out' into the massive grounding grid of a plant (which is usually bare copper), draining the CP system and leaving the pipeline unprotected.",
1),

(D,"mcq",
"13. What is the risk of 'Over-protection' (driving the potential too negative, e.g., beyond -1200 mV CSE) on a coated steel pipeline?",
"The pipe will become too cold.\nThe steel will melt.\nExcessive hydrogen gas generation at the pipe surface causes 'Cathodic Disbondment', stripping the coating off the pipe, and can cause Hydrogen Embrittlement in high-strength steels.\nThere is no risk; more negative is always better.",
"Excessive hydrogen gas generation at the pipe surface causes 'Cathodic Disbondment', stripping the coating off the pipe, and can cause Hydrogen Embrittlement in high-strength steels.",
"If CP potentials are driven too high, water is electrolyzed at the cathode (pipe) creating massive amounts of hydrogen gas and high alkalinity. This blows the coating off the pipe (cathodic disbondment). In high-strength steels, the hydrogen atoms can enter the steel lattice and cause catastrophic brittle failure (Hydrogen Embrittlement).",
1),

(D,"mcq",
"14. When measuring pipe-to-soil potential with a standard digital multimeter, which terminal is connected to the reference electrode?",
"The positive (red) terminal.\nThe negative (COM/black) terminal.\nEither terminal, it doesn't matter.\nThe Amps terminal.",
"The negative (COM/black) terminal.",
"By NACE convention, the reference electrode is connected to the negative (COM) terminal of the voltmeter, and the structure is connected to the positive terminal. This ensures that the reading displayed for a protected steel pipe is a negative number (e.g., -850 mV).",
1),

(D,"mcq",
"15. What instrument is required to accurately perform 'Instant-Off' potential measurements?",
"A standard analog multimeter.\nA specialized datalogger or multimeter with a fast sampling rate synchronized with a GPS-timed current interrupter.\nA soil resistivity meter.\nA clamp-on ammeter.",
"A specialized datalogger or multimeter with a fast sampling rate synchronized with a GPS-timed current interrupter.",
"To capture the 'instant-off' potential, the measuring device must read the voltage within milliseconds of the rectifier current being interrupted (before the pipe depolarizes). Standard meters are too slow. Modern surveys use GPS-synchronized interrupters and fast dataloggers.",
1),

(D,"mcq",
"16. Which method is most commonly used to measure the electrical resistivity of the soil along a proposed pipeline route?",
"The Wenner Four-Pin method.\nThe Sand Cone method.\nThe Proctor test.\nThe Slump test.",
"The Wenner Four-Pin method.",
"The Wenner 4-pin method involves driving four pins into the soil at equal spacing (a). A current is passed between the outer pins, and the voltage drop is measured between the inner pins. It provides the average soil resistivity down to a depth equal to the pin spacing (a).",
1),

(D,"mcq",
"17. In an Impressed Current system, how must the DC cables be connected to ensure protection?",
"DC Positive (+) to the Structure, DC Negative (-) to the Anode Groundbed.\nDC Positive (+) to the Anode Groundbed, DC Negative (-) to the Structure.\nBoth to the Structure.\nIt does not matter.",
"DC Positive (+) to the Anode Groundbed, DC Negative (-) to the Structure.",
"This is critical. Current must flow FROM the anode, through the soil, TO the structure. Therefore, the Anode is connected to the Positive terminal (making it an anode that corrodes), and the Pipeline is connected to the Negative terminal (making it a cathode that is protected). Reverse connection will destroy the pipeline rapidly.",
1),

(D,"mcq",
"18. What is the primary purpose of a 'CIPS' (Close Interval Potential Survey) on a buried pipeline?",
"To measure the thickness of the pipe wall.\nTo provide a continuous, highly detailed profile of the pipe-to-soil potential over the entire length of the pipeline, identifying localized areas of under-protection or coating defects.\nTo locate buried cables.\nTo measure the flow rate of the product inside.",
"To provide a continuous, highly detailed profile of the pipe-to-soil potential over the entire length of the pipeline, identifying localized areas of under-protection or coating defects.",
"Standard test stations are miles apart. CIPS involves an operator walking directly over the pipeline, trailing a wire connected to a test station, and taking potential measurements every 1 to 3 meters with a datalogger, ensuring no localized defects are missed between test stations.",
1),

(D,"mcq",
"19. What is a 'DCVG' (Direct Current Voltage Gradient) survey used for?",
"To measure soil resistivity.\nTo pinpoint the exact location and estimate the severity of coating defects (holidays) on a buried pipeline.\nTo measure the output of the rectifier.\nTo test the insulation of flange kits.",
"To pinpoint the exact location and estimate the severity of coating defects (holidays) on a buried pipeline.",
"DCVG measures the voltage gradient in the soil caused by CP current flowing to a coating defect. An operator walks the line with two probes. When a defect is approached, a voltage difference is seen between the probes, allowing exact pinpointing of the coating holiday.",
1),

(D,"mcq",
"20. Why must thermite welds (e.g., Cadweld) used to attach CP cables to a pipeline be coated after cooling?",
"To make them look neat.\nTo prevent galvanic corrosion between the copper weld material and the steel pipe, and to restore the integrity of the pipeline coating system.\nTo increase the electrical conductivity of the weld.\nTo prevent the pipe from overheating.",
"To prevent galvanic corrosion between the copper weld material and the steel pipe, and to restore the integrity of the pipeline coating system.",
"The thermite weld process exposes bare steel and deposits a copper-alloy weld nugget. Copper and steel are dissimilar metals; the steel will corrode aggressively as an anode if exposed to the soil. The weld and all bare steel must be coated (e.g., with a patch or mastic) holiday-free.",
1),

(D,"mcq",
"21. A galvanic magnesium anode is tested before connection to the pipeline. Its open-circuit potential measured against a CSE is typically around:",
"-0.85 V\n-1.50 V to -1.75 V\n+1.50 V\n0 V",
"-1.50 V to -1.75 V",
"Magnesium is highly active. A standard potential for a high-potential magnesium anode is around -1.75 V (CSE). This high negative potential is what provides the driving voltage to push current to a steel pipeline resting at -0.5 V to -0.6 V.",
1),

(D,"mcq",
"22. What device allows CP current to pass between a pipeline and a plant grounding grid, but blocks DC current from draining the CP system?",
"A solid copper wire.\nA Polarization Cell or a Solid State Decoupler (SSD).\nA resistor.\nA diode.",
"A Polarization Cell or a Solid State Decoupler (SSD).",
"SSDs (or older liquid polarization cells) act as a DC block and an AC short. They block the low-voltage DC CP current from draining into the grounding grid, but allow high-voltage AC faults or lightning strikes to pass safely to ground, maintaining electrical safety without compromising CP.",
1),

(D,"mcq",
"23. Which of the following environments has the LOWEST electrical resistivity (and is therefore the most corrosive)?",
"Dry sand\nGranite rock\nSeawater\nFresh water",
"Seawater",
"Seawater has extremely low resistivity (typically 20-30 ohm-cm) due to the high concentration of dissolved salts (ions). This makes it an excellent electrolyte, allowing massive corrosion currents to flow easily, resulting in very high corrosion rates for unprotected steel.",
1),

(D,"mcq",
"24. When conducting a current requirement test on a new pipeline to size a CP system, what is the primary factor that dictates how much current is needed?",
"The diameter of the pipe.\nThe length of the pipe.\nThe total area of bare steel exposed to the soil (the quality and integrity of the coating).\nThe operating pressure of the pipe.",
"The total area of bare steel exposed to the soil (the quality and integrity of the coating).",
"A perfectly coated pipeline requires almost zero CP current. CP only protects the bare steel exposed at coating defects (holidays). Therefore, the total current required is directly proportional to the coating breakdown factor (the percentage of bare steel).",
1),

(D,"mcq",
"25. What is the typical consumption rate of a High Silicon Cast Iron (HSCI) impressed current anode compared to a Magnesium galvanic anode?",
"HSCI consumes much faster than Magnesium.\nHSCI has a much lower consumption rate (e.g., 0.5 kg/A-yr) compared to Magnesium (e.g., 4.0 kg/A-yr), allowing it to last decades even at high current outputs.\nThey have the same consumption rate.\nHSCI does not consume at all.",
"HSCI has a much lower consumption rate (e.g., 0.5 kg/A-yr) compared to Magnesium (e.g., 4.0 kg/A-yr), allowing it to last decades even at high current outputs.",
"Impressed current anodes (HSCI, MMO, Graphite) are practically 'inert' and consume very slowly, allowing them to output large amounts of current for 20+ years. Galvanic anodes consume rapidly as part of the energy-generation process.",
1),

(D,"mcq",
"26. An insulating flange kit fails and shorts out. What is the immediate effect on the CP system of the protected pipeline?",
"The pipeline potential will become more negative.\nThe CP system will immediately shut down.\nThe pipeline potential will drop (become less negative) because the CP current is now draining into the unprotected structure, leaving the pipeline under-protected.\nThe rectifier voltage will spike.",
"The pipeline potential will drop (become less negative) because the CP current is now draining into the unprotected structure, leaving the pipeline under-protected.",
"A shorted isolation flange provides a low-resistance path for the CP current to flow into massive foreign structures (like a plant grounding grid). The CP system cannot supply enough current for both, so the potential of the intended pipeline drops below the -850 mV criterion.",
1),

(D,"mcq",
"27. What is 'Microbiologically Influenced Corrosion' (MIC)?",
"Corrosion caused by microscopic animals chewing on the pipe.\nCorrosion initiated or accelerated by the metabolic activities of microorganisms (like Sulfate Reducing Bacteria - SRB) in the soil or water.\nCorrosion that only occurs under a microscope.\nCorrosion caused by algae on the surface.",
"Corrosion initiated or accelerated by the metabolic activities of microorganisms (like Sulfate Reducing Bacteria - SRB) in the soil or water.",
"MIC is a severe form of localized corrosion. SRB thrive in anaerobic (oxygen-free) conditions (like heavy clays) and consume sulfates, producing highly corrosive hydrogen sulfide (H2S) at the pipe surface. CP can mitigate MIC, but often requires more negative potentials (e.g., -950 mV).",
1),

(D,"mcq",
"28. During a CP survey, you measure a pipe-to-soil potential of -1.150 V (CSE) with the rectifier ON. You interrupt the rectifier and measure an instant-off potential of -0.920 V (CSE). What is the IR Drop?",
"0.230 V (or 230 mV)\n0.920 V\n1.150 V\n2.070 V",
"0.230 V (or 230 mV)",
"The IR drop is the difference between the 'On' potential and the 'Instant-Off' polarized potential. |-1.150| - |-0.920| = 0.230 V (230 mV). The true polarized potential is -0.920 V, which meets the -850 mV criterion.",
1),

(D,"mcq",
"29. Why must the porous plug of a Copper/Copper Sulfate (CSE) reference electrode be kept moist?",
"To prevent the copper rod from rusting.\nTo ensure ionic conductivity between the copper sulfate solution inside the electrode and the soil electrolyte outside; if it dries out, the circuit is broken and readings will be unstable or impossible.\nTo keep the electrode heavy.\nTo cool the electrode down.",
"To ensure ionic conductivity between the copper sulfate solution inside the electrode and the soil electrolyte outside; if it dries out, the circuit is broken and readings will be unstable or impossible.",
"The CSE works by allowing ions to pass through the porous ceramic plug to establish an electrical connection with the soil. If the plug dries out, resistance goes to infinity, and the high-impedance voltmeter will give erratic, floating, or zero readings.",
1),

(D,"mcq",
"30. What is a 'Deep Well Groundbed' in ICCP systems?",
"A groundbed located at the bottom of a water well.\nA vertical borehole, typically 50 to 100 meters deep, containing a string of anodes surrounded by conductive coke breeze backfill, used to distribute current over a wide area and overcome high surface soil resistivity.\nA groundbed used for submarines.\nA groundbed installed inside the pipeline.",
"A vertical borehole, typically 50 to 100 meters deep, containing a string of anodes surrounded by conductive coke breeze backfill, used to distribute current over a wide area and overcome high surface soil resistivity.",
"Deep well groundbeds are used in congested areas where horizontal space is limited, to minimize stray current interference with shallow foreign structures, or to bypass dry, highly resistive surface soils to reach conductive layers deep underground.",
1),

(D,"mcq",
"31. When testing the insulation of an isolation flange BEFORE it is buried, what is the best instrument to use?",
"A standard digital multimeter set to Ohms (Resistance).\nA high-voltage holiday detector.\nA specialized Radio Frequency (RF) isolation tester (e.g., Gas Electronics Model 601) that can measure the flange integrity without being fooled by parallel ground paths.\nA clamp-on ammeter.",
"A specialized Radio Frequency (RF) isolation tester (e.g., Gas Electronics Model 601) that can measure the flange integrity without being fooled by parallel ground paths.",
"Standard multimeters are unreliable for testing installed flanges because they measure DC resistance, which is easily fooled by parallel paths through the soil or piping network. RF testers measure the capacitive/inductive properties to accurately determine if the flange itself is shorted or open.",
1),

(D,"mcq",
"32. What is the purpose of 'Coke Breeze' backfill in an Impressed Current groundbed?",
"To provide fuel for a fire.\nTo significantly lower the electrical resistance between the anode and the earth, and to act as the primary surface that consumes/discharges current, thereby prolonging the life of the central anode.\nTo absorb water.\nTo make the groundbed look black.",
"To significantly lower the electrical resistance between the anode and the earth, and to act as the primary surface that consumes/discharges current, thereby prolonging the life of the central anode.",
"Coke breeze (calcined petroleum coke) is highly conductive carbon. When packed tightly around an MMO or HSCI anode, the current transfers from the anode to the coke electronically. The coke then discharges the current electrolytically to the soil, meaning the coke consumes rather than the expensive anode.",
1),

(D,"mcq",
"33. A pipeline runs parallel to a high-voltage overhead AC transmission line. What CP hazard must be mitigated?",
"The AC line will drain the CP batteries.\nAC induction can create dangerously high AC voltages on the pipeline, posing a lethal shock hazard to personnel and causing AC corrosion; mitigation requires AC mitigation grounding systems (e.g., zinc ribbon or deep grounds with solid-state decouplers).\nThe AC line will melt the pipeline coating.\nThe pipeline will fly up to the wires.",
"AC induction can create dangerously high AC voltages on the pipeline, posing a lethal shock hazard to personnel and causing AC corrosion; mitigation requires AC mitigation grounding systems (e.g., zinc ribbon or deep grounds with solid-state decouplers).",
"Long parallel runs cause the pipeline to act as the secondary coil of a massive transformer. Induced AC voltages can easily exceed safe touch potentials (15V AC). The pipeline must be grounded for AC using decouplers that pass AC to ground but block the DC CP current.",
1),

(D,"mcq",
"34. In a Galvanic (Sacrificial) Anode system, what restricts the total current output of the anode?",
"The size of the wire used.\nThe driving voltage of the anode material (e.g., -1.75V for Mg) divided by the total circuit resistance (primarily the anode-to-soil resistance), following Ohm's Law.\nThe rectifier setting.\nThe pipeline coating color.",
"The driving voltage of the anode material (e.g., -1.75V for Mg) divided by the total circuit resistance (primarily the anode-to-soil resistance), following Ohm's Law.",
"Galvanic systems have a fixed, low driving voltage. Because I = V/R, the current output is entirely dependent on the soil resistance. In highly resistive soil, a magnesium anode will output very little current, which is why galvanic systems are generally limited to low-resistivity soils or very well-coated short structures.",
1),

(D,"mcq",
"35. Which testing method verifies the bond between the copper cable and the steel pipe at a thermite weld (Cadweld)?",
"Radiographic testing (RT).\nStriking the weld sharply with a 2-pound hammer to ensure mechanical strength; if it pops off, the weld failed.\nUltrasonic testing (UT).\nMagnetic particle testing (MT).",
"Striking the weld sharply with a 2-pound hammer to ensure mechanical strength; if it pops off, the weld failed.",
"The standard field test for a thermite weld is a physical 'hammer test'. A sharp, glancing blow with a hammer will knock off a cold or poorly fused weld, but a properly fused weld will easily withstand the impact.",
1),

(D,"mcq",
"36. What is 'Depolarization' in the context of CP criteria?",
"Removing the battery from the multimeter.\nThe decay of the negative potential of the structure back toward its native state after the CP current is turned off; the 100 mV criterion requires observing at least 100 mV of decay.\nIncreasing the rectifier output.\nThe coating falling off.",
"The decay of the negative potential of the structure back toward its native state after the CP current is turned off; the 100 mV criterion requires observing at least 100 mV of decay.",
"If you cannot measure the native potential before CP is applied, you can turn the CP off and watch the potential decay (depolarize) over time (hours or days). If it decays by 100 mV or more from the instant-off potential, adequate CP was being provided.",
1),

(D,"mcq",
"37. Why must you place the reference electrode exactly over the centerline of the buried pipeline during a potential survey?",
"To minimize the IR drop in the soil; placing it to the side measures the voltage gradient in the earth rather than the true pipe potential, leading to inaccurate readings.\nTo avoid stepping on snakes.\nTo ensure you don't lose the electrode.\nIt doesn't matter where you place it within 10 meters.",
"To minimize the IR drop in the soil; placing it to the side measures the voltage gradient in the earth rather than the true pipe potential, leading to inaccurate readings.",
"Current flows through the earth to the pipe in a radial pattern, creating voltage gradients (like a funnel). Placing the electrode directly over the pipe puts it at the lowest point of the soil voltage gradient, minimizing the soil IR drop included in the measurement.",
1),

(D,"mcq",
"38. What does the term 'Attenuation' mean in a cathodic protection system?",
"The noise made by the rectifier.\nThe gradual loss of CP potential (the pipe becomes less negative) as the distance from the CP current source (drain point) increases, due to the electrical resistance of the pipe steel and coating leakage.\nThe increase in current over time.\nThe drying out of the soil.",
"The gradual loss of CP potential (the pipe becomes less negative) as the distance from the CP current source (drain point) increases, due to the electrical resistance of the pipe steel and coating leakage.",
"A rectifier injects current at a 'drain point', making the pipe very negative there. As you travel miles down the pipeline, the potential becomes less negative because current leaks out through coating defects and the pipe steel has longitudinal resistance. This is attenuation.",
1),

(D,"mcq",
"39. When installing a Transformer Rectifier, what must be done to the enclosure for safety?",
"It must be painted bright pink.\nIt must be solidly grounded (earthed) to a safety ground rod to prevent electrical shock if an internal AC fault energizes the casing.\nIt must be suspended in the air.\nIt must be filled with oil.",
"It must be solidly grounded (earthed) to a safety ground rod to prevent electrical shock if an internal AC fault energizes the casing.",
"Standard electrical safety. A TR handles lethal AC grid voltages. The metallic enclosure must be grounded. NOTE: This safety ground must be completely separate from the CP Anode groundbed.",
1),

(D,"mcq",
"40. What is a 'Bond Box' or 'Resistance Bond' used for where two different pipelines cross each other?",
"To hold the pipes together mechanically.\nTo electrically connect the two pipes through a variable resistor to mitigate stray current interference (allowing stray current to return safely to its source without jumping through the soil and causing corrosion).\nTo measure the temperature of the pipes.\nTo apply coating to the intersection.",
"To electrically connect the two pipes through a variable resistor to mitigate stray current interference (allowing stray current to return safely to its source without jumping through the soil and causing corrosion).",
"If Pipe A's CP system causes stray current to jump onto Pipe B, Pipe B will corrode where the current jumps back to Pipe A through the soil. A resistance bond provides a safe metallic path for the current to return, stopping the corrosion while allowing control over the amount of current shared.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Explain the theory of Cathodic Protection. Detail the four required components of a corrosion cell and how CP intervenes to stop corrosion.",
"","",
"Grade on: Corrosion cell components: Anode (where metal is lost/oxidized), Cathode (where reduction occurs, no metal loss), Electrolyte (soil/water to conduct ions), and Metallic Return Path (the pipe itself conducting electrons). How CP works: CP artificially turns the entire structure into a Cathode. It does this by introducing a new, massive Anode (galvanic or impressed) and forcing direct current through the electrolyte TO the structure. Since corrosion only happens at the anode, the structure (now entirely a cathode) stops corroding.",
20),

(D,"essay",
"2. Compare and contrast Galvanic (Sacrificial) Anode systems with Impressed Current Cathodic Protection (ICCP) systems. Discuss their advantages, limitations, and typical applications.",
"","",
"Grade on: Galvanic: Uses natural potential difference (Mg, Zn). No external power needed. Low maintenance. Cannot be wired backward. Limitations: Very limited driving voltage, only works in low resistivity soil, limited current output. Use: Short lines, well-coated lines, offshore offshore structures. ICCP: Uses external power (TR) and inert anodes (MMO, HSCI). Advantages: Massive driving voltage, can overcome high resistivity soil, can protect miles of bare/poorly coated pipe, adjustable output. Limitations: Requires AC power, high maintenance, risk of catastrophic stray current or reverse wiring.",
20),

(D,"essay",
"3. Describe the procedure for performing a 'Close Interval Potential Survey' (CIPS). What equipment is required, what data is collected, and how is the data interpreted?",
"","",
"Grade on: Equipment: GPS-synchronized current interrupters on all influential rectifiers, trailing wire measuring spool, data logger, two CSE electrodes on walking sticks. Procedure: Interrupters cycle (e.g., 3s ON, 1s OFF). Operator walks directly over the pipe, planting electrodes every 1-3 meters. Datalogger captures 'ON' and 'Instant-OFF' potentials at each step. Interpretation: Data is plotted on a graph (Potential vs. Distance). Dips in the Instant-OFF graph below -850 mV indicate under-protected areas, often correlating with severe coating defects (holidays) or stray current interference.",
20),

(D,"essay",
"4. What is 'Stray Current Interference'? Describe a scenario where it occurs between two pipelines, explain the mechanism of corrosion, and detail how to mitigate it.",
"","",
"Grade on: Scenario: Pipeline A (with ICCP) crosses Pipeline B (no CP). Current from A's groundbed travels through the soil, finds Pipeline B (a low-resistance metallic path), travels along B, and then discharges back into the soil to jump back to Pipeline A near the crossing. Mechanism: Where current ENTERS B, B is protected. Where current EXITS B into the soil, B suffers massive, rapid electrolytic corrosion (1 Amp = 20 lbs of steel lost per year). Mitigation: Install a Resistance Bond (cable with adjustable resistor) between A and B at the crossing to provide a metallic return path, or coat the crossing area, or add galvanic anodes to the discharge point.",
20),

(D,"essay",
"5. Detail the NACE SP0169 criteria for Cathodic Protection. Explain the difference between 'On' potential, 'Instant-Off' polarized potential, and the 100 mV polarization shift.",
"","",
"Grade on: 1. -850 mV Polarized Potential: Measured immediately after current interruption (Instant-Off) to eliminate IR drop in the soil. The true potential must be <= -850mV CSE. 2. 100 mV Shift: The polarized (Instant-Off) potential must be at least 100 mV more negative than the native/static potential of the pipe. On Potential: Measured with rectifier running. It includes the true polarized potential PLUS the voltage drop through the soil (IR drop). It is NOT a valid criterion on its own unless IR drop is proven negligible.",
20),

(D,"essay",
"6. You are inspecting the installation of a Deep Well Groundbed for an ICCP system. Outline the critical quality control steps from drilling to final connection.",
"","",
"Grade on: 1. Verify drill depth and diameter. 2. Verify anode type (e.g., MMO tubular), quantity, and spacing on the suspension rope. 3. Check individual anode cable insulation (HMWPE/Kynar) for nicks before lowering (crucial - a nicked cable will corrode in days and sever the anode). 4. Lowering: ensure centralizer use. 5. Backfill: Pump fluid coke breeze from the bottom up using a tremie pipe to prevent bridging/voids. 6. Install vent pipe to allow chlorine/oxygen gas to escape. 7. Test resistance of each anode before tying into the junction box.",
20),

(D,"essay",
"7. Explain the function of a Transformer Rectifier (TR) in an ICCP system. Describe the routine inspection parameters you would record during a monthly TR check.",
"","",
"Grade on: Function: Steps down AC grid voltage and rectifies it to DC to drive the CP system. Inspection parameters: 1. Safety check (grounding intact, no burning smell, no insect nests). 2. Record Output DC Voltage (Volts). 3. Record Output DC Current (Amps). 4. Calculate circuit resistance (R = V/I) and compare to baseline (drastic increase means dry groundbed, cut cable, or depleted anodes). 5. Check oil level/clarity (if oil-cooled). 6. Record tap settings (Coarse/Fine). 7. Record AC input voltage.",
20),

(D,"essay",
"8. Discuss the installation and testing of an Insulating Flange Kit (Isolation Joint). Why are they necessary, how are they installed, and how do you prove they are working?",
"","",
"Grade on: Necessity: To electrically isolate the cathodically protected pipeline from unprotected structures (plants, grounding grids, other pipelines) to prevent CP current drain. Installation: Clean flange faces. Insert isolating gasket (e.g., Pikotek). Insert isolating sleeves over every bolt. Place isolating washers and steel washers under nuts. Tighten in star pattern. Testing: Do NOT use a standard ohmmeter. Use a specialized RF tester (Gas Electronics) to check for shorts. Alternatively, measure pipe-to-soil potentials on both sides; a significant difference indicates isolation. Measure voltage ACROSS the flange.",
20),

(D,"essay",
"9. What is 'Cathodic Disbondment' and why is it a major concern for pipeline integrity? How do coatings and CP systems interact regarding this phenomenon?",
"","",
"Grade on: Disbondment is the loss of adhesion between the coating and the steel substrate. Concern: Disbonded coating can shield the steel from CP current while allowing water to seep under the coating, creating a highly corrosive micro-environment that CP cannot reach, leading to catastrophic failure. Interaction: CP current generates hydrogen gas and high alkalinity (hydroxide ions) at the cathode (steel surface). If the CP voltage is driven too high (over-protection, e.g., > -1.2V), this alkaline environment rapidly attacks the coating bond. Coatings must be formulated to resist this (CDT testing).",
20),

(D,"essay",
"10. Describe the procedure for performing a Soil Resistivity survey using the Wenner 4-Pin method. How does soil resistivity affect CP design?",
"","",
"Grade on: Procedure: Drive 4 pins into the soil in a straight line at equal spacing 'a'. Connect outer pins to the current terminals of a soil resistance meter (e.g., Nilsson or Miller 400), inner pins to voltage terminals. Meter outputs Resistance (R). Calculate Resistivity (Rho) = 2 * pi * a * R. Effect on design: Low resistivity (e.g., <1000 ohm-cm) is highly corrosive but makes CP easy to apply (requires fewer anodes/less voltage). High resistivity (e.g., >50,000 ohm-cm) is less corrosive but makes driving CP current very difficult, requiring deep wells or high-voltage rectifiers.",
20),

(D,"essay",
"11. Detail the procedure for preparing and executing a Thermite Weld (Cadweld) to attach a test cable to a live, pressurized pipeline. Include safety and QC steps.",
"","",
"Grade on: Safety: Ensure pipeline thickness allows welding (prevent burn-through), check for explosive atmosphere. Prep: Remove coating, grind a small window (approx 2x2 inches) to bright metal (SP-10). Strip cable end, install copper sleeve. Ensure mold and steel are DRY (moisture causes steam explosion). Execution: Clamp graphite mold securely to pipe. Insert metal disk, pour weld powder, sprinkle starting powder on lip. Ignite with flint gun. QC: Wait to cool. Remove mold. Slag removal. Hammer test the weld (strike sharply with 2lb hammer). If it holds, coat the entire bare area with approved mastic/epoxy holiday-free.",
20),

(D,"essay",
"12. What is a 'DCVG' survey and how does it differ from a 'CIPS' survey? When would you employ each method?",
"","",
"Grade on: DCVG (Direct Current Voltage Gradient): Uses two probes walked like walking sticks to measure the voltage gradient in the soil caused by current funneling into a coating defect. It pinpoints the EXACT location of the defect (holiday) and estimates its size (%IR). CIPS (Close Interval Potential Survey): Trails a wire to measure the pipe-to-soil potential every meter to prove the pipeline meets the -850mV criteria continuously. Employment: Use CIPS to verify overall CP effectiveness and regulatory compliance. Use DCVG to locate specific coating damage for excavation and repair.",
20),

(D,"essay",
"13. Discuss the concept of 'AC Mitigation' on pipelines sharing a corridor with high-voltage overhead power lines. What are the hazards and the solutions?",
"","",
"Grade on: Hazards: The pipeline acts as a secondary transformer coil. AC voltage is induced onto the pipeline. 1. Personnel safety (shock hazard at test stations/valves if AC voltage > 15V). 2. AC Corrosion (high AC current densities at small coating defects cause rapid pitting). Solutions: Install bare zinc ribbon or grounding rods parallel to the pipe in the high-induction zones. Connect these grounds to the pipeline via Solid State Decouplers (SSDs/DC blocks). The SSD allows the dangerous AC to drain safely to earth while blocking the DC CP current from being lost to the grounding system.",
20),

(D,"essay",
"14. Explain how a Copper/Copper Sulfate (CSE) Reference Electrode works. How do you maintain and calibrate it in the field?",
"","",
"Grade on: Working: Contains a pure copper rod immersed in a saturated solution of copper sulfate, enclosed in a tube with a porous ceramic plug. It provides a stable, known half-cell potential to measure the unknown pipeline potential against. Maintenance: Keep the solution saturated (visible blue crystals must be present). Keep the copper rod clean (sandpaper bright). Keep the porous plug moist. Do not allow it to freeze or become contaminated with chlorides/soil. Calibration: Cannot be formally 'calibrated', but verified against a known 'master' electrode kept in the office. If difference > 5mV, rebuild it.",
20),

(D,"essay",
"15. A new pipeline has been installed and coated with 3LPE. The CP system is turned on, but the rectifier is outputting almost zero amps, yet the pipeline potential is -1.100 V for its entire length. Explain this phenomenon.",
"","",
"Grade on: This represents an excellent, near-perfect coating installation. 3LPE is a highly dielectric, robust coating. Because there are virtually no coating defects (holidays) exposing bare steel to the soil, the total resistance of the pipeline to earth is massive. Therefore, the rectifier needs to output almost zero current (I = V/R) to polarize the microscopic amount of bare steel that might exist. The pipe polarizes instantly and deeply (-1.100V) with minuscule current. This is the ideal scenario.",
20),

(D,"essay",
"16. You arrive at a test station to measure CP potentials. The wire is broken off flush with the soil. What are your options to get a reading, and what is the long-term fix?",
"","",
"Grade on: Short-term options: If the pipeline is visible nearby (e.g., at a valve station), connect the multimeter there and run a long wire back to the soil location to place the reference electrode. Alternatively, use a soil probe to try and contact the pipe, though this is risky and damages coating. Long-term fix: The location must be excavated (hydro-vac preferred to prevent pipe damage). A new test cable must be thermite welded to the pipe, hammer tested, coated, and routed back into the test station box.",
20),

(D,"essay",
"17. Describe the structure and function of a 'Test Station' in a CP system. What typical wires are found inside, and what measurements can be taken?",
"","",
"Grade on: Structure: A durable post or flush-mounted box above the pipeline containing a terminal board. Function: Allows access to the buried pipeline for electrical measurements without digging. Wires: Usually two wires thermite-welded to the pipe (one for measurement, one for backup/current application). May also contain wires from a buried reference cell, or galvanic anodes. Measurements: Pipe-to-soil potential (structure to CSE). Can also measure line current if calibrated spans are installed (4-wire test station measuring mV drop along a known length of pipe).",
20),

(D,"essay",
"18. Discuss the hazards of Hydrogen Embrittlement related to Cathodic Protection. Which types of steel are susceptible, and how is it prevented?",
"","",
"Grade on: Hazard: Excessive CP (potentials too negative, e.g., beyond -1.2V CSE) generates atomic hydrogen at the steel surface (cathode). Atomic hydrogen is small enough to diffuse into the steel lattice. It combines into molecular hydrogen gas inside the steel, creating massive internal pressure that causes the steel to crack and fail brittlely (Hydrogen Embrittlement / Hydrogen Induced Cracking - HIC). Susceptible: High-strength steels (e.g., API 5L X70, X80 and above), hardened welds, and bolts. Prevention: Strictly limit the maximum negative CP potential (e.g., do not exceed -1.100 V or -1.200 V Instant-Off) on high-strength structures.",
20),

(D,"essay",
"19. What is 'Microbiologically Influenced Corrosion' (MIC)? How do Sulfate-Reducing Bacteria (SRB) attack steel, and how does CP interact with MIC?",
"","",
"Grade on: MIC is corrosion accelerated by microbes. SRB are the most common in pipelines. They live in anaerobic (oxygen-free) environments like dense clay or under disbonded coatings. They 'breathe' sulfates and excrete highly corrosive Hydrogen Sulfide (H2S) directly onto the steel, causing rapid, deep pitting. CP Interaction: Standard CP (-850mV) provides an alkaline environment which inhibits SRB growth. However, if MIC is confirmed active, NACE recommends increasing the CP polarization criterion (making it more negative, e.g., -950 mV to -1000 mV) to effectively shut down the bacterial corrosion process.",
20),

(D,"essay",
"20. You are commissioning a newly installed Impressed Current CP system. Outline the steps to turn it on, adjust it, and verify protection while ensuring no over-protection.",
"","",
"Grade on: 1. Verify all wiring (Positive to Anodes, Negative to Structure). 2. Measure Native potentials at all test stations. 3. Turn TR on at lowest tap setting. 4. Measure Output Volts and Amps. 5. Measure 'On' potentials at nearest and furthest test stations. 6. Perform 'Instant-Off' measurements using an interrupter. 7. Gradually increase TR tap settings until the Instant-Off potential at the furthest point reaches -850mV (or 100mV shift). 8. Verify the Instant-Off potential at the drain point (closest to groundbed) does not exceed the over-protection limit (e.g., -1.200V). 9. Let system polarize for 3-4 weeks, then re-survey and fine-tune.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. Why is the 'Instant-Off' potential measurement considered more accurate than the 'On' measurement?",
"","",
"Grade on: The 'On' measurement includes the voltage drop (IR drop) caused by the CP current flowing through the resistance of the soil. This artificially inflates the reading, making the pipe seem more protected than it is. The 'Instant-Off' measurement captures the voltage in the milliseconds after the current stops but before the pipe loses its polarization, removing the IR drop error.",
10),

(D,"oral",
"2. You measure a pipe-to-soil potential of -0.650 V (CSE). The pipeline has no CP connected. What does this tell you?",
"","",
"Grade on: This is the 'Native' or 'Static' potential of the steel in that specific soil. It indicates that the steel is currently freely corroding (active). It also establishes the baseline; if you use the 100 mV shift criterion, you must polarize the pipe to at least -0.750 V to achieve protection.",
10),

(D,"oral",
"3. What is the difference between a Sacrificial Anode and an Impressed Current Anode?",
"","",
"Grade on: Sacrificial (Galvanic) anodes (Magnesium, Zinc) generate their own protective current through natural galvanic corrosion—they consume themselves rapidly to protect the steel. Impressed current anodes (MMO, Cast Iron) are inert; they require an external power source (Rectifier) to push current, and they consume very slowly.",
10),

(D,"oral",
"4. You open a rectifier cabinet and see that the positive cable is bolted to the structure terminal, and the negative cable is bolted to the anode terminal. What do you do?",
"","",
"Grade on: Turn the rectifier OFF immediately. This is reverse polarity. It turns the pipeline into the anode, forcing it to discharge massive amounts of current into the soil. This will cause the pipeline to corrode catastrophically and rapidly (electrolysis). Rewire it correctly (Positive to Anode, Negative to Structure).",
10),

(D,"oral",
"5. Why must you coat a thermite weld (Cadweld) on a pipeline?",
"","",
"Grade on: The thermite weld process burns off the pipeline coating and deposits a copper alloy weld nugget on the steel. Copper is more noble (cathodic) than steel. If left bare in the soil, an aggressive galvanic cell forms where the surrounding steel (anode) rusts rapidly to protect the copper weld. Coating it seals it from the electrolyte.",
10),

(D,"oral",
"6. What is 'Cathodic Disbondment'?",
"","",
"Grade on: It is the peeling away or separation of the protective coating from the steel pipeline, caused by the alkaline environment (high pH) and hydrogen gas bubbles generated at the steel surface by the cathodic protection current. It is exacerbated if the CP system is turned up too high (over-protection).",
10),

(D,"oral",
"7. How does a Copper/Copper Sulfate Reference Electrode work?",
"","",
"Grade on: It provides a stable, known baseline voltage. A pure copper rod sits in a saturated solution of copper sulfate. A porous ceramic plug at the bottom allows the solution to make electrical contact (ionic transfer) with the soil. You measure the difference between the pipeline voltage and this stable copper electrode voltage.",
10),

(D,"oral",
"8. You are doing a CP survey and your multimeter numbers are jumping all over the place, not stabilizing. What is the most likely cause?",
"","",
"Grade on: The most common cause is high contact resistance between the reference electrode and the soil. This happens if the soil is bone dry, if you place the electrode on pavement/gravel instead of soil, or if the porous plug on the electrode has dried out. Fix: Pour water on the soil, or wet the electrode plug.",
10),

(D,"oral",
"9. What is 'Stray Current' and why is it dangerous?",
"","",
"Grade on: Stray current is foreign electrical DC current flowing through the ground (e.g., from a nearby transit system or another pipeline's CP system). It enters your pipeline (protecting it), travels down the pipe, and then EXITS the pipe back into the soil to return to its source. Where it exits, it causes extreme, rapid pitting corrosion.",
10),

(D,"oral",
"10. What is an Isolation Flange kit used for?",
"","",
"Grade on: It is used to electrically separate a cathodically protected pipeline from an unprotected structure (like a plant, a pump station, or a grounding grid). Without it, the CP current would drain into the massive plant grounding grid, leaving the pipeline totally unprotected.",
10),

(D,"oral",
"11. Why do we put 'Coke Breeze' around Impressed Current anodes in a groundbed?",
"","",
"Grade on: Coke breeze is highly conductive carbon. It increases the effective surface area of the anode, drastically lowering the resistance to earth. More importantly, the current transfers electronically from the anode to the coke, and the coke discharges it to the soil. This means the cheap coke breeze consumes over time, protecting the expensive anode.",
10),

(D,"oral",
"12. Explain the 100 mV Polarization Shift criterion.",
"","",
"Grade on: It is used when the strict -850 mV criterion cannot be reached. You measure the 'Native' potential before CP is applied. You then apply CP and measure the 'Instant-Off' polarized potential. If the Instant-Off potential is at least 100 mV MORE NEGATIVE than the Native potential, the pipeline is considered adequately protected.",
10),

(D,"oral",
"13. What is the difference between CIPS and DCVG surveys?",
"","",
"Grade on: CIPS (Close Interval Potential Survey) measures the pipe-to-soil potential continuously (every meter) to ensure the pipe meets the CP criteria everywhere, not just at test stations. DCVG (Direct Current Voltage Gradient) measures voltage gradients in the soil to pinpoint the exact location of coating defects (holidays).",
10),

(D,"oral",
"14. A magnesium anode is connected to a pipeline. The soil is dry sand with a resistivity of 150,000 ohm-cm. Will the pipeline be protected?",
"","",
"Grade on: Highly unlikely. Magnesium anodes have a very low driving voltage (about 1.75V). In extremely high resistance soil (150,000 ohm-cm), Ohm's law (I=V/R) dictates that virtually zero current will flow. Impressed current systems are required for high resistivity soils.",
10),

(D,"oral",
"15. What is the risk of having a CP potential of -1.300 V on a high-strength steel pipeline?",
"","",
"Grade on: That is severe over-protection. It generates massive amounts of hydrogen gas at the pipe surface. On high-strength steel, atomic hydrogen can migrate into the steel structure causing Hydrogen Embrittlement, making the steel brittle and leading to catastrophic cracking and failure.",
10),

(D,"oral",
"16. When taking a pipe-to-soil measurement, which color lead of the multimeter goes to the pipe, and which goes to the reference electrode?",
"","",
"Grade on: By industry convention, the Positive (Red) lead goes to the structure/pipe, and the Negative (Black/COM) lead goes to the Reference Electrode. This ensures that a protected pipe reads as a negative value (e.g., -850 mV).",
10),

(D,"oral",
"17. You are inspecting an isolation flange using a standard digital multimeter set to Ohms. It reads 2 Ohms. Is the flange shorted?",
"","",
"Grade on: You cannot conclusively tell. A standard multimeter measures DC resistance, which will read the parallel path through the conductive fluid inside the pipe and the surrounding soil. To accurately test an in-service isolation flange, you must use a specialized RF (Radio Frequency) isolation tester that ignores parallel paths.",
10),

(D,"oral",
"18. What is a Solid State Decoupler (SSD) used for on a pipeline?",
"","",
"Grade on: It is an electrical safety device used where pipelines run parallel to high-voltage power lines. It connects the pipeline to a ground rod. It blocks the low-voltage DC CP current (keeping it on the pipe), but acts as a short circuit to drain dangerous induced high-voltage AC or lightning strikes safely to ground.",
10),

(D,"oral",
"19. What does 'Attenuation' mean in a cathodic protection system?",
"","",
"Grade on: It is the drop in CP potential (the pipe becomes less negative) as you move further away from the current source (the rectifier/drain point). This is caused by the electrical resistance of the pipe steel itself and current leaking away through minor coating defects over distance.",
10),

(D,"oral",
"20. How do you 'Hammer Test' a thermite weld?",
"","",
"Grade on: After the weld has cooled and the slag is chipped off, you take a 2-pound hammer and strike the weld nugget sharply with a glancing blow. If the weld is cold or poorly fused, it will pop right off. If it is a good weld, it will withstand the blow easily.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Demonstrate how to properly set up a digital multimeter and a Copper/Copper Sulfate Reference Electrode to measure a pipe-to-soil potential at a test station.",
"","",
"Grade on: 1. Remove cap from CSE, ensure it is full of blue fluid/crystals. 2. Plant CSE firmly into moist soil directly over the pipeline. 3. Connect the Negative (COM/Black) lead of the multimeter to the CSE. 4. Connect the Positive (Red) lead to the pipeline test wire. 5. Set multimeter to DC Volts (2V or 20V scale). 6. Read the negative voltage (e.g., -0.950 V).",
15),

(D,"practical",
"2. Review a CP survey log. The 'On' potential is -1.250 V. The 'Instant-Off' potential is -0.910 V. Calculate the IR Drop and determine if the NACE -850mV criterion is met.",
"","",
"Grade on: IR Drop = |On Potential| - |Instant-Off Potential| = 1.250 - 0.910 = 0.340 V (340 mV). The criterion relies on the Instant-Off (polarized) potential. The Instant-Off is -0.910 V, which is more negative than -0.850 V. Therefore, the pipeline IS protected and meets the NACE criterion.",
15),

(D,"practical",
"3. Identify the components required to make a Thermite Weld (Cadweld) on a pipe and explain the sequence of assembly.",
"","",
"Grade on: Components: Graphite mold, steel disk, weld powder cartridge, starting powder, flint gun, copper sleeve for wire. Sequence: Strip wire, put on sleeve. Grind pipe clean/dry. Clamp mold to pipe with wire inserted. Drop in steel disk. Pour in weld powder. Sprinkle start powder on lip. Close lid, ignite with flint gun. Let cool before removing.",
15),

(D,"practical",
"4. You are provided with an unfamiliar Rectifier. Demonstrate how you would safely measure the DC Voltage and DC Current output without relying on the panel gauges.",
"","",
"Grade on: Safety: Wear appropriate PPE, do not touch AC terminals. Voltage: Set multimeter to DC Volts. Place probes across the main DC Positive (Anode) and DC Negative (Structure) output lugs. Current: Do not break the circuit. Locate the 'Shunt' (a precision resistor, e.g., 50mV = 50A). Measure the millivolt drop across the shunt screws. Calculate current using the shunt ratio.",
15),

(D,"practical",
"5. Inspect a Copper/Copper Sulfate Reference Electrode (CSE) and determine if it is fit for service.",
"","",
"Grade on: Check 1: Is the copper rod bright and clean? (If green/black, it must be sanded). Check 2: Is the fluid clear and are excess blue copper sulfate crystals visible at the bottom? (Ensures saturation). Check 3: Is the porous ceramic tip moist? Check 4: No cracks in the plastic tube.",
15),

(D,"practical",
"6. Given a Soil Resistivity Meter (e.g., Nilsson) and 4 pins, draw the setup for a Wenner 4-Pin soil resistivity test and explain what the 'spacing' dictates.",
"","",
"Grade on: Draw 4 pins in a straight line at equal spacing 'a'. Connect outer pins to C1/C2 (Current), inner pins to P1/P2 (Potential/Voltage). The spacing 'a' dictates the DEPTH of the soil being measured. (e.g., if pins are 5 meters apart, the reading represents the average soil resistivity down to a depth of 5 meters).",
15),

(D,"practical",
"7. Review a schematic of an Impressed Current CP system. Identify the Rectifier, Anode Groundbed, Pipeline, and indicate the direction of DC current flow in the soil.",
"","",
"Grade on: Identify TR. Positive output goes to Anode Groundbed. Negative output goes to Pipeline. Show current leaving the TR, flowing down the anode cable, exiting the anodes, traveling THROUGH THE SOIL, entering the pipeline at coating holidays, traveling along the pipe metal, and returning up the negative cable to the TR.",
15),

(D,"practical",
"8. An isolation flange is installed above ground. Demonstrate how you would test its integrity using a Gas Electronics Model 601 (or similar RF tester).",
"","",
"Grade on: Turn tester on, short leads together to zero/calibrate. Place one probe on the pipe on the 'protected' side of the flange, and the other probe on the pipe on the 'unprotected' side. Read the meter dial. (A needle in the green 'isolated' zone means good; in the red 'shorted' zone means bad). Must test before the flange is buried.",
15),

(D,"practical",
"9. Explain how to perform a 100 mV Polarization Decay (Depolarization) test.",
"","",
"Grade on: 1. Leave CP system running normally. 2. Use a synchronized interrupter to measure the 'Instant-Off' polarized potential (e.g., -0.780 V). 3. Turn the Rectifier completely OFF and leave it off. 4. Return after a specific time (e.g., 24, 48 hours or longer) and measure the new potential (e.g., -0.650 V). 5. Calculate decay: |-0.780| - |-0.650| = 130 mV. Since 130 > 100, the criteria is met.",
15),

(D,"practical",
"10. Inspect a photograph of an excavated pipeline showing severe pitting corrosion grouped tightly on the bottom of the pipe near a foreign pipeline crossing. Diagnose the likely cause.",
"","",
"Grade on: The localized, severe pitting at a crossing location is the hallmark of Stray Current Interference. Current from the foreign pipeline's CP system entered this pipeline, traveled along it, and discharged (jumped off) exactly at this point to return to the foreign pipe, taking the steel with it.",
15),

(D,"practical",
"11. Calculate the expected current output of a Magnesium Anode system. Driving voltage of Mg = -1.75V. Polarized potential of pipe = -0.85V. Total circuit resistance (mostly soil) = 15 Ohms.",
"","",
"Grade on: Net Driving Voltage (Delta V) = |-1.75 V| - |-0.85 V| = 0.90 Volts. Ohm's Law: I = V / R. I = 0.90 V / 15 Ohms = 0.06 Amps (or 60 mA). The anode will output 60 mA of protective current.",
15),

(D,"practical",
"12. You measure the potential on a pipeline and get a reading of +0.850 V instead of -0.850 V. What is the most likely mistake you made?",
"","",
"Grade on: The polarity of the multimeter leads is reversed. You connected the Red (Positive) lead to the Reference Electrode and the Black (Negative/COM) lead to the Pipeline. Swap the leads to get the correct negative reading.",
15),

(D,"practical",
"13. Review a set of CIPS (Close Interval Potential Survey) data plotted on a graph. Identify the areas where the pipeline is under-protected and suggest a cause.",
"","",
"Grade on: Look at the graph line representing the 'Instant-Off' potential. Identify any dips where the line moves above -850 mV (e.g., -700 mV). These 'valleys' are under-protected. Causes: Major coating damage (holidays) drawing too much current, stray current interference, or being too far from the rectifier (attenuation).",
15),

(D,"practical",
"14. Demonstrate how to read a Rectifier Shunt to determine current output. The shunt is stamped '50 mV = 50 A'. You measure 25 mV across the shunt screws with your multimeter.",
"","",
"Grade on: The shunt ratio is 50A / 50mV = 1 Amp per millivolt. If you measure 25 mV across the shunt, the current flowing is 25 mV * (1 A/mV) = 25 Amps. The rectifier is outputting 25 Amps.",
15),

(D,"practical",
"15. Evaluate a scenario: A pipeline is protected by ICCP. The rectifier is maxed out at 50 Volts, but is only outputting 2 Amps. It used to output 30 Amps at 15 Volts. What is the problem?",
"","",
"Grade on: Calculate Resistance: R = V/I. Old R = 15/30 = 0.5 Ohms. New R = 50/2 = 25 Ohms. The circuit resistance has skyrocketed. Likely causes: The anode groundbed has dried out completely, the positive header cable is cut/broken, or the anodes have completely consumed themselves and disconnected.",
15),

(D,"practical",
"16. Identify the difference between a Magnesium anode and a Zinc anode visually or by application, and state when you would use Zinc.",
"","",
"Grade on: Magnesium is used in standard/high resistivity soils because it has a high driving voltage (-1.75V). Zinc has a lower driving voltage (-1.1V). Zinc is typically used in extremely low resistivity environments (like seawater, mud, or salt marshes) where Magnesium would consume far too rapidly. (Visual: Anodes often have stamped IDs or specific shapes depending on manufacturer).",
15),

(D,"practical",
"17. Inspect a test station box. There are two thick cables and two thin cables. Explain how you would set up a '4-Wire' current span test to measure current flowing along the pipeline.",
"","",
"Grade on: A 4-wire span has two wires attached at Point A, and two attached at Point B (e.g., 100 feet away). Measure the millivolt drop between the inner two wires using a high-precision voltmeter. Apply a known current between the outer two wires using a battery to calibrate the span (determine the resistance of that 100ft of pipe). Use Ohm's law to calculate the actual pipeline current based on the mV drop.",
15),

(D,"practical",
"18. You are tasked with installing a galvanic anode. Demonstrate the preparation of the anode and backfill prior to burial.",
"","",
"Grade on: Leave the cloth bag ON the anode (it contains the special backfill). DO NOT remove the bag. Pre-soak the anode/bag in a bucket of water until it stops bubbling to ensure the backfill is saturated and conductive immediately upon burial. Lower into the hole, backfill with native soil, and compact.",
15),

(D,"practical",
"19. Review a DCVG (Direct Current Voltage Gradient) survey report. The operator noted an 'IR %' of 55% at Station 10+500. What does this mean and what action is required?",
"","",
"Grade on: DCVG estimates coating defect severity by expressing the voltage gradient to the defect as a percentage of the total IR drop. 55% is a 'Severe' defect (typically > 35% is severe). Action: This location must be marked for immediate excavation, physical inspection, and coating repair.",
15),

(D,"practical",
"20. Explain the safety procedures required when working on a pipeline affected by AC induction from overhead power lines before disconnecting any CP cables.",
"","",
"Grade on: Never break a connection with bare hands. Use an AC voltmeter to measure the pipe-to-ground AC voltage. If it is >15V AC, it is a lethal shock hazard. Wear Class 0 electrical insulating gloves. Use jumper cables to maintain continuity before cutting or disconnecting any bonds or test cables, as an arc can strike and cause electrocution.",
15),

]  # end QUESTIONS
