"""
E&I QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: NFPA 70 (NEC), IEC 60079, IEC 61511, SAES-J, SAES-P, API RP 500, ISA
"""

D = "E&I QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. When routing instrument and electrical power cables in the same trench, what is the minimum typical separation distance required between 415V power cables and 24VDC instrument signal cables per SAES standards to prevent EMI?",
"0 mm (can be bundled together)\n100 mm\n300 mm\n1000 mm",
"300 mm",
"To prevent Electromagnetic Interference (EMI) from power cables inducing noise onto sensitive instrument signal cables, a physical separation of at least 300 mm (approx. 12 inches) is standard practice when routed in parallel without metallic barriers.",
1),

(D,"mcq",
"2. In a hazardous area classification drawing, a sump pit containing flammable liquids is typically classified as:",
"Zone 0 (or Class I, Div 1)\nZone 1\nZone 2\nSafe Area",
"Zone 0 (or Class I, Div 1)",
"A sump pit holding flammable liquids represents an area where an explosive gas atmosphere is present continuously or for long periods, which meets the definition of Zone 0 (or Class I, Div 1 under NEC).",
1),

(D,"mcq",
"3. What is the primary purpose of a 'Cable Transit System' (e.g., MCT - Multi Cable Transit) where cables pass through a control room wall?",
"To organize cables neatly.\nTo prevent water ingress only.\nTo maintain the fire rating and gas-tight integrity of the wall.\nTo provide strain relief for the cables.",
"To maintain the fire rating and gas-tight integrity of the wall.",
"MCTs use intumescent blocks that expand under heat. Their primary safety function is to seal the cable penetration, maintaining the structural fire rating and preventing toxic/flammable gases from migrating into safe areas like control rooms.",
1),

(D,"mcq",
"4. Which of the following grounding systems is dedicated solely to protecting sensitive electronic instrumentation from electrical noise?",
"Protective Earth (PE) / Safety Ground\nInstrument Clean Ground (Isolated Ground)\nLightning Protection System (LPS)\nStatic Bonding Ground",
"Instrument Clean Ground (Isolated Ground)",
"The Instrument Clean Ground (or Isolated Ground) is a separate grounding network designed to provide a low-noise reference potential for instrument shields and electronic circuits, isolated from the noisy electrical safety ground (PE) until a single point of connection at the main earth triad.",
1),

(D,"mcq",
"5. An Ex e (Increased Safety) junction box relies on which principle for explosion protection?",
"Containing an internal explosion without rupturing.\nLimiting the energy of a spark to below the ignition threshold.\nPreventing the occurrence of arcs, sparks, and excessive temperatures in normal operation.\nPurging the enclosure with a continuous flow of clean air.",
"Preventing the occurrence of arcs, sparks, and excessive temperatures in normal operation.",
"Ex e (Increased Safety) equipment is designed with high-integrity components (like special non-loosening terminals and high-quality insulation) to ensure that arcs, sparks, or dangerous temperatures cannot occur under normal operation. It does not contain explosions.",
1),

(D,"mcq",
"6. What is the standard testing voltage for performing an Insulation Resistance (Megger) test on a 24VDC instrument cable?",
"50 VDC\n250 VDC or 500 VDC\n1000 VDC\n5000 VDC",
"250 VDC or 500 VDC",
"For low voltage instrument cables (typically rated 300/500V), a Megger test is usually performed at 250 VDC or 500 VDC to avoid over-stressing and damaging the thin insulation.",
1),

(D,"mcq",
"7. When installing a gland on an armored cable (SWA) entering an Ex d (Flameproof) enclosure in a Zone 1 area, what must the gland provide?",
"Electrical isolation from the enclosure.\nClamping of the armor for grounding and a flameproof seal on the inner bedding of the cable.\nWaterproofing only.\nA flexible connection.",
"Clamping of the armor for grounding and a flameproof seal on the inner bedding of the cable.",
"An Ex d armored cable gland must perform multiple functions: it must physically secure and electrically ground the steel wire armor (SWA), and it must provide an inner seal (often via a compressible ring or poured resin compound) to maintain the flameproof integrity of the enclosure.",
1),

(D,"mcq",
"8. A DCS analog output card sends a 4-20mA signal to a control valve positioner. If the wire is accidentally short-circuited to ground midway, what will happen?",
"The positioner will open fully.\nThe DCS card will blow a fuse or go into fault, and the valve will fail to its safe state.\nThe DCS will automatically increase voltage to push the current through.\nThe positioner will remain in its last position.",
"The DCS card will blow a fuse or go into fault, and the valve will fail to its safe state.",
"A short to ground in an active 4-20mA output loop will cause maximum current to flow, likely tripping the DCS channel's short-circuit protection (or blowing a fuse). The loss of signal at the positioner will cause the valve to move to its designed fail-safe mechanical position.",
1),

(D,"mcq",
"9. In an Intrinsically Safe (IS) circuit, what color is globally recognized for IS cables, terminals, and junction boxes?",
"Red\nYellow\nLight Blue\nGreen/Yellow",
"Light Blue",
"Light blue is the standard industry color code (per IEC standards) used to readily identify Intrinsically Safe wiring, terminals, and cable jackets, ensuring they are not accidentally mixed with non-IS circuits.",
1),

(D,"mcq",
"10. Which device is used to safely isolate a high-voltage electrical circuit to allow instrumentation work on a connected potential transformer (PT)?",
"A standard light switch\nA molded case circuit breaker (MCCB) only\nA physical disconnect switch (Isolator) that provides a visible break and can be padlocked (LOTO)\nA contractor",
"A physical disconnect switch (Isolator) that provides a visible break and can be padlocked (LOTO)",
"For safety isolation (Lockout/Tagout), a disconnect switch that provides a guaranteed visible mechanical break in the circuit and can be padlocked in the open position is required to ensure the circuit cannot be inadvertently energized.",
1),

(D,"mcq",
"11. What does the term 'Cold Junction Compensation' apply to?",
"RTD measurement circuits\nThermocouple measurement circuits\nFiber optic splicing\nMotor bearing cooling",
"Thermocouple measurement circuits",
"Thermocouples generate a voltage based on the temperature difference between the hot junction and the cold junction (the terminals). Cold Junction Compensation (CJC) is required at the receiving instrument to measure the terminal temperature and calculate the true hot junction temperature.",
1),

(D,"mcq",
"12. What is the purpose of an 'End of Line' (EOL) resistor in a fire and gas detection loop?",
"To reduce the voltage to the detectors.\nTo allow the control panel to monitor the integrity of the wiring for open or short circuits.\nTo increase the sensitivity of the detector.\nTo act as a surge protector.",
"To allow the control panel to monitor the integrity of the wiring for open or short circuits.",
"An EOL resistor is placed at the very end of a detector loop. A small continuous current flows through it. If the wire breaks (open circuit), current drops to zero. If the wire shorts, current spikes. The panel uses this to monitor wire integrity.",
1),

(D,"mcq",
"13. When installing cable trays for electrical and instrumentation cables, how should they be oriented horizontally?",
"High voltage trays at the bottom, instrument trays at the top.\nInstrument trays at the top, high voltage trays at the bottom.\nSide-by-side with no gap.\nIt does not matter.",
"Instrument trays at the top, high voltage trays at the bottom.",
"Standard practice is to route highest voltage cables at the lowest tier and lowest voltage/instrument cables at the highest tier. This is for safety (heavy power cables won't crush light instrument cables if a tray drops) and to minimize heat rising from power cables onto signal cables.",
1),

(D,"mcq",
"14. A variable frequency drive (VFD) is used to control a pump motor. What type of cable is strongly recommended between the VFD and the motor to prevent EMI and bearing damage?",
"Standard unshielded PVC cable\nArmored but unshielded cable\nSymmetrical shielded VFD cable (e.g., 3 phase conductors + 3 symmetrical grounds with copper tape/braid shield)\nTwisted pair instrument cable",
"Symmetrical shielded VFD cable (e.g., 3 phase conductors + 3 symmetrical grounds with copper tape/braid shield)",
"VFDs generate high-frequency PWM switching noise. Specially designed VFD cables with continuous shielding and symmetrical ground wires are required to contain EMI and reduce common-mode currents that can destroy motor bearings.",
1),

(D,"mcq",
"15. What is the typical failure mode (safe state) for an ESD (Emergency Shutdown) blowdown valve on a gas compressor?",
"Fail Closed (FC)\nFail Last Position (FL)\nFail Open (FO)\nFail Indeterminate",
"Fail Open (FO)",
"A blowdown valve's safety function is to quickly vent pressurized gas to the flare during an emergency. Therefore, upon loss of air or power, the valve must automatically Fail Open.",
1),

(D,"mcq",
"16. In ATEX/IECEx marking, what does 'Ex i' indicate?",
"Increased safety\nFlameproof\nIntrinsically safe\nPressurized",
"Intrinsically safe",
"Ex i designates Intrinsic Safety. The circuit's energy is limited to prevent sparks or thermal effects capable of causing ignition. Subcategories include ia (Zone 0), ib (Zone 1), and ic (Zone 2).",
1),

(D,"mcq",
"17. A Fieldbus segment requires power. How is power delivered to Foundation Fieldbus transmitters?",
"Via a separate 110VAC power cable to each instrument.\nVia solar panels.\nPower and digital communications share the same two-wire twisted pair.\nThrough the metallic conduit.",
"Power and digital communications share the same two-wire twisted pair.",
"Foundation Fieldbus H1 and PROFIBUS PA provide both DC power (from a power conditioner) and digital communication signals over the same two-wire twisted pair shielded cable.",
1),

(D,"mcq",
"18. When performing a loop check on a motor from the DCS, what signal is typically sent FROM the DCS to start the motor?",
"A 4-20mA analog signal\nA 220VAC power supply\nA dry contact closure (Digital Output) to the MCC control circuit\nA Modbus integer",
"A dry contact closure (Digital Output) to the MCC control circuit",
"The DCS typically provides a Digital Output (DO), which is a relay contact closure. This closes a low-power control circuit in the Motor Control Center (MCC), which then energizes the main contactor coil to start the motor.",
1),

(D,"mcq",
"19. Which test is critical to perform on an electrical motor before coupling it to a pump for the first time?",
"Vibration test at full load\nBump test to verify direction of rotation\nTemperature rise test\nEfficiency test",
"Bump test to verify direction of rotation",
"Before coupling, a 'bump test' (briefly energizing the motor) must be performed uncoupled to ensure the motor rotates in the correct direction. Running a pump backwards can cause catastrophic damage (e.g., unscrewing impellers).",
1),

(D,"mcq",
"20. What is the function of a 'Zener Barrier' in an instrumentation circuit?",
"To amplify a weak 4-20mA signal.\nTo divert fault voltages to ground and limit current, making the field circuit intrinsically safe.\nTo convert AC to DC power.\nTo filter out high-frequency electrical noise.",
"To divert fault voltages to ground and limit current, making the field circuit intrinsically safe.",
"A Zener barrier uses Zener diodes to clamp fault voltages to a safe level (diverting excess to ground) and resistors to limit current, ensuring the energy reaching the hazardous area remains below ignition levels.",
1),

(D,"mcq",
"21. According to NEC/API RP 500, how is a 'Class I, Division 2' area defined?",
"An area where ignitable concentrations of flammable gases are present continuously.\nAn area where flammable gases are handled, but are normally confined within closed piping/systems, escaping only during accidental rupture or breakdown.\nAn area with combustible dust.\nAn area completely free of any hazards.",
"An area where flammable gases are handled, but are normally confined within closed piping/systems, escaping only during accidental rupture or breakdown.",
"Class I, Div 2 (roughly equivalent to Zone 2) is an area where hazardous gases are not normally present in explosive concentrations, occurring only under abnormal conditions like a leak or equipment failure.",
1),

(D,"mcq",
"22. When calibrating a smart pressure transmitter, what does the term 'Trim' mean?",
"Cutting the wires to the correct length.\nAdjusting the digital reading of the sensor to match a known precise pressure standard (Sensor Trim) or adjusting the 4-20mA output to match a precision multimeter (Output Trim).\nPainting the housing.\nSetting the engineering units.",
"Adjusting the digital reading of the sensor to match a known precise pressure standard (Sensor Trim) or adjusting the 4-20mA output to match a precision multimeter (Output Trim).",
"Trimming is a true calibration adjustment. Sensor Trim corrects the digital interpretation of the physical sensor. Analog Output Trim (D/A Trim) ensures the digital command for 4mA actually produces exactly 4.000mA on the wire.",
1),

(D,"mcq",
"23. What type of signal does a standard industrial RTD (Resistance Temperature Detector) output?",
"Voltage (mV)\nCurrent (4-20mA)\nResistance (Ohms)\nDigital Pulses",
"Resistance (Ohms)",
"An RTD is a passive element whose electrical resistance changes predictably with temperature. It outputs resistance (Ohms), which must be read by a bridge circuit in a transmitter or PLC input card.",
1),

(D,"mcq",
"24. In an electrical schematic, what does 'NO' and 'NC' stand for regarding relay contacts?",
"No Output / No Connection\nNormally Open / Normally Closed\nNew Option / Next Circuit\nNegative Output / Negative Current",
"Normally Open / Normally Closed",
"Normally Open (NO) contacts are open when the relay coil is de-energized and close when energized. Normally Closed (NC) contacts are closed when de-energized and open when energized.",
1),

(D,"mcq",
"25. Why are instrumentation cable shields grounded at one end only?",
"To save wire and installation time.\nTo prevent the flow of ground loop currents through the shield, which would introduce electrical noise into the signal.\nBecause the field end does not have a ground rod.\nTo allow the shield to act as an antenna.",
"To prevent the flow of ground loop currents through the shield, which would introduce electrical noise into the signal.",
"If a shield is grounded at both the field and control room ends, slight differences in earth potential between the two locations will cause a current (ground loop) to flow through the shield. This current induces noise into the signal wires inside.",
1),

(D,"mcq",
"26. What is the primary purpose of a 'Seal Fitting' (EYS) in a conduit system installed in a Class I, Div 1 hazardous area?",
"To keep rainwater out of the conduit.\nTo provide a physical stop for pulling cables.\nTo prevent the passage of explosive gases or flames from one portion of the electrical installation to another through the conduit system.\nTo ground the conduit.",
"To prevent the passage of explosive gases or flames from one portion of the electrical installation to another through the conduit system.",
"Conduit seal fittings are filled with a specialized expanding cement compound. They prevent an explosion occurring in one enclosure from traveling down the conduit pipe and igniting gases in another area.",
1),

(D,"mcq",
"27. During a megger test on a 415V motor, the resistance is measured between the phases and the motor casing (ground). What is a generally acceptable minimum reading for a new motor?",
"0 Ohms\n1 Kilo-ohm\n100 Mega-ohms or greater\n1 Ohm",
"100 Mega-ohms or greater",
"A new 415V motor should have very high insulation resistance to ground, typically well over 100 Mega-ohms (MΩ). A reading in Kilo-ohms or a few Mega-ohms indicates severe moisture or insulation failure.",
1),

(D,"mcq",
"28. A 'P&ID' is a critical document for E&I QC. What does P&ID stand for?",
"Power and Instrument Diagram\nPiping and Instrumentation Diagram\nProcess and Interlock Document\nPressure and Indication Diagram",
"Piping and Instrumentation Diagram",
"The Piping and Instrumentation Diagram (P&ID) is the primary schematic showing all piping, equipment, and instrumentation/control loops in a process plant.",
1),

(D,"mcq",
"29. Which device is used to measure the current flowing through a large high-voltage cable without breaking the circuit?",
"A standard inline multimeter\nA Potential Transformer (PT)\nA Current Transformer (CT) or a clamp-on ammeter\nA Wheatstone bridge",
"A Current Transformer (CT) or a clamp-on ammeter",
"Current Transformers (CTs) step down high currents to safely measurable levels (e.g., 5A or 1A). Clamp-on ammeters use the CT principle to measure the magnetic field around a conductor without disconnecting it.",
1),

(D,"mcq",
"30. A solenoid valve coil is rated for 24VDC. The technician measures the voltage at the coil and reads 18VDC. The valve fails to open. What is the most likely cause?",
"The coil is short-circuited.\nExcessive voltage drop in the control cable due to the wire gauge being too small or the run being too long.\nThe valve is mechanically stuck.\nThe air supply pressure is too high.",
"Excessive voltage drop in the control cable due to the wire gauge being too small or the run being too long.",
"A voltage drop from 24V at the source to 18V at the coil indicates high resistance in the wiring (too long or too thin). Solenoid coils require a minimum voltage (pull-in voltage) to generate enough magnetic force to open the valve.",
1),

(D,"mcq",
"31. In SIL (Safety Integrity Level) terminology, what does 'PFD' stand for?",
"Process Flow Diagram\nProbability of Failure on Demand\nPrimary Fault Detection\nProcess Failure Data",
"Probability of Failure on Demand",
"PFD is the statistical probability that a safety system (like an ESD loop) will fail to perform its specified safety function when a hazardous demand occurs. A lower PFD corresponds to a higher SIL rating.",
1),

(D,"mcq",
"32. What is the function of an 'Interposing Relay' in a DCS motor control circuit?",
"To measure the motor current.\nTo electrically isolate the low-voltage DCS digital output from the higher-voltage/current MCC control circuit.\nTo provide overload protection for the motor.\nTo act as a variable frequency drive.",
"To electrically isolate the low-voltage DCS digital output from the higher-voltage/current MCC control circuit.",
"DCS digital output cards (e.g., 24VDC, low current) cannot directly switch large contactor coils in an MCC (e.g., 110VAC or 220VAC). An interposing relay acts as a bridge, allowing the safe, low-power DCS signal to switch the heavier MCC load.",
1),

(D,"mcq",
"33. When inspecting an Ex d (Flameproof) enclosure after maintenance, you notice a deep scratch across the machined flange face. What is the implication?",
"It is a cosmetic issue; paint over it.\nThe enclosure is compromised. The scratch creates a path that could allow hot gases/flames from an internal explosion to escape and ignite the external atmosphere.\nIt improves cooling of the enclosure.\nApply silicone sealant to the scratch to fix it.",
"The enclosure is compromised. The scratch creates a path that could allow hot gases/flames from an internal explosion to escape and ignite the external atmosphere.",
"Ex d enclosures rely on the tight tolerance of the metal-to-metal flame path (flange) to cool escaping gases. A scratch ruins this tolerance, destroying the certification. The enclosure must be replaced or repaired by a certified facility (sealants are strictly forbidden).",
1),

(D,"mcq",
"34. A 'UPS' is critical in E&I systems. What does UPS stand for and what is its primary function?",
"Universal Power Supply; converts AC to DC.\nUninterruptible Power Supply; provides continuous emergency battery power to critical systems (like DCS) during a main power failure.\nUnified Pressure System; maintains instrument air.\nUtility Power Switch; transfers power to the grid.",
"Uninterruptible Power Supply; provides continuous emergency battery power to critical systems (like DCS) during a main power failure.",
"A UPS uses batteries and an inverter to provide clean, seamless AC power to critical control and safety systems, allowing them to remain operational or shut down safely during a total plant power outage.",
1),

(D,"mcq",
"35. Which calibration parameter describes the maximum difference between upscale and downscale readings for the same applied input?",
"Linearity\nAccuracy\nHysteresis\nZero Drift",
"Hysteresis",
"Hysteresis (often grouped with deadband) is the difference in output reading when an input is approached from a lower value (upscale) versus when the same input is approached from a higher value (downscale).",
1),

(D,"mcq",
"36. What is the purpose of 'Heat Tracing' on instrument impulse lines?",
"To increase the pressure of the fluid.\nTo maintain the fluid inside the tubing at a specific temperature, preventing freezing or crystallization.\nTo melt the tubing for easy bending.\nTo burn off impurities in the process fluid.",
"To maintain the fluid inside the tubing at a specific temperature, preventing freezing or crystallization.",
"Electrical or steam heat tracing is wrapped around impulse lines (and covered with insulation) to prevent static fluids from freezing in cold weather or highly viscous fluids/waxes from solidifying and blocking the measurement lines.",
1),

(D,"mcq",
"37. In fiber optic communications, what does an 'OTDR' measure?",
"Optical voltage and current.\nThe exact location of splices, breaks, and attenuation (signal loss) along the length of the fiber optic cable.\nThe color of the light.\nThe digital bit rate of the network.",
"The exact location of splices, breaks, and attenuation (signal loss) along the length of the fiber optic cable.",
"An Optical Time-Domain Reflectometer (OTDR) sends light pulses down a fiber and measures the reflected light. It acts like an optical radar, creating a 'trace' that identifies the exact distance to faults, splices, and measures signal loss (dB/km).",
1),

(D,"mcq",
"38. A control valve requires a 4-20mA signal and a 60 psi air supply. However, the DCS can only output 4-20mA, and the valve actuator is pneumatic. What device is required mounted on the valve?",
"A Limit Switch\nA Solenoid Valve\nAn I/P (Current to Pressure) Transducer / Smart Positioner\nA Pressure Regulator",
"An I/P (Current to Pressure) Transducer / Smart Positioner",
"An I/P transducer (or an electro-pneumatic smart positioner) receives the 4-20mA electrical signal from the DCS and converts it into a proportional pneumatic output pressure to physically move the valve actuator.",
1),

(D,"mcq",
"39. When meggering a motor, you must strictly avoid meggering which type of components attached to the circuit?",
"The copper windings.\nThe steel casing.\nElectronic components such as VFDs, soft starters, or electronic protection relays.\nThe terminal block.",
"Electronic components such as VFDs, soft starters, or electronic protection relays.",
"Meggers apply high DC voltages (500V or 1000V) to test insulation. If this voltage is applied to sensitive solid-state electronic devices (like VFD power electronics or electronic relays), it will instantly destroy them. They must be disconnected before testing.",
1),

(D,"mcq",
"40. What is a 'Junction Box (JB)' primary function in an E&I installation?",
"To act as a localized control panel with pushbuttons.\nTo consolidate multiple individual field instrument/power cables into a larger multi-core home-run cable leading to the control room or substation.\nTo step down high voltage to low voltage.\nTo generate a 4-20mA signal.",
"To consolidate multiple individual field instrument/power cables into a larger multi-core home-run cable leading to the control room or substation.",
"Junction boxes serve as consolidation points. Instead of running 50 separate cables 500 meters to a control room, they are run short distances to a local JB, and then one large 50-pair multi-core cable is run the 500 meters, saving massive amounts of copper, tray space, and labor.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Explain the differences between Intrinsically Safe (Ex i) and Flameproof (Ex d) protection concepts. Detail the inspection requirements for both types of installations before commissioning.",
"","",
"Grade on: Definitions: Ex i limits energy (V, I, capacitance, inductance) so sparks cannot ignite gas. Ex d contains the explosion and cools escaping gases via flame paths. Inspection Ex i: Verify barrier type matches design, cable parameters (L, C) are within barrier limits, light blue cable/terminals, segregation from non-IS circuits, grounding of IS earth. Inspection Ex d: Flange gaps within tolerance, no scratches on flame paths, all bolts present and torqued, correct certified cable glands, poured seals if conduit is used, enclosure not compromised.",
20),

(D,"essay",
"2. Describe the step-by-step process of performing a complete loop check for a motor controlled from a DCS. Include coordination between the control room, MCC, and the field.",
"","",
"Grade on: 1. Ensure all wiring/megger tests are complete. 2. Station personnel at DCS, MCC, and Motor. 3. Ensure motor is uncoupled from load. 4. DCS sends 'Start' command. 5. MCC personnel verify contactor pulls in. 6. Field verifies motor turns and notes direction (Bump Test). 7. DCS sends 'Stop', verify motor stops. 8. Simulate field trips (e.g., Local Stop button, ESD). 9. Simulate MCC trips (Thermal overload). 10. Verify all feedback statuses (Run, Stop, Fault, Local/Remote) are correctly displayed on DCS HMI. 11. Sign off loop folder.",
20),

(D,"essay",
"3. You are auditing a contractor's cable tray installation in a petrochemical plant. Detail the specific Quality Control checks you will perform regarding routing, segregation, fill capacity, and grounding.",
"","",
"Grade on: Routing: Follows approved drawings, avoids hot surfaces/vibration. Segregation: Minimum 300mm spacing between HV power, LV power, and Instrument/IS trays. Top-down arrangement (Instrument top, HV bottom). Fill Capacity: Maximum 40-50% fill to allow heat dissipation and future additions. Grounding: Tray sections bonded across splices using earth jumpers; tray system connected to plant earth grid at regular intervals (e.g., every 15-30m) to prevent floating potentials.",
20),

(D,"essay",
"4. What is a Safety Instrumented System (SIS)? How does it differ from a Basic Process Control System (BPCS)? Explain the concept of SIL and the importance of Proof Testing.",
"","",
"Grade on: SIS is an independent system designed to take the process to a safe state when predefined limits are breached. BPCS is the normal DCS used for day-to-day dynamic control. They must be physically and logically separated. SIL (Safety Integrity Level) is a measure of the reliability (Probability of Failure on Demand) of the SIS loop (SIL 1 to 4). Proof Testing is periodic manual testing (e.g., stroking an ESD valve) to find hidden dangerous failures that automatic diagnostics miss, maintaining the required SIL rating.",
20),

(D,"essay",
"5. Detail the procedure for calibrating a Smart Differential Pressure Transmitter used for flow measurement. Discuss the equipment needed, the five-point calibration method, and the calculation of error.",
"","",
"Grade on: Equipment: HART communicator, pressure calibrator (pump + precision gauge), multimeter. Setup: Isolate via 5-valve manifold, vent to atmosphere. 5-Point check: Apply 0%, 25%, 50%, 75%, 100% of the DP range. Record mA output at each step. Calculation: Error = [(Actual mA - Ideal mA) / 16mA] × 100. Adjustments: If error exceeds tolerance (e.g., 0.25%), use HART to perform 'Sensor Trim' (adjusting digital reading to actual pressure) and 'Analog Output Trim' (adjusting output to exactly 4 and 20mA). Document As-Found/As-Left.",
20),

(D,"essay",
"6. Discuss the importance and methodology of testing a plant's Grounding (Earthing) System. Include descriptions of the Fall-of-Potential method and continuity testing.",
"","",
"Grade on: Importance: Personnel safety (prevents touch potentials), equipment protection (lightning/fault currents), and instrumentation noise reduction. Fall-of-Potential: Used to measure the resistance of the main earth grid to true earth. Involves driving a current probe far away, moving a voltage probe at intervals, and plotting resistance to find the 'flat' plateau (true resistance, typical spec <1 Ohm or <5 Ohms). Continuity testing: Ensures all equipment frames, vessels, and trays are solidly connected to the grid (typical spec <0.1 Ohms).",
20),

(D,"essay",
"7. A newly installed control valve is hunting (oscillating) uncontrollably. As the E&I Inspector, outline your troubleshooting methodology covering pneumatic, mechanical, and electronic systems.",
"","",
"Grade on: Electronic: Check DCS PID tuning (Proportional gain too high?). Check 4-20mA signal stability at the positioner. Pneumatic: Check instrument air supply pressure (is it dropping under load?). Check positioner internal relays/piezo. Mechanical: Check valve stem for binding/friction (overtightened packing, galled trim). 'Stick-slip' behavior causes hunting. Run a valve signature trace using HART diagnostics to view friction and hysteresis.",
20),

(D,"essay",
"8. Explain the principles of Foundation Fieldbus (FF). How does its architecture reduce wiring, and what specific physical layer parameters must a QC inspector verify during commissioning?",
"","",
"Grade on: Principles: A digital, two-way, multi-drop communication protocol where instruments act as nodes on a LAN, allowing peer-to-peer control in the field. Reduces wiring by putting multiple devices (up to 12-16) on a single twisted pair (trunk/spur) instead of point-to-point. QC checks: Verify segment voltage (>9VDC at furthest device). Verify exactly TWO terminators per segment. Check for correct cable type (Type A). Perform segment checkout using oscilloscope/analyzer to check signal amplitude, noise levels, and jitter.",
20),

(D,"essay",
"9. Describe the inspection criteria for cable glanding and termination of a Steel Wire Armored (SWA) cable into an electrical panel. What are the common faults you would look for?",
"","",
"Grade on: Preparation: Cable cut clean, armor cut to correct length, inner bedding intact. Gland assembly: Cone and ring correctly clamping the armor (not too loose, not cutting armor). Shroud fitted. Termination: Earth tag installed and bonded to panel earth bus. Conductors stripped without nicking copper. Correct size crimp lugs used and crimped with calibrated tool (no loose strands). Heat shrink applied if specified. Common faults: Armor not gripping, armor exposed outside shroud, loose crimps, incorrect gland type for area classification.",
20),

(D,"practical",
"10. What is an Automatic Transfer Switch (ATS) and a Uninterruptible Power Supply (UPS)? Explain their roles during a total plant power failure.",
"","",
"Grade on: ATS senses loss of main utility power, sends a start signal to the emergency diesel generator, and safely transfers the electrical load to the generator once voltage/frequency are stable. UPS utilizes a rectifier/battery bank/inverter to provide instantaneous, uninterrupted clean AC power to critical control systems (DCS, SIS). Sequence: Power fails -> UPS instantly carries critical load on batteries -> Generator starts (10-15s) -> ATS switches to Gen -> Gen supplies plant emergency loads and recharges UPS.",
20),

(D,"essay",
"11. Discuss the specific hazards associated with Variable Frequency Drives (VFDs) regarding harmonics and motor bearing currents. How are these mitigated in the installation?",
"","",
"Grade on: Harmonics: VFD rectifiers pull non-linear current, distorting the plant AC voltage sine wave, causing overheating in transformers. Mitigated by line reactors or active harmonic filters. Bearing Currents: High-frequency PWM switching creates common-mode voltages that discharge through motor bearings, causing pitting/fluting and premature failure. Mitigated by using symmetrical shielded VFD cables, grounding rings on the motor shaft, and isolated motor bearings.",
20),

(D,"essay",
"12. Detail the requirements for installing impulse tubing for a differential pressure flow transmitter measuring steam flow. Why are condensate pots used?",
"","",
"Grade on: Tubing must slope continuously down from the orifice taps to the transmitter (usually mounted below) to keep lines full of condensate and prevent air pockets. Condensate Pots (Seal Pots) must be installed at the same elevation at the tapping points. Purpose: To provide a reservoir of condensed water, ensuring the impulse lines remain full of liquid and protecting the transmitter diaphragm from live, high-temperature steam. Both pots must be filled with water equally before opening to the process to prevent zero shift.",
20),

(D,"essay",
"13. Outline the Quality Control documentation package (dossier) required for the handover of an E&I project. What certificates, drawings, and reports must be included?",
"","",
"Grade on: Dossier must include: Approved IFC drawings updated to 'As-Built' (P&IDs, Loop Diagrams, Cable Schedules). Instrument Calibration Certificates (NIST traceable). Cable test reports (Megger, Continuity, OTDR for fiber). Earth resistance test reports. Loop Check and Functional Test sign-off sheets. Ex (Hazardous Area) Equipment Register and inspection sheets. Material Test Certificates (MTCs) for bulk items. FAT/SAT reports for major packages (DCS, UPS).",
20),

(D,"essay",
"14. A motor control center (MCC) is being tested prior to energization. Describe the Insulation Resistance (Megger) and Dielectric Withstand (Hi-Pot) tests performed on the busbars.",
"","",
"Grade on: Megger test: Uses 500V or 1000V DC to check resistance between phases (A-B, B-C, C-A) and Phase to Ground. Looking for >100 MegaOhms. Assesses gross insulation health/moisture. Hi-Pot test: Applies a much higher voltage (e.g., 2000V AC or DC) for a specific time (1 minute) to stress the insulation and verify it won't break down under voltage spikes. Acceptance is no breakdown/arcing and leakage current below specified micro-amps. Hi-Pot is a destructive test if insulation fails; Megger is non-destructive.",
20),

(D,"essay",
"15. Explain the operating principle of a Coriolis mass flowmeter. Why is the installation location and pipe support critical for this specific instrument?",
"","",
"Grade on: Principle: Measures mass flow directly by vibrating a tube and measuring the phase shift (twist) caused by the Coriolis effect of the flowing mass. Density is measured by the resonant frequency. Installation criticality: Because it relies on precise measurement of micro-vibrations, it is highly susceptible to external mechanical pipe vibration. It must be installed with rigid, heavy pipe supports immediately upstream and downstream. It must remain completely full of liquid (no air bubbles) so U-tube designs are mounted 'belly down'.",
20),

(D,"essay",
"16. Discuss the purpose of a Fire and Gas (F&G) System in an oil and gas facility. Describe the difference between point gas detectors and open-path (line-of-sight) gas detectors.",
"","",
"Grade on: F&G Purpose: Continuous monitoring of hazardous areas to detect leaks of flammable/toxic gases or flames early, initiate alarms, and automatically trigger executive actions (ESD, blowdown, deluge systems) to prevent catastrophe. Point Detectors (Catalytic/IR): Measure gas concentration exactly at the sensor location. Good for enclosed areas or near specific leak sources. Open-Path (Line-of-Sight IR): Transmits an IR beam over a long distance (up to 100m) to a receiver. Measures the total gas cloud intersecting the beam. Great for open, windy perimeters.",
20),

(D,"essay",
"17. You are inspecting the termination of a fiber optic cable in a control room patch panel. What specific QC checks and testing methods (e.g., OTDR, Power Meter) are required for acceptance?",
"","",
"Grade on: Visual check: Verify correct connector types (LC/SC/ST), proper bend radii maintained (fiber is fragile), and clean routing in the splice tray. Cleaning: Ensure end-faces are microscopically cleaned before mating. Testing: 1. OTDR (Optical Time Domain Reflectometer) trace to verify no micro-bends, verify splice quality, and measure total cable length. 2. Optical Power Meter and Light Source test (Insertion Loss test) to measure the exact dB loss from end to end. The dB loss must be below the calculated optical link budget.",
20),

(D,"essay",
"18. Describe the concept of 'Cathodic Protection' (CP) for underground pipelines. What is the difference between Sacrificial Anode and Impressed Current systems?",
"","",
"Grade on: CP prevents corrosion of buried metals by making the pipeline the cathode of an electrochemical cell. Sacrificial Anode (Galvanic): Uses a metal more active than steel (e.g., Zinc, Magnesium) connected to the pipe. The anode corrodes away, sacrificing itself to protect the steel. No external power needed. Impressed Current (ICCP): Uses an external DC power supply (Transformer-Rectifier) and inert anodes (e.g., MMO, Graphite). Forces protective current onto the pipeline. Used for large structures/long pipelines requiring higher current.",
20),

(D,"essay",
"19. In the context of Control Valves, explain the phenomena of 'Flashing' and 'Cavitation'. How do they damage valves, and how can they be mitigated?",
"","",
"Grade on: Both occur when pressure drops below the fluid's vapor pressure at the vena contracta. Flashing: Pressure remains below vapor pressure downstream; fluid turns to vapor and stays vapor. Causes high-velocity erosion (sandblasting effect). Cavitation: Pressure recovers above vapor pressure downstream, causing vapor bubbles to collapse violently. Causes severe pitting (looks like sponge/craters) and severe noise/vibration. Mitigation: Use anti-cavitation trim (multi-stage pressure drop), harder trim materials (Stellite), or increase downstream pressure.",
20),

(D,"essay",
"20. Discuss the requirements for 'Lockout/Tagout' (LOTO) when performing maintenance on a 415V MCC bucket. Detail the steps a technician must take to prove the circuit is dead before starting work.",
"","",
"Grade on: 1. Identify the correct breaker/bucket. 2. Open breaker to isolate power. 3. Apply physical padlock and danger tag to the handle. 4. KEEP the key. 5. Try to start the motor locally to verify isolation (Try-out). 6. Put on appropriate Arc Flash PPE. 7. Open the bucket door. 8. Use a certified multimeter (Test Before Touch). 9. Test meter on a known live source. 10. Test all phases to ground, and phase-to-phase in the isolated bucket to prove zero volts. 11. Re-test meter on live source to prove meter didn't break.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. What is the primary safety purpose of grounding (earthing) the metal casing of an electrical motor?",
"","",
"Grade on: To provide a low-resistance path to earth for fault currents. If the internal winding insulation fails and the live conductor touches the casing, the earth wire safely carries the high fault current to ground, which trips the circuit breaker immediately. Without it, the casing becomes live and poses a lethal shock hazard to personnel.",
10),

(D,"oral",
"2. When looking at a P&ID, what is the difference between a solid line, a dashed line, and a line with hash marks (bubbles) connecting instruments?",
"","",
"Grade on: Solid line = Instrument capillary tube or physical process pipe. Dashed line = Electronic electrical signal (e.g., 4-20mA or 24VDC). Line with hash marks/bubbles = Pneumatic signal (e.g., 3-15 psi air). Line with diamonds = Digital data link (e.g., Fieldbus or DCS internal software link).",
10),

(D,"oral",
"3. You find a contractor using standard PVC electrical tape to splice an instrument signal cable inside a junction box. Why is this unacceptable?",
"","",
"Grade on: Instrument signals (like 4-20mA or RTDs) are highly sensitive to resistance changes. Twisting wires and taping them creates a high-resistance, mechanically weak joint susceptible to corrosion, which will distort the signal. Cables must be terminated on proper terminal blocks using crimped lugs or ferrules. Mid-run splices are generally forbidden in instrumentation.",
10),

(D,"oral",
"4. What is the purpose of an RTD (Resistance Temperature Detector) and how does it work?",
"","",
"Grade on: An RTD is used for highly accurate temperature measurement. It works on the principle that the electrical resistance of certain metals (typically Platinum, e.g., Pt100) changes in a highly predictable and linear way as temperature changes. As temperature increases, resistance increases.",
10),

(D,"oral",
"5. Explain why a 4-20mA standard is used for analog signals instead of 0-20mA.",
"","",
"Grade on: The 'live zero' of 4mA allows the control system to distinguish between a true zero reading (e.g., tank is empty = 4mA) and a broken wire/failed transmitter (current drops to 0mA). It also provides enough loop power (4mA) to power the electronics in a 2-wire transmitter.",
10),

(D,"oral",
"6. What does a 'Megger' do, and why must you disconnect electronic instruments before using it?",
"","",
"Grade on: A Megger is an insulation resistance tester that outputs high DC voltage (e.g., 500V or 1000V) to check if the insulation surrounding a conductor is degraded. If left connected, this high voltage will overload and permanently destroy sensitive electronic components (like DCS cards or transmitter boards) which are only rated for 24VDC.",
10),

(D,"oral",
"7. What is an 'Explosion-proof' (Ex d) enclosure, and how does it protect the plant?",
"","",
"Grade on: It is a heavy, robust metal enclosure designed to house spark-producing equipment in a hazardous area. It is NOT gas-tight. If explosive gas enters and ignites inside, the enclosure is strong enough to contain the explosion without rupturing. The escaping hot gases are cooled as they pass through tight, machined 'flame paths' (flanges), preventing ignition of the outside atmosphere.",
10),

(D,"oral",
"8. Why is it important to strictly follow the manufacturer's recommended bend radius for a fiber optic cable?",
"","",
"Grade on: Fiber optic cables carry light through a fragile glass core. If bent too sharply (exceeding bend radius), two things happen: 1. Micro-bending causes the light to leak out of the core (attenuation/signal loss). 2. The physical stress can cause the glass core to fracture, completely breaking the data link.",
10),

(D,"oral",
"9. What is a 'Bump Test' on a motor, and when should it be performed?",
"","",
"Grade on: A bump test involves energizing a 3-phase motor for just a fraction of a second to observe the direction the shaft spins, ensuring it matches the required direction of the driven equipment. It MUST be performed with the motor uncoupled from the pump/compressor to prevent mechanical damage if the rotation is backwards.",
10),

(D,"oral",
"10. Explain the function of a 'Current Transformer' (CT) in an electrical switchgear panel.",
"","",
"Grade on: A CT steps down high alternating currents (e.g., 1000 Amps flowing through a main busbar) to a safe, standardized low current (typically 1 Amp or 5 Amps). This low current is used safely by metering equipment (to display Amps) and protective relays (to trip breakers during a fault).",
10),

(D,"oral",
"11. What is the difference between a 'Digital Input' (DI) and an 'Analog Input' (AI) on a DCS?",
"","",
"Grade on: Digital Input (DI) receives a discrete, two-state signal (On/Off, True/False, Open/Closed), such as a pressure switch or valve limit switch. Analog Input (AI) receives a continuously variable signal representing a physical value (e.g., 4-20mA representing 0-100 psi from a pressure transmitter).",
10),

(D,"oral",
"12. During cable tray inspection, why must you ensure that the cable fill does not exceed 40-50% capacity?",
"","",
"Grade on: Overfilling cable trays prevents adequate air circulation around the cables. Power cables generate heat (I²R losses). If they cannot dissipate heat, the insulation will overheat, degrade, and eventually cause a short circuit or fire. It also prevents adding future cables safely.",
10),

(D,"oral",
"13. What is a 'Limit Switch' on a control valve, and how is it used by the DCS?",
"","",
"Grade on: A limit switch is a mechanical/magnetic switch mounted on the valve actuator that physically detects when the valve has reached its fully open or fully closed position. It sends a Digital Input (DI) to the DCS, providing positive feedback to the operator that the valve actually moved to the commanded position.",
10),

(D,"oral",
"14. Why is 'Ferruling' (wire marking) critical inside a junction box or control panel?",
"","",
"Grade on: Ferrules (wire markers) identify every single wire at its termination point, matching the wiring schematics. It is critical for commissioning, future troubleshooting, and safety. Without markers, it is impossible to identify which wire goes where, making maintenance extremely dangerous and time-consuming.",
10),

(D,"oral",
"15. What is the difference between a 'Normally Open' (NO) and 'Normally Closed' (NC) contact on a relay?",
"","",
"Grade on: Normally Open (NO) means the electrical contact is open (circuit broken) when the relay coil has no power, and it closes when power is applied. Normally Closed (NC) means the contact is touching (circuit complete) when there is no power, and it opens when power is applied.",
10),

(D,"oral",
"16. In a Fire and Gas system, what is an 'End of Line' (EOL) resistor?",
"","",
"Grade on: It is a resistor placed at the very last detector in a zone loop. It allows a small 'supervisory' current to flow continuously. The F&G panel monitors this current. If the wire breaks, current stops (Fault). If a detector triggers (shorts the circuit), current spikes (Alarm). It proves wire integrity.",
10),

(D,"oral",
"17. What is 'Intrinsically Safe' (IS) grounding, and why must it be separated from plant safety grounding?",
"","",
"Grade on: IS grounding connects the IS barriers (Zener barriers) to earth so they can safely dump dangerous fault voltages to ground. It must be highly reliable (<1 Ohm) and physically isolated from the noisy, high-current plant safety ground grid to prevent plant fault currents from traveling backward through the IS ground and causing a spark in the hazardous area.",
10),

(D,"oral",
"18. You are inspecting a newly installed radar level transmitter. The contractor left the unused cable entry port open. What is the problem?",
"","",
"Grade on: An open port destroys the IP (Ingress Protection) rating of the instrument, allowing water, dust, and corrosive moisture to enter and destroy the electronics. If it is in a hazardous area, it completely breaches the explosion-proof (Ex d) certification. It must be sealed with a certified metallic blanking plug.",
10),

(D,"oral",
"19. What is a 'Thermocouple Extension Wire' and why can't you use standard copper wire to connect a thermocouple to a DCS?",
"","",
"Grade on: Extension wire is made of alloys with the same thermoelectric properties as the thermocouple itself. If standard copper wire is used, a new dissimilar metal junction is created at the connection head, which generates its own unwanted voltage (Seebeck effect), causing massive temperature reading errors at the DCS.",
10),

(D,"oral",
"20. Explain the role of an I/P (Current to Pressure) transducer on a pneumatic control valve.",
"","",
"Grade on: The DCS outputs an electronic signal (4-20mA). The valve actuator requires pneumatic air pressure to physically move. The I/P transducer acts as a translator, taking the electrical 4-20mA signal and converting it into a proportional 3-15 psi air pressure signal to drive the valve.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Identify and demonstrate how to use a Digital Multimeter to test a 24VDC solenoid valve coil to determine if it is burnt out.",
"","",
"Grade on: Disconnect power. Set multimeter to Resistance (Ohms). Place probes across the two coil terminals. A good coil will read a specific resistance (e.g., 20 to 100 Ohms depending on wattage). If it reads OL (Open Loop / Infinite), the coil wire is broken/burnt out. If it reads 0 Ohms, it is short-circuited.",
15),

(D,"practical",
"2. Given a P&ID snippet, trace the signal path of a pressure control loop from the field process connection to the final control element, identifying all components.",
"","",
"Grade on: Identify Process connection -> Impulse tubing -> 3-valve manifold -> PT (Pressure Transmitter) -> 4-20mA cable -> DCS I/O Card -> PIC (Pressure Indicating Controller algorithm in software) -> DCS Output Card -> 4-20mA cable -> I/P Transducer / Positioner -> PCV (Pressure Control Valve).",
15),

(D,"practical",
"3. Inspect a physical (or photo) termination of a Steel Wire Armored (SWA) cable into a metal junction box using an Ex d cable gland. Identify 3 critical quality checks.",
"","",
"Grade on: 1. Ensure the SWA is fully clamped by the gland armor cone (for grounding and mechanical strength). 2. Verify an earth tag is installed on the gland and bolted securely to the box ground. 3. Check the inner seal is compressed onto the cable bedding. 4. Verify no exposed copper or nicked insulation on the individual cores.",
15),

(D,"practical",
"4. Demonstrate the setup for calibrating a Type K Thermocouple transmitter on the bench. What equipment is used to simulate the input?",
"","",
"Grade on: Use a specialized Process Calibrator (e.g., Fluke 744/754) set to 'Source TC Type K'. Connect TC mini-plugs (Yellow/Red for US) or copper wire to the transmitter input. Connect calibrator mA measure (loop power) to the transmitter output. The calibrator simulates the millivolt signal of a Type K TC while automatically providing internal Cold Junction Compensation.",
15),

(D,"practical",
"5. Given a loop drawing and a multimeter, demonstrate how to measure the 4-20mA signal in a live circuit without breaking the wire.",
"","",
"Grade on: Many modern terminal blocks have a built-in diode test point. The candidate should demonstrate putting the multimeter in 'mA DC' mode and placing the probes across the test points (which bypasses the diode, forcing current through the meter without opening the circuit). Alternatively, use a milliamp clamp meter around the wire.",
15),

(D,"practical",
"6. Perform a physical inspection of an Ex d (Flameproof) junction box before the cover is bolted on. What specific checks are required on the flange faces?",
"","",
"Grade on: 1. Clean the machined flange faces completely to remove dirt/debris. 2. Inspect carefully for any scratches, pitting, or rust that crosses the flame path. 3. Ensure a light coating of approved non-setting grease is applied for rust prevention (never use silicone or hardening sealants). 4. Verify all original bolts are present and correct grade.",
15),

(D,"practical",
"7. Interpret an instrument cable schedule. Given a cable tag, identify the source, destination, cable type (e.g., 12P x 1.5mm2 IS), routing, and gland size required.",
"","",
"Grade on: Ability to read standard engineering schedules. '12P' means 12 Pairs (24 wires + drain). '1.5mm2' is wire gauge. 'IS' means Intrinsically Safe (requires blue jacket). Source/Destination columns define from/to. Proper gland size must be matched to overall cable diameter.",
15),

(D,"practical",
"8. A motor is controlled by a 'Start/Stop' push-button station. Given a basic electrical schematic, identify the 'Seal-in' (or 'Latching') contact and explain its purpose.",
"","",
"Grade on: Identify the Normally Open (NO) auxiliary contact of the motor contactor wired in parallel with the momentary 'Start' push-button. Explain: When 'Start' is pressed, the contactor closes, closing the auxiliary contact. When the operator releases the 'Start' button, power continues to flow through this auxiliary 'seal-in' contact to keep the coil energized.",
15),

(D,"practical",
"9. Conduct a visual inspection of an installed impulse tubing run for a liquid flow transmitter. Identify requirements for slope, supports, and manifold orientation.",
"","",
"Grade on: Tubing must slope continuously DOWN from the orifice pipe taps to the transmitter (min 1:12 slope) to allow any trapped gas bubbles to vent back up into the pipe. Tubing must be supported continuously on tray or with clamps to prevent vibration fatigue. 5-valve manifold must be accessible.",
15),

(D,"practical",
"10. Demonstrate how to verify a 3-phase motor's windings using a multimeter (before high-voltage meggering).",
"","",
"Grade on: Disconnect motor links. Set meter to Low Ohms. Measure resistance across U1-U2, V1-V2, and W1-W2. All three phase windings should show a very low, nearly identical resistance (balanced). Measure between phases (U1-V1, etc.); should be Open Limit (OL). Measure from each phase to the earth casing; should be OL.",
15),

(D,"practical",
"11. You are given a HART communicator. Demonstrate how to connect it to a smart pressure transmitter and perform a 'Zero Trim'.",
"","",
"Grade on: Connect HART leads across transmitter terminals (requires minimum 250 ohm loop resistance). Ensure transmitter is physically vented to atmospheric pressure (0 psi). Navigate HART menu: Device Setup -> Diag/Service -> Calibration -> Sensor Trim -> Zero Trim. Acknowledge warnings that loop should be in manual. Execute trim to teach the sensor that its current physical state is exactly 'Zero'.",
15),

(D,"practical",
"12. Inspect an installed grounding (earthing) connection on a steel vessel. What are the quality criteria for a compliant connection?",
"","",
"Grade on: 1. Crimp lug must be proper size and tightly crimped (no loose strands). 2. The vessel surface must be ground down to BARE METAL (paint removed) before bolting the lug to ensure electrical contact. 3. Star washer used for 'bite'. 4. After bolting, the connection must be coated with anti-corrosion paint/compound to prevent rusting.",
15),

(D,"practical",
"13. Given a set of PID tuning parameters (P=2.0, I=10s, D=0s) on a level controller, the operator complains the valve is opening and closing wildly (hunting). Suggest practical adjustments to stabilize it.",
"","",
"Grade on: 'Hunting' or wild oscillation usually means the Proportional Gain is too high, or the Integral time is too fast (too low). To stabilize: 1. Decrease the Proportional Gain (P) (e.g., cut it in half to 1.0). 2. Increase the Integral time (I) (e.g., change to 20s or 30s) to slow down the reset action. Wait and observe response.",
15),

(D,"practical",
"14. Identify the correct method for terminating shielded twisted pair (STP) instrument cable in a DCS marshalling cabinet.",
"","",
"Grade on: Strip outer jacket without nicking shield. Cut off foil shield. Isolate the bare drain wire with a piece of heat shrink or green/yellow sleeving. Crimp a ferrule onto the drain wire. Terminate the drain wire exclusively to the isolated Instrument Clean Ground busbar. Terminate black/white pairs to signal blocks.",
15),

(D,"practical",
"15. Perform a functional test of a point combustible gas detector (e.g., LEL Catalytic bead). What equipment is used?",
"","",
"Grade on: Requires a cylinder of certified calibration gas (e.g., 50% LEL Methane in air) and a flow regulator with a calibration cup. Place cup over sensor, open gas flow. Verify the local display rises, verify the DCS HMI registers the gas, verify High and High-High alarms trigger at the correct setpoints. Remove gas and verify readings return to zero.",
15),

(D,"practical",
"16. Review an Electrical Single Line Diagram (SLD). Locate a specific motor starter, identify the upstream breaker rating, the contactor size, and the current transformer (CT) ratio.",
"","",
"Grade on: Ability to navigate the hierarchy of an SLD. Trace the bus down to the specific bucket. Identify symbols for MCCB (breaker), Contactor (coil symbol), Overload relay, and CT (circle over line with ratio, e.g., 100/5A).",
15),

(D,"practical",
"17. Explain and demonstrate how to check for an 'Earth Fault' (Ground Fault) on a 24VDC instrument loop that is causing a DCS fuse to blow intermittently.",
"","",
"Grade on: Power down loop. Disconnect field wires at the DCS. Use a multimeter in High Ohms or a 250V Megger. Place one probe on the positive wire, the other on the panel ground. Repeat for negative wire. A reading of low resistance indicates the wire insulation is chafed and touching the conduit or tray in the field. Must walk the line to find the damage.",
15),

(D,"practical",
"18. Inspect a pneumatic control valve positioner hookup. Identify the air supply port, instrument signal port, and output to actuator. How do you verify supply pressure is correct?",
"","",
"Grade on: Locate the air filter regulator (AFR) feeding the positioner. Read the gauge on the AFR. It should typically read slightly higher than the maximum actuator spring range (e.g., for a 3-15 psi spring, supply is usually regulated to 20-30 psi; for a 6-30 psi spring, supply is ~40 psi). Verify tubing is securely swaged and leak-free.",
15),

(D,"practical",
"19. Demonstrate the procedure to safely isolate a 415V motor for mechanical maintenance (Lockout/Tagout - LOTO).",
"","",
"Grade on: 1. Identify correct MCC bucket. 2. Switch breaker handle to OFF position. 3. Insert personal padlock through the handle lockout mechanism. 4. Attach signed/dated Danger tag. 5. Crucial step: Attempt to start the motor using the local field push button (Try-out) to prove the circuit is dead before allowing mechanics to work.",
15),

(D,"practical",
"20. You are commissioning a radar level transmitter. The tank is currently empty. Demonstrate how to perform a 'False Echo Suppression' (or Empty Tank Mapping).",
"","",
"Grade on: Access the transmitter interface (local display or HART tool). Navigate to Echo Setup / False Echo Mapping. Initiate the mapping function. The radar will scan the empty tank, identify reflections from internal structures (agitators, ladders), and memorize them as false echoes so it ignores them during normal filling operation. Save the curve.",
15),

]  # end QUESTIONS
