"""
Instrumentation QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: ISA, IEC 61508, IEC 61511, SAES-J-002, SAES-J-003, SAES-J-902, 
           API RP 551, API RP 552, IEC 60079
"""

D = "Instrumentation QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. During loop testing of a 4-20mA pressure transmitter, the applied pressure is at 50% of the calibrated range. The multimeter connected in series reads 10mA. The acceptable tolerance is ±0.25% of span. What is the finding?",
"Acceptable — 10mA is 50% of the 20mA maximum signal.\nRejectable — at 50% of the range, the output should be 12mA; 10mA is out of tolerance and indicates calibration error.\nAcceptable — the reading is within ±2mA tolerance.\nRejectable — the transmitter should output 8mA at 50% of range.",
"Rejectable — at 50% of the range, the output should be 12mA; 10mA is out of tolerance and indicates calibration error.",
"The 4-20mA span is 16mA. At 50% of the range, the output should be 4mA + (0.50 × 16mA) = 12mA. A reading of 10mA at 50% of the range is a gross error (representing 37.5% of range, not 50%).",
1),

(D,"mcq",
"2. Which protocol is typically used for smart instrument calibration and diagnostics superimposed over a 4-20mA analog signal?",
"Modbus RTU\nFoundation Fieldbus\nHART (Highway Addressable Remote Transducer)\nProfibus PA",
"HART (Highway Addressable Remote Transducer)",
"The HART protocol superimposes a high-frequency digital signal (FSK - Frequency Shift Keying) on top of the standard 4-20mA analog current loop without disrupting the analog signal, allowing for remote calibration and diagnostics.",
1),

(D,"mcq",
"3. A thermocouple (Type K) is connected to a temperature transmitter using copper wire instead of Type K extension wire. What will be the effect on the measurement?",
"No effect, as long as the copper wire is shielded.\nThe measurement will be incorrect due to the introduction of new cold junctions at the connection points with the copper wire.\nThe transmitter will automatically compensate for the copper wire resistance.\nThe transmitter will report an open-circuit fault.",
"The measurement will be incorrect due to the introduction of new cold junctions at the connection points with the copper wire.",
"Thermocouples rely on the Seebeck effect. If standard copper wire is used instead of matching extension wire, new dissimilar metal junctions are created at the connection points, generating their own thermoelectric voltages and resulting in a highly inaccurate temperature reading.",
1),

(D,"mcq",
"4. An Orifice Plate is used for flow measurement. To measure flow accurately, the flow computer must extract the square root of the differential pressure signal. If the DP transmitter is ranged 0-100 inches H2O for a flow of 0-1000 BPD, what flow rate does a DP of 25 inches H2O represent?",
"250 BPD\n500 BPD\n750 BPD\n1000 BPD",
"500 BPD",
"Flow is proportional to the square root of differential pressure. At 25% of the DP range (25/100), the flow is sqrt(0.25) = 0.50, or 50% of the maximum flow. 50% of 1000 BPD is 500 BPD.",
1),

(D,"mcq",
"5. A Safety Instrumented System (SIS) valve is required to be 'Fail-Safe'. The process requires the valve to close on loss of air and power to prevent a dangerous chemical release. What type of actuator configuration is required?",
"Air-to-Close, Spring-to-Open (Fail Open)\nAir-to-Open, Spring-to-Close (Fail Closed)\nDouble Acting with no springs\nMotor Operated Valve (MOV) with battery backup",
"Air-to-Open, Spring-to-Close (Fail Closed)",
"To achieve a 'Fail Closed' state on loss of utility (air/power), the actuator must have a mechanical spring that forces the valve closed when air pressure opposing the spring is lost. This is 'Air-to-Open, Spring-to-Close'.",
1),

(D,"mcq",
"6. During calibration of an RTD (Pt100), the resistance measured at 0°C should be:",
"0 Ohms\n100 Ohms\n138.5 Ohms\n4-20 Ohms",
"100 Ohms",
"A Pt100 RTD (Platinum resistance temperature detector) has a nominal resistance of 100 Ohms at 0 degrees Celsius.",
1),

(D,"mcq",
"7. What is the purpose of an intrinsically safe (IS) barrier in an instrument loop?",
"To prevent electrical noise from affecting the measurement.\nTo limit the voltage and current entering a hazardous area to levels below what can ignite an explosive atmosphere.\nTo isolate the 4-20mA signal from ground loops.\nTo convert a digital signal to an analog signal.",
"To limit the voltage and current entering a hazardous area to levels below what can ignite an explosive atmosphere.",
"Intrinsically Safe (IS) barriers (Zener barriers or galvanic isolators) limit the electrical energy (voltage and current) that can flow into a classified hazardous area under normal and fault conditions, preventing sparks or thermal effects capable of causing ignition.",
1),

(D,"mcq",
"8. A control valve is 'hunting' (oscillating continuously around the setpoint). Which PID tuning parameter is most likely set too high?",
"Proportional Gain (or too low Proportional Band)\nIntegral Time (Reset Time)\nDerivative Time (Rate)\nDeadband",
"Proportional Gain (or too low Proportional Band)",
"Excessive proportional gain (or a very narrow proportional band) causes the controller to overreact to small errors, leading to continuous oscillation or 'hunting' around the setpoint.",
1),

(D,"mcq",
"9. In impulse piping for a liquid flow transmitter (DP type), where should the transmitter be mounted relative to the orifice tapping points?",
"Above the tapping points to allow liquid to drain back.\nBelow the tapping points to ensure impulse lines are full of liquid and air bubbles can vent back to the pipe.\nAt exactly the same elevation.\nIt does not matter if bleed valves are installed.",
"Below the tapping points to ensure impulse lines are full of liquid and air bubbles can vent back to the pipe.",
"For liquid service, the transmitter should be mounted below the tapping points so that the impulse lines remain completely full of liquid and any trapped air bubbles rise and vent back into the process line, preventing erroneous differential pressure readings.",
1),

(D,"mcq",
"10. A pressure switch is calibrated to actuate (trip) at 100 psi and reset at 90 psi. The difference of 10 psi is known as:",
"Deadband (or Hysteresis)\nAccuracy\nRepeatability\nLinearity",
"Deadband (or Hysteresis)",
"The difference between the actuation point (setpoint) and the de-actuation point (reset point) of a switch is called the deadband or differential. It prevents the switch from chattering when the process value hovers around the setpoint.",
1),

(D,"mcq",
"11. What is the standard pneumatic signal range used in process instrumentation?",
"0-100 psi\n3-15 psi\n4-20 psi\n1-5 psi",
"3-15 psi",
"The standard pneumatic signal range for process control instruments is 3 to 15 psig (pounds per square inch gauge), which analogously maps to the 4-20mA electrical standard.",
1),

(D,"mcq",
"12. During a loop check, the field instrument is disconnected, and a loop calibrator is used to source 12mA into the DCS input card. The DCS HMI displays 50% of the PV range. This test verifies:",
"The field transmitter's calibration.\nThe integrity of the wiring and the DCS scaling/configuration.\nThe control valve's response.\nThe process variable's actual value.",
"The integrity of the wiring and the DCS scaling/configuration.",
"Sourcing a known current directly into the DCS verifies the cable continuity from that point to the DCS, the I/O card function, and that the DCS software scaling correctly interprets the 4-20mA signal into engineering units.",
1),

(D,"mcq",
"13. According to IEC 61511, SIL stands for:",
"Standard Instrument Loop\nSafety Integrity Level\nSystematic Incident Log\nSafe Interlock Limit",
"Safety Integrity Level",
"SIL (Safety Integrity Level) is a measurement of performance required for a Safety Instrumented Function (SIF) to maintain a process in a safe state, ranging from SIL 1 to SIL 4 (highest integrity).",
1),

(D,"mcq",
"14. A Coriolis mass flowmeter measures:",
"Volumetric flow rate only.\nDirect mass flow rate and fluid density.\nVelocity of the fluid.\nDifferential pressure across a restriction.",
"Direct mass flow rate and fluid density.",
"Coriolis flowmeters measure direct mass flow rate using the Coriolis effect on vibrating tubes, and they can also measure fluid density based on the resonant frequency of the tubes.",
1),

(D,"mcq",
"15. In a hazardous area classification (Zone 1), a junction box is marked Ex d IIC T4. What does 'Ex d' mean?",
"Intrinsically Safe\nIncreased Safety\nFlameproof (Explosion-proof)\nNon-sparking",
"Flameproof (Explosion-proof)",
"Ex d is the protection concept for 'Flameproof' enclosures. The enclosure is designed to withstand an internal explosion of a flammable mixture and prevent the propagation of the flame to the surrounding explosive atmosphere.",
1),

(D,"mcq",
"16. A level transmitter uses a bubbler system. The purge gas flows through a dip tube into an open tank of water (density = 1000 kg/m3). The dip tube outlet is 5 meters below the water surface. What is the approximate back-pressure measured by the transmitter?",
"0.5 bar\n1.0 bar\n5.0 bar\n10.0 bar",
"0.5 bar",
"Pressure = height × density × gravity = 5 m × 1000 kg/m3 × 9.81 m/s2 = 49050 Pa ≈ 0.49 bar. Rule of thumb: 10 meters of water is roughly 1 bar, so 5 meters is ~0.5 bar.",
1),

(D,"mcq",
"17. When calibrating an instrument, 'zero shift' refers to:",
"A change in the slope of the calibration curve.\nA constant error across the entire measurement range.\nA random error that occurs only at zero input.\nThe hysteresis of the instrument.",
"A constant error across the entire measurement range.",
"A zero shift (or zero error) shifts the entire calibration curve up or down by a constant amount across the full range, without changing the span (slope) of the instrument.",
1),

(D,"mcq",
"18. Which type of control valve is best suited for tight shut-off and throttling of highly viscous fluids or slurries?",
"Globe Valve\nButterfly Valve\nEccentric Plug Rotary Valve (Segmented Ball Valve)\nNeedle Valve",
"Eccentric Plug Rotary Valve (Segmented Ball Valve)",
"Segmented ball valves or eccentric rotary plug valves provide a straight-through flow path suitable for slurries, offer high capacity, and can shear through suspended solids for tight shut-off.",
1),

(D,"mcq",
"19. What is the function of a 'Positioner' on a pneumatic control valve?",
"To convert a digital signal to an analog signal.\nTo ensure the valve stem position exactly matches the control signal command by adjusting air pressure to the actuator.\nTo provide a manual override for the valve.\nTo filter the instrument air supply.",
"To ensure the valve stem position exactly matches the control signal command by adjusting air pressure to the actuator.",
"A valve positioner compares the control signal (e.g., 4-20mA or 3-15 psi) with the actual mechanical position of the valve stem and applies corrective air pressure to the actuator to overcome friction and process forces, ensuring accurate positioning.",
1),

(D,"mcq",
"20. In an instrument air system, what is the typical requirement for the air dew point?",
"It must be 10°C below the lowest expected ambient temperature to prevent condensation and freezing in instrument lines.\nIt must be exactly 0°C.\nIt must be equal to the ambient temperature.\nDew point is not critical as long as the air is filtered.",
"It must be 10°C below the lowest expected ambient temperature to prevent condensation and freezing in instrument lines.",
"Instrument air must be extremely dry to prevent water condensation, which can cause corrosion, block small orifices, or freeze in cold conditions. The standard requirement (e.g., ISA-S7.0.01) is a dew point at least 10°C (18°F) below the lowest recorded ambient temperature.",
1),

(D,"mcq",
"21. A radar level transmitter uses FMCW (Frequency Modulated Continuous Wave) technology. How does it calculate the level?",
"By measuring the time of flight of a short pulse.\nBy measuring the frequency difference between the transmitted signal and the received echo.\nBy measuring the capacitance change of the fluid.\nBy measuring the pressure exerted by the fluid.",
"By measuring the frequency difference between the transmitted signal and the received echo.",
"FMCW radar emits a continuous sweep of frequencies. The reflected signal is compared to the signal being transmitted at that instant. The frequency difference is proportional to the time delay, which translates to distance (and thus level).",
1),

(D,"mcq",
"22. Which material is commonly used for the sensing diaphragm of a pressure transmitter in highly corrosive H2S (sour) service?",
"304 Stainless Steel\nBrass\nHastelloy C-276 or Monel\nCarbon Steel",
"Hastelloy C-276 or Monel",
"In sour service (containing H2S), materials highly resistant to sulfide stress cracking (SSC) are required per NACE MR0175. Hastelloy C-276 or Monel are standard choices for wetted diaphragms in such harsh environments.",
1),

(D,"mcq",
"23. In a Foundation Fieldbus network, what is the role of the LAS (Link Active Scheduler)?",
"To provide DC power to the segment.\nTo terminate the bus to prevent signal reflections.\nTo control communication on the bus by granting tokens to devices, determining who can transmit.\nTo convert Fieldbus signals to standard 4-20mA.",
"To control communication on the bus by granting tokens to devices, determining who can transmit.",
"The LAS is the deterministic bus master in Foundation Fieldbus. It orchestrates all scheduled communication on the H1 segment by issuing tokens, ensuring time-critical control data is transmitted reliably.",
1),

(D,"mcq",
"24. A temperature transmitter configured for a PT100 RTD (3-wire) shows a slightly higher temperature reading than the actual process temperature. A common cause for this in a 3-wire system is:",
"The lead wire resistance of all three wires is perfectly matched.\nUnequal resistance in the lead wires connecting the RTD to the transmitter.\nThe transmitter is scaled for degrees Fahrenheit instead of Celsius.\nThe RTD is a Pt1000 instead of a Pt100.",
"Unequal resistance in the lead wires connecting the RTD to the transmitter.",
"A 3-wire RTD circuit relies on the assumption that the resistance of the two current-carrying lead wires is identical, allowing the bridge to compensate for them. If the lead wires have unequal resistance (e.g., bad connection, different lengths), the compensation fails, introducing a positive temperature error.",
1),

(D,"mcq",
"25. What is the primary advantage of a vortex shedding flowmeter?",
"It can measure zero flow accurately.\nIt requires no straight pipe runs upstream or downstream.\nIt has no moving parts and the frequency output is directly proportional to volumetric flow rate.\nIt directly measures mass flow regardless of density changes.",
"It has no moving parts and the frequency output is directly proportional to volumetric flow rate.",
"Vortex flowmeters measure the frequency of vortices shed from a bluff body. They have no moving parts to wear out, and the shedding frequency is linearly proportional to the fluid velocity (and thus volumetric flow), making them reliable and relatively maintenance-free for many fluids.",
1),

(D,"mcq",
"26. Which type of valve characteristic provides equal percentage changes in flow for equal increments of valve stroke?",
"Linear\nQuick Opening\nEqual Percentage\nModified Parabolic",
"Equal Percentage",
"An equal percentage valve trim is designed so that a given percentage change in valve lift (e.g., 10%) produces a constant percentage change (e.g., 50%) in the existing flow rate, which is very useful for controlling processes with highly variable pressure drops.",
1),

(D,"mcq",
"27. During a site acceptance test (SAT), an instrument inspector verifies the cable shield grounding for analog signals. What is the correct industry practice?",
"Ground the shield at both the field instrument and the DCS panel to ensure maximum protection.\nGround the shield at the field instrument end only.\nGround the shield at the DCS (control room) end only, and isolate it at the field end.\nDo not ground the shield; connect it to the negative signal wire.",
"Ground the shield at the DCS (control room) end only, and isolate it at the field end.",
"Instrument cable shields must be grounded at one point only (typically the control room/marshalling cabinet ground bus) to prevent ground loops. If grounded at both ends, differences in ground potential will drive current through the shield, inducing noise into the signal wires.",
1),

(D,"mcq",
"28. A magnetic flowmeter requires the fluid being measured to be:",
"A hydrocarbon liquid.\nA gas.\nElectrically conductive.\nHighly viscous.",
"Electrically conductive.",
"Magnetic flowmeters operate on Faraday's Law of Electromagnetic Induction. The fluid must be electrically conductive (e.g., water, acids, slurries) to generate a voltage as it passes through the magnetic field. They cannot measure non-conductive fluids like pure hydrocarbons or gases.",
1),

(D,"mcq",
"29. In an instrument loop diagram (ILD), a symbol showing a circle with a solid horizontal line across the middle represents:",
"A field-mounted instrument.\nAn instrument mounted on the main control panel, accessible to the operator.\nAn instrument mounted behind the panel, not accessible to the operator.\nA software link in the DCS.",
"An instrument mounted on the main control panel, accessible to the operator.",
"Per ISA symbology (ISA-5.1), a circle with a solid horizontal line indicates an instrument or function located on the primary control panel (accessible to the operator, e.g., DCS HMI display).",
1),

(D,"mcq",
"30. Which of the following is required for installing instruments in a SIL 3 safety instrumented function (SIF)?",
"Only standard process instruments are needed if calibrated frequently.\nInstruments must have a SIL 3 certification (e.g., from TUV or exida) or be proven in use with sufficient failure data, and often require redundant configurations (e.g., 1oo2 or 2oo3 voting).\nThe instruments must be painted red.\nOnly pneumatic instruments are allowed in SIL 3.",
"Instruments must have a SIL 3 certification (e.g., from TUV or exida) or be proven in use with sufficient failure data, and often require redundant configurations (e.g., 1oo2 or 2oo3 voting).",
"SIL 3 applications require high reliability and low probability of failure on demand (PFD). This necessitates using instruments specifically designed and certified for safety applications (IEC 61508) or those with extensive 'prior use' data, almost always deployed in redundant voting architectures.",
1),

(D,"mcq",
"31. A technician is calibrating a DP transmitter for open tank level measurement. The low pressure (LP) port is vented to atmosphere. The high pressure (HP) port is connected to the bottom of the tank. If the maximum liquid height is 10 meters (SG = 1.0), the calibration range should be:",
"0 to 10 mmH2O\n0 to 1000 mmH2O\n0 to 10000 mmH2O\n0 to 100000 mmH2O",
"0 to 10000 mmH2O",
"1 meter of water is equal to 1000 mmH2O. Therefore, 10 meters of water exerts a pressure of 10,000 mmH2O. The transmitter should be calibrated 0 to 10,000 mmH2O.",
1),

(D,"mcq",
"32. For a closed tank level measurement using a DP transmitter with a dry leg (wet gas above liquid), where should the LP and HP ports be connected?",
"HP to the top of the tank, LP to the bottom.\nHP to the bottom of the tank, LP to the top of the tank (above maximum liquid level).\nBoth ports to the bottom of the tank.\nLP to the bottom of the tank, HP vented to atmosphere.",
"HP to the bottom of the tank, LP to the top of the tank (above maximum liquid level).",
"In a closed tank, the pressure above the liquid affects the total pressure at the bottom. The HP port connects to the bottom to measure liquid head + vapor pressure. The LP port connects to the top (dry leg) to measure just the vapor pressure. The DP transmitter subtracts the LP from HP, leaving only the liquid head pressure.",
1),

(D,"mcq",
"33. What is the typical failure mode for a thermocouple?",
"It drifts to a lower temperature reading.\nIt drifts to a higher temperature reading.\nIt fails open-circuit (infinite resistance).\nIt fails short-circuit to ground.",
"It fails open-circuit (infinite resistance).",
"Thermocouples typically fail by the wires breaking or burning out, resulting in an open circuit. Modern transmitters are configured to detect this open circuit and drive the output to a safe fail state (e.g., upscale >20mA or downscale <4mA).",
1),

(D,"mcq",
"34. Which calibration parameter is adjusted first when performing a full calibration of an analog transmitter?",
"Span\nLinearity\nZero\nDeadband",
"Zero",
"The standard procedure is to adjust the Zero first (at the 0% input) because adjusting the span often interacts with the zero. The process is iteratively check zero, adjust zero, check span, adjust span.",
1),

(D,"mcq",
"35. In an orifice plate installation, what is the purpose of the 'weep hole' (or vent/drain hole)?",
"To measure differential pressure.\nTo prevent the buildup of liquid (in gas service) or gas (in liquid service) in front of the plate.\nTo reduce the pressure drop across the plate.\nTo increase the accuracy of the measurement.",
"To prevent the buildup of liquid (in gas service) or gas (in liquid service) in front of the plate.",
"A weep hole is drilled near the edge of the orifice plate. In gas flow, it is placed at the bottom to allow liquids to pass through. In liquid flow, it is placed at the top to allow entrapped gas bubbles to pass, preventing blockages.",
1),

(D,"mcq",
"36. The 'Cv' of a control valve is defined as:",
"The control variable of the process.\nThe number of US gallons per minute of water at 60°F that will flow through the fully open valve with a 1 psi pressure drop.\nThe critical velocity of the fluid.\nThe coefficient of variation of the valve actuator.",
"The number of US gallons per minute of water at 60°F that will flow through the fully open valve with a 1 psi pressure drop.",
"Cv is the valve flow coefficient, an industry standard used to compare valve capacities and properly size a valve for a specific flow rate and allowable pressure drop.",
1),

(D,"mcq",
"37. When using a deadweight tester to calibrate a pressure gauge, the accuracy of the calibration depends primarily on:",
"The local ambient temperature.\nThe exact knowledge of the local acceleration of gravity and the precision of the weights and piston area.\nThe type of hydraulic fluid used.\nThe speed at which the weights are spun.",
"The exact knowledge of the local acceleration of gravity and the precision of the weights and piston area.",
"A deadweight tester is a primary standard. Pressure = Force / Area. Force is mass × gravity. Therefore, precise calibration requires knowing the exact mass of the weights, the exact effective area of the piston, and correcting for local gravity and temperature.",
1),

(D,"mcq",
"38. Which NDT method is typically used to inspect the integrity of the seal welds on a thermowell before installation?",
"Radiography (RT)\nUltrasonic Testing (UT)\nDye Penetrant Testing (PT)\nMagnetic Particle Testing (MT)",
"Dye Penetrant Testing (PT)",
"Liquid penetrant testing (PT) is the standard method for detecting surface-breaking defects (like cracks or porosity) in the seal welds of thermowells, particularly those made of non-magnetic stainless steels.",
1),

(D,"mcq",
"39. A 5-valve manifold is commonly used with which type of transmitter?",
"Temperature Transmitter\nAbsolute Pressure Transmitter\nDifferential Pressure (DP) Transmitter used for level measurement\nDifferential Pressure (DP) Transmitter used for flow measurement with high static pressure requiring equalization and venting/draining",
"Differential Pressure (DP) Transmitter used for flow measurement with high static pressure requiring equalization and venting/draining",
"A 5-valve manifold (2 block valves, 1 equalizer valve, 2 vent/drain valves) is standard for DP flow transmitters. It allows blocking the process, equalizing the pressure to check zero safely, and venting/draining the impulse lines.",
1),

(D,"mcq",
"40. In hazardous area wiring, what is the primary purpose of 'cable glands' (e.g., Ex d or Ex e)?",
"To provide strain relief and seal the cable entry against gas, dust, and moisture, maintaining the integrity of the explosion-proof or increased safety enclosure.\nTo connect the cable shield to ground.\nTo identify the cable number.\nTo improve the electrical conductivity of the wires.",
"To provide strain relief and seal the cable entry against gas, dust, and moisture, maintaining the integrity of the explosion-proof or increased safety enclosure.",
"Cable glands in hazardous areas are critical safety components. They must securely grip the cable (strain relief) and provide a seal (using a rubber grommet or poured compound) to prevent explosive gases from entering the enclosure or flames from escaping, maintaining the Ex certification of the box.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. Describe the step-by-step procedure for performing a wet calibration on a DP transmitter used for closed-tank level measurement. Include the setup, equipment used, and calculation of the LRV (Lower Range Value) and URV (Upper Range Value).",
"","",
"Grade on: Definition of closed tank level setup (dry leg vs wet leg); Calculation of LRV (offset due to wet leg or elevation/suppression); Calculation of URV (LRV + Span based on max level); Equipment: loop calibrator/multimeter, HART communicator, precision pressure calibrator (hand pump); Procedure: isolate from process, vent, connect pressure source to HP (and LP if wet leg simulation needed), apply 0% pressure, check/adjust 4mA, apply 100% pressure, check/adjust 20mA, perform 5-point check (0, 25, 50, 75, 100%), document 'As Found' and 'As Left'.",
20),

(D,"essay",
"2. Explain the principle of operation of a Coriolis Mass Flowmeter. Discuss its advantages over volumetric flowmeters (like orifice plates) and mention any installation constraints.",
"","",
"Grade on: Principle: Fluid flows through vibrating tubes; the Coriolis force caused by the fluid's mass inertia creates a phase shift (twist) in the tube vibration, which is directly proportional to mass flow; resonant frequency changes with fluid density. Advantages: direct mass measurement (no compensation for temp/pressure needed), highly accurate, measures density, no straight pipe run requirements. Constraints: high initial cost, susceptible to severe pipe vibration (needs good support), high pressure drop compared to ultrasonic.",
20),

(D,"essay",
"3. You are an Instrumentation QC Inspector reviewing a contractor's loop check packages for a Safety Instrumented System (SIS). What specific documentation, verifications, and signatures would you expect to see to consider a SIL-rated loop check complete and acceptable?",
"","",
"Grade on: SIS loop check requires rigorous documentation; Verify instrument tags match P&ID and SRS (Safety Requirement Specification); Calibration certificates for field devices (in date, traceable); Point-to-point wiring continuity and megger tests; Functional verification: simulating the trip condition in the field and verifying the exact action of the final control element (e.g., valve fails closed within specified stroke time); Verification of DCS/SIS HMI alarms and graphics; Sign-off by Contractor QA/QC, Client Representative, and often a functional safety specialist; 'As Built' loop diagrams.",
20),

(D,"essay",
"4. Compare and contrast Foundation Fieldbus (FF) and traditional 4-20mA analog instrumentation. Focus on wiring topology, data transmission, control architecture, and commissioning troubleshooting.",
"","",
"Grade on: Wiring: FF uses a trunk-and-spur digital bus (multiple devices on one pair of wires), 4-20mA uses home-run point-to-point. Data: FF transmits multiple digital variables (PV, status, diagnostics), 4-20mA transmits one analog variable. Control: FF allows control in the field (instruments communicate peer-to-peer), 4-20mA control resides centrally in DCS. Troubleshooting: FF requires network diagnostic tools (segment checkers, oscilloscopes) to check signal quality, noise, and terminators; 4-20mA requires simple multimeter for current/voltage checks.",
20),

(D,"essay",
"5. A control valve is performing poorly (sticking and jumping). Describe the diagnostic tests you would perform using a smart valve positioner (e.g., Fisher FIELDVUE) to identify the mechanical issue without removing the valve from the line.",
"","",
"Grade on: Use of HART/Fieldbus diagnostic software (e.g., ValveLink); Perform a 'Valve Signature' or 'Step Response' test; Analyze the friction (stick-slip behavior) — high static friction indicates overtightened packing or galled trim; Analyze the deadband and hysteresis graph; Check available actuator pressure vs required travel; Verify pneumatic relay integrity (air consumption/leaks).",
20),

(D,"essay",
"6. Discuss the requirements for installing instruments in a Class I, Division 1 (or Zone 1) hazardous location. Compare Intrinsically Safe (IS) and Explosion-proof (Ex d) protection methods.",
"","",
"Grade on: General reqs: Equipment must be certified for the specific gas group and temperature class. Explosion-proof (Ex d): Contains explosion internally, requires heavy enclosures, poured seals or certified glands within specific distances, maintaining flame paths (no scratches). Intrinsically Safe (IS): Prevents ignition by limiting energy, requires IS barriers in the safe area, segregated wiring (usually light blue), no heavy enclosures needed, allows live maintenance. IS is preferred for instrumentation due to lower energy levels.",
20),

(D,"essay",
"7. Explain the function of a PID controller. Describe the specific effect of increasing the Proportional (P), Integral (I), and Derivative (D) terms on the process response.",
"","",
"Grade on: PID minimizes error between Setpoint and Process Variable. P (Gain): Reacts to current error size. Increasing P speeds up response but can cause oscillation/instability if too high. I (Reset): Reacts to accumulation of past errors. Eliminates steady-state offset. Decreasing Integral Time (increasing action) speeds up return to setpoint but can cause overshoot. D (Rate): Reacts to rate of change of error (predictive). Dampens overshoot, but amplifies process noise if set too high.",
20),

(D,"essay",
"8. What is 'Cavitation' in a control valve? Describe the physical mechanism, its damaging effects, and the methods or valve trim designs used to mitigate it.",
"","",
"Grade on: Mechanism: Fluid pressure drops below vapor pressure in the vena contracta, causing vapor bubbles to form. As pressure recovers downstream, bubbles collapse violently. Effects: Severe noise (sounds like gravel), intense localized shockwaves causing pitting/erosion of valve trim and body. Mitigation: Use anti-cavitation trim (multi-stage pressure drop, tortuous path, or drilled hole cages) to keep pressure drop per stage small, or inject air downstream, or use a harder trim material (Stellite), though material hardness only delays the damage.",
20),

(D,"essay",
"9. Describe the procedure and acceptance criteria for performing an Impulse Line Pressure Test (Leak Test) for a newly installed differential pressure flow transmitter in high-pressure gas service.",
"","",
"Grade on: Procedure: Disconnect or isolate transmitter (to avoid overpressuring the sensor if test pressure exceeds rating); connect hydrostatic or pneumatic test pump to impulse lines; pressurize to 1.5x design pressure (hydro) or 1.1x (pneumatic); hold for specified time (e.g., 30 mins). Acceptance: No visible drop on calibrated test gauge; apply soapy water (Snoop) to all threaded fittings and manifold connections to verify zero bubble formation; document test with QC signature.",
20),

(D,"essay",
"10. Explain the principles of operation for an Ultrasonic Flowmeter. Compare Transit-Time and Doppler types, specifying which is best for clean liquids versus slurries.",
"","",
"Grade on: Principle: Uses high-frequency sound waves. Transit-Time: Measures the time difference for an ultrasonic pulse to travel upstream vs downstream; time diff is proportional to fluid velocity. Best for clean liquids. Doppler: Measures the frequency shift (Doppler effect) of sound waves reflected off particles or bubbles in the fluid. Best for dirty liquids, slurries, or aerated liquids. Transit-time will fail in slurries due to signal scattering; Doppler fails in clean liquids due to lack of reflectors.",
20),

(D,"essay",
"11. As a QC Inspector, what specific checks would you perform on the installation of an Orifice Plate and its associated meter run to ensure measurement accuracy?",
"","",
"Grade on: Verify orifice plate tag/bore size matches design sheet; ensure sharp edge is facing upstream; check plate for flatness and no damage/nicks to the bore edge; verify correct installation of gaskets (not protruding into pipe); check upstream and downstream straight pipe run lengths (e.g., 20D/5D minimum per AGA/ISO standards); verify orientation of pressure taps (horizontal for liquid, top for gas); ensure weep hole is positioned correctly.",
20),

(D,"essay",
"12. Discuss the importance of 'Grounding and Shielding' in instrument systems. How do ground loops occur, and how are they prevented in a DCS architecture?",
"","",
"Grade on: Importance: Protects sensitive low-voltage signals from EMI/RFI noise. Ground Loops: Occur when a shield or signal wire is grounded at two points that are at different electrical potentials, causing a noise current to flow through the shield. Prevention: Instrument grounds must be isolated from electrical safety grounds. Shields must be grounded at ONE end only (usually the DCS marshalling cabinet isolated instrument ground bus). Ensure field devices (if not isolated internally) are properly insulated from the pipe/structure if necessary.",
20),

(D,"essay",
"13. Outline the steps required to commission a Motor Operated Valve (MOV) equipped with a smart actuator (e.g., Rotork or Limitorque).",
"","",
"Grade on: Verify power and control wiring against schematics; Check manual handwheel operation; Set mechanical open/close limit switches; Configure electronic limits and torque settings via Bluetooth/IR tool or local display; Perform remote open/close stroke from DCS; Verify stroke times meet process requirements; Verify feedback signals (Open, Closed, Fault, Local/Remote status) correctly display on DCS HMI; Verify fail-safe action on loss of signal.",
20),

(D,"essay",
"14. What is a Proof Test in the context of a Safety Instrumented System (SIS)? Why is it necessary, and give an example of how to proof test a high-level trip switch on a tank.",
"","",
"Grade on: Definition: A periodic test performed to reveal hidden dangerous failures in a safety system that are not detected by automatic diagnostics, ensuring the SIF meets its designed PFD (Probability of Failure on Demand). Example (High Level Switch): The best proof test is a 'wet test' — physically raising the liquid level in the tank until the switch trips, verifying the physical float/sensor, the wiring, the logic solver, and the final final valve closing. If wet testing is impossible, simulate the physical movement of the sensor and verify the entire loop responds.",
20),

(D,"essay",
"15. Explain the difference between 'Calibration' and 'Loop Checking'. What are the objectives of each, and in what sequence should they be performed during a project?",
"","",
"Grade on: Calibration: An isolated test of the field instrument against a certified standard to ensure its output accurately represents the input physical parameter (e.g., 0-100 psi = 4-20mA). Done first, often in a calibration shop. Loop Checking: An end-to-end test of the entire circuit (instrument, cabling, barriers, I/O card, DCS logic, and HMI display). Ensures wiring is correct, scaling in DCS matches instrument calibration, and alarms/graphics function. Sequence: Calibrate instruments -> Install -> Cable testing -> Loop Check.",
20),

(D,"essay",
"16. Describe the common types of Thermocouples (e.g., J, K, T, E) and RTDs (e.g., Pt100). Explain the criteria for choosing an RTD over a Thermocouple for a specific process application.",
"","",
"Grade on: TC Types: K (Chromel-Alumel, wide range), J (Iron-Constantan), etc. RTDs: Pt100 (Platinum, 100 ohms at 0C). Selection criteria: RTDs offer higher accuracy, better stability/repeatability, and are ideal for narrower, lower temperature ranges (up to ~600C). Thermocouples are more rugged, respond faster, can measure much higher temperatures (e.g., >1000C for Type K or S), and are cheaper, but are less accurate and require specific extension wire.",
20),

(D,"essay",
"17. A pneumatic control valve fails to stroke fully open when commanded by the DCS. As an Instrument Inspector, outline your troubleshooting methodology to isolate the root cause.",
"","",
"Grade on: Step 1: Check DCS output (is it actually sending 100%/20mA?). Step 2: Check I/P converter output (is it generating 15 psi?). Step 3: Check Instrument Air supply pressure to the positioner (is it adequate, e.g., 30-60 psi?). Step 4: Check positioner output to actuator (is it sending full supply pressure to the diaphragm?). Step 5: Mechanical check (is the valve stem stuck due to overtightened packing, or is the actuator spring broken/diaphragm ruptured?).",
20),

(D,"essay",
"18. Discuss the requirements for tubing installations (Impulse Lines) for pressure and differential pressure instruments. Mention sloping, supports, tube fittings, and material selection.",
"","",
"Grade on: Sloping: Minimum 1:12 slope; upwards to transmitter for gas (to drain liquids), downwards for liquid/steam (to vent gases). Supports: Tubing must be supported continuously (e.g., tray) or clipped at specific intervals to prevent vibration fatigue. Fittings: Use specific double-ferrule fittings (e.g., Swagelok) correctly swaged with a gap gauge. Material: Typically 316SS (or higher alloys like Monel for corrosive service) to prevent external and internal corrosion.",
20),

(D,"essay",
"19. What is an Analyzer Shelter (or AMADAS)? Describe the key QC inspection points for a newly installed gas chromatograph analyzer shelter before it is powered up.",
"","",
"Grade on: Shelter houses sensitive analytical equipment. QC points: HVAC system verification (temp control is critical for analyzers); Ex p (pressurization/purge) system functional test and interlocks (must purge before power-up in hazardous area); Calibration gas cylinder securement and manifold leak testing (using helium leak detector or snoop); Sample conditioning system (SCS) installation (filters, heated lines to prevent condensation, pressure regulators); Wiring segregation (power vs signals).",
20),

(D,"essay",
"20. Explain the concept of 'Split-Range Control' in a process plant. Provide an example of where it is used and how the control valves are calibrated to achieve it.",
"","",
"Grade on: Concept: One controller output (e.g., 4-20mA) drives two or more control valves operating in sequence. Example: Tank blanketing/pressure control. Valve A (Nitrogen supply) opens to increase pressure; Valve B (Vent to flare) opens to decrease pressure. Calibration: Controller output 4-12mA strokes Valve A from 100% to 0% (Fail Open vent). Output 12-20mA strokes Valve B from 0% to 100% (Fail Closed supply). At 12mA, both valves are closed.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. If you find a field instrument with a cracked glass on its display in a Zone 1 hazardous area, what is your immediate action and why?",
"","",
"Grade on: Immediate action: Notify operations to de-energize the instrument or issue a hot work permit if it must remain live, and raise an NCR to replace the instrument. Why: The cracked glass compromises the Ex d (flameproof) or Ex e (increased safety) integrity of the enclosure, making it capable of igniting the surrounding hazardous atmosphere.",
10),

(D,"oral",
"2. Explain the difference between 'Accuracy' and 'Repeatability' when referring to a transmitter.",
"","",
"Grade on: Accuracy is how close the measured value is to the true, absolute value (requires calibration to a standard). Repeatability is how consistently the instrument gives the SAME reading for the same input under the same conditions, regardless of whether that reading is actually accurate. High repeatability is often more important in closed-loop control than absolute accuracy.",
10),

(D,"oral",
"3. Why must a 3-valve or 5-valve manifold be operated in a specific sequence when removing a DP transmitter from service?",
"","",
"Grade on: To prevent damaging the transmitter sensor. The equalizer valve must be opened BEFORE the block valves are closed to ensure the pressure on both sides of the diaphragm equalizes. If a high-pressure block valve is closed while the low-pressure is open (without equalizing), the sensor can be subjected to unilateral static overpressure, permanently rupturing or deforming the diaphragm.",
10),

(D,"oral",
"4. What is a 'Smart' transmitter, and what are its main advantages over a conventional analog transmitter?",
"","",
"Grade on: A smart transmitter contains a microprocessor. Advantages: Digital communication (HART/Fieldbus) allowing remote calibration and configuration; internal diagnostics (sensor health, electronics failure); multi-variable measurement (e.g., measuring DP, static pressure, and temp in one unit); and the ability to characterize/linearize the sensor output internally.",
10),

(D,"oral",
"5. How do you verify the calibration of a pH sensor in the field?",
"","",
"Grade on: pH sensors cannot be calibrated electronically; they require a wet calibration using buffer solutions. You must remove the sensor, rinse it, and place it sequentially in certified buffer solutions (typically pH 4, 7, and 10). The transmitter is adjusted to match the known buffer values (adjusting the 'zero' or asymmetry at pH 7, and the 'slope' at pH 4 or 10).",
10),

(D,"oral",
"6. What is the purpose of an 'I/P Converter'?",
"","",
"Grade on: I/P stands for Current to Pressure. It converts a standard analog electrical control signal (typically 4-20mA DC from a DCS) into a proportional pneumatic signal (typically 3-15 psi) to operate a pneumatic control valve actuator.",
10),

(D,"oral",
"7. During cable pulling, the contractor applies pulling grease (lubricant) to instrument cables. What must you verify as a QC inspector?",
"","",
"Grade on: You must verify that the cable lubricant used is chemically compatible with the cable jacket material (e.g., PVC, XLPE). Using the wrong lubricant (like petroleum-based grease on some plastics) can degrade the cable jacket over time, leading to insulation failure.",
10),

(D,"oral",
"8. Why is it critical to ensure 'Clean and Dry' instrument air? What happens if water gets into the pneumatic lines?",
"","",
"Grade on: Instrument air runs positioners and I/P converters which have very small orifices and flappers. Moisture can cause internal corrosion, blocking these orifices. In cold weather, moisture freezes, completely disabling control valves. This leads to loss of process control and potential plant shutdowns.",
10),

(D,"oral",
"9. What is a 'Thermowell' and why is it used?",
"","",
"Grade on: A thermowell is a pressure-tight cylindrical fitting installed in a pipe or vessel that protects the temperature sensor (TC or RTD) from the corrosive, high-pressure, or high-velocity process fluid. It allows the sensor to be removed for calibration or replacement without draining the pipe or stopping the process.",
10),

(D,"oral",
"10. Explain what 'Fail-Safe' means in the context of process control.",
"","",
"Grade on: Fail-safe is a design principle where, upon loss of motive power (instrument air, electrical power) or loss of the control signal, the final control element (valve) automatically moves to a state that puts the process into a safe condition (e.g., a fuel gas valve fails closed to stop a fire, a cooling water valve fails open to prevent overheating).",
10),

(D,"oral",
"11. What is the difference between an 'Active' and a 'Passive' 4-20mA loop device?",
"","",
"Grade on: An active device provides its own power to drive the 4-20mA current loop (it acts as a power supply). A passive device relies on external loop power (typically 24VDC provided by the DCS input card or an external supply) to operate and regulate the current. 2-wire transmitters are passive; 4-wire transmitters are usually active.",
10),

(D,"oral",
"12. You see a contractor using Teflon tape on the threads of a straight-threaded compression fitting (like Swagelok) on an impulse line. Is this correct?",
"","",
"Grade on: No, this is incorrect. Compression fittings seal via the metal-to-metal contact of the ferrules against the tubing and the fitting body. Teflon tape should ONLY be used on tapered pipe threads (NPT) to prevent galling and provide a seal. Using it on straight threads can interfere with the ferrule swaging process.",
10),

(D,"oral",
"13. What is a 'Capillary Tube' used for in differential pressure measurement?",
"","",
"Grade on: Capillary tubes are used in Remote Seal DP transmitters. They are fluid-filled tubes that transmit the process pressure from a diaphragm seal at the tapping point to the transmitter sensor. Used when the process fluid is highly corrosive, highly viscous, prone to freezing/plugging, or at extreme temperatures that would damage the transmitter.",
10),

(D,"oral",
"14. What does the term 'Span' mean when calibrating an instrument?",
"","",
"Grade on: Span is the algebraic difference between the Upper Range Value (URV) and the Lower Range Value (LRV). For example, if a temperature transmitter is calibrated to measure from 50°C to 150°C, the URV is 150, the LRV is 50, and the Span is 100°C.",
10),

(D,"oral",
"15. Why do we use RTDs (Pt100) with 3-wire or 4-wire configurations instead of just 2 wires?",
"","",
"Grade on: An RTD measures tiny changes in resistance. If a 2-wire system is used, the resistance of the long copper lead wires is added to the RTD resistance, causing a massive temperature error. 3-wire and 4-wire configurations use bridge circuits to measure and mathematically cancel out the lead wire resistance, ensuring accurate temperature readings.",
10),

(D,"oral",
"16. In Foundation Fieldbus, what is a 'Terminator' and where should it be installed?",
"","",
"Grade on: A terminator is an RC circuit (Resistor-Capacitor) used to prevent signal reflection at the ends of the network cable, which would corrupt the digital communication. Exactly TWO terminators must be installed on every FF segment, one at each extreme end of the trunk cable.",
10),

(D,"oral",
"17. What is the main safety risk when opening a live junction box in an Intrinsically Safe (IS) circuit versus an Explosion-proof (Ex d) circuit?",
"","",
"Grade on: For an IS circuit, opening the box live poses no ignition risk, as the energy is inherently limited to safe levels by the barrier. For an Ex d circuit, opening the box live breaches the explosion-proof protection. If a spark occurs inside while open, it WILL ignite any surrounding hazardous atmosphere. Ex d boxes must be de-energized and gas-tested before opening.",
10),

(D,"oral",
"18. How do you verify the operation of a solenoid valve?",
"","",
"Grade on: Check the coil resistance (should not be open or shorted). Apply rated voltage and listen for a distinct 'click' as the plunger actuates. Verify the pneumatic routing: ensure air passes through the correct ports when energized and exhausts correctly when de-energized. Check for air leaks.",
10),

(D,"oral",
"19. What is 'Cold Junction Compensation' (CJC) in thermocouple measurement?",
"","",
"Grade on: Thermocouples generate a voltage proportional to the temperature DIFFERENCE between the hot junction (measurement point) and the cold junction (where the TC wires connect to the DCS/transmitter copper terminals). Because the cold junction is at ambient temperature (not 0°C), a CJC sensor (like an RTD or thermistor) measures the terminal temperature, and the transmitter calculates the compensation to find the true hot junction temperature.",
10),

(D,"oral",
"20. Before signing a loop check folder as accepted, what is the most important thing you must verify regarding the DCS HMI display?",
"","",
"Grade on: You must verify that the Tag Number, Engineering Units, Range (Scale), and Alarm limits (High/Low) displayed on the operator's HMI perfectly match the approved P&ID, the Instrument Data Sheet, and the actual physical calibration of the field instrument.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. Calculate the required output of a DP transmitter (4-20mA) measuring liquid level in an open tank. LRV = 0 mmH2O, URV = 5000 mmH2O. The current liquid level is applying 3750 mmH2O of pressure to the transmitter. What should the multimeter read?",
"","",
"Grade on: Range = 5000 - 0 = 5000. Current pressure = 3750. Percentage of range = (3750 / 5000) × 100 = 75%. mA output = 4mA + [0.75 × (20mA - 4mA)] = 4 + (0.75 × 16) = 4 + 12 = 16mA. The multimeter must read 16.00 mA.",
15),

(D,"practical",
"2. Review a given P&ID snippet. Identify the following instrument bubbles: FI, FIC, FCV, FT. Explain the function of each in a typical flow control loop.",
"","",
"Grade on: FT = Flow Transmitter (measures the flow in the field). FI = Flow Indicator (local or panel display of flow). FIC = Flow Indicator Controller (the PID algorithm in the DCS comparing flow to setpoint and generating an output). FCV = Flow Control Valve (the final element in the field modulating the flow based on the FIC output).",
15),

(D,"practical",
"3. Inspect a physical installation (or photo) of an orifice plate meter run. Identify at least 3 installation errors based on API/AGA standards.",
"","",
"Grade on: Look for: Orifice plate installed backwards (bevel must face downstream). Tapping points in wrong orientation (gas should be top, liquid should be horizontal). Impulse lines lacking continuous slope. Missing 5-valve manifold. Insufficient straight pipe runs upstream/downstream of the orifice flanges.",
15),

(D,"practical",
"4. You are provided with a loop calibrator and a standalone 2-wire 4-20mA pressure transmitter. Demonstrate how to wire the calibrator to power the transmitter and measure its output simultaneously (Loop Power mode).",
"","",
"Grade on: Connect the positive (Red) lead of the loop calibrator (set to Loop Power / mA Measure mode, typically 24V output) to the Positive (+) terminal of the transmitter. Connect the negative (Black) lead of the calibrator to the Negative (-) terminal of the transmitter. Verify a reading of ~4mA at zero pressure.",
15),

(D,"practical",
"5. A Pt100 RTD gives a resistance reading of 119.4 Ohms. Using standard RTD alpha 385 tables (or a rule of thumb: approx 0.385 ohms/°C), estimate the current temperature.",
"","",
"Grade on: At 0°C, R = 100 Ohms. Difference = 119.4 - 100 = 19.4 Ohms. Temperature ≈ 19.4 / 0.385 ≈ 50.39°C. (Candidate should state approximately 50°C).",
15),

(D,"practical",
"6. Examine an ATEX nameplate on an instrument: 'CE 1180 Ex II 2 G Ex d IIC T5 Gb'. Decode every part of this classification string.",
"","",
"Grade on: CE 1180 = European conformity and notified body number. Ex = Explosion protection. II = Surface industry (not mining). 2 = Category 2 (suitable for Zone 1 or 2). G = Gas hazard. Ex d = Flameproof enclosure. IIC = Gas group (Hydrogen/Acetylene, most severe). T5 = Max surface temp 100°C. Gb = Equipment Protection Level (Zone 1).",
15),

(D,"practical",
"7. Perform a continuity check on a multi-core instrument cable drum before installation. How do you prove there are no short circuits between cores or to the shield?",
"","",
"Grade on: Ensure both ends of the cable are separated and not touching. Use a multimeter on 'Ohms' or 'Continuity/Beep' mode. Place one probe on Core 1. Place the other probe sequentially on Core 2, Core 3... Core N, and finally the drain wire (shield). All readings must show OL (Open Loop / Infinite resistance). Repeat by moving the first probe to Core 2, etc.",
15),

(D,"practical",
"8. Given a control valve data sheet specifying 'Air-to-Open', and a positioner gauge reading 0 psi output to the actuator. Is the valve open or closed? If the DCS commands 100% (20mA), what should the positioner output pressure gauge read (assuming standard 3-15 psi actuator)?",
"","",
"Grade on: 'Air-to-Open' means springs close the valve when air is lost. At 0 psi, the valve is fully CLOSED (Fail Closed). If DCS commands 100% (20mA), the positioner should output its maximum calibrated pressure to fully overcome the springs, which should be approximately 15 psi (or higher, depending on supply pressure and bench set) to force the valve fully OPEN.",
15),

(D,"practical",
"9. Review a tubing hook-up drawing for a gas pressure transmitter. The drawing shows the transmitter mounted 2 meters BELOW the tapping point, with impulse lines sloping down. Is this correct? Why or why not? Redline the drawing.",
"","",
"Grade on: Incorrect. For GAS service, the transmitter should be mounted ABOVE the tapping point, with impulse lines sloping continuously UP to the transmitter. This allows any condensation/liquids that form in the lines to drain back into the process pipe by gravity. If mounted below, liquids will pool in the lines, causing a hydrostatic head error in the pressure reading. Redline: Move transmitter above pipe.",
15),

(D,"practical",
"10. Connect a HART communicator to a smart transmitter in a live 4-20mA loop. What is the minimum loop resistance required for the HART communicator to function, and where do you connect the leads?",
"","",
"Grade on: Minimum loop resistance required is typically 250 Ohms. Without it, the high-frequency HART signal is shorted out by the power supply. Connect the HART communicator leads in parallel with the transmitter (across the + and - terminals of the transmitter) or across the 250 Ohm resistor.",
15),

(D,"practical",
"11. Calculate the 'Bench Set' or spring range required for a control valve. Actuator area = 100 sq inches. Valve plug unbalanced area = 10 sq inches. Maximum process pressure drop (shutoff) = 100 psi. Packing friction = negligible. Assume Air-to-Open.",
"","",
"Grade on: Force required to keep valve shut against process = Area × Pressure = 10 sq in × 100 psi = 1000 lbs. This force must be provided by the actuator spring pre-load. Spring pre-load pressure (bench set initial point) = Force / Actuator Area = 1000 lbs / 100 sq in = 10 psi. Therefore, the bench set must start at least at 10 psi (e.g., a 10-30 psi spring range) to ensure tight shutoff against the process pressure.",
15),

(D,"practical",
"12. Identify the correct Type K thermocouple wire colors based on ANSI (US) and IEC (European) standards.",
"","",
"Grade on: ANSI (US): Positive = Yellow, Negative = Red (Overall jacket usually Yellow). IEC (European): Positive = Green, Negative = White (Overall jacket usually Green). Note: Red is always negative in ANSI standards.",
15),

(D,"practical",
"13. Review a completed Instrument Calibration Certificate. Identify at least 4 critical fields that must be present and correctly filled out for QA/QC acceptance.",
"","",
"Grade on: 1. Instrument Tag Number & Serial Number. 2. Calibration Range (LRV & URV). 3. Test Equipment used (Standard) with its own Calibration Due Date & Traceability number. 4. 'As Found' and 'As Left' data points (error %). 5. Signature of the technician and date of calibration.",
15),

(D,"practical",
"14. Demonstrate the setup for calibrating a differential pressure transmitter used for level measurement with a remote seal capillary system. What precautions must be taken regarding the capillary tubes?",
"","",
"Grade on: The transmitter and both remote seals must be placed on the exact same horizontal plane (elevation) on the workbench to eliminate hydrostatic head differences in the capillary fill fluid during zeroing. Precautions: Never lift the transmitter by the capillaries. Do not kink or bend capillaries beyond their minimum bend radius. Keep them away from extreme heat sources.",
15),

(D,"practical",
"15. A Foundation Fieldbus segment has 10 devices. The voltage at the power conditioner is 24VDC. The voltage measured at the furthest device is 7VDC. The FF standard requires a minimum of 9VDC at any device. Identify the likely causes and the required QC action.",
"","",
"Grade on: Likely causes: Total cable length exceeds FF limits (max 1900m depending on cable type). Cable used is incorrect type (high resistance, not Type A). Too many devices drawing too much current (overloading the segment). Poor terminations causing high resistance. QC Action: Raise NCR. Segment fails design criteria. Requires re-engineering (split segment, shorten cable, or upgrade power conditioner).",
15),

(D,"practical",
"16. Given a Megger (Insulation Resistance Tester), demonstrate how to safely test a newly pulled instrument cable. What voltage setting do you use for a standard 300V/500V rated instrument cable?",
"","",
"Grade on: Safety first: Ensure both ends of the cable are completely disconnected from all sensitive electronic instruments (DCS, Transmitters) to prevent destroying them with high voltage. Select a test voltage appropriate for instrument cables, typically 250V DC or 500V DC (never 1000V). Test Core to Core, and Core to Shield. Acceptable reading is usually > 100 MegaOhms.",
15),

(D,"practical",
"17. Analyze a scenario where an Orifice plate is installed with the bevel facing upstream. Calculate the qualitative effect on the flow reading.",
"","",
"Grade on: The sharp edge must face the flow (upstream) to create a defined, sudden vena contracta. If the bevel faces upstream, it acts like a nozzle, smoothing the flow convergence. This results in a much lower differential pressure being generated for the same actual flow rate. Therefore, the transmitter will output a DP that is too low, and the DCS will read a falsely LOW flow rate.",
15),

(D,"practical",
"18. You are inspecting a newly installed radar level transmitter on a storage tank. Identify potential installation obstructions that would cause false echoes and explain how to mitigate them via transmitter configuration.",
"","",
"Grade on: Obstructions: Agitator blades, internal ladders, heating coils, or filling streams falling through the radar beam. Mitigation: Ensure physical installation avoids these if possible. Configuration mitigation: Use the transmitter's 'False Echo Mapping' (or TVT curve - Time Varying Threshold) function while the tank is empty. The radar scans the empty tank, memorizes the stationary obstruction reflections, and ignores them during normal operation.",
15),

(D,"practical",
"19. Demonstrate how to check the stroke time of an Emergency Shutdown (ESD) valve. What constitutes a pass/fail?",
"","",
"Grade on: Coordinate with Operations/DCS. Command the valve to trip via DCS or local push button. Use a stopwatch to measure the time from the moment the command is given (or solenoid de-energizes) until the valve reaches the fully closed (or safe) position, indicated by the mechanical pointer and limit switch. Pass/Fail is dictated by the Safety Requirement Specification (SRS), e.g., 'Must close in < 3.0 seconds'. If it takes 3.5 seconds, it FAILS.",
15),

(D,"practical",
"20. Review a Hazardous Area layout drawing. An instrument is located in a Zone 0 area. The contractor has proposed an Ex d (Flameproof) transmitter. Is this acceptable? Justify your decision based on IEC standards.",
"","",
"Grade on: Not acceptable. Zone 0 is an area where an explosive atmosphere is present continuously or for long periods. IEC standards dictate that equipment in Zone 0 must have 'EPL Ga' (Equipment Protection Level), which typically means Intrinsically Safe 'Ex ia'. 'Ex d' (Flameproof) provides EPL Gb, which is only suitable for Zone 1 or Zone 2. A flameproof enclosure breathes and can allow gas inside; a spark inside will cause an internal explosion, which is not permitted in Zone 0. Must use Ex ia.",
15),

]  # end QUESTIONS
