"""
Welding QC — 100 ARAMCO-aligned questions
40 MCQ | 20 Essay | 20 Oral | 20 Practical
Standards: ASME IX, ASME B31.3, ASME VIII Div.1, AWS D1.1,
           SAES-W-011, SAES-W-012, SAES-W-014, SAEP-1142, SATIP-W-011
Tuple format: (discipline, kind, question, options, correct_answer, rubric, max_points)
"""

D = "Welding QC"

QUESTIONS = [

# ── MCQ 1–40 ────────────────────────────────────────────────────────────────

(D,"mcq",
"1. A WPS qualified per ASME IX uses GTAW root pass on P-No.8 (316L SS), 2G position, 12 mm thickness. The contractor proposes using this WPS for a 1G, 20 mm thick P-No.8 joint. Which statement is correct?",
"The WPS covers 1G since ASME IX QW-461 allows any position qualified at 2G to be used in 1G.\nThe WPS does not cover 20 mm because ASME IX QW-451 limits upward range to 2T (24 mm) only for P-No.8 materials above 19 mm.\nThe WPS is not applicable; position is an essential variable for GTAW and changing from 2G to 1G requires requalification.\nThe WPS covers both changes; no action is needed.",
"The WPS covers 1G since ASME IX QW-461 allows any position qualified at 2G to be used in 1G.",
"Position is NOT an essential variable for GTAW (QW-256) — 2G covers 1G per QW-461.1. For a 12 mm P-No.8 test coupon, qualified range is 3–24 mm (2T); 20 mm is within range. Both changes are acceptable under the existing WPS. Distractor B misapplies a 19 mm threshold from a different table.",
1),

(D,"mcq",
"2. During P91 production welding per SAES-W-011, preheat is found at 175°C at tacking. The minimum preheat for P91 >19 mm is 200°C. The welder reheated, but the ITP hold point for preheat was already signed 30 min earlier at 210°C. What is the correct action?",
"Accept the tacks; the hold-point record confirms 210°C was achieved before welding.\nIssue an NCR, quarantine the tacked joint, verify temperature before resuming, and investigate why temperature dropped below minimum during the hold period.\nConvert the hold to a witness point and continue; the specification allows a 25°C field tolerance.\nRequest the welder re-tack without an NCR since no fusion weld was deposited during the low-temperature event.",
"Issue an NCR, quarantine the tacked joint, verify temperature before resuming, and investigate why temperature dropped below minimum during the hold period.",
"A hold-point record is valid only at the time of inspection. Temperature drop during the interval is a nonconformance. Tack welds are production welds under SAES-W-011. No tolerance band exists without documented project deviation. Quarantine prevents further work until disposition.",
1),

(D,"mcq",
"3. A welder's WPQ was last verified 7 months ago. The QC Manager states it is still valid since no test failure is recorded. The weld log shows he has been performing only grinding and fit-up for 5 months. What is the inspector's assessment?",
"Valid — ASME IX QW-322.1 only requires 6-month continuity if the welder uses any welding process, including grinding.\nLapsed — ASME IX QW-322.1 requires the qualified process to have been used within 6 months; grinding and fit-up do not constitute welding.\nValid — the 6-month clock resets upon joining a new project.\nValid — only a log review is needed, not an actual weld test, so continuity is maintained.",
"Lapsed — ASME IX QW-322.1 requires the qualified process to have been used within 6 months; grinding and fit-up do not constitute welding.",
"ASME IX QW-322.1: welder must have deposited weld metal using the qualified process. Grinding and fit-up are not welding. A 5-month gap without welding activity within the 6-month window lapses the WPQ.",
1),

(D,"mcq",
"4. An RT film of a butt weld (ASME B31.3 Normal Fluid Service, 12 mm wall) shows a linear indication 4 mm long at the weld root that cannot be distinguished as slag or lack of fusion by RT alone. What is the correct disposition?",
"Accept — 4 mm is below the 6 mm maximum slag inclusion length in ASME B31.3 Table 341.3.2.\nReject — any linear indication at the root suspected of being lack of fusion must be treated as the more severe defect type.\nPerform supplementary UT to confirm the nature of the indication before final disposition.\nConsult the welding engineer and accept provisionally if indication length is less than 1/3 of weld thickness.",
"Reject — any linear indication at the root suspected of being lack of fusion must be treated as the more severe defect type.",
"ASME B31.3 requires LOF to be rejected regardless of size. When RT cannot distinguish slag from LOF, conservative characterisation as LOF is mandatory. Applying slag acceptance criteria to an indeterminate indication is non-conservative and non-code-compliant.",
1),

(D,"mcq",
"5. SAES-W-011 requires PMI for all P5 chrome-moly filler materials. An E9018-B3 electrode passes XRF, but the XRF calibration label expired 3 days ago. What action should the QC Inspector take?",
"Accept the PMI results — 3-day expiry is within the typical ±1 week grace period for field instruments.\nReject the PMI results, quarantine tested electrodes, re-calibrate the XRF against a certified reference, and retest all electrodes verified since the last confirmed calibration date.\nAccept — XRF drift over 3 days is negligible for alloy content verification.\nRequest the filler material MTC as a substitute for PMI.",
"Reject the PMI results, quarantine tested electrodes, re-calibrate the XRF against a certified reference, and retest all electrodes verified since the last confirmed calibration date.",
"An expired calibration certificate invalidates all readings taken after expiry. No grace period exists unless explicitly stated in the approved inspection procedure. Quarantine scope extends back to the last confirmed valid calibration date. The MTC is not a substitute for in-situ PMI.",
1),

(D,"mcq",
"6. A repair excavation PT reveals a defect extending to 14 mm depth (70% through-wall) in a 20 mm weld. The original WPS was qualified on 20 mm plate, repair depth ≤10 mm. The supervisor wants to use the same WPS. What is correct?",
"The WPS is applicable — repair depth is not an essential variable under ASME IX.\nThe WPS is not applicable — a repair exceeding 50% through-wall on P91 requires a dedicated repair WPS with full-thickness test coupon and evaluation of temper-bead techniques.\nThe WPS requires only a minor amendment signed by the welding engineer.\nAccept the repair WPS only if PWHT is applied after repair.",
"The WPS is not applicable — a repair exceeding 50% through-wall on P91 requires a dedicated repair WPS with full-thickness test coupon and evaluation of temper-bead techniques.",
"Repair depth >50% through-wall on creep-resistant alloys mandates evaluation of temper-bead welding or full-thickness repair qualification per SAES-W-011. The original WPS does not cover a 14 mm repair on a 20 mm wall.",
1),

(D,"mcq",
"7. A welder qualifies in 6G position, SMAW, 25 mm carbon steel pipe per ASME IX. A new job requires FCAW on 19 mm carbon steel structural members in the flat (1F) position. Can the welder proceed?",
"No — FCAW is a different process from SMAW and is a separate essential variable requiring its own WPQ.\nYes — 6G covers all positions and SMAW qualification may extend to FCAW for structural work under ASME IX QW-303.\nNo — FCAW requires its own WPS and qualification regardless of SMAW status.\nYes — but a supplementary FCAW test on the structural members is required per SAES-W-011.",
"No — FCAW is a different process from SMAW and is a separate essential variable requiring its own WPQ.",
"Welding process is an essential variable for welder qualification (ASME IX QW-303). SMAW and FCAW are different processes. A welder qualified in SMAW is not automatically qualified for FCAW production.",
1),

(D,"mcq",
"8. Visual inspection of a completed socket weld (ASME B31.3) shows a 5 mm fillet on a pipe with 4 mm wall. The inspector also notes the pipe was pushed fully into the socket before welding with no gap. What is the finding?",
"Accept — fillet size 5 mm exceeds the pipe wall of 4 mm, meeting the minimum size requirement.\nIssue an NCR — ASME B31.3 para 328.5.2 requires ~1.5 mm gap between pipe end and socket bottom; full insertion is a nonconformance.\nAccept if PWHT is applied to relieve thermal stress from the zero-gap condition.\nRequest UT examination of the socket weld before making a disposition.",
"Issue an NCR — ASME B31.3 para 328.5.2 requires ~1.5 mm gap between pipe end and socket bottom; full insertion is a nonconformance.",
"ASME B31.3 para 328.5.2 requires the pipe to be withdrawn ~1.5 mm (1/16 in) before welding to accommodate thermal cycling stress. Full insertion is a code violation independent of fillet size compliance.",
1),

(D,"mcq",
"9. PWHT records for a P22 nozzle weld show 720°C for 60 minutes. SAES-W-014 requires 720°C–760°C for 2 hours minimum. ASME VIII UCS-56 minimum is 620°C. What is the correct disposition?",
"Accept — 720°C meets both ASME code minimum (620°C) and project specification minimum (720°C).\nIssue an NCR — 60 minutes does not meet the SAES-W-014 minimum of 2 hours; the more stringent project specification governs.\nAccept — ASME code soak time requirements are not volume-dependent for nozzle welds.\nRequest an MTC review to determine whether base material chemistry allows a reduced soak time.",
"Issue an NCR — 60 minutes does not meet the SAES-W-014 minimum of 2 hours; the more stringent project specification governs.",
"When the project specification is more stringent than the code, SAES-W-014 Section 1 requires the specification to govern. The 60-minute soak satisfies temperature but fails the 2-hour duration.",
1),

(D,"mcq",
"10. A weld map shows W-42 was executed using WPS-CS-04. An audit reveals WPS-CS-04 was approved after the weld was completed. RT shows no recordable indications. What must the inspector do?",
"Accept — RT acceptance confirms weld quality and the WPS has since been approved.\nIssue an NCR — the weld was executed without a valid approved WPS, regardless of acceptable RT results.\nAccept with a documented deviation request signed by the client.\nIssue a technical query to the welding engineer for retrospective WPS approval.",
"Issue an NCR — the weld was executed without a valid approved WPS, regardless of acceptable RT results.",
"A WPS must be approved BEFORE welding begins. NDT results do not retroactively validate procedural nonconformance. Disposition options include rejection/repair or formal client concession with technical risk assessment.",
1),

(D,"mcq",
"11. The MTC for API 5L X65 shows CE = 0.43. The approved WPS specifies a maximum preheat of 100°C for CE ≤ 0.40. What is the correct action?",
"Apply 100°C preheat — the 0.03 difference in CE is within typical material variability tolerance.\nHold welding and issue an NCR — actual CE exceeds the WPS preheat threshold; this WPS cannot be used without revision or replacement.\nPreheat to 150°C as a conservative field adjustment without revising the WPS.\nAccept the WPS since CE is a material parameter, not a WPS essential variable under ASME IX.",
"Hold welding and issue an NCR — actual CE exceeds the WPS preheat threshold; this WPS cannot be used without revision or replacement.",
"WPS preheat requirements are tied to the base material CE range. If the actual MTC CE falls outside the WPS material envelope the inspector must halt welding. Unilateral field adjustment without WPS revision is not acceptable.",
1),

(D,"mcq",
"12. An RT film of a 16 mm girth weld (ASME B31.3 Normal Fluid Service) shows a 3.5 mm diameter circular indication. The radiographer classifies it as isolated porosity. What is the correct acceptance determination?",
"Reject — isolated porosity exceeding 3 mm diameter is always rejected under B31.3 regardless of wall thickness.\nAccept — the pore is below the 6 mm maximum diameter limit and less than 1/4T (4 mm), meeting both criteria.\nAccept — 3.5 mm is less than 1/4T (4 mm) only, which is the sole criterion.\nReject — B31.3 requires all porosity to be evaluated under ASME V Article 2 technique requirements before any acceptance.",
"Accept — the pore is below the 6 mm maximum diameter limit and less than 1/4T (4 mm), meeting both criteria.",
"ASME B31.3 Table 341.3.2 accepts rounded indications up to 1/4T or 6 mm, whichever is less. 1/4T of 16 mm = 4 mm. The 3.5 mm pore is below both limits — acceptable. Distractor A invents a 3 mm blanket rejection rule.",
1),

(D,"mcq",
"13. A low-hydrogen E7018 electrode has been in the welder's quiver for 3 hours 55 minutes. The project maximum out-of-oven holding time is 4 hours. The crew supervisor says to continue welding. What is the correct action?",
"Continue — 5 minutes margin is negligible; electrodes are typically acceptable up to 8 hours in the field.\nStop the welder — at 3 hrs 55 min the electrode will exceed the 4-hour limit before the pass is complete; return it to the oven for reconditioning.\nContinue — the 4-hour limit applies to the completed weld, not to each electrode individually.\nAccept and document the time deviation in the daily weld log.",
"Stop the welder — at 3 hrs 55 min the electrode will exceed the 4-hour limit before the pass is complete; return it to the oven for reconditioning.",
"The 4-hour limit is absolute per AWS A5.1 and the project specification. Starting a weld pass that will not be completed before the limit is exceeded is procedurally unsound. Return the electrode for reconditioning.",
1),

(D,"mcq",
"14. A welder qualifies 6G SMAW on 2-inch NPS (60.3 mm OD), 25 mm wall, P-No.1 carbon steel. A production weld requires SMAW on 8-inch NPS (219 mm OD), 19 mm wall, P-No.1, 2G position. Can the welder proceed with only this qualification?",
"No — the 8-inch pipe requires a separate OD qualification test per ASME IX QW-452.\nYes — 6G covers all positions and the OD range ≥25 mm OD is unlimited above the test pipe diameter per ASME IX QW-452.\nNo — the welder must test on 8-inch pipe because thermal mass difference creates different metallurgical conditions.\nYes — but a supplementary test on 8-inch pipe is required for ARAMCO projects per SAES-W-011.",
"Yes — 6G covers all positions and the OD range ≥25 mm OD is unlimited above the test pipe diameter per ASME IX QW-452.",
"ASME IX QW-452: for a test pipe OD >25 mm, the welder is qualified for all ODs equal to or greater than the test OD. 60.3 mm >25 mm; 219 mm ≥ 60.3 mm — covered. 6G covers all positions. The welder can proceed.",
1),

(D,"mcq",
"15. During FCAW of A36 structural steel per AWS D1.1, the interpass temperature is 320°C. The WPS maximum is 250°C. The supervisor argues that AWS D1.1 prequalification does not limit interpass temperature for A36. What is correct?",
"The supervisor is correct — AWS D1.1 prequalified WPS for A36 does not specify an interpass limit; 320°C is acceptable.\nThe inspector is correct — the approved WPS maximum of 250°C governs even if the code has no default limit for A36.\nThe supervisor is correct — interpass temperature limits apply only to steels above 70 ksi yield.\nRaise a technical query and allow welding to continue pending resolution.",
"The inspector is correct — the approved WPS maximum of 250°C governs even if the code has no default limit for A36.",
"The project-specific approved WPS is always controlling. Even where a code has no default interpass limit, if the WPS specifies one it is binding. The inspector must halt welding until temperature returns to ≤250°C.",
1),

(D,"mcq",
"16. Visual inspection of a completed pressure pipe weld (ASME B31.3, 8 mm wall) shows undercut 0.8 mm deep and 25 mm long on the OD surface. What is the correct finding?",
"Accept — ASME B31.3 allows undercut up to 1 mm depth for wall thickness >6 mm in Normal Fluid Service.\nReject — undercut depth of 0.8 mm exceeds the B31.3 limit of 0.5 mm (1/64 in) for any wall thickness condition.\nAccept — the 25 mm length distributes stress over a large area, reducing depth significance.\nReject — any undercut in pressure piping is rejectable per B31.3 regardless of depth.",
"Reject — undercut depth of 0.8 mm exceeds the B31.3 limit of 0.5 mm (1/64 in) for any wall thickness condition.",
"ASME B31.3 Table 341.3.2: undercut must not exceed 0.5 mm (1/64 in). 0.8 mm > 0.5 mm → reject and repair. Distractor A invents a 1 mm tolerance.",
1),

(D,"mcq",
"17. An E316L electrode batch shows delta ferrite = 3 FN on the MTC. SAES-W-011 requires a minimum of 4 FN for austenitic stainless filler metals. What is the correct action?",
"Accept — E316L by definition has 4–10 FN; the MTC value may be a minor transcription error.\nReject the batch, quarantine, issue an NCR, and notify procurement — delta ferrite <4 FN is non-compliant with SAES-W-011 regardless of electrode designation.\nAccept subject to delta ferrite re-testing in the field with a Ferrite Number meter.\nRequest a welding engineer disposition — 3 FN may be acceptable for thin-wall applications.",
"Reject the batch, quarantine, issue an NCR, and notify procurement — delta ferrite <4 FN is non-compliant with SAES-W-011 regardless of electrode designation.",
"SAES-W-011 sets a minimum delta ferrite floor to prevent hot cracking. MTC data governs, not the electrode designation. Field re-testing post-receipt is not a recognised incoming material acceptance pathway.",
1),

(D,"mcq",
"18. For ASTM A516 Gr.70 (C=0.28, Mn=1.0, no significant other alloys), CE = C + Mn/6 = 0.28 + 0.167 = 0.447 ≈ 0.45. Per AWS D1.1 Table 3.2, what minimum preheat is required for 38 mm plate thickness using low-hydrogen SMAW?",
"66°C (150°F) — CE category 0.41–0.45 with low-hydrogen process allows the lower preheat tier.\n107°C (225°F) — CE Category III (0.41–0.45) and thickness >19 mm requires 107°C minimum for low-hydrogen electrodes per D1.1 Table 3.2.\n150°C — any CE >0.40 requires 150°C for low-hydrogen process on 38 mm plate.\nNo preheat required — SMAW with low-hydrogen electrodes exempts preheat up to CE 0.45 per D1.1.",
"107°C (225°F) — CE Category III (0.41–0.45) and thickness >19 mm requires 107°C minimum for low-hydrogen electrodes per D1.1 Table 3.2.",
"CE = 0.45, Category III, 38 mm plate, low-hydrogen SMAW → AWS D1.1 Table 3.2 specifies 107°C (225°F). Distractor A misstates the threshold temperature. Distractor D incorrectly exempts preheat.",
1),

(D,"mcq",
"19. After PWHT of P5B (9Cr-1Mo) pipe for sour service, a hardness survey shows HV10 = 285 on the HAZ. SAES-W-011 maximum for P5B sour service is 248 HV10. What is the correct action?",
"Accept — ASME B31.3 has no hardness limit for P5B HAZ after PWHT.\nIssue an NCR and reject the weld — HV10 285 exceeds the 248 limit; investigate PWHT adequacy and assess repair options including re-PWHT.\nConduct additional hardness tests at 5 more locations before making a disposition.\nAccept with an SAES deviation request, as HV10 285 is within typical P91 expectations.",
"Issue an NCR and reject the weld — HV10 285 exceeds the 248 limit; investigate PWHT adequacy and assess repair options including re-PWHT.",
"SAES-W-011 sour service hardness limits are absolute. HV10 285 > 248 is a clear nonconformance. The investigation should address inadequate soak time, non-uniform temperature distribution, or improper alloying.",
1),

(D,"mcq",
"20. During MPI of a structural fillet weld per ASME V Article 7, the AC yoke lifts exactly 4.5 kg at 4-inch leg spacing. The procedure requires ≥4.5 kg for AC yokes. However, the yoke type used is not documented in the inspection record. What is the issue?",
"No issue — the yoke lifts 4.5 kg which meets the minimum; the yoke type is a minor administrative detail.\nThe AC minimum of 4.5 kg (10 lb) is correctly met, but if the yoke is actually a DC type, the minimum must be 18 kg (40 lb); yoke type must be confirmed and documented.\nThe yoke must be re-tested using a 6.8 kg reference block, not a free weight.\nThe lift test must be performed at the exact field weld spacing, not at 4 inches.",
"The AC minimum of 4.5 kg (10 lb) is correctly met, but if the yoke is actually a DC type, the minimum must be 18 kg (40 lb); yoke type must be confirmed and documented.",
"ASME V T-750.2: AC electromagnetic yoke ≥ 4.5 kg; DC or permanent magnet yoke ≥ 18 kg at maximum spacing. Without documented yoke type, compliance cannot be confirmed. The inspector must verify and record this information.",
1),

(D,"mcq",
"21. During an audit, the heat numbers on three P22 pipe spools do not match the MTCs in the dossier. Welding and PWHT are complete. What is the first action?",
"Quarantine the three spools, issue an NCR, and initiate a material traceability investigation to locate correct MTCs and cross-reference with receiving inspection records.\nAccept — P22 alloy content is visually distinctive and PWHT confirms thermal treatment.\nConduct PMI on all three spools to confirm composition before issuing any NCR.\nAccept with a client concession request since the discrepancy is administrative, not metallurgical.",
"Quarantine the three spools, issue an NCR, and initiate a material traceability investigation to locate correct MTCs and cross-reference with receiving inspection records.",
"Heat number mismatches after PWHT mean thermal treatment records cannot be linked to verified material. Quarantine and NCR precede any disposition. PMI supports investigation but does not replace traceability documentation.",
1),

(D,"mcq",
"22. A completed weld in ASME B31.3 Category D Fluid Service (gauge pressure <150 psi, non-toxic, temperature −29°C to 186°C) requires which minimum NDE?",
"100% RT per ASME B31.3 Table 341.3.2 for all butt welds in Category D.\nVisual inspection only is sufficient per ASME B31.3 para 341.4 for Category D Fluid Service.\nMinimum 10% random RT per ASME B31.3 Table 341.3.2 for Normal Service, which also applies to Category D.\nPT or MT on all welds plus 5% RT on butt welds.",
"Visual inspection only is sufficient per ASME B31.3 para 341.4 for Category D Fluid Service.",
"ASME B31.3 para 341.4 explicitly states that for Category D Fluid Service, only visual examination is required. This is one of the most commonly misapplied provisions in the field.",
1),

(D,"mcq",
"23. An E7018 lot certification meets AWS A5.1 E7018 chemistry but does not include a Charpy impact test at −29°C. ASME B31.3 para 323.3 requires Charpy testing below −29°C. The design temperature is −10°C. What is correct?",
"Reject — Charpy testing is required regardless of design temperature for all pressure piping filler materials.\nAccept — Charpy testing of filler metals is required only when design temperature is below −29°C; −10°C is above the threshold.\nAccept with a deviation request since AWS A5.1 E7018 is prequalified for low-temperature service.\nReject — filler metal Charpy data must always be included in the MTC for ARAMCO projects.",
"Accept — Charpy testing of filler metals is required only when design temperature is below −29°C; −10°C is above the threshold.",
"ASME B31.3 impact testing triggers below −29°C (−20°F). At −10°C, impact testing of filler metals is not mandatory. Distractor A overstates the requirement.",
1),

(D,"mcq",
"24. A WPQT root bend test specimen for a 2G pipe weld shows a 4.2 mm crack on the tension surface. The bend radius was correct. What is the disposition per ASME IX QW-163?",
"Pass — 4.2 mm crack is within the 6 mm acceptance criterion in ASME IX QW-163 for root bend tests.\nFail — the 4.2 mm crack exceeds the 3 mm (1/8 in) maximum allowed per ASME IX QW-163; the welder must retest.\nFail — any crack on the tension surface is an automatic failure regardless of length.\nPass — root bend specimens have a separate acceptance criterion of 6 mm for pipe welds.",
"Fail — the 4.2 mm crack exceeds the 3 mm (1/8 in) maximum allowed per ASME IX QW-163; the welder must retest.",
"ASME IX QW-163: no open defect exceeding 3 mm (1/8 in) in any direction. A 4.2 mm crack fails. Distractor A misquotes the limit as 6 mm (which applies only to corner cracks).",
1),

(D,"mcq",
"25. During a hydrostatic hold at 1.5× design pressure (test pressure 15 bar) for 10 minutes, pressure drops from 15 bar to 14.8 bar after 8 minutes. The supervisor says 0.2 bar is within tolerance. What is the correct action?",
"Accept — a 0.2 bar drop represents less than 2% pressure loss, within ASME B31.3 hydrostatic test tolerance.\nFail the test — any pressure drop during the hold period requires investigation before acceptance; no pressure loss tolerance is defined in B31.3 for hydrostatic testing.\nContinue to 10 minutes; if pressure stabilises, accept — the initial drop may be due to temperature equalisation.\nExtend the hold to 20 minutes to compensate for minor pressure variation.",
"Fail the test — any pressure drop during the hold period requires investigation before acceptance; no pressure loss tolerance is defined in B31.3 for hydrostatic testing.",
"ASME B31.3 para 345.4.2 requires the system to maintain test pressure without leakage for the hold period. No pressure loss tolerance is codified. A pressure drop must be investigated for leakage.",
1),

(D,"mcq",
"26. Automated orbital GTAW of 316L SS tubing requires <20 ppm oxygen back-purge before root pass. The purge monitor reads 150 ppm. The crew wants to begin welding. What is the correct action?",
"Begin welding — 150 ppm is below the 500 ppm threshold typically accepted for SS purging.\nHold welding — 316L requires <20 ppm oxygen before root pass to prevent sensitisation and root oxidation (sugaring); 150 ppm is unacceptable.\nBegin welding — oxygen measurement is only a post-weld quality check, not a pre-weld hold.\nHold welding — SAES-W-011 requires 0 ppm oxygen for all SS back-purge before welding begins.",
"Hold welding — 316L requires <20 ppm oxygen before root pass to prevent sensitisation and root oxidation (sugaring); 150 ppm is unacceptable.",
"Oxygen content >20–50 ppm during SS GTAW root pass causes oxidation (sugaring), leading to intergranular corrosion. Industry best practice and SAES-W-011 require <20 ppm before commencing root pass. 150 ppm is well above this threshold.",
1),

(D,"mcq",
"27. A P91 girth weld cools to ambient temperature during a 35-minute safety evacuation. The WPS requires 200°C minimum preheat and 300°C maximum interpass. Upon return, the supervisor instructs the welder to reheat and continue. What must the QC Inspector verify first?",
"Verify only that preheat is restored to ≥200°C at the joint before the next pass.\nVerify preheat restoration to ≥200°C, inspect the partially completed weld by PT or MT for hydrogen-induced cracking developed during uncontrolled cool-down, and confirm WPS compliance for restart.\nVerify preheat only — P91 does not crack during short interruptions if PWHT will follow.\nVerify preheat and update the weld traveler; no NDT is needed unless visible cracks are present.",
"Verify preheat restoration to ≥200°C, inspect the partially completed weld by PT or MT for hydrogen-induced cracking developed during uncontrolled cool-down, and confirm WPS compliance for restart.",
"Uncontrolled cooling of a partially completed P91 weld creates significant hydrogen cold cracking risk. Simply reheating and continuing without intermediate NDT is inadequate. SAES-W-011 requires inspection of the exposed weld surface before the next pass after an unplanned cool-down.",
1),

(D,"mcq",
"28. An RT film of a pressure vessel shell seam (ASME VIII Div.1, 18 mm wall) shows a cluster of three pores — 3 mm, 2.5 mm, and 2 mm diameter — within a 12 mm band. What is the correct assessment?",
"Accept — all individual pore diameters are below 6 mm and below 1/4T (4.5 mm for this weld).\nReject — the cluster must be evaluated per ASME VIII Div.1 Appendix 4 porosity chart, and this cluster density is likely to exceed the chart allowable.\nAccept — ASME VIII permits any number of rounded indications if no single indication exceeds 1/3T.\nReject — ASME VIII mandates rejection of all porosity clusters without exception.",
"Reject — the cluster must be evaluated per ASME VIII Div.1 Appendix 4 porosity chart, and this cluster density is likely to exceed the chart allowable.",
"ASME VIII Div.1 App. 4 uses a porosity density chart that evaluates accumulated porosity within a reference length. A 3+2.5+2 mm cluster in 12 mm length must be plotted against the chart — using single-indication B31.3-style logic is inapplicable to ASME VIII pressure vessels.",
1),

(D,"mcq",
"29. The WPS requires E7018-H4R electrodes. Incoming electrodes are E7018-H4 without the 'R' suffix. What is the difference and what action is required?",
"Accept — E7018-H4 and E7018-H4R are identical; 'R' is a packaging code only.\nReject — E7018-H4R designates moisture-resistant electrodes (≤10 ml/100g after 9 hr exposure at 27°C/80% RH per AWS A5.1); without 'R', moisture resistance is unverified and the electrode does not meet the WPS requirement.\nAccept — H4 hydrogen designation is the controlling requirement; moisture resistance is a supplemental commercial designation.\nReject — E7018-H4R is required only for weld repairs, not production welds.",
"Reject — E7018-H4R designates moisture-resistant electrodes (≤10 ml/100g after 9 hr exposure at 27°C/80% RH per AWS A5.1); without 'R', moisture resistance is unverified and the electrode does not meet the WPS requirement.",
"The 'R' suffix in AWS A5.1 indicates the electrode passed a moisture-resistance test. If the WPS specifies H4R, ordinary H4 electrodes cannot be substituted without a formal deviation. Critical in humid coastal environments.",
1),

(D,"mcq",
"30. Weld Joint W-107 (DN50 nozzle-to-shell weld, ASME VIII Div.1) has no RT, UT, or PT/MT in the NDE log. What is the minimum code NDE requirement for this nozzle weld?",
"RT of the nozzle weld is mandatory per ASME VIII UW-51 for all pressure vessels regardless of nozzle size.\nFor a DN50 nozzle-to-shell connection, ASME VIII Div.1 UW-11 requires only visual inspection if the vessel is not in the fully radiographed category.\nPT or MT is required for all nozzle welds in ASME VIII regardless of vessel category.\nUT is the preferred alternative to RT for nozzle welds per ASME VIII Div.1 Appendix 12.",
"For a DN50 nozzle-to-shell connection, ASME VIII Div.1 UW-11 requires only visual inspection if the vessel is not in the fully radiographed category.",
"ASME VIII UW-11 defines RT scope by vessel category. For non-fully-radiographed vessels, small nozzle welds may require only VT. However, project specification and SAES may impose additional requirements that must also be checked.",
1),

(D,"mcq",
"31. A pipe-to-pipe girth weld fit-up (ASME B31.3) shows internal misalignment of 2.0 mm on an 8 mm wall pipe. ASME B31.3 para 328.4.2 limits hi-lo to 1.5 mm or 1/4T, whichever is less. What is the finding?",
"Accept — 2.0 mm misalignment is within the 2 mm hi-lo commonly accepted in ARAMCO field practice.\nReject — 2.0 mm exceeds the governing limit of 1.5 mm (which is less than 1/4T = 2 mm); re-fit-up is required.\nAccept — 2.0 mm equals 1/4 × 8 mm = 2 mm and is within one of the two acceptance criteria.\nReject only if the misalignment is detectable on the RT film.",
"Reject — 2.0 mm exceeds the governing limit of 1.5 mm (which is less than 1/4T = 2 mm); re-fit-up is required.",
"The limit is 1.5 mm or 1/4T, whichever is LESS. 1/4T = 2 mm; 1.5 mm < 2 mm; therefore 1.5 mm governs. 2.0 mm > 1.5 mm → reject fit-up. Distractor C misapplies 'whichever is less' to mean either criterion can be used.",
1),

(D,"mcq",
"32. Fifteen P22 welds were completed using an unapproved WPS over 6 days. The welds have passed RT. What is the correct immediate action?",
"Issue an NCR, halt all further welding on these joints, quarantine all 15 welds, and initiate a formal disposition process.\nAccept the welds since RT shows acceptable quality and the WPS has since been approved.\nRequest a weld procedure deviation from the client to allow a retrospective approval.\nConduct PT on each weld and accept if no surface defects are found.",
"Issue an NCR, halt all further welding on these joints, quarantine all 15 welds, and initiate a formal disposition process.",
"Welding without a valid approved WPS is a major procedural nonconformance. NDT results do not retroactively validate procedural compliance. All 15 welds must be quarantined and formally dispositioned.",
1),

(D,"mcq",
"33. A PWHT soak record shows TC1–TC5 on the weld/HAZ at 720°C while TC6 on the base metal 300 mm from the weld reads 650°C. The required minimum is 700°C. Which thermocouple set governs PWHT compliance?",
"650°C — the lowest recorded temperature on any thermocouple governs compliance.\n720°C — TC1–TC5 on the weld and HAZ govern; TC6 at 300 mm is outside the heated band and is a gradient monitoring point only.\n700°C — the specification minimum is the benchmark; since TC1–TC5 met 720°C the PWHT is compliant.\n710°C — the average of the lowest weld TC and TC6 is used for reporting.",
"720°C — TC1–TC5 on the weld and HAZ govern; TC6 at 300 mm is outside the heated band and is a gradient monitoring point only.",
"ASME VIII Div.1 Appendix 49 and SAES-W-011 require the weld, HAZ, and adjacent base metal within the heated band to achieve minimum temperature. TC6 at 300 mm is beyond the required soak band and serves as a gradient monitoring point, not a compliance thermocouple.",
1),

(D,"mcq",
"34. An RT film shows a density of 4.3 H&D. The procedure requires 1.8–4.0 H&D for Class II radiography. What is the correct action?",
"Accept — 4.3 H&D is close to 4.0 and within densitometer measurement uncertainty.\nReject the film — 4.3 H&D exceeds the 4.0 maximum; the film is too dark for reliable defect detection and must be retaken.\nAccept — Class II radiography density limits are guidelines, not absolute requirements.\nAccept — if IQI sensitivity is confirmed adequate, density above 4.0 does not affect film acceptance.",
"Reject the film — 4.3 H&D exceeds the 4.0 maximum; the film is too dark for reliable defect detection and must be retaken.",
"Maximum film density is a hard acceptance limit. Film at 4.3 H&D is too dark for reliable indications to be detected. The film must be retaken at reduced exposure. IQI sensitivity is a separate criterion and does not override the density limit.",
1),

(D,"mcq",
"35. A WPS for 9% Ni steel A333 Gr.8 cryogenic service at −196°C is proposed using a 1G PQR test. Beyond standard ASME IX PQR mechanical tests, what additional testing is specifically required?",
"Charpy V-notch impact tests at −196°C on weld metal and HAZ specimens to verify notch toughness at design temperature.\nHardness survey per AWS D1.1 Table 4.5 for all weld zones.\nChemical analysis of PQR coupon weld metal only.\nMinimum 10% elongation test on weld metal tensile specimen only.",
"Charpy V-notch impact tests at −196°C on weld metal and HAZ specimens to verify notch toughness at design temperature.",
"For cryogenic 9% Ni steel service at −196°C, impact testing at design temperature is mandatory. SAES-W-011 and project specifications for LNG service require CVN tests at −196°C minimum. Standard ASME IX PQR alone is insufficient.",
1),

(D,"mcq",
"36. After a hydrostatic test, a leak is found at W-55 — a weld that had been released based on RT showing no recordable indications. A 2 mm through-crack was oriented parallel to the RT beam. What is the primary lesson?",
"The RT technique was inadequate — RT cannot detect cracks parallel to the beam; supplementary angle-beam UT or PAUT should have been specified.\nThe RT film was processed incorrectly — correct processing would have revealed the crack.\nThe WPS was deficient — proper PWHT would have prevented the crack from forming.\nThe hydrostatic test was the root cause — pressure testing should not be used on welds without prior UT.",
"The RT technique was inadequate — RT cannot detect cracks parallel to the beam; supplementary angle-beam UT or PAUT should have been specified.",
"RT has a fundamental limitation: it cannot reliably detect planar defects oriented parallel to the beam. For applications where crack detection is critical, complementary methods (UT angle beam, PAUT) are required per ASME V and SAEP-1142.",
1),

(D,"mcq",
"37. A WIR for Weld W-88 was signed by an inspector whose CSWIP Level II certification expired 2 months before the weld date. What must be done?",
"Issue an NCR, invalidate the WIR for W-88, and arrange for a currently certified inspector to review the original RT films and re-sign where technically defensible.\nAccept the WIR — the physical inspection was performed correctly regardless of certification status of the signatory.\nIssue a document correction note (DCN) substituting the certifier's name without reissuing the WIR.\nReject the weld and re-weld — the invalid certification taints all NDT findings.",
"Issue an NCR, invalidate the WIR for W-88, and arrange for a currently certified inspector to review the original RT films and re-sign where technically defensible.",
"Inspection records signed by uncertified individuals are invalid. If original RT films exist and are interpretable, a certified inspector may formally re-review and re-issue the record. Re-welding is not required if physical evidence is intact and reviewable.",
1),

(D,"mcq",
"38. XRF of an E9018-B3 electrode coating shows Cr = 2.1%. The MTC specifies Cr = 2.25–2.75%. Is the result acceptable?",
"Accept — XRF on electrode coating is not representative of weld metal chemistry; only weld deposit analysis applies.\nReject — Cr of 2.1% is below the MTC minimum of 2.25%, indicating possible grade mix-up requiring investigation.\nAccept — 2.1% Cr is within typical ±10% XRF measurement uncertainty for coated electrodes.\nReject — SAES-W-011 requires PMI to match the exact nominal MTC value, not a range.",
"Reject — Cr of 2.1% is below the MTC minimum of 2.25%, indicating possible grade mix-up requiring investigation.",
"A reading of 2.1% Cr vs. a 2.25% minimum on the MTC is a meaningful low signal suggesting possible grade mix-up. The correct action is to flag for investigation rather than accepting on XRF uncertainty grounds alone.",
1),

(D,"mcq",
"39. A pre-weld full-penetration T-joint fit-up for structural steel shows: root opening 3 mm (WPS range 0–3 mm); groove angle 42° (specified 45° ±5°). Is the fit-up acceptable per AWS D1.1 prequalified joint tolerances?",
"No — both conditions are on boundary limits and require documented engineering approval before proceeding.\nYes — 3 mm root opening and 42° groove angle are both within prequalified tolerances and the fit-up is acceptable.\nNo — AWS D1.1 requires groove angles to be exactly as specified; any deviation requires re-cutting.\nYes — root opening at maximum is acceptable only when groove angle is also at maximum.",
"Yes — 3 mm root opening and 42° groove angle are both within prequalified tolerances and the fit-up is acceptable.",
"AWS D1.1 Table 3.1: groove angle tolerance is ±5° (40°–50° for a 45° joint). 42° is within tolerance. 3 mm root opening is at the specified maximum of 0–3 mm — within range. Both conditions meet prequalified joint tolerances.",
1),

(D,"mcq",
"40. A welder performing a 6G position SMAW weld at 220 A is using a shade No. 8 helmet lens instead of the WPS-specified minimum shade No. 10. What is the correct action?",
"Stop the welder immediately — shade No. 8 is insufficient protection at 220 A, risking arc flash eye injury; correct PPE must be in place before welding resumes.\nAllow the welder to continue — shade selection is a personal preference with no impact on weld quality.\nIssue a safety observation card and allow welding to continue until the end of the current pass.\nRequest the safety officer to address the issue; the QC Inspector's authority is limited to weld quality.",
"Stop the welder immediately — shade No. 8 is insufficient protection at 220 A, risking arc flash eye injury; correct PPE must be in place before welding resumes.",
"SAES-W-011, ARAMCO GI-150.100, and QC inspector stop-work authority cover safety violations. Inadequate eye protection is both a safety hazard and a quality risk (poor arc visibility leads to weld defects). The inspector must intervene immediately.",
1),

# ── ESSAY 1–20 ───────────────────────────────────────────────────────────────

(D,"essay",
"1. During routine QC surveillance you discover 15 P22 pipe spool welds were completed using an unapproved WPS over 6 days. The welds passed RT. Develop a complete NCR response: (a) containment scope and immediate actions; (b) root cause analysis methodology; (c) ARAMCO and ASME IX implications; (d) disposition options with technical justification; (e) corrective and preventive actions.",
"","",
"Grade on: Correct quarantine scope (all 15 welds), structured RCA (5-Why or fishbone), understanding that RT acceptance does not retroactively validate procedural non-compliance, exploration of disposition options (reject/repair, client concession with risk assessment, retrospective WPS approval where permissible), systemic corrective actions targeting the process control breakdown.",
20),

(D,"essay",
"2. A QC audit reveals that 3 approved WPSs cover a fabrication shop, but 7 distinct material-process combinations are being used in production. Describe your approach to: (a) identifying all WPS coverage gaps; (b) assessing risk to welds already completed; (c) prioritising requalification efforts; (d) managing the transition without excessive schedule impact.",
"","",
"Grade on: Systematic gap analysis (WPS-PQR matrix), link to in-service risk (safety class, fluid service, pressure), understanding of ASME IX essential variables, realistic risk communication to client, ARAMCO project specification compliance path.",
20),

(D,"essay",
"3. A P91 pressure piping girth weld fails PWHT acceptance (HAZ hardness HV10 = 310 vs. maximum 248). The weld is already pressure-tested and insulated. Develop a complete corrective action plan: (a) immediate containment; (b) hardness root cause investigation; (c) re-PWHT vs. cut-and-replace options; (d) implications for similar welds in the system.",
"","",
"Grade on: Understanding P91 hard-zone failure modes (creep, SSC), re-PWHT feasibility (cycle count limits), requirement to evaluate all P91 welds from the same batch/welder/WPS, impact on system pressure test re-execution.",
20),

(D,"essay",
"4. During an electrode traceability audit of 50 E316L electrodes (MTC heat 2024-XYZ), 12 in-use electrodes cannot be cross-referenced to that heat. Describe: (a) your audit trail steps; (b) how you handle the traceability break; (c) disposition options; (d) recurrence prevention.",
"","",
"Grade on: Systematic audit trail (receiving records → storage log → issue log → use log), understanding that unverified filler materials are nonconforming, correct disposition sequence (quarantine → investigate → PMI → accept/reject), corrective actions targeting material management procedures.",
20),

(D,"essay",
"5. An NDT subcontractor's Level II RT technician has been signing films for 3 weeks. A client Level III oversight review finds 6 films with missed recordable indications. Describe: (a) immediate actions; (b) scope of film re-review; (c) implications for already-released welds; (d) personnel and certification management steps.",
"","",
"Grade on: Re-review scope (all films signed by this technician since last confirmed accurate review), quarantine of released welds pending re-review, escalation to client, NCR scope, assessment of technician's Level II certification validity, systemic NDT quality oversight improvements.",
20),

(D,"essay",
"6. A sour service pipeline project requires low-hydrogen process per SAES-W-011. Post-audit you find 8 root passes were deposited using E6010 (cellulosic) electrodes over the past month. Welds passed RT and visual inspection. Describe your complete NCR management and disposition approach.",
"","",
"Grade on: NACE MR0175 / ISO 15156 SSC risk from cellulosic H > 15 ml/100g, understanding that E6010 root cannot be adequately dispositioned for sour service without removal (cut-and-replace), client notification protocol, system-wide risk assessment for all sour service welds from same period.",
20),

(D,"essay",
"7. Welder continuity logs have not been maintained for 3 months at a vendor facility. Multiple welders are working on P5B (9Cr-1Mo) pressure piping. Describe: (a) immediate actions to establish qualification status; (b) handling welds made during the lapse; (c) corrective actions; (d) documentation requirements.",
"","",
"Grade on: ASME IX QW-322 — without records, qualification cannot be confirmed; options for requalification testing; welds placed on hold pending disposition; client notification; systemic corrective actions for welder qualification management.",
20),

(D,"essay",
"8. A WPS qualifies SMAW for P-No.1 carbon steel based on a 13 mm PQR test coupon. A production joint requires 38 mm thick carbon steel plates. Explain: (a) whether the WPS covers this joint; (b) which ASME IX essential variables are at issue; (c) additional testing for a new PQR; (d) SAES-W-011 supplementary requirements.",
"","",
"Grade on: ASME IX QW-451 — 13 mm PQR qualifies up to 2T = 26 mm for P-No.1; 38 mm exceeds range; identification of essential vs. supplementary essential variables; new PQR testing requirements (tensile, bend, macro, potentially impact); SAES-W-011 requirements for heavy-wall carbon steel.",
20),

(D,"essay",
"9. A 316L SS piping system for a seawater lift pump experiences weld HAZ cracking 18 months after commissioning. Lab analysis shows intergranular corrosion (IGC). Conduct an RCA and describe: (a) the metallurgical mechanism; (b) how the QC programme failed to prevent it; (c) inspection techniques that could have indicated risk during construction; (d) long-term corrective actions.",
"","",
"Grade on: Sensitisation (Cr carbide precipitation) due to excessive heat input or inadequate back-purge during welding, critique of QC programme gaps (purge O₂ monitoring, heat input control, post-weld solution anneal requirements), detection options (ASTM A262, electrochemical potentiodynamic reactivation).",
20),

(D,"essay",
"10. A PQR test for P91 pipe welding used a 25 mm coupon, but production requires welds on 63 mm wall pipe. Describe: (a) your assessment of WPS coverage per ASME IX; (b) additional data the welding engineer must provide; (c) temper-bead requirements if applicable; (d) PWHT considerations for thick-wall P91.",
"","",
"Grade on: ASME IX QW-451 range — some editions allow 25 mm PQR to qualify up to 200 mm for P91, but qualitative risks differ significantly at 63 mm (heat input, gradient control, temper bead, PWHT gradient); candidate should flag metallurgical risks even if the code range is technically met.",
20),

(D,"essay",
"11. A P5B 6G WPQT root bend fails. The supervisor claims the specimen was machined 3.2 mm thick instead of the required 3.8 mm. Describe: (a) whether the machining error invalidates the test; (b) what options exist; (c) how to manage the welder's active production welds.",
"","",
"Grade on: ASME IX QW-160/QW-180 — incorrect specimen dimensions are a test execution error that may affect outcome; the test should be re-run with correctly machined specimens; active production welds placed on hold pending retest; if retest passes, welds released; if fails, NCR and disposition of production welds.",
20),

(D,"essay",
"12. Describe the complete QC documentation package required to close out a single pressure piping girth weld from fit-up through final release for pressure testing per SAES-W-011 and SAEP-1150. Include all hold points, witness points, and mandatory records.",
"","",
"Grade on: Completeness — joint detail/WPS reference, fit-up record (hi-lo, gap, alignment), preheat record, weld traveler/rod issue sheet, in-process inspection records (root, hot pass, fill, cap), PWHT chart, NDE reports, hardness records, visual inspection sign-off, material traceability (base metal + filler + consumables).",
20),

(D,"essay",
"13. The contractor proposes local PWHT using flexible ceramic resistance pads for all P-No.4 chrome-moly butt welds. Evaluate: (a) adequacy vs. furnace PWHT; (b) thermocouple placement requirements; (c) heating band width and gradient control; (d) documentation and acceptance criteria.",
"","",
"Grade on: ASME VIII Div.1 Appendix 49 local PWHT — heated band ≥ 1 in beyond weld each side (or per SAES-W-014), thermocouple placement on weld/HAZ/gradient zone, maximum gradient (25°C/25 mm), cooling rate limits above 315°C, all TC channels recorded with time-temperature traces.",
20),

(D,"essay",
"14. You are auditing a welding subcontractor's filler material management system. Describe audit scope, checklist items, and critical compliance criteria for: (a) receiving inspection; (b) storage and handling; (c) issue and return control; (d) traceability to individual welds.",
"","",
"Grade on: Receiving (MTC verification, heat/lot number, dimensional check, visual); storage (LH oven temperatures, humidity, segregation); issue control (rod issue log with quantity, heat number, WPS reference, joint number, welder ID); return and reconditioning procedures for LH electrodes.",
20),

(D,"essay",
"15. A TOFD scan of a 40 mm thick pressure vessel seam shows a laterally diffracted signal 3–5 mm from the OD surface, 15 mm long. Describe: (a) interpretation of this signal type; (b) TOFD near-surface limitations; (c) supplementary NDE you would specify; (d) characterisation and disposition per ASME VIII.",
"","",
"Grade on: TOFD near-surface dead zone (2–5 mm from each surface); near-surface indication at 3 mm may be in the dead zone and unreliable; supplementary techniques (PAUT with encoded scan, PT/MT for OD surface); ASME VIII Appendix 12 UT acceptance criteria for sized indications.",
20),

(D,"essay",
"16. A completed duplex SS 2205 pipe weld fails ferrite testing at 68 FN (project limit 35–65 FN). Describe: (a) implications of high ferrite for in-service performance; (b) probable causes; (c) additional testing required; (d) disposition options.",
"","",
"Grade on: High ferrite → sigma phase embrittlement at >300°C and increased pitting risk; causes include excessive dilution, wrong filler, or insufficient heat input; additional testing — impact (ASTM A923), corrosion (ASTM G48), microstructural examination; disposition — weld removal and replacement is typically the only safe option.",
20),

(D,"essay",
"17. An ITP audit finds 100% of girth welds signed off by the contractor QC Inspector with no evidence of ARAMCO PMC Inspector countersignature over 2 weeks. Describe your investigation, implications, and corrective actions.",
"","",
"Grade on: ARAMCO/PMC hold points are mandatory — bypass is a major nonconformance; investigation to determine bypass scope; all affected welds quarantined pending PMC review; systemic review of ITP enforcement; contractor QC management accountability.",
20),

(D,"essay",
"18. Compare ASME B31.3 weld acceptance criteria for Normal Fluid Service vs. Severe Cyclic Service for: (a) undercut; (b) weld reinforcement; (c) linear indications; (d) porosity. Explain the engineering rationale for the differences.",
"","",
"Grade on: Severe Cyclic is more restrictive — undercut ≤0.4 mm (vs. 0.5 mm Normal); tighter reinforcement height; same zero tolerance for LOF/cracks; potentially zero porosity acceptance in some editions; engineering rationale: cyclic loading drives fatigue crack initiation at stress concentrators — geometric defects tolerable under static load become critical under cyclic stress.",
20),

(D,"essay",
"19. A client representative issues a Stop Work Order on 50 weld joints because welding machine calibration records cannot be found. The contractor argues machine calibration is not mandatory per ASME IX. Describe how you investigate and resolve this conflict.",
"","",
"Grade on: ASME IX does not require welding machine calibration as a WPS/PQR condition, but SAES-W-011 and the project ITP may impose it; if ITP designates it as a hold point, the SWO is valid; resolution: locate calibration records; assess whether machine performance was actually compromised; issue NCR for procedural lapse; reach a disposition on welds with missing calibration evidence.",
20),

(D,"essay",
"20. You discover that hydrotest water used on P91 creep-resistant piping had uncontrolled chloride content, and the piping sat water-filled for 3 months before draining. Describe: (a) potential damage mechanisms; (b) required inspections; (c) implications for system life assessment.",
"","",
"Grade on: Chloride SCC risk for martensitic P91; MIC (microbiologically influenced corrosion) under stagnant conditions; required inspections: VT, PT, UT thickness at low points and dead legs; potential for internal pitting corrosion; life assessment: any confirmed Cl-induced crack is rejectable and may require replacement.",
20),

# ── ORAL 1–20 ────────────────────────────────────────────────────────────────

(D,"oral",
"1. The production supervisor tells you stopping the welder for missing preheat documentation will delay the project 2 days and cost $50,000. He asks you to accept the weld and document it later. Walk me through exactly what you say and do.",
"","",
"Grade on: Professional firmness — explain that releasing work without required documentation is a QC system failure, not a documentation delay; offer to escalate to the QC Manager for rapid disposition; explain that retrofitted documentation is not equivalent to contemporaneous records; cite SAEP-1150 or ITP hold-point requirements; no compromise on procedural integrity regardless of cost pressure.",
10),

(D,"oral",
"2. Without using a code book, explain the difference between a WPS, a PQR, and a WPQ under ASME IX — and why ARAMCO requires all three on file before welding begins.",
"","",
"Grade on: WPS — document specifying HOW to weld; PQR — test record proving the WPS produces acceptable mechanical properties; WPQ — test record proving the individual welder can execute the WPS; ARAMCO requires all three because WPS without PQR is unvalidated, and WPS+PQR without WPQ means no individual competency proof.",
10),

(D,"oral",
"3. You arrive at a P91 girth weld mid-root pass and notice the welder has no calibrated contact thermometer and is checking preheat by spitting on the pipe. What do you do?",
"","",
"Grade on: Immediate stop-work for P91 root pass without verified preheat — P91 requires 200°C minimum; spitting is not an accepted method; quarantine the partially completed weld; issue NCR; determine preheat status at tacking and whether root is compromised; ensure a calibrated instrument is provided before any resumption.",
10),

(D,"oral",
"4. Without looking at a code, explain what an 'essential variable' is in the context of WPS qualification and give three examples for SMAW.",
"","",
"Grade on: Essential variable = a change that requires a new PQR test coupon; examples include: change in base metal P-number, change in filler metal F-number, change in PWHT (PWHT to no-PWHT or vice versa), major thickness changes outside the qualified range. Candidate should show conceptual understanding, not just memorised lists.",
10),

(D,"oral",
"5. You find an RT film with a 6 mm linear indication at the fusion line called 'slag' and accepted by the radiographer. The film shows it as very dark (dense) and sharp-edged. What do you do?",
"","",
"Grade on: Dark, sharp-edged linear indication at the fusion line is more consistent with LOF than slag. Per B31.3, any indication characterised as or suspected to be LOF is rejectable regardless of size. Inspector should either conservatively reject or request Level III review — accepting on the radiographer's call without independent verification is inadequate.",
10),

(D,"oral",
"6. How do you verify that a PWHT temperature chart recorder is producing reliable data before accepting a PWHT cycle record?",
"","",
"Grade on: Calibration certificate must be current; span check (verify chart scale accuracy); thermocouple identification — each TC channel labelled and mapped to weld/HAZ locations; drift check — TC readings consistent with adjacent TCs within expected gradients; time marker synchronisation — chart speed calibration; verify TC physical attachment.",
10),

(D,"oral",
"7. A newly arrived welder presents a WPQ test certification card from a previous employer showing 6G qualification. What do you check before allowing him to weld on ARAMCO production?",
"","",
"Grade on: Card alone is insufficient — obtain original WPQ records; verify 6-month continuity (documented welding date); confirm process, F-number, P-number, and position match production requirements; verify certifying body is ARAMCO-acceptable; consider requiring a test weld or initial weld under close observation per SAES-W-011 for new welders on project.",
10),

(D,"oral",
"8. Describe step-by-step how you proceed from being assigned to inspect a girth weld to signing the release for pressure testing.",
"","",
"Grade on: Pre-weld (WPS, WPQ, material certs, joint dimensions, cleanliness, preheat); in-process (rod control, preheat continuity, interpass temperature, pass sequence, PWHT if required); post-weld (visual per ASME V Art.9, NDT per ITP, hardness if required, dimensional check); documentation (WIR, NDT reports, preheat records, PWHT charts compiled and signed); release for hydrotest based on complete documentation.",
10),

(D,"oral",
"9. The NDT technician tells you the radiograph shows 'no recordable indications.' Independently, how do you verify this conclusion is credible without interpreting the film yourself?",
"","",
"Grade on: Verify film quality independently — check density (densitometer), IQI/penetrameter visible and correctly placed (right side of source, correct designation for weld thickness), film coverage, identification markers. If any of these fail, the film is invalid regardless of interpretation. Inspector should not blindly rely on technician's assessment.",
10),

(D,"oral",
"10. A welder completes a weld and immediately begins grinding the cap without your presence. When you arrive the original profile is altered. What are the implications and what do you do?",
"","",
"Grade on: Grinding without inspection presence invalidates the visual inspection hold point; original weld surface evidence is destroyed; possible concealment of defects; issue NCR; document timeline; notify QC management; assess whether post-grinding NDT (RT/UT) can still detect subsurface defects; consider enhanced NDE requirements for this weld.",
10),

(D,"oral",
"11. What is hydrogen cracking and why is it particularly relevant for P91 pipe welds?",
"","",
"Grade on: HIC/cold cracking occurs when: susceptible microstructure (martensite in HAZ) + hydrogen (from moisture, cellulosic electrodes, contaminated gas) + tensile residual stress are all present simultaneously; P91 is particularly susceptible because its as-welded martensitic microstructure has very high hydrogen susceptibility; preheat and controlled interpass temperature are primary preventions; delayed cracking can occur hours after welding.",
10),

(D,"oral",
"12. You review a film that a Level II technician has accepted. You identify what appears to be a 3 mm linear indication near the weld toe. What is your next step?",
"","",
"Grade on: As a QC inspector (typically not a qualified NDT technician), correct action is to formally bring the film to the Level II technician's attention in writing, request a documented second review; if technician maintains acceptance, escalate to Level III for independent interpretation; do not release the weld until the indication is formally reviewed and dispositioned.",
10),

(D,"oral",
"13. Explain why socket welds are not typically used in severe cyclic service or when full radiographic examination is required.",
"","",
"Grade on: Socket welds have a gap between pipe end and socket bottom — a crevice that traps corrosive media; the joint creates a stress concentration at the weld root; full RT of a socket weld root is technically impossible (geometry prevents imaging of the root); for severe cyclic service, the notch at the weld root initiates fatigue cracks; ASME B31.3 restricts socket welds in severe cyclic service.",
10),

(D,"oral",
"14. The contractor QC Manager says an NCR you issued for a failed PWHT is 'invalid' because a certified PWHT company performed the work. How do you respond?",
"","",
"Grade on: Certification of the PWHT company does not exempt the work from compliance with the approved WPS and project specification; if results (temperature, time, TC placement) do not meet required parameters, the PWHT is nonconforming regardless of who performed it; NCR remains valid; request formal disposition through the NCR process; escalate to PMC if contractor refuses.",
10),

(D,"oral",
"15. What is delta ferrite and why does SAES-W-011 require a minimum ferrite level in austenitic stainless steel weld metal?",
"","",
"Grade on: Delta ferrite is a BCC ferrite phase in austenitic SS weld metal; it forms during solidification and prevents hot cracking (solidification cracking) by providing grain boundary barriers; SAES-W-011 minimum (typically 4–8 FN) ensures hot cracking resistance while avoiding excessive ferrite that causes sigma phase embrittlement at elevated temperatures; measured using a Ferrite Number meter calibrated to WRC-1992.",
10),

(D,"oral",
"16. During a site audit you find E7018 electrodes in open cardboard boxes exposed to the humid Saudi coastal environment for 48 hours. What immediate action do you take and what are the subsequent steps?",
"","",
"Grade on: Quarantine all exposed E7018 electrodes; check oven availability and temperature (holding 65°C–120°C per AWS A5.1); electrodes exposed >4 hours must be redried (350°C–430°C for 1 hour per AWS A5.1, maximum two re-drying cycles); identify all joints welded with this batch since last confirmed storage verification; issue NCR; corrective action for filler material storage procedures.",
10),

(D,"oral",
"17. You observe arc strikes adjacent to a completed weld on the base metal. What is the significance and what action is required?",
"","",
"Grade on: Arc strikes create localised hard spots (untempered martensite) in base metal HAZ due to rapid self-quenching; susceptible to HIC and corrosion in sour or cyclic service; ASME B31.3 and SAES-W-011 require removal by grinding to bare metal followed by PT or MT to verify complete removal and absence of cracks; ground area must remain within base metal thickness tolerance.",
10),

(D,"oral",
"18. You are called because a pneumatic pressure test on a P91 pipe spool discovered a leak at a weld. The test was supposed to be a hydrostatic test. What are your immediate safety and quality actions?",
"","",
"Grade on: SAFETY FIRST — pneumatic testing stores far more energy than hydrostatic; immediate evacuation of exclusion zone, isolate and depressurise safely, notify safety officer and QC Manager; after safe depressurisation: assess weld failure mode (crack vs. porosity), issue NCR, determine why hydro procedure was not followed, do NOT re-pressurize until comprehensive assessment complete.",
10),

(D,"oral",
"19. What is the significance of the 'F-number' of a filler metal in ASME IX and how does it affect welder qualification portability?",
"","",
"Grade on: F-number groups filler metals by usability characteristics per ASME IX QW-432; a welder qualified on one filler metal is qualified for all others in the same F-number; portability: a welder qualified on F4 (E7018) is not automatically qualified for F3 (E6010) — different F-number requires requalification; important when electrodes are substituted due to supply chain issues.",
10),

(D,"oral",
"20. A senior welding foreman tells you 'We've been doing this for 30 years and never had a failure. Your inspection is slowing us down.' How do you professionally handle this situation?",
"","",
"Grade on: Acknowledge expertise respectfully without compromising standards; explain that personal experience and quality systems serve different purposes — ITP/SAES requirements protect them as much as the client; offer to discuss ITP optimisation through proper channels (witness vs. hold review); maintain stop-work authority if a mandatory hold point is being challenged; escalate appropriately if pressure continues.",
10),

# ── PRACTICAL 1–20 ───────────────────────────────────────────────────────────

(D,"practical",
"1. You receive a P91 PWHT chart showing: ramp rate 120°C/hr (spec max 100°C/hr); soak at TC1=745°C, TC2=748°C, TC3 (HAZ)=728°C for 2 hours (spec 730°C–760°C minimum 2 hours); cooling rate 200°C/hr above 300°C (spec max 200°C/hr). Evaluate the chart and state your findings with code references.",
"","",
"Grade on: (1) Ramp rate 120°C/hr > 100°C/hr limit — FAIL (NCR required); (2) TC3 at 728°C < 730°C minimum — the entire 2-hour soak is invalid because all monitored weld-zone points must simultaneously achieve minimum temperature — FAIL; (3) Cooling rate at limit (200°C/hr) — PASS but note boundary condition. Overall: PWHT FAILS on two counts. Both require NCR and repeat PWHT.",
15),

(D,"practical",
"2. Review this WPS for a P22 (P-No.5A) GTAW sour service application and identify all missing or nonconforming items: Process: GTAW; Base metal: A335 P22; Filler: ER90S-B3; Shielding: Argon 99.99%; Preheat: 150°C; Interpass max: 350°C; PWHT: None (PQR performed without PWHT).",
"","",
"Grade on: (1) PWHT absent — SAES-W-011 mandates PWHT for P5A in sour service regardless of B31.3 thickness threshold; (2) PQR without PWHT — essential variable change under ASME IX QW-407; new PQR required; (3) Preheat 150°C — SAES-W-011 requires 200°C minimum for P22 >19 mm; (4) Sour service hardness acceptance criteria not referenced in WPS.",
15),

(D,"practical",
"3. An RT film of a 12 mm wall CS butt weld (ASME B31.3 Normal Fluid Service) shows: density 2.4 H&D; IQI 2-2T hole visible; Indication 1: 5 mm rounded pore at centreline; Indication 2: 8 mm linear indication at fusion line. State your finding for each item.",
"","",
"Grade on: (1) Density 2.4 — within 1.8–4.0 range — ACCEPTABLE; (2) IQI 2-2T — verify correct designation for 12 mm per ASME V T-276; if correct, ACCEPTABLE; (3) 5 mm rounded pore — 1/4T = 3 mm, 6 mm max; 5 mm > 3 mm — REJECT; (4) 8 mm linear at fusion line — LOF suspected — REJECT regardless of size.",
15),

(D,"practical",
"4. Verify the following A335 P91 MTC against ASTM A335 Grade P91 requirements: C=0.11%, Si=0.38%, Mn=0.45%, P=0.012%, S=0.005%, Cr=8.8%, Mo=0.95%, V=0.21%, Nb=0.08%, N=0.048%, Al=0.005%. State acceptance or rejection for each element and overall MTC status.",
"","",
"Grade on: ASTM A335 P91 limits — C 0.08–0.12 ✓; Si 0.20–0.50 ✓; Mn 0.30–0.60 ✓; P ≤0.020 ✓; S ≤0.010 ✓; Cr 8.00–9.50 ✓; Mo 0.85–1.05 ✓; V 0.18–0.25 ✓; Nb 0.06–0.10 ✓; N 0.030–0.070 ✓; Al ≤0.040 ✓. All within limits — MTC ACCEPTABLE. Candidate should also note need for heat treatment, tensile, and impact verification.",
15),

(D,"practical",
"5. A WPQT bend test record shows: Face Bend 1 — no cracks; Face Bend 2 — 2.8 mm crack on tension surface; Root Bend 1 — 1.5 mm corner crack; Root Bend 2 — 4.2 mm crack on tension surface. Per ASME IX QW-163, evaluate each result and state the overall qualification outcome.",
"","",
"Grade on: QW-163 limit — no open defect >3 mm (1/8 in) in any direction; corner cracks ≤6 mm acceptable. Face Bend 1: PASS; Face Bend 2: 2.8 mm < 3 mm — PASS; Root Bend 1: 1.5 mm corner crack ≤6 mm — PASS; Root Bend 2: 4.2 mm > 3 mm — FAIL. Overall: FAIL — welder must retest.",
15),

(D,"practical",
"6. Review this P91 pipe weld ITP and identify any missing or incorrectly designated hold/witness points: (a) Fit-up — Contractor QC only; (b) Preheat verification — Contractor QC + ARAMCO Witness; (c) Root pass visual — Contractor QC only; (d) PWHT — Contractor QC + ARAMCO Hold; (e) RT — Contractor QC + ARAMCO Review; (f) Hardness testing — not listed.",
"","",
"Grade on: (a) Fit-up for P91 — ARAMCO should be minimum witness, not contractor only; (b) Preheat witness — appropriate; (c) Root pass for P91 — should be ARAMCO witness at minimum; (d) PWHT hold — correct; (e) RT review — appropriate; (f) Hardness not listed — MISSING — SAES-W-011 mandatory for P91 sour service; must be added as witness or hold. Candidate identifies missing hold point and under-specified designations.",
15),

(D,"practical",
"7. Review this WIR for Weld W-201 and flag all discrepancies: WPS No.: WPS-P91-01; Welder ID: WLD-007; Base Metal Heat No.: BM-4477; Filler Heat No.: FM-2288; Preheat (°C): 205; Interpass Max (°C): Not recorded; PWHT: Attached (Chart No. PWHT-201); RT Report No.: NDT-RT-1055; Inspector Signature: J. Smith; Certification: CSWIP 3.1 (Exp: 2025-03); Weld Date: 2025-11-15.",
"","",
"Grade on: (1) Interpass max not recorded — procedurally required, critical for P91; (2) Certification expired 2025-03, weld date 2025-11-15 — expired 8 months at inspection — INVALID WIR, must be reissued; (3) PWHT chart attached — verify chart is for this specific weld; (4) Hardness test record missing — mandatory for P91; (5) No PT/MT of root pass record — check if required by ITP.",
15),

(D,"practical",
"8. A production welding log shows welder WLD-012 deposited 42 welds in January using SMAW on carbon steel. His WPQ last official continuity entry was 7 months ago. The QC Manager states WLD-012 is qualified because he welded throughout January. Evaluate whether this qualification is valid.",
"","",
"Grade on: ASME IX QW-322.1 — qualification remains in effect if the welder has used the qualified process within the preceding 6 months. The 7-month official record gap is the compliance concern — January weld log suggests activity but must be cross-referenced with official continuity log to confirm process matches the WPQ process. Official continuity log lapse at 7 months triggers re-establishment of qualification status through a requalification test.",
15),

(D,"practical",
"9. Examine this PQR and determine if it can support the proposed WPS: PQR — P-No.1 Gr.1 (A106 Gr.B), 10 mm, GTAW, 2G, ER70S-2 (F-6 A-1), no PWHT, no impact. Proposed WPS — P-No.1 Gr.2 (A106 Gr.C), 22 mm, GTAW, 5G, PWHT required, impact testing required at −29°C.",
"","",
"Grade on: (1) P-No.1 Gr.1 PQR covers Gr.2 — OK; (2) 10 mm PQR qualifies up to 20 mm (2T) — 22 mm EXCEEDS range — new PQR needed; (3) 2G does not cover 5G — essential variable — new PQR needed; (4) No PWHT to PWHT — essential variable QW-407 — new PQR needed; (5) No impact to impact required — supplementary essential variable — new PQR needed. Overall: PQR does NOT support this WPS.",
15),

(D,"practical",
"10. You inspect the electrode storage area and observe: (a) E7018-H4R in holding oven at 55°C; (b) E6010 in a closed toolbox; (c) E309L-16 SS electrodes in the same oven as E7018 at 55°C; (d) A batch of E7018 with no MTC or heat number tag. Identify each nonconformance with corrective action.",
"","",
"Grade on: (a) Oven at 55°C — AWS A5.1 holding requirement is 65°C–120°C; 55°C too low — raise temperature immediately; (b) E6010 in toolbox — cellulosic electrodes do not require oven storage — acceptable if no moisture exposure; (c) E309L-16 in E7018 oven — cross-contamination and traceability risk; separate storage required; (d) E7018 with no MTC/heat number — quarantine for use; must establish traceability before release.",
15),

(D,"practical",
"11. Evaluate these 316L SS GTAW root oxidation colours and state acceptability for a sour service application: (a) Silver/white metallic; (b) Light straw/golden; (c) Iridescent purple/blue; (d) Heavy gray-black.",
"","",
"Grade on: (a) Silver/white — full shielding achieved — ACCEPTABLE; (b) Light straw/golden — marginal; for sour service 316L typically REJECTED — indicates oxygen exposure and potential sensitisation risk; (c) Purple/blue — significant oxidation — REJECTED for sour and critical SS applications; (d) Gray-black (sugaring) — severe oxidation — REJECTED — cut out required. Understanding colour-to-oxygen-contamination relationship is key.",
15),

(D,"practical",
"12. Review the welder qualification matrix and identify the one production weld NOT covered: Qualification — SMAW, P-No.1, F-4, A-1, 6G, OD 60.3 mm, 10 mm wall, no PWHT, no impact. Production welds: (a) SMAW, A106 Gr.B, 5G, OD 168 mm, 8 mm wall; (b) SMAW, A106 Gr.B plate, 1G groove, 20 mm thick; (c) SMAW, A572 Gr.50 (P-No.1), 6G, OD 60.3 mm, 6 mm wall; (d) SMAW, A335 P22 (P-No.5A), 2G, OD 114 mm, 8 mm wall.",
"","",
"Grade on: (a) 5G, OD 168 mm — 6G covers all positions; OD > 60.3 mm covered — COVERED; (b) Plate 1G — pipe ≥25 mm OD covers groove welds in all positions on plate per QW-461.4 — COVERED; (c) Same OD/thickness, 6G — COVERED; (d) P-No.5A — welder is P-No.1 qualified only; P-No.5A requires separate qualification — NOT COVERED. Answer: (d).",
15),

(D,"practical",
"13. Identify all nonconformances in this carbon steel girth weld fit-up inspection (ASME B31.3): Pipe OD 168 mm; Wall 9.5 mm; Internal hi-lo 2.8 mm; Root gap 3.5 mm; WPS root gap 2.0–3.0 mm; Joint angle 62° (WPS 60°±5°); Weld line — grinding marks visible, no oil/moisture.",
"","",
"Grade on: (1) Hi-lo 2.8 mm — limit is 1.5 mm or 1/4T (=2.375 mm), whichever is less = 1.5 mm; 2.8 mm > 1.5 mm — FAIL; (2) Root gap 3.5 mm — WPS max 3.0 mm; 3.5 mm > 3.0 mm — FAIL; (3) Joint angle 62° — WPS 60°±5° = 55°–65°; 62° within range — PASS; (4) Grinding marks, no contaminants — PASS. Two nonconformances: hi-lo and root gap.",
15),

(D,"practical",
"14. A PAUT report for a 20 mm wall CRA-clad pipe weld shows an indication at 3–5 mm depth from OD, 22 mm long, 18 dB above reference. Rejection threshold is 14 dB. Identify the finding and specify what additional characterisation is needed.",
"","",
"Grade on: Finding — REJECT; 18 dB > 14 dB threshold; 22 mm long in upper 1/4T region. Additional characterisation: TOFD scan to confirm depth sizing accuracy; additional PAUT angles to determine through-wall height; possibly RT to correlate; if LOF or crack confirmed, reject weld and proceed to excavation/repair.",
15),

(D,"practical",
"15. Review this PWHT soak record. WPS requirement: 690°C–720°C for 1 hour minimum. Chart: TC1 (weld) 710°C at 08:15; TC2 (HAZ) 695°C at 08:22; TC3 (HAZ) 720°C at 08:12; TC4 (base metal 50 mm from weld) 640°C, never exceeds 688°C. Soak ended at 09:20. State the soak start time, duration, and overall result.",
"","",
"Grade on: Soak start = when LAST required TC achieves minimum = 08:22 (TC2). Soak end = 09:20. Duration = 58 minutes. FAIL — 58 minutes < 60 minutes minimum. TC4 at 640°C — if within the required heated band this is a second failure; if outside the band, it is a gradient monitoring point only. Overall: PWHT FAILS on soak duration.",
15),

(D,"practical",
"16. Weld W-303 (P91, 2-inch SCH 160) was released for hydrotest. The weld file contains: WPS, WPQ, fit-up record, preheat record, weld traveler — all signed. Missing: PWHT chart, hardness test record, RT report. All three are ITP hold points. What are your actions?",
"","",
"Grade on: All three missing records are for hold points — releasing for hydrotest without hold-point completion is a major NCR; ACTIONS: (1) Halt hydrotest immediately for this spool; (2) Issue NCR; (3) Determine if PWHT was actually performed (check PWHT contractor records); (4) Determine if RT was performed (check NDT subcontractor logs); (5) If work was done but not filed — obtain/verify records; (6) If work was not done — complete all hold-point activities before any pressure test.",
15),

(D,"practical",
"17. Review this MPI report for structural fillet welds: AC electromagnetic yoke; lift test 4.5 kg; white contrast paint applied; fluorescent wet particles used; UV light intensity 1000 μW/cm² at inspection surface. Identify any technique nonconformances per ASME V Article 7.",
"","",
"Grade on: Key issue — white contrast paint + fluorescent particles is a contradiction. Visible MT uses contrast paint (white/black or red particles in visible light); fluorescent MT uses fluorescent particles under UV-A light WITHOUT contrast paint (white paint interferes with fluorescent indication visibility). This is a technique inconsistency. Inspector must determine which method was actually used and whether retesting is required.",
15),

(D,"practical",
"18. Identify what is missing from this P91 pressure pipe weld traveler: WPS: WPS-P91-GTAW-001; Welder: WLD-009; Date: 2025-10-01; Joint: W-155; Base Metal: A335 P91; Filler: ER90S-B9; Root Pass Visual: Accepted; Fill/Cap Visual: Accepted; RT Status: Pending.",
"","",
"Grade on: Missing: (1) Welder's WPQ number/qualification status not referenced; (2) Preheat temperature not recorded; (3) Interpass temperature not recorded; (4) Post-heat/controlled cool-down to ≤65°C before PWHT — not recorded (mandatory for P91); (5) PWHT chart reference — not listed; (6) Hardness test reference — mandatory per SAES-W-011 sour service; (7) Shielding/purge gas details for GTAW; (8) Back-purge oxygen content record for GTAW root.",
15),

(D,"practical",
"19. A WPS proposes GMAW short-circuit transfer (GMAW-S) for an ASME B31.3 pressure piping application. What specific concern must you flag and what code clause or specification requirement applies?",
"","",
"Grade on: ASME B31.3 Appendix D and SAES-W-011 specifically prohibit GMAW-S (short-circuit transfer mode) for pressure-containing welds due to inadequate penetration and proneness to lack of fusion defects. The WPS must be rejected and replaced with an approved GMAW transfer mode (spray, pulse, or globular). This is one of the most common field misapplications of GMAW in pressure piping.",
15),

(D,"practical",
"20. Design the scope of a weld repair on a P91 girth weld with a 12 mm deep PAUT indication at mid-wall (20 mm wall pipe). The original WPS used GTAW root + SMAW fill/cap. Address: excavation method, inspection during excavation, WPS applicability, and special requirements.",
"","",
"Grade on: (1) Excavation — arc gouging NOT recommended for P91 (carbon contamination); grinding preferred to ≥2 mm beyond confirmed defect depth; (2) In-process inspection — PT at each excavation stage to confirm defect removal; (3) WPS — 12 mm deep repair on 20 mm wall (60% through-wall) may require dedicated repair WPS; check existing WPS coverage; (4) Special requirements — maintain 200°C preheat throughout; PWHT after repair (full cycle); full PAUT post-repair; impact testing if required by specification.",
15),

]  # end QUESTIONS
